kickstarter/ios-oss

- Kickstarter.xcodeproj/project.pbxproj
Found a ghost file reference in PBXBuildFile
> Remove non-existent file reference

- Kickstarter-iOS/AppDelegate.swift
- Makefile
- circle.yml
In the changes last night #36 we accidentally stopped failing the build if swiftlint fails. i think this fixes it...
> Fail the build if swiftlint fails

- Kickstarter-iOS/Tests/Views/ProjectPamphletContentViewControllerTests.swift
- Kickstarter-iOS/Views/Storyboards/Main.storyboard
- Kickstarter-iOS/Views/Storyboards/Profile.storyboard
- Kickstarter-iOS/Views/Storyboards/WebModal.storyboard
- Kickstarter.xcodeproj/project.pbxproj
- Library/Navigation.swift
- Library/PKPaymentRequest.swift
- Library/Tests/FormatTests.swift
- Library/ViewModels/EmptyStatesViewModel.swift
- Library/ViewModels/ProjectNavigatorViewModel.swift
- Makefile
- circle.yml
What started as me trying to fix our scripts that make/distribute archives of the app, turned into a few things:
1) Turned on automatic code signing to fix our weird signing errors
2) Added missing embedded binaries to prevent insta-crash on devices
3) Added long compile time warning and fixed a few bad offenders
4) Fixed our deploy scripts
> Builds fixes and optimizations

- Kickstarter-iOS/Views/Cells/DashboardActionCell.swift
- Kickstarter-iOS/Views/Cells/MessageThreadCell.swift
- Kickstarter-iOS/Views/Controllers/LoginToutViewController.swift
- Kickstarter-iOS/Views/Controllers/LoginViewController.swift
- Kickstarter-iOS/Views/Controllers/MessagesViewController.swift
- Kickstarter-iOS/Views/Storyboards/Login.storyboard
- Kickstarter-iOS/Views/Storyboards/Messages.storyboard
We had some mismatched IB outlets and actions in our storyboards, and they are causing some production crashes. I've fixed a bunch of em.
Incidentally I just started using this new tool [IBAnalyzer](https://github.com/fastred/IBAnalyzer) that helps find these problems. Would be nice to get it into our CI environments at some point.
> Fixed a bunch of IB misconfigurations.

- Library/Koala/Koala.swift
- Library/Tests/ViewModels/LiveStreamDiscoveryViewModelTests.swift
- Library/ViewModels/LiveStreamDiscoveryViewModel.swift
> Add tracking to live discovery.

- Kickstarter-iOS/Views/Cells/BackingCell.swift
- Library/Tests/ViewModels/BackingCellViewModelTests.swift
- Library/ViewModels/BackingCellViewModel.swift
@kickstarter/native-squad 
Fixed format of estimated delivery date in backing cell
> Backing cell estimated delivery date fix

- Kickstarter-iOS/Views/Controllers/SignupViewController.swift
Basically the same as https://github.com/kickstarter/android-oss/pull/77 from the android repo...
> Don't use a title for signup errors.

- Kickstarter-iOS/Library/WebViewController.swift
- Library/ExpandableRow.swift
- Library/SelectableRow.swift
- LiveStream/Models/lenses/LiveStreamEvent.BackgroundImageLenses.swift
- LiveStream/Models/lenses/LiveStreamEvent.CreatorLenses.swift
Same as https://github.com/kickstarter/ios-ksapi/pull/23 and https://github.com/kickstarter/Kickstarter-Prelude/pull/71
> Remove `LensType` protocol

- .fastlane/Fastfile
- Kickstarter-iOS/Info.plist
- circle.yml
Just added what I think we need to deliver to the app store via Fastlane again.
Would like to test this with our next submission.
Reference: https://docs.fastlane.tools/actions/#deliver
> Fastlane deliver

- Kickstarter.xcodeproj/project.pbxproj
Looks like I accidentally removed it here https://github.com/kickstarter/ios-oss/pull/132, and not sure why :/
> Add back runes :/

- Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Looks like swiftlint got a [new version](https://github.com/realm/SwiftLint/releases/tag/0.19.0), and with it came a small linting issue. This fixes it.
> Fixed a swiftlint issue.

- Kickstarter-iOS/AppDelegate.swift
Thank you for very interesting OSS project!
I can learn a lot from this.
I found a small improvement!
> Fix indent

- Kickstarter-iOS/Views/Controllers/ThanksViewController.swift
10.3 introduced [SKStoreReviewController](https://developer.apple.com/documentation/storekit/skstorereviewcontroller), which will be the required way to prompt users to leave a review. On the plus side, it allows users to rate inline without leaving the app!
> Use SKStoreReviewController

- Kickstarter-iOS/Library/WebViewController.swift
- Kickstarter-iOS/Views/Controllers/ProjectDescriptionViewController.swift
- Kickstarter.xcodeproj/project.pbxproj
- Library/ViewModels/ProjectDescriptionViewModel.swift
- Library/ViewModels/ProjectDescriptionViewModelTests.swift
Just a quick loading indicator!
> Add loader to campaign description view

- Kickstarter-iOS/ViewModels/RootViewModel.swift
- Library/ViewModels/DiscoveryExpandableRowCellViewModel.swift
- Library/ViewModels/DiscoveryFiltersViewModel.swift
- Library/ViewModels/DiscoveryNavigationHeaderViewModel.swift
- Library/ViewModels/ThanksViewModel.swift
The latest couple Xcode betas don't compile.
> Command failed due to signal: Illegal instruction: 4
This commit should allow us to work in Xcode 9 again.
> Fix build for Xcode 9 beta 6

- Library/AppEnvironment.swift
- Library/AppEnvironmentTests.swift
- Library/KeyValueStoreType.swift
These interfaces are unavailable in Xcode 9.
> Update KeyValue protocol to reflect naming changes

- Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
- Kickstarter-iOS/Views/Controllers/DebugPushNotifictionsViewController.swift
- Kickstarter-iOS/Views/Storyboards/DebugPushNotifications.storyboard
Added 48hr reminder to debug push notifications.
To confirm that notification is working as expected.
> 48hr reminder to debug push

- KsApi/models/Location.swift
- KsApi/models/LocationTests.swift
- KsApi/models/UserTests.swift
- KsApi/models/lenses/LocationLenses.swift
- KsApi/models/templates/LocationTemplates.swift
- Library/ViewModels/RewardShippingPickerViewModel.swift
- Library/ViewModels/RewardShippingPickerViewModelTests.swift
We've been returning untranslated countries from the API for a long time. Let's make things nicer!
> Localize shipping rules

- Kickstarter.xcodeproj/project.pbxproj
Looks like we lost this in the upgrade.
> Bundle Hockey resources

- KsApi/MockService.swift
Here's an example of some key path lenses! 🎁
Now y'all get to delete lots of code 😄
> One last PR!

- README.md
Update to the xcode link in the readme
So no one else downloads Xcode 8.3.3 when they're getting started. 😄
> Update README to point to Xcode 9 download

- Kickstarter-iOS/Views/Storyboards/Discovery.storyboard
Fixed discovery in landscape (iPhone X)
https://trello.com/c/KVCqHZu4/144-iphone-x-landscape-mode-in-discovery.
Enabling `Use safe Area Layout Guides` on Discovery.storyboard
> Fixed discovery in landscape (iPhone X)

- Kickstarter-iOS/Views/Cells/DashboardReferrersCell.swift
- Kickstarter-iOS/Views/Storyboards/Dashboard.storyboard
- Library/ViewModels/DashboardReferrersCellViewModel.swift
Custom referrers is no longer set to hidden to reflect web.
> custom referrers shown

- Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
- Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
- Kickstarter-iOS/Views/Cells/DiscoveryPostcardCell.swift
- Kickstarter-iOS/Views/Controllers/DiscoveryPageViewControllerTests.swift
- Kickstarter-iOS/Views/Storyboards/DiscoveryPage.storyboard
- KsApi/models/DiscoveryParams.swift
- KsApi/models/DiscoveryParamsTests.swift
- KsApi/models/Project.swift
- KsApi/models/ProjectTests.swift
- KsApi/models/lenses/Project.DatesLenses.swift
- KsApi/models/lenses/ProjectLenses.swift
- KsApi/models/templates/ProjectTemplates.swift
- Library/RefTag.swift
- Library/RefTagTests.swift
- Library/ShortcutItem.swift
- Library/ViewModels/DiscoveryPageViewModel.swift
- Library/ViewModels/DiscoveryPageViewModelTests.swift
- Library/ViewModels/DiscoveryPostcardViewModel.swift
- Library/ViewModels/DiscoveryPostcardViewModelTests.swift
We have remove POTD from homepage and want to reflect this on iOS.
> Remove POTD

- Kickstarter-iOS/Views/Storyboards/ProjectPamphlet.storyboard
- Kickstarter.xcodeproj/project.pbxproj
- Library/String+base64.swift
Fixed bug of ProjectPage in landscape when using iPhoneX 
https://trello.com/c/VixtCxuZ/332-bug-project-page-not-showing-correctly-in-landscape-iphone-x
Activating Safe Area \o/!
> Fixed layout of projectPage in landscape(iPhoneX)

- Kickstarter-iOS/Views/Controllers/ThanksViewController.swift
- Kickstarter-iOS/Views/Storyboards/Thanks.storyboard
- Library/ViewModels/ThanksViewModel.swift
Fixed the Thank you label that was being compressed on smaller devices.
Making the header view change the height dynamically.
> Dynamic header view bug fix

- Kickstarter-iOS/Views/Cells/DiscoveryExpandedSelectableRow.swift
- KsApi/models/Category.swift
- KsApi/models/CategoryTests.swift
- KsApi/models/Project.swift
- Library/RootCategory.swift
- Library/ViewModels/ActivityFriendBackingViewModel.swift
- Library/ViewModels/DiscoveryNavigationHeaderViewModel.swift
- Library/ViewModels/ThanksViewModel.swift
Fixed bug that didn't show category name if user goes to Discovery from Thanks page.
> Header title bug fix

- README.md
> Happy new year!

- README.md
There are related closed issues, but this description will help some new user who doesn't figure out the oss version default behavior.
kickstarter#33
kickstarter#35
kickstarter#109
> Add description for the mock version

- Kickstarter-iOS/Views/Cells/DiscoveryPostcardCell.swift
- Kickstarter-iOS/Views/Storyboards/DiscoveryPage.storyboard
- Kickstarter-iOS/Views/Storyboards/DiscoveryPostcardCell.xib
- Library/ViewModels/DiscoveryPostcardViewModel.swift
- Library/ViewModels/DiscoveryPostcardViewModelTests.swift
Removed Creator's name experiment.
https://trello.com/c/iwYQwG02/498-move-creator-on-project-card-to-100-remove-experiment
> removed creators name experiment

- Makefile
Fixes https://github.com/kickstarter/ios-oss/issues/75
> Setting `OPENTOK_VERSION` in `Makefile`

- Kickstarter-iOS/Info.plist
- KsApi/ServerConfig.swift
- KsApi/models/Config.swift
Adding the project card category experiment. Also updating the local environment base url.
> Adding project card category experiment

- Kickstarter.xcodeproj/project.pbxproj
Added a build script that will run swiftlint on build if it's installed.
It's really frustrating to be blocked from pushing because of swiftlint errors/warnings that you don't see until you run swiftlint in the command line. Now you can see the errors when you build 😄
> Run swiftlint in build phase

- Configs/Base.xcconfig
- Kickstarter.xcodeproj/project.pbxproj
Adding the Fabric & Crashlytics framework paths to the target
> Add Fabric & Crashlytics framework path

- Kickstarter.xcodeproj/project.pbxproj
Adds back the Crashlytics and Fabric frameworks to the project.
> Add back frameworks to project

- Kickstarter-iOS/DataSources/SettingsAccountDataSource.swift
- Kickstarter-iOS/Views/Controllers/ChangeEmailViewController.swift
- Kickstarter-iOS/Views/Controllers/ChangePasswordViewController.swift
- Kickstarter-iOS/Views/Controllers/SettingsAccountViewController.swift
- Kickstarter-iOS/Views/Storyboards/Settings.storyboard
- Kickstarter.xcodeproj/project.pbxproj
- Library/ViewModels/SettingsAccountViewModel.swift
UI for the change password feature on iOS.
Added a new scene to the `Settings` storyboard.
> Change password UI

- Kickstarter-iOS/GraphError+LocalizedDescription.swift
- Kickstarter.xcodeproj/project.pbxproj
- KsApi/GraphMutation.swift
- KsApi/GraphSchema.swift
- KsApi/MockService.swift
- KsApi/Service+RequestHelpers.swift
- KsApi/Service.swift
- KsApi/ServiceType.swift
- KsApi/ServiceTypeTests.swift
- KsApi/models/ChangePasswordInput.swift
- KsApi/mutations/Mutations.swift
- Library/AppEnvironment.swift
- Library/AppEnvironmentTests.swift
See https://github.com/kickstarter/ios-oss/pull/440 for description.
> Graph mutations clean

- Kickstarter.xcodeproj/project.pbxproj
Added Currency Picker Cell to Frameworks.
App was crashing when currency cell was tapped.
> added currency picker cell to frameworks

- .github/PULL_REQUEST_TEMPLATE.md
Adds a section for acceptance criteria to our PR template.
We're serious about our QA and this should be a step that we include in every PR ✅
> Add acceptance criteria to our PR template

- Gemfile.lock
Updates our Fastlane gem.
Our current version is not compatible with changes to app store connect.
`bundle update fastlane`
https://github.com/fastlane/fastlane/releases
> Update fastlane gem

- README.md
Small README update
We don't require specific version of Xcode (mentioned previously) plus there are multiple channels how to get Xcode (Mac App Store vs direct download from developer.apple.com)
> Update readme with more generic getting started instructions

- README.md
> Increment year

- Kickstarter-iOS.playground/Sources/playgroundController.swift
- Kickstarter-iOS.playground/Sources/setup.swift
Migrates playground support files to Swift 4.2
It's one of the first steps necessary for fixing playgrounds.
> 🏰 Update playgrounds to Swift 4.2

- Kickstarter-iOS.playground/Pages/Buttons.xcplaygroundpage/Contents.swift
- Kickstarter-iOS.playground/Pages/Color Palettes.xcplaygroundpage/Contents.swift
- Kickstarter-iOS.playground/Pages/Typography.xcplaygroundpage/Contents.swift
- Kickstarter-iOS.playground/Sources/playgroundController.swift
- Library/ViewModels/AddNewCardViewModel.swift
Fixes live preview of playgrounds.
This is probably the best feature of playgrounds, so it would be great if we can actually use it.
Turns out, creating view hierarchy + view controller containment using auto layout fixes some of the vague crash logs we've been seeing in the console.
Turning on Live Preview in the assistant editor and playing these playgrounds should preview them on screen
If you're getting a compiler error in `setup.swift` follow these steps:
Comment out following lines like this
```
//import Library
import UIKit
// This needs to be called manually in playgrounds.
public func initialize() {
//  UIView.doBadSwizzleStuff()
//  UIViewController.doBadSwizzleStuff()
}
```
Save
Revert back to
```
import Library
import UIKit
// This needs to be called manually in playgrounds. …
```
> 👩‍🔬 [Investment Day] Fix playgrounds, yet again 🤦‍♂️ 

- .github/PULL_REQUEST_TEMPLATE.md
Adds `Performance` section to our PR template
Blended layers support is usually something that's very easy to implement, yet also super easy to forget. Hopefully this section will help us remember performance optimizations that we can and should focus at
> Add performance section to PR template

- Kickstarter-iOS/DataSources/SettingsNotificationsDataSource.swift
- Kickstarter-iOS/Views/Cells/FindFriendsFacebookConnectCell.swift
- Kickstarter-iOS/Views/Controllers/BetaToolsViewController.swift
- Kickstarter-iOS/Views/Controllers/ChangePasswordViewController.swift
- Kickstarter-iOS/Views/Controllers/LoginToutViewController.swift
- Kickstarter-iOS/Views/Controllers/SettingsNotificationsViewController.swift
- Kickstarter-iOS/Views/SelectCurrencyTableViewHeader.swift
- KsApi/Service+RequestHelpers.swift
- Library/DataSource/ValueCellDataSource.swift
- Library/Navigation.swift
- Library/ViewModels/DiscoveryPostcardViewModelTests.swift
- Library/ViewModels/FacebookConfirmationViewModel.swift
- Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift
- Library/ViewModels/RewardCellViewModelTests.swift
- Library/ViewModels/SettingsViewModel.swift
- Library/ViewModels/ThanksViewModel.swift
- Library/ViewModels/UpdateDraftViewModel.swift
Adds `-` into our pragma marks in order to add separators to Xcode's jump bar .. making the code groups more explicit and visually distinct.
Beter tooling experience
> 👩‍🔬 [Investment Day] Pragma mark separators

- Kickstarter-iOS/Views/Controllers/CreatePasswordTableViewController.swift
Renames `Binding` pragma mark to `View model` which goes better with our other naming conventions like `Styles` for `bindStyles`.
Consistency, synergy, you name it
> 👩‍🔬 [Investment Day] - Consistent pragma mark naming (master)

- Kickstarter-iOS/Views/Cells/PledgeAmountCell.swift
- Kickstarter-iOS/Views/Cells/PledgeDescriptionCell.swift
- Kickstarter-iOS/Views/Cells/PledgeShippingLocationCell.swift
- Kickstarter-iOS/Views/Cells/PledgeSummaryCell.swift
- Kickstarter-iOS/Views/Controllers/CreatePasswordTableViewController.swift
- Kickstarter-iOS/Views/Controllers/ShippingRulesTableViewController.swift
- Kickstarter-iOS/Views/PledgeCTAContainerView.swift
Renames `Binding` pragma mark to `View model` which goes better with our other naming conventions like `Styles` for `bindStyles`.
Consistency, synergy, you name it
> 👩‍🔬 [Investment Day] - Consistent pragma mark naming (feature branch)

- Kickstarter-iOS/Library/UIViewController+HelpWebViewController.swift
- Library/Styles/CheckoutStylesTests.swift
- Fixes tests to pass
- Fixes import formatting
To make Circle 💚 since we've removed some of the styling and didn't update tests.
> 💲[Native Checkout] Pledge Screen Refactor: UITableView -> UIStackView - Fix Tests 🙌

- Kickstarter-iOS/Info.plist
> Bump version to 3.20.1

- Kickstarter-iOS/Views/Controllers/ManagePledgePaymentMethodView.swift
- Kickstarter-iOS/Views/Controllers/ManagePledgeViewController.swift
Fixes some of the issues found in #851
Since @Scollaco is away we want to merge his PR addressing some of the last issues found on it.
> [NT-204] Additional fixes

- Kickstarter-iOS/Views/RewardCardView.swift
Fixes an indentation issue that was merged accidentally 
To avoid issues with other branches that rebase from master.
> Swiftformat fix

- Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
- Kickstarter-iOS/Locales/de.lproj/Localizable.strings
- Kickstarter-iOS/Locales/es.lproj/Localizable.strings
- Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
- Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
- Library/Strings.swift
- Library/ViewModels/PledgeAmountViewModel.swift
Updates a string key for better consistency.
Justin has [noticed](https://github.com/kickstarter/kickstarter/pull/17585#discussion_r332110200) this inconsistency after the PR has been merged, so this is merely a quick loop on removing a code debt.
> Update string key

- Library/OptimizelyExperiment.swift
- Library/ViewModels/ProjectDescriptionViewModel.swift
- Library/ViewModels/ProjectDescriptionViewModelTests.swift
- Library/ViewModels/ProjectPamphletMainCellViewModel.swift
- Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift
Adds the tests for the experimental treatment added in #1072.
The experiment was added separately in #1073 and this additional PR adds the tests to make things easier to review.
Removed the `TODOs` and added the tests.
> [NT-876] Add Project Campaign Experiment Tests

- Library/ViewModels/ProjectDescriptionViewModel.swift
- Library/ViewModels/ProjectDescriptionViewModelTests.swift
- Library/ViewModels/ProjectPamphletMainCellViewModel.swift
- Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift
- Library/ViewModels/ProjectPamphletViewModel.swift
- Library/ViewModels/ProjectPamphletViewModelTests.swift
Adds `Campaign Details Button Clicked`, `Project Page Pledge Button Clicked` and `Campaign Details Pledge Button Clicked` to be tracked via Optimizely.
In order to track the success of our Project page experiment.
Adds these two events and their respective attributes and event tags.
> [NT-877] Project page Optimizely Events

- Library/OptimizelyClientType.swift
- Library/Tracking/Koala.swift
- Library/Tracking/KoalaTests.swift
- Library/ViewModels/PledgeViewModelTests.swift
Merges in the changes from the `release-4.3.0` branch:
- #1074 
- #1084
> Merge release-4.3.0

- Library/Tracking/Koala.swift
- Library/ViewModels/ActivitiesViewModel.swift
- Library/ViewModels/PledgeViewModel.swift
Fixes a bad merge.
Feature branch is now fixed and up to date with master
> Should fix feature branch

- .gitignore
- Cartfile.resolved
Updating .gitignore to include vendor/bundle and .bundle/config. 
While setting up my local environment I required some additional set up for my gems and bundle installation.
Updated .gitignore directly.
> [NT-1535] Add vendor/bundle and .bundle/config to .gitignore

- Library/SharedFunctions.swift
- Library/SharedFunctionsTests.swift
- Library/ViewModels/PledgeViewModel.swift
Refactor checkoutProperties into SharedFunctions
We want to be able to reuse a function that creates checkout properties for different view models in the pledge flow
> Checkout Properties Refactor

- KsApi/models/DiscoveryParams.swift
- Library/RefTag.swift
- Library/Styles/DiscoveryStyles.swift
- Library/Tracking/KSRAnalytics.swift
Adding/Updating some properties related to `discover`.
Insights is cleaning up the events and properties we are sending to Segment so they can understand our data and make actionable decisions based on it.
> [EP-188] Create properties (phase 2)

- Library/Tracking/KSRAnalytics.swift
- Library/Tracking/KSRAnalyticsTests.swift
- Library/ViewModels/EmptyStatesViewModel.swift
- Library/ViewModels/EmptyStatesViewModelTests.swift
Adding a new tracking event for when a user selects the `Explore Projects` button in the empty state ActivitiesViewController.
Another addition to our segment implementation for phase two.
> [EP-234] - CTA Clicked (discover)

- Library/Tracking/KSRAnalytics.swift
- Library/Tracking/KSRAnalyticsTests.swift
- Library/ViewModels/ManagePledgeViewModel.swift
- Library/ViewModels/ManagePledgeViewModelTests.swift
Implement page viewed event tracking for manage pledge screen
This is part of phase 3 iOS Native events to send tracking data to segment
> [EP-249] Page Viewed (manage pledge)

- Library/Tracking/KSRAnalytics.swift
- Library/Tracking/KSRAnalyticsTests.swift
- Library/ViewModels/ProjectPamphletMainCellViewModel.swift
- Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift
Added a new event for when a creator's name is clicked
Phase 4 Segment Integration
> [EP-316] CTA Clicked(Creator Details)

- Library/Tracking/KSRAnalytics.swift
- Library/Tracking/KSRAnalyticsTests.swift
- Library/ViewModels/VideoViewModel.swift
- Library/ViewModels/VideoViewModelTests.swift
1. Added `trackProjectVideoPlaybackStarted` function to track when a project video playback starts.
2. Added  new track properties called `Video Properties`.
3. Added tests for `trackProjectVideoPlaybackStarted ` `KSRAnalytics` and `VideoViewModel`
Phase 4 of Segment Integration.
> [EP-260] Video Playback Started

- Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-iOS.xcscheme
- Library/OptimizelyClientType.swift
- Library/OptimizelyClientTypeTests.swift
- Library/SharedFunctions.swift
- Library/SharedFunctionsTests.swift
- Library/Tracking/KSRAnalytics.swift
- Library/Tracking/KSRAnalyticsTests.swift
- Library/ViewModels/PledgeViewModel.swift
- Library/ViewModels/PledgeViewModelTests.swift
- Library/ViewModels/RewardsCollectionViewModelTests.swift
- Library/ViewModels/ThanksViewModelTests.swift
Addressing some properties that were flagged as incorrect during QA for phase one of our Segment implementation.
Most of these are type changes from a number to a string or vice-versa.
> [EP-410] QA Property Fixes (phase_one)

- Library/Tracking/KSRAnalytics.swift
- Library/Tracking/KSRAnalyticsTests.swift
Add missing page context property when tracking Add Ons Continue CTA
Part of phase 1 events QA
> [EP-456] QA CTA Clicked (Add Ons Continue) Phase 1

- Library/Tracking/KSRAnalytics.swift
- Library/Tracking/KSRAnalyticsTests.swift
context_page = "pledge” but should be "checkout"
> [EP-457] QA CTA Clicked (pledge_submit) Phase 1

- Library/Tracking/KSRAnalytics.swift
- Library/Tracking/KSRAnalyticsTests.swift
- Library/ViewModels/PledgeViewModel.swift
Add event track for when Apple Pay button is clicked to submit a pledge.
Segment Integration
> [EP-426] CTA Clicked (pledge_submit)

- Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-iOS.xcscheme
- Library/Tracking/KSRAnalytics.swift
- Library/Tracking/KSRAnalyticsTests.swift
- Library/ViewModels/ThanksViewModel.swift
Update for the event that is fired when the user taps on a project in the recommendations list on the Thanks page.
The following event properties was updated.
- event name: from `cardClicked` to `ctaClicked`.
- `typeContext`: from `project` to `recommended`
- `locationContext`: from  `recommendations` to `curated`
This is part of implementation for changes to event properties sent when a project card is tapped on Thanks page.
1. Successfully back a project
2. On the Thank you page click on one of the recommended projects
3. Verify that the following event properties are been sent.
Event Name = "CTA Clicked"
`context_cta` = `project`
`context_page` = `thanks`
`context_location` = `curated`
`context_type` = `recommended`
> [EP-434] CTA Clicked (project)

- Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
- Add sound notification type when registering for push notifications.
Push notification on iOS has no sound (or buzz), both on internal as external builds.
- Users phone chimes and buzzes when a new push notification is received
> [NT-1882] Push notifications have no sound (or buzz)

- LICENSE
- NOTICE.md
- README.md
Updates our OSS licenses and some dates in our own readme and license files.
Housekeeping and good practice.
> [NT-1993] Update OSS Licenses

- Kickstarter.xcodeproj/project.pbxproj
- KsApi/models/graphql/adapters/Backing+BackingFragment.swift
- KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
- KsApi/models/graphql/adapters/Comment+CommentFragment.swift
- KsApi/models/graphql/adapters/Comment+GraphComment.swift
- KsApi/models/graphql/adapters/User+UserFragment.swift
Adapts a `Backing` from a `BackingFragment`.
**Note:** Added `TODO`s for work that will be done in subsequent PRs to keep them smaller. `Reward` is not handled yet in this PR.
Continuation of the work to move our GraphQL requests to Apollo.
Added adaptation code for `Backing` from `BackingFragment` and tested it.
> [NT-2072] Backing From BackingFragment

- Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
- Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
- Library/Extensions/Feature+Helpers.swift
- Library/Extensions/Feature+HelpersTests.swift
- Library/Feature.swift
Removing the feature flag for Braze and all of its references.
We are live with our Braze implementation and therefore no longer need to worry about toggling its state.
> [NT-1854] Remove Braze feature flag

- Library/ViewModels/PledgeViewModel.swift
- Library/ViewModels/PledgeViewModelTests.swift
After merging our feature branch for risk messaging into `main` we realized we were presenting the risk messaging copy to backers even in the update pledge context. This PR will make it so that risk messaging is only shown when creating a backing and not when updating.
The risk messaging is particularly important before the backer has initiated their pledge but not necessary to show after that. Updating a pledge typically involves either changing a reward or bonus amount and risk messaging does not need to be shown again within this context.
Updated the `PledgeViewModel` to check the `context` signal for an `isCreating` status before presenting risk messaging.
> [NTV-158] No longer presenting risk messaging modal when updating pledge

- .circleci/config.yml
- Kickstarter.xcodeproj/project.pbxproj
Updating Main branch with Release 5.5.0 marketing version.
> [Unticketed] Release 5.5.0 to Main

- .fastlane/Fastfile
unsure if this will fix the issue but I strongly suspect it will!
> attempt to fix Fastlane S3 access

- Kickstarter.xcodeproj/project.pbxproj
> Release 5.6.2 to Main

- Kickstarter.xcodeproj/project.pbxproj
This is the release from 5.8.0 to Main
> [MBL-841] Release 5.8.0 to Main

- Kickstarter.xcodeproj/project.pbxproj
This is the release from 5.9.0 to Main with the correct marketing version update.
> Release 5.9.0 to Main

- Kickstarter.xcodeproj/project.pbxproj
This is the release from 5.10.0 to Main with the correct marketing version update.
> Release 5.10.0 to Main

- Kickstarter-iOS/Features/ConfirmDetails/Controllers/ConfirmDetailsViewController.swift
- Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift
- Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
- Kickstarter-iOS/Locales/de.lproj/Localizable.strings
- Kickstarter-iOS/Locales/es.lproj/Localizable.strings
- Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
- Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
- Kickstarter-iOS/SharedViews/HeaderFooterViews/RewardsCollectionViewHeaderView.swift
- KsApi/models/templates/ProjectTemplates.swift
- Library/Strings.swift
- Library/ViewModels/PostCampaignPledgeRewardsSummaryViewModel.swift
- Library/ViewModels/ThanksViewModel.swift
- Library/ViewModels/ThanksViewModelTests.swift
- Runs `make strings` to pull in new translations
- Updates the hardcoded strings to use the new localized ones
> [MBL-1217] Post Campaign Pledge Copy Translations

- Kickstarter-iOS/Locales/de.lproj/Localizable.strings
- Kickstarter-iOS/Locales/es.lproj/Localizable.strings
- Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
- Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
- Library/Strings.swift
Run `make strings` to pull in the translations for the "pledge immediately" string.
> Update translations for late pledge string

- Kickstarter.xcodeproj/project.pbxproj
📲 What
Update the marketing version to 5.18.0 for release.
missed one target in the other PR 😢
> Update marketing version 5.18.0

- Kickstarter-iOS/Features/LoginTout/Controller/LoginToutViewController.swift
- Kickstarter-iOS/SharedViews/SwiftUIHelpers/ButtonStyles.swift
- Kickstarter-iOS/SharedViews/SwiftUIHelpers/ButtonStylesTests.swift
I'm not sure why swift format didn't get mad at me last week, but I just noticed I left in some weird formatting from last week's prs (mostly the button styles one). I ran our format script to fix that.
> Fix weird formatting from button styles

- Kickstarter.xcodeproj/project.pbxproj
Updates marketing version to 5.19.0 for release
> [NO TICKET] 5.19.0 Marketing Version

- Library/ViewModels/NoShippingPledgeViewModel.swift
- Library/ViewModels/NoShippingPledgeViewModelTests.swift
With the "no shipping at pledge" flag on, trying to update the payment method of a reward with shipping doesn't work. We didn't show the shipping in the reward summary table and we defaulted the shipping amount to zero. This pr fixes both of these and adds a test to ensure that'll stay true.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1821)
| --- | --- |
| ![Simulator Screen Recording - iPhone 16 - 2024-10-23 at 11 45 16](https://github.com/user-attachments/assets/020b7eb3-8213-4250-a666-e0bf1b06d20d) | ![Simulator Screen Recording - iPhone 16 - 2024-10-23 at 12 12 44](https://github.com/user-attachments/assets/c30b2380-7d28-4c45-ad93-ef70ad948ad9) |
> [MBL-1821] Get shipping info from backing if there's no shipping rule selected

- Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
- Kickstarter-iOS/Locales/de.lproj/Localizable.strings
- Kickstarter-iOS/Locales/es.lproj/Localizable.strings
- Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
- Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
- Library/Strings.swift
- Library/ViewModels/PledgeStatusLabelViewModel.swift
Pulls in and implements new PLOT copy
This goes along with the temporary fix pledge workaround. Providing translations for these changes: https://github.com/kickstarter/ios-oss/pull/2257
normal strings update
- `make strings` script
-  use strings
> [MBL-2011] New PLOT Translations

- Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOAddressSummary.swift
- Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOAlertFlag.swift
- Kickstarter-iOS/Features/PledgedProjectsOverview/PPOView.swift
- Library/PagedContainer/PagedTabBar.swift
Changes some accessibility elements for PPO so the screen reads better with voiceover.
Some SwiftUI elements were marked as accessibility elements combining their children, and had a few traits specified.
> [MBL-2118] Voiceover fixes for PPO

- Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
- Kickstarter-iOS/Locales/de.lproj/Localizable.strings
- Kickstarter-iOS/Locales/es.lproj/Localizable.strings
- Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
- Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
- Library/Strings.swift
Update strings.
Get the latest translations in for sort and filter.
> MBL-2232: Update strings

- Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCardModel+Parsing.swift
- KsApi/GraphAPI.swift
- KsApi/graphql-schema.json
- KsApi/models/graphql/adapters/Reward+RewardFragment.swift
- Library/UseCases/SimilarProjects/SimilarProject+Parsing.swift
Update our GraphQL schema and fix a few changes.
Looks like a few properties were made non-nullable and it temporarily broke the build. (Existing apps are fine, though.)
> Update GraphQL schema and fix schema changes

- Kickstarter.xcodeproj/project.pbxproj
- Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Adds [Lottie](https://github.com/airbnb/lottie-ios.git) via SPM
For [the new onboarding flow](https://www.figma.com/design/cCLSxffRzm3jCVkQd0F4fw/Native-Onboarding-Flow?node-id=38-2888&p=f&m=dev) design has made some Lottie animations for us.
We'll use the SDK to load these animations into a `LottieAnimationView`.
The animations will be stored locally in the app, and the design will give us .json files for each supported language since these animations contain some copy.
We'll then keep these files in locale specific directories and load them up similarly to how we handle localized strings.
- The alternative would be to pull in each animation via a URL request. I'd prefer to do this with local .json files, but if anyone's opposed lmk.
Add the sdk via Swift Package Manager to our Library …
> [MBL-2418] Lottie SDK Integration

- Kickstarter-iOS/Features/SurveyResponse/Controller/SurveyResponseViewController.swift
- Library/ViewModels/SurveyResponseViewModel.swift
- Library/ViewModels/SurveyResponseViewModelTests.swift
If the survey webview is opened without a current logged in user, trigger login.
Note: If they dismiss login without actually logging in, they'll still get into a weird/bad state in the pledge redemption webview. However, if they tap the link again, they get another chance to log in.
If we log in the user before trying to show a survey or pledge redemption flow, we're able to actually display the survey in the webview. This is particularly important for net new backers, since they may open pledge redemption in a webview before they've backed a single project (and thus possibly before they've even created an account).
I'm not 100% sure if old surveys need a user to log in. This is hard to test because if they still exist in prod, they're definitely rare. However, I did confirm that they …
> [MBL-2427] Support login in survey webview

- Kickstarter.xcodeproj/project.pbxproj
Update marketing version. 
The patch release is tagged as `5.26.1` in Github.
> Update marketing version for 5.26.1

- Kickstarter-iOS/Features/SortFilter/FilterRootView/FilterRootView.swift
- Kickstarter-iOS/Features/SortFilter/LocationView/LocationView.swift
- Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
- Kickstarter-iOS/Locales/de.lproj/Localizable.strings
- Kickstarter-iOS/Locales/es.lproj/Localizable.strings
- Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
- Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
- Library/Strings.swift
- Library/UseCases/SearchFilters/SearchFilters.swift
Update translated strings for Location filter.
I verified that each of these strings has been translated in all locations ✅
> Update translated strings for Location filter

- KsApi/GraphAPI.swift
- KsApi/graphql-schema.json
- KsApi/queries/SearchQuery.graphql
- Library/ViewModels/SearchViewModel+GraphQL.swift
Update `SearchQuery` to support the toggle booleans, and update the `DiscoveryParams` -> `SearchQuery` adapter code.
> MBL-2560: Update SearchQuery and DiscoveryParams for search filter toggles
