kickstarter/ios-oss

Configs/Secrets.swift.example
Kickstarter-iOS/Tests/Views/ActivitiesViewControllerTests.swift
Makefile

Managing our secrets via private submodule prevents OSS builds from bootstrapping. By cloning the repo instead, we can more gracefully handle this failure.
This PR should fix #7.

Clone secrets or fall back

---

Makefile

The `secrets` make target didn’t work for me after #8 still, with failing git clone aborting the whole process and resulting in missing secrets on build stage.
Solution suggested here works as follows: (1) remove the secrets directory, (2) try cloning with git ignoring errors, and (3) if directory is nonexistent after that, create it and copy the example secrets.
I don’t like the initial forced removal too much, but it does offer an additional benefit in ensuring a simple `make bootstrap` would update secrets if they’re rotated. (A better solution could check if there’s a repo in native-secrets and do a force pull in such a case, but at a cost of increased complexity.)

Ensuring secrets bootstrapping works without access to native-secrets repo

---

Makefile

I've got multiple versions of Xcode on my machine (for the sake of projects in various states), which causes problems when attempting to run tests:
```bash
$ make test-all
PLATFORM=iOS /Applications/Xcode 7.app/Contents/Developer/usr/bin/make test
/bin/sh: /Applications/Xcode: No such file or directory
make: *** [test-all] Error 127
```
This change just wraps `$(MAKE)` in quotes so that spaces don't break it.

Wrap make path in quotes to handle spaces in path

---

Library/Navigation.swift

Fun little optimization: we can use `@autoclosure` to approach the laziness we get using `if`–`let` more traditionally.
Might be nice to extract this (and a few more overloads for 3-argument zip, 4-, etc.) to Prelude!

Minor optimization to Optional zip

---

LiveStream/Service/LiveStreamService.swift

When we dismiss a live stream we 'delete' the Firebase DB instance to be sure resources are free'd up.
However the way deleteDatabase() was being called it would instantiate a database only to immediately delete it.  This makes the call to deleteDatabase() idempotent if a database instance does not exist.

Improve LiveStreamService's deleteDatabase()

---

.swiftlint.yml
Library/Tests/.swiftlint.yml

Hey, our CircleCI is running SwiftLint 0.16.1 since homebrew updated and it's introduced some new rules which are breaking our builds. @mbrandonw and I decided to disable them for now until we have time to implement some of them properly. The disabled rules are `class_delegate_protocol`, `large_tuple` and `vertical_parameter_alignment`.
More info in the SwitLint release notes: https://github.com/realm/SwiftLint/releases/tag/0.16.0.

Disabling new linting rules

---

.swiftlint.yml
Kickstarter-iOS/Views/Controllers/LiveStreamContainerViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletContentViewController.swift
Library/Tests/.swiftlint.yml
Library/Tests/ViewModels/LiveStreamContainerViewModelTests.swift
Library/Tests/ViewModels/ProjectPamphletContentViewModelTests.swift
Library/ViewModels/LiveStreamContainerViewModel.swift
Library/ViewModels/ProjectPamphletContentViewModel.swift
LiveStream/Views/Controllers/LiveVideoViewController.swift
LiveStream/Views/VideoGridView.swift

Just some fixes that we need for live streaming:
- Fix a `systemLayoutSizeFitting` sizing issue with the nav bar title view which was causing a layout warning.
- Allow live streams to be played if the creator goes live early.
- A fix so that the loader view isn't shown again when the creator goes off air.
- Added a setting for OpenTok to support a beta feature of theirs which should allow viewers up to ~1000 before we need to scale to HLS. The setting suppresses connection messages to reduce traffic overhead while the client is connected to a live stream.

Live streaming fixes

---

LiveStream/Views/Controllers/LiveStreamViewController.swift

`LiveStreamViewController` was crashing on dismiss.
@mbrandonw this seems to be since the refactor of the container view, a `LiveStreamViewController` instance is automatically created by the story board instantiation before our `createAndConfigureLiveStreamViewController` signal in `LiveStreamContainerViewModel` even emits.
On dismiss `LiveStreamViewController` is trying to call `deleteDatabase()` on its implicitly unwrapped `liveStreamService` property. Quick fix is to make this optional, this problem will be resolved once my other refactor of removing `Project.LiveStream` is completed as we will then no longer have this asynchronous fetching of the `LiveStreamEvent` after the `LiveStreamContainerViewController` is created.

LiveStreamViewController dismiss crash fix

---

Library/Koala/Koala.swift
Library/Tests/Koala/KoalaTests.swift
Library/Tests/ViewModels/LiveStreamContainerViewModelTests.swift
Library/Tests/ViewModels/LiveStreamCountdownViewModelTests.swift
Library/ViewModels/LiveStreamContainerViewModel.swift
Library/ViewModels/LiveStreamCountdownViewModel.swift

This adds a few small updates to our live stream tracking:
- `duration` value for `Watch Live Stream` and `'Watch Live Stream Replay` events is now always a constant integer of 1.
- Added tracking for `Close Live Stream` event.
- Added tracking for `Close Live Stream Replay` event.
- Added tracking for `Close Live Stream Countdown` event.

Live stream tracking updates

---

Library/Koala/KoalaTrackingClient.swift

I just realized that we have a crash in the oss builds of the app once events are attempted to be sent. The reason is that we have stubbed secrets in the oss build, and so those requests fail in a bad way (we don't even get an `HTTPURLResponse ` value back), and that leads to an assertion failure.
Seems like we should just not assert?

Fix koala crash on oss builds

---

Kickstarter-iOS/Info.plist
Kickstarter-iOS/Views/Controllers/UpdateDraftViewController.swift
Kickstarter.xcodeproj/project.pbxproj

So far the only ios 10 crash we've seen from the swift 3 upgrade is when you try to attach images/video to a project update. This fixes that.
Info here: https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html

Add permissions keys for access to camera/photos

---

Kickstarter-iOS/Views/Controllers/SearchViewController.swift

We just uncovered a subtle deadlock sitch in our search vm. Basically, there's some unfortunate ping-ponging between inputs/outputs where we tell the VM that we focused on something, and then the VM tells the view to focus, and then we tell the VM we focused on something, and then the VM ....
This happened due to our change of `observeForControllerAction` to `observeForUI` on a specific output. The latter is the correct one to use, but it runs the block immediately instead of on the next runloop, and that was causing the deadlock.
I'm going to do the naive/slightly-incorrect fix now, but in the future we could better delineate our inputs/outputs to avoid this.

Go back to observeForControllerAction to fix deadlock

---

Kickstarter-iOS/Views/Controllers/VideoViewController.swift
LiveStream/Views/Controllers/LiveVideoViewController.swift

So as @mbrandonw and I recently discovered, `AVPlayerViewController` leaks when it's used as an embedded child view controller and the user taps to go full-screen. In our testing we could only reproduce this when going full-screen, it appeared to release correctly if only watching it as an embedded video.
I played around with Xcode 8's memory debugger a bit and found these sorts of things after dismissing the video view so it seems as if internal KVO observers may be the cause?:
Our temporary solution was to just pause the video on dismiss so that we didn't continue to hear the audio after the modal was gone, however this would only reduce the memory footprint from around **145MB** (while playing) to around **130MB** after dismissal.
I found that adding the two lines in this PR, which go …

Reduce AVPlayerViewController memory leak overhead

---

Makefile
circle.yml

Previously we were downloading the OpenTok binary on each Circle build. This change writes the current version to a file alongside `OpenTok.framework` (already gitignore'd) and does a comparison on the version number to check if it differs and requires downloading.
If we need to update OpenTok in the future we can just modify this version number in the Makefile.
@stephencelis does this look ok? I'm not super familiar with Makefile and shell scripts.

Version OpenTok in Makefile

---

LiveStream/Service/LiveStreamService.swift

Whoops! I changed the live stream subscribe toggle api request to post `JSON` because it looked neater in the code but I didn't realise that the API was specifically expecting form data, and because we don't have any real error handling on this call it _appeared_ to work at the client but was in fact not. My bad!
This is a quick fix, I'm going to do more work to create an envelope struct for this response and do some proper error handling and tests for it.

Send subscribe toggle as form data, not JSON

---

Library/ViewModels/DiscoveryFiltersViewModel.swift

hey it's me again, just filtering backings, don't mind me
in case you forgot:
> We filter user's backed projects from recommendations on web, and we also filter them in the native Thanks activity. Filtering them here will homogenize the backer experience across our platforms and stop people from asking jeff what's up with that rec engine.
> 
> The Thanks activity also filters backings from staff picks, so that's a possibility here.
cc. @kickstarter/native-squad

 Filter backings from recommended projects

---

Library/SelectableRow.swift
Library/Tests/ViewModels/DiscoveryFiltersViewModelTests.swift

Filters backed projects in the DiscoveryFilterViewModel tests in response to #74.
🍤

:shrimp: Filter backings in discovery filter tests :shrimp:

---

Library/Tests/ViewModels/ProjectPamphletViewModelTests.swift
Library/ViewModels/ProjectPamphletViewModel.swift

This is a quick fix for refreshing a project's live streams when the project page appears.
Alternatively we could be more specific about only doing this when dismissing a live stream/replay but it would require more delegate calls etc due to the nested nature of the project page and the fact that live streams are launched on `ProjectPamphletContentViewController` and fetched in `ProjectPamphletViewModel`.
Perhaps worth doing that though?

Refresh live streams on project page appearing

---

LiveStream/ViewModels/LiveVideoViewModel.swift
LiveStream/ViewModels/LiveVideoViewModelTests.swift
LiveStream/Views/Controllers/LiveVideoViewController.swift

@theginbin picked up a tasty bug which caused two live streams to play over one another when navigating to the live stream from discovery, tapping 'go to project page' and then once again navigating to the live stream. The video would continue in the background and the new one would start over it.
I initially thought this was going to be a doozy and that we'd have to trash the OpenTok session and recreate it etc causing a weird experience, but it turns out that all we need to do is unsubscribe and resubscribe the subscribers from and to the session.
In the case of HLS it's a simply `pause()` and `play()` on the `AVPlayer`.

Pause live video on disappear/reappear

---

Kickstarter-iOS/Views/Controllers/LiveStreamDiscoveryViewController.swift
Library/Tests/ViewModels/LiveStreamDiscoveryViewModelTests.swift
Library/ViewModels/LiveStreamDiscoveryViewModel.swift

This adds a couple of different ways that the Live Stream Discovery view will be refreshed to avoid navigating back and seeing 'stale' cards that are perhaps no longer live and now in replay, or were upcoming and are now live, etc.
It will refresh the following ways:
- when `isActive` is set to `true` (causes a fetch as before)
- when `isActive` is set to `false` (clears data source as before)
- when the view disappears and reappears
- when the app returns from the background
- when 5 minutes has passed
All of these will only emit when `isActive` is `true`.
Having done all of this I'm now no longer sure if this is really what we want, it feels like there are just so many ways that this view can be refreshed, but it's done and seems to work fine so let me know what you think!

Refreshing of the Live Stream Discovery view

---

Library/Tests/TestHelpers/TestCase.swift
Library/Tests/ViewModels/LiveStreamDiscoveryLiveNowCellViewModelTests.swift
Library/ViewModels/LiveStreamDiscoveryLiveNowCellViewModel.swift

Let's not do the live streaming in discovery when the user isn't on wifi. This was a point brought up by @sarenji with regards to people with slow internet and people who need to conserve cellular data.
We have a  `reachability` signal producer in the app environment that emits the current value immediately and then any new values as they come. We simply combine this into the signals that control playing/stopping the video and _BAM_. That easy.

Don't stream vid in discovery when not on wifi.

---

Library/Tests/ViewModels/LiveStreamEventDetailsViewModelTests.swift
Makefile

Not sure when we lost this, but we want any swiftlint warning to be treated as an error in circle.

Make swiftlint error in circle when there are warnings

---

Kickstarter-iOS/Tests/ViewModels/UpdateViewModelTests.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/UpdateViewModel.swift
Kickstarter-iOS/Views/Controllers/ActivitiesViewController.swift
Kickstarter-iOS/Views/Controllers/DiscoveryPageViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectActivitiesViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectUpdatesViewController.swift
Kickstarter-iOS/Views/Controllers/UpdatePreviewViewController.swift
Kickstarter-iOS/Views/Controllers/UpdateViewController.swift
Library/Koala/Koala.swift
Library/Tests/ViewModels/ProjectUpdatesViewModelTests.swift
Library/ViewModels/ProjectUpdatesViewModel.swift

* Instrumented a couple of update events 
* Fixed a navigation bug (Safari browser opened when it shouldn't) when you tap through Update indexes
Bug:
Fix:

Instrument updates, fix update load bug

---

Library/Tests/ViewModels/LiveStreamContainerViewModelTests.swift
Library/ViewModels/LiveStreamContainerViewModel.swift

We recently had an issue where we'd receive a past `LiveStreamEvent` which was parsing successfully by Argo but met none of the filter criteria for it to pass through the signal that configures our `LiveStreamViewController`.
We allow pretty much all events through and our error handling which was always in place deals with them appropriately.
- Back in the days of `Project.LiveStream` we would always fetch the corresponding `LiveStreamEvent` when landing on the `LiveStreamContainerViewController`.
- We made more decisions about whether we were live or in replay etc based on playback states rather than values on the `LiveStreamEvent`. But this became confusing so we decided to mostly rely on the latter.
Now here's where it gets interesting 🍿:
- During the removal of `Project.LiveStream` …

Improve error handling for past live streams without replays

---

Library/Koala/KoalaTrackingClient.swift

This is a p bad one :(
The over tracking issues we are having comes from a small logical typo from our Swift 3 #26 conversion. It's unfortunately on some untested code, but @stephencelis and I will fix that soon.
The issue is that we never remove successfully tracked events from the event queue, and so we keep on re-tracking those events as the user continues using the app more.

Fix an over-tracking issue.

---

Kickstarter-iOS/Tests/ViewModels/UpdateViewModelTests.swift
Kickstarter-iOS/ViewModels/UpdateViewModel.swift
Kickstarter-iOS/Views/Controllers/UpdateViewController.swift
Library/Koala/Koala.swift
Library/Tests/ViewModels/ProjectUpdatesViewModelTests.swift
Library/ViewModels/ProjectUpdatesViewModel.swift

The pr #103 added some tracking to updates that isn't needed since it's done on the server side. So just removing that and correcting a few small things.

Remove unneeded update tracking.

---

Kickstarter-iOS/Views/Controllers/LiveStreamContainerViewController.swift
Kickstarter-iOS/Views/Controllers/LiveStreamCountdownViewController.swift
Kickstarter-iOS/Views/Storyboards/Activity.storyboard
Library/Styles/BaseStyles.swift

This is just for posterity, but #104 messed with some nav bar styles on our live streaming controllers and this fixes that. Will merge when tests pass.

Fixed live styles

---

.swiftlint.yml

SwiftLint is migrating to a more robust YAML parser (libYAML, see https://github.com/realm/SwiftLint/pull/1411). The previous parser wasn't spec-compliant and actually accepted invalid YAML sequences as input.
This commit makes .swiftlint.yml pass validation at http://www.yamllint.com.

fix validation errors in .swiftlint.yml

---

Kickstarter-iOS/ViewModels/RootViewModel.swift
Kickstarter-iOS/ViewModels/RootViewModelTests.swift

During #107 I picked up that logging in while a modal view controller was presented on `LiveStreamDiscoveryViewController` caused it to disappear. This was due to a `combineLatest` in `RootViewModel`'s `filterDiscovery` output.
Changing this to a `takePairWhen` solves the problem.
This will affect logging in to subscribe in the current live build when presented from live discovery.

Prevent login filtering Discovery

---

Kickstarter-iOS.playground/Sources/playgroundController.swift

Hi guys. As I was shamelessly copy/pasting your awesomely useful playgroundController.swift to our project ❤️ I noticed a couple of things. 
For us, it's useful to see the interface on 4/4S as well as iPad Pro 12 inch size, so I've added them to the `Device` enum. Though Apple want devs thinking in terms of traits rather than sizes, it's still useful to double check stuff on these sizes anyways, at least for us.
And a small fix for 5/5S/SE height as well.
And thanks again for this treasure trove of great code. I hope to contribute in a more substantial way sometime to give back!

Playground ViewController Sizes

---

circle.yml

just caught this note on circleci about deprecating Xcode "8.3" in order to force using an 8.3.x and so thought I might as well bump us to the newest 8.3.2
https://discuss.circleci.com/t/we-are-deprecating-the-xcode-8-3-build-image/12115

Update to Xcode 8.3.2

---

Kickstarter-iOS/Views/Controllers/DiscoveryViewController.swift

We've been seeing a number of crashes with the following message:
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [views count] == 3'`
Pretty much all searches for this type of crash suggest that the call to `UIPageViewController` `setViewControllers(_:direction:animated:completion:)` is not happening on the main thread.
Example: http://stackoverflow.com/questions/24000712/pageviewcontroller-setviewcontrollers-crashes-with-invalid-parameter-not-satisf
I've not been able to reproduce this but according to Hockey it seems to be happening frequently enough on app startup for it to be something we'd want to solve.
I added a symbolic breakpoint to trace the first call to `-[UIPageViewController …

Possible fix for setViewController crash

---

Library/Koala/Koala.swift
Library/Koala/KoalaTests.swift
Library/ViewModels/LiveStreamChatViewModel.swift
Library/ViewModels/LiveStreamChatViewModelTests.swift

Koala tracking event for when a chat message is sent.
Also removed a redundant tracking method that should've been removed from #107.

Track sent chat message

---

Kickstarter-iOS/Views/Controllers/LiveVideoViewController.swift
Kickstarter.xcodeproj/project.pbxproj
Makefile

We are getting some strange start up crashes on iOS 9 devices:
```
Dyld Error Message: 
Dyld Message: Symbol not found: _kABPersonAddressCityKey 
Referenced from: /private/var/containers/Bundle/Application/0CD4EEF4-5A94-4891-9FBF-FA459B87F3F9/Kickstarter.app/Frameworks/Kickstarter_Framework.framework/Kickstarter_Framework 
Expected in: dyld shared cache 
in /private/var/containers/Bundle/Application/0CD4EEF4-5A94-4891-9FBF-FA459B87F3F9/Kickstarter.app/Frameworks/Kickstarter_Framework.framework/Kickstarter_Framework 
Dyld Version: 390.7
```
The `_kABPersonAddressCityKey` is something in AddressBook.framework, which we only link in our app because of Firebase (a dependency of live streaming) requires it. I tried just removing it to see what happens... everything still seems to work?

Remove AddressBook.framework

---

Kickstarter-iOS/Views/LiveStreamNavTitleViewTests.swift
Library/ViewModels/LiveStreamChatViewModel.swift
Library/ViewModels/LiveStreamContainerPageViewModelTests.swift
Library/ViewModels/LiveStreamContainerViewModel.swift
Library/ViewModels/LiveStreamNavTitleViewModel.swift
Library/ViewModels/LiveStreamNavTitleViewModelTests.swift
LiveStream/Models/LiveApiError.swift
LiveStream/Models/LiveStreamChatMessage.swift
LiveStream/Models/LiveStreamChatMessageTests.swift
LiveStream/Models/templates/LiveStreamChatMessageTemplates.swift
LiveStream/Service/LiveStreamService.swift

During our testing we picked up that the view count on the live stream stopped updating and that chat messages would also randomly stop feeding through.
- Number of people watching timeout check is a one-time thing now.
- `LiveStreamChatMessage`s that fail to decode will simply be discarded.
- We don't care about the format of the `userId` anymore on these messages.
We chatted about this on Slack but the reason number of people was failing after a little while is because I had a 10 second timeout which would basically check if there was no response from that firebase path within 10 seconds of loading the stream it should switch to HLS. I didn’t realize however that it would expect a value _every_ 10 seconds or it would consider it to have timed out. So I’ve now just moved things around so …

Live chat fix view count and messages fix

---

Kickstarter-iOS/Views/Controllers/ProjectCreatorViewController.swift
Library/ViewModels/ProjectCreatorViewModel.swift
Library/ViewModels/ProjectCreatorViewModelTests.swift

We have a small bug in that users can tap to message creators while they are logged out but then upon sending their message receive an error saying that they need to be logged in ([Trello](https://trello.com/c/nISUH4vr/1963-logged-out-ask-a-question-button-allows-user-to-start-drafting-message)).
This PR just adds the fix to present the `LoginToutViewController` when attempting to message the creator while logged out. It seems that there was a `.messageCreator` `LoginIntent` for this already so I just used that.

Login to message creator

---

Kickstarter-iOS/Views/Controllers/LiveVideoViewController.swift

Quick fix for a bug that crept in with #145 - because we now do set the `delegate` on our `OTSubscriber` views we need to nil that delegate just before removing the subscribers.

Nil delegate when removing subscriber view

---

Library/ViewModels/LiveStreamChatViewModel.swift
Library/ViewModels/LiveStreamChatViewModelTests.swift

We found a bug that is causing the keyboard to be arbitrarily dismissed during chat. We observe `UIDeviceOrientationDidChange` to dismiss the keyboard when rotating to landscape and transitioning the video to full screen. However the code doesn't take into consideration the orientation changes between `faceUp` and `faceDown` causing it to dismiss on those changes while in `portrait`.
I've just added a `filter` to ensure that the orientation `isLandscape`.

Chat keyboard dismiss fix

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift

Turns out there are two types of routes that can go to a survey, and we were only looking for one in our deep linking code. The unfortunate side effect of that is a user would tap a survey link in their email, it would deep link them to the app, and they would be just left there :(

Recognize other type of survey deep link

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
Library/Navigation.swift

Right now our routing systems has a big ole list of URLs on Kickstarter that we want to recognize in a variety of situations, e.g. when inspecting requests in a web view, and when deep linking into the app.
Sometimes we want to use a different set of recognizable routes depending on the situation we are routing. In particular, when deep linking there is a smaller set of routes we want to recognize, and then anything we don't recognize can bump the user back to mobile safari.
That's what this PR does...
There are smarter ways to do this, and would love to try it out soon, but this will do the job and is well tested!

Make an allow list of deep linkable routes

---

Kickstarter-iOS/Views/Storyboards/DiscoveryPage.storyboard

Gradient position in project card were shifting on reuse because of conflicting storyboard constraints. Before the project view overlay's leading, trailing and top space was constrained to the superview, now it is constrained to the leading, trailing, and top space of the project image.

Discovery Gradient fix

---

Kickstarter-iOS/Views/Controllers/CheckoutViewController.swift
Kickstarter-iOS/Views/Controllers/RewardPledgeViewController.swift

There is a crash that is affecting a small number of users where if you first choose not to do Apple Pay in the reward pledge screen, but then later decide to use Apple Pay from the credit card page, you will get a crash once you drill down to the thanks screen. This is happening because the checkout view is removed from the navigation stack, and that is where the pay sheet had been presented from, and something deep in the bowels of UIKit doesn't like that :/
Turns out though, we totally don't need to be messing with the nav stack during this flow. Let's just push the thanks screen onto the stack. We already hide the back button on that screen anyway...

Fix ApplePay crash

---

Kickstarter-iOS/Views/Controllers/SearchViewController.swift

Related to https://github.com/kickstarter/kickstarter/pull/6769.
In the above PR we changed a feature flag which was enabling `observeForUI()` on 10 percent of users and internal admins.
This PR removes the check from our code in anticipation of the feature flag being removed from the web at a later stage.
`observeForUI` still crashes so we want to always `observeForControllerAction`.

Always observeForControllerAction when scrollToProjectRow

---

Kickstarter-iOS/DataSources/DiscoveryFiltersDataSource.swift
Kickstarter-iOS/DataSources/DiscoveryFiltersDataSourceTests.swift
Kickstarter-iOS/Views/Controllers/DiscoveryFiltersViewController.swift
Kickstarter.xcodeproj/project.pbxproj
Library/ViewModels/DiscoveryFiltersViewModel.swift
Library/ViewModels/DiscoveryFiltersViewModelTests.swift

I found a bug while trying to fix other bugs that I was attempting to reproduce in airplane mode. This uncovered the fact that tapping the Discovery Filter without any network connection could crash the app as it attempts to remove the row for the loader indicator that was never added if the network request immediately failed.
Changes in this PR:
- Only return an `IndexPath` to delete if a row was really removed.
- Only animate the row deletion if there's a row to delete.
- Reload the table view after adding the loader indicator row to be sure.
I also noticed that in the corresponding test file the VM was being used directly and not via it's protocol type so just corrected that 👍

Prevent discovery filter crash on network error

---

Library/Koala/Koala.swift
Library/ViewModels/LoginViewModelTests.swift

replaced property _1password_extension_available_ with property _one_password_extension_available_ for _Viewed Login_ tracking event. Kept property _1password_extension_available_ for _User Login_ event intact because it is marked as deprecated and will be removed..  
Reference Trello card: Update 1password property

One pass availability reporting

---

LICENSE

Just noticed that we still had template text in our LICENSE file 🙂

Replace template text

---

Kickstarter-iOS/Views/Controllers/CommentsViewController.swift

A description of the change.
Back this project button on empty comments returns you to update, not project page.
Used `popToRootViewController` to present the the project page.

Back project button in comments fix

---

Kickstarter.xcodeproj/project.pbxproj

I added a bunch of our dependencies back as embedded binaries in the app target.
When we moved KsApi into the main app repo a whole lot of things moved around and I forgot to test that it was building correctly on device 😞, it was fine on simulator and Circle (also simulator).
Tested this on my device and seems good! But please test a device build too.

Add libraries back as embedded binaries

---

Kickstarter.xcodeproj/project.pbxproj

This just reverts our code signing back to manual for CircleCI and moves Result and Runes frameworks into the correct places.
@christopherwright found that `gym` had an issue with code signing on Circle and it seems that I somehow committed Automatic Code Signing **enabled** in Xcode somewhere during #185. This is only necessary to make it simpler for building on device during development so I've reverted it to manual. After doing that I discovered the way that Result and Runes were being included also wasn't working for `gym` so I moved things around:

Fix code signing on Circle

---

Kickstarter-iOS/DataSources/ProjectPamphletContentDataSource.swift
Kickstarter-iOS/DataSources/ProjectPamphletContentDataSourceTests.swift
Kickstarter-iOS/Views/Cells/NoRewardCell.swift

TIL a bit more about what our `ValueCell`s do behind the scenes! Namely: their associated data type is bound directly to the data source's index paths. We recently removed the project type from our "No Reward" cell configuration (we weren't using it in the function directly), but this broke the connection for no-reward pledging! Here's a quick lil fix and quick lil test.

Bind project to no reward cell

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift

This is a PR on top of @bormind's PR for push notification opt-in and out. I thought this would be the easiest way to explain a refactor. I will make comments inline to explain the changes, which are mainly to clean up the flow of input/outputs based on the [Apple dev guide](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/index.html#//apple_ref/doc/uid/TP40008194-CH3-SW1) and avoid the use of the protocol/enum wrapper for `UNAuthorizationStatus`.  Let me know what you think @bormind @justinswart @stephencelis!
**The revised flow:**
_For iOS 10:_
On app launch, we should call `requestAuthorization(options: UNAuthorizationOptions, completionHandler:)` for new users or users with undetermined notification authorization status. …

revise push handling

---

Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

Updated code in `ProjectPamphletViewModel` that constructs an `HTTPCookie` to use our `DateProtocol` type on `AppEnvironment`.
`ProjectPamphletViewModelTests.testTracksRefTag()` keeps randomly failing on Circle and I think it has to do with equality of `HTTPCookie`s being set in the `Set<HTTPCookie>` on `MockCookieStorage`. Usually rebuilding on Circle fixes it but then it subsequently fails again.
I noticed that the code which we were using to create `HTTPCookie`s was not using our `DateProtocol` type on our `AppEnvironment` and therefore in tests it would not be using `MockDate` so results in tests could be unpredictable. Perhaps the two `HTTPCookie`s that we are constructing in this test might have a different `created` date property and are seen as unique when they're added to the …

Use MockDate when constructing HTTPCookie

---

Kickstarter-iOS/DataSources/MessageThreadsDataSource.swift
Kickstarter-iOS/DataSources/MessageThreadsDataSourceTests.swift
Kickstarter.xcodeproj/project.pbxproj

Was testing something for @tiegz  and found a bug where we didn't have the correct reuse identifier for empty Messages cells! Woops. This fixes that as well as points us to `master` on `ReactiveExtensions` with @stephencelis's  latest update.

Fix reuseIdentifier for empty message cells

---

Kickstarter-iOS/ViewModels/UpdateViewModel.swift
Library/Format.swift
Library/Koala/Koala.swift
Library/ViewModels/RewardPledgeViewModel.swift

Real quick PR to satisfy a new swiftlint rule.
See swiftlint's [releases](https://github.com/realm/SwiftLint/releases) for more info but they said it best:
> Add private_over_fileprivate correctable rule to check for top-level usages
of fileprivate and recommend private instead. This is in line with
SE-0169's goal "for fileprivate to be used rarely". There is a also a new
strict_fileprivate opt-in rule that will mark every fileprivate
as a violation (especially useful with Swift 4).
Literally just ran `swiftlint autocorrect` for this one.

Prefer private over fileprivate

---

Kickstarter-iOS/Views/Controllers/BackerDashboardViewController.swift
Kickstarter-iOS/Views/Controllers/DiscoveryViewController.swift
Kickstarter-iOS/Views/Controllers/LiveStreamContainerPageViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectNavigatorViewController.swift

Page view controllers [need to have their child view controllers configured before rendering](https://developer.apple.com/library/content/documentation/WindowsViews/Conceptual/ViewControllerCatalog/Chapters/PageViewControllers.html#//apple_ref/doc/uid/TP40011313-CH4-SW10), so let's avoid any signal-based races.
We push all our logic into our signal chains, which means we've seen a few sporadic crashes around page view controllers rendering before they've been fully configured. This is a naive fix for these outlier crashes.

Pre-configure page view controllers to avoid potential race/crash

---

Library/ViewModels/DiscoveryPostcardViewModel.swift
Library/ViewModels/DiscoveryPostcardViewModelTests.swift

This just improves how we set the `hidden` attribute of the `metadataView` in `DiscoveryPostcardCell`.
@ktman noticed that we were incorrectly showing the project of the day label on saved projects:
Previously we had two separate signals, one that emitted the metadata and another that set the `hidden` attribute based on whether or not there _should_ be metadata. The change here is just to base the latter on the former.
Also added more tests for the `metadataViewHidden` output.

Fix project of the day label visibility

---

KsApi/models/ProjectStatsEnvelope.swift
KsApi/models/ProjectStatsEnvelopeTests.swift
KsApi/models/lenses/ProjectStatsEnvelope.ReferrerStatsLenses.swift
Library/ViewModels/DashboardReferrerRowStackViewViewModel.swift
Library/ViewModels/DashboardReferrersCellViewModel.swift
Library/ViewModels/DashboardReferrersCellViewModelTests.swift

Referrer data comes back as a decimal, but we were converting to `Int`, losing precision along the way.

Dashboard data fix

---

NOTICE.md
README.md

Add a few licenses for third-party dependencies. If the dependency is contained within this repository, or it's included as a submodule under the Kickstarter org, I've included its license under `NOTICE.md`.
Ensuring we comply with licenses from our dependencies.

Add licenses for more third-party dependencies

---

Kickstarter-iOS/Views/Controllers/MessageDialogViewController.swift
Kickstarter-iOS/Views/Storyboards/Messages.storyboard

Quick fix to bring back the cancel button on `MessageDialogViewController`.
It's needed to dismiss the dialog if one does not want to send a message.
I think it might have been removed during #224, so if "Cancel" was the default in the Storyboard then the button would have no text not not appear.

Put cancel button back on MessageDialogViewController

---

.fastlane/Fastfile
circle.yml

Some changes needed to build our app using Xcode 9 on CircleCI.
Changes are:
- Set CircleCI to use Xcode 9
- Allow fastlane's `gym` command to timeout after 30 mins
`gym` seems to take nearly 20 mins to successfully compile our app now and this was failing with the default 10 min timeout option. Increasing this to 30 mins gets us successful deployments. I would suggest that we keep an eye on this and if we see these times dropping in the future we can try removing this option.

CircleCI Xcode 9 updates

---

Kickstarter-iOS/Views/Controllers/SearchViewController.swift
Kickstarter-iOS/Views/Storyboards/Search.storyboard

On iOS 11 and the iPhone X our search text field broke:
This is possibly due to a change in the way that iOS 11 handles `intrinsicContentSize` for `UITextField`.
Changed the structure of the view a bit and added some more explicit height and width constraints.

Fix search bar layout constraints

---

Library/SafariActivity.swift
Library/ViewModels/ShareViewModel.swift

Fixed a bug that caused our shared links to copy twice to the paste board.
iOS 11 introduced a bug in that our shared links would be concatenated and therefore not share correctly.
This seems to be caused by putting a `URL` object directly into the `activityItems` array that we pass to instantiate a `UIActivityViewController`. iOS 11 appears to incorrectly interpret this in some way.
However we _do_ need to pass a URL to `activityItems` so that it is passed to our `SafariActivity` so that we can present the _Open in Safari_ item.
Proposed solution here is to wrap the `URL` in a `SafariURL` so that iOS 11 does not try to internally interpret it but still passes it to our `SafariActivity` so that we might.
Not sure if this is the best way to go about it but it does seem to fix the issue, …

Fix double paste bug

---

Kickstarter-iOS/Info.plist

This pull request adds `ksr.dev` to the ExceptionDomains list, so that KSR devs can run the app in the simulator against APIs running locally.

Adds ksr.dev support

---

Kickstarter-iOS/Info.plist

Fix date localizations.
The app was showing American date format for all languages (iOS 11).
Adding manually the supported localizations .

Added supported localizations to CFBundleLocalizations

---

Kickstarter-iOS/Info.plist
Library/FormatTests.swift

Added Format tests for Japanese and just made our language identifiers consistent for `CFBundleLocalizations`.

Add format tests, consistent language identifiers

---

Kickstarter-iOS/Views/Cells/RewardCell.swift
Kickstarter-iOS/Views/Storyboards/RewardCell.xib
Library/ViewModels/RewardCellViewModel.swift
Library/ViewModels/RewardCellViewModelTests.swift

Added Shipping summary on page rewards.
https://trello.com/c/sJ5bI434/95-display-shipping-metadata-on-project-page-rewards

Added shipping metadata on page rewards

---

Kickstarter-iOS/Views/Cells/RewardCell.swift
Library/ViewModels/RewardCellViewModel.swift
Library/ViewModels/RewardCellViewModelTests.swift

This is a bug fix for the manage pledge button resizing. 
Manage Pledge Button was compressing whenever it was tapped because the `footerStackView` was becoming visible on tap.
button compressed on tap

Manage pledge button fix

---

Kickstarter-iOS/Views/Controllers/DiscoveryViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletViewController.swift
Kickstarter-iOS/Views/Storyboards/Discovery.storyboard
Kickstarter-iOS/Views/Storyboards/ProjectPamphlet.storyboard
Kickstarter-iOS/Views/Storyboards/Search.storyboard
Kickstarter-iOS/Views/Transitions/ProjectNavigatorTransitionAnimator.swift
Library/ViewModels/DiscoveryViewModel.swift
Library/ViewModels/ProjectPamphletViewModel.swift

Fixes Discovery header height discrepancy.
https://trello.com/c/lXSjlfPa/195-discovery-header-height-discrepancy
This discrepancy occurred due the new safeArea on XCode 9. So while with iOS 10 the layout would look normal (header keeping the same height as Search, Activity, etc), with iOS 11 an extra space(safeArea) is added to the top, making the Discovery header look taller than the other tabs.

Ios11 compatibility tweaks

---

Kickstarter-iOS/Views/Controllers/ProjectPamphletViewController.swift

Fixed layout of project page when the view is loaded due deeplink, notification interaction or after dismiss Reward page.
https://trello.com/c/ByhEfJkd/217-p2-project-page-header-is-misaligned-after-exiting-reward-view
Updating constraints when `viewDidLayoutSubviews()` is called, instead of `viewDidAppear(animated:)`.
**Before :**
**After :**

Fixed project layout when page opens from deeplink

---

Library/ProjectActivityItemProvider.swift

Fixed bug that didn't show link while sharing project.
https://trello.com/c/QzFxcdqA/218-p2-no-link-when-sharing-project.
Appending the url to the project name.
#

Fixed bug that didn't show link while sharing project

---

Kickstarter.xcodeproj/project.pbxproj
Library/UITableViewCell+SeparatorCatch.swift

We've been having a bizarre crash for a large number of users running on iOS 11.
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView setDrawsWithVibrantLightMode:]: unrecognized selector sent to instance 0x15defa6d0'`
This _only_ happens to users that have `Darken colors` enabled under accessibility settings.
It seems that this in an internal bug in UIKit, this message is being sent but the selector doesn't exist.
Simple fix - add an extension that implements the method name but does nothing when it's called.

Add catch for non-existent method name in iOS 11

---

.gitmodules

Update the url for Argo to use https instead of http
While running `make bootstrap` on my machine (macOS Sierra with git 2.7.2), I got this error:
Apparently http is no longer supported by Github ¯\_(ツ)_/¯ So I thought maybe this will help someone who tries to set thing up locally.
N/A
N/A
N/A

Change Argo's url from http -> https

---

Kickstarter-iOS/Info.plist
Library/UIPageViewController+Extensions.swift

Added new iOS 11 `NSPhotoLibraryAddUsageDescription` privacy key.
Some of our users are experiencing crashes (`__CRASHING_DUE_TO_PRIVACY_VIOLATION__`) and adding this key to the info.plist could solve this problem.

Privacy violation crash fix

---

Kickstarter-iOS/Views/Controllers/DiscoveryPageViewController.swift
Kickstarter-iOS/Views/Controllers/DiscoveryViewController.swift
Kickstarter.xcodeproj/project.pbxproj
Library/UIPageViewController+Extensions.swift
Library/ViewModels/DiscoveryPageViewModel.swift
Library/ViewModels/DiscoveryPageViewModelTests.swift

Fixes a bug that shows the EmptyState screen when user selects any personal filter (Recommended, Saved...).
https://trello.com/c/cQlCKsYS/275-p2-empty-states-appearing-for-personalized-discovery-filters
The `showEmptyState` signal was emitting because `paginatedProjects` sometimes sends false empty arrays (first sending an empty array and sending an array of Projects right after). This behaviour was making the app show the EmptyState screen when we actually had projects to be shown.

Bug fix - Recommended filter

---

Kickstarter.xcodeproj/project.pbxproj
Library/ProjectActivityItemProvider.swift
Library/ProjectActivityItemProviderTests.swift

A fix for a bug on which didn't allow users to share projects with 3rd-party social networks.
https://trello.com/c/UPQLLZdj/323-p2-sharing-still-not-working-for-some-contexts
Our code were return Project name as default for 3rd-party social networks. Now the default is name + url.

Third party sharing bug

---

Kickstarter-iOS/Views/Controllers/ProjectCreatorViewController.swift
Library/ViewModels/ProjectCreatorViewModel.swift
Library/ViewModels/ProjectCreatorViewModelTests.swift

Inside a project: tapping on Creator's name > Project cover, a webView is presented instead of taking the user back to the project.
https://trello.com/c/AMqoLZxB/227-inside-a-project-tapping-on-creators-name-project-cover-thing-launch-of-web-view
Adding a logic that compares the request URL(when tapping the WKWebView) and project URL. If they are the same, we should go back to the project page.

Project image tap event bug

---

KsApi/models/Config.swift
KsApi/models/ConfigTests.swift
Library/Koala/Koala.swift
Library/Koala/KoalaTests.swift

Change the place where we send `current_variants` property with Koala events.
Because we were sending `current_variants` with `Viewed Discovery` Koala event, the property was being renamed to `discover_current_variants`, what doesn't exist on the backend.

Koala event fix

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Library/Navigation.swift
Library/NavigationTests.swift

Before deep linking into project campaign faqs and update would only take user to the homescreen. Links work properly now.
UPDATES:
FAQ:
For now, the faq links take the user to the campaign description and from there the user can see the faqs by tapping on the faq button. This is because we do not have a native view for faq.

Links to project update fix

---

KsApi/models/Config.swift
Library/ViewModels/DiscoveryPostcardViewModel.swift
Library/ViewModels/DiscoveryPostcardViewModelTests.swift

Added A/B experiment to show/hide creators name on PostCardCell.
The previous experiment called `ios_test_test` was renamed to `show_created_by_discovery` and now contains logic to show/hide creators name based on the bucket the user is in.

Implemented creators name A/B experiment

---

KsApi/models/Project.Video.swift
KsApi/models/Project.swift
KsApi/models/lenses/Project.VideoLenses.swift
KsApi/models/templates/Project.VideoTemplates.swift
Library/ViewModels/VideoViewModel.swift
Library/ViewModels/VideoViewModelTests.swift

Adds support for hls streaming on iOS.
Creators now can create HD videos, and by adding HLS support, we allow users to watch these videos on iOS.

Add HD video support

---

Kickstarter-iOS/Views/Controllers/CheckoutViewController.swift
Kickstarter-iOS/Views/Controllers/SurveyResponseViewController.swift

- Update WKUIDelegate to match swift 4 signature.
https://trello.com/c/EnGIhpb5/522-p0-revert-thanks-page-to-native-screen
- Swift 4 changed the WKUIDelegate protocol functions signature. This was causing a bug where the app was showing webviews when should present native views, and the reason for that is, because we had outdated code, the delegate methods were not being called.

[Bug Fix] App showing webview ThanksPage instead of native screen.

---

Library/Koala/Koala.swift

Added current_variants to missing event.
A Koala event wasn't sending current_variant of `default_rec_projects` experiment.

Added current_variants to missing event

---

Kickstarter-iOS/Library/WebViewController.swift
KsApi/ServiceType.swift
KsApi/models/Config.swift

Fixes an issue where user-agent header was being overwritten with a default value,  making some `Completed Checkout` events be shown  as `client_type = web`.
https://trello.com/c/pl9yHIQ0/543-native-clienttype-detection

User agent fix

---

Kickstarter-iOS/Views/Controllers/ProjectUpdatesViewController.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/models/Config.swift
Library/DataSource/ValueCellDataSource.swift
Library/ViewModels/ProjectUpdatesViewModel.swift
Library/ViewModels/ProjectUpdatesViewModelTests.swift

Fixed crash caused when user tapped email link on Project Updates.
The app was treating links with url scheme `mailto:` as a safari link, instead of email. Because the WebView couldn't handle this kind of url, the app crashed.

Crash on email link fix

---

Kickstarter-iOS.playground/Pages/Buttons.xcplaygroundpage/Contents.swift

Update of the playground to the newer `UIControlProtocol` API
The playground was throwing errors.
Some method was changed, however, the playground was not updated.
For instance: 
- ` title(_ for: _)`  -> `title(_ forState: _)`

Updated to methods changes

---

.fastlane/Fastfile

It seems that we now need to specify the target in `get_version_number` since switching to CircleCI 2.0, this might be due to a newer version of Fastlane being used.
https://docs.fastlane.tools/actions/get_version_number/

Specify target in get_version_number

---

.fastlane/Fastfile
.gitignore

Two more quick fastlane-related changes.
1. nil-coalescing the xcode version number for when we run `match` locally.
2. Ignoring some fastlane docs artifacts that are created when we run `match`. As @Scollaco mentioned, we can also use `skip_docs` to do this but it will still create the `report.xml` so I think we should just ignore both in the .gitignore.

Fastlane tweaks

---

.fastlane/Fastfile

Our builds on CircleCI 2.0 have been breaking on the `xcversion` command. This is something we previously needed to run on CircleCI 1.0 because it sometimes had multiple versions of Xcode in the same container. It seems that it's no longer necessary on CI 2.0 and removing this should fix our builds.
Should have tried this sooner, but ¯\_(ツ)_/¯
I've also moved `setup_circle_ci` to the `match_all` lane because it is only needed there.
Related: https://github.com/kickstarter/drip-ios/pull/48

Remove xcversion command from Fastfile

---

Library/PKPaymentRequest.swift
Library/ViewModels/DiscoveryFiltersViewModel.swift

Replace `flatMap` with `compactMap` in some places
Lint was complaining during compilation so I felt like fixing it while waiting for the build
Auto fixed it using xcode

Replace flatMap with compactMap in some places

---

.fastlane/Fastfile

Just a quick change to add the `DripAlpha` app identifier to our match configuration. We're going to use this in Drip and just makes sense to keep these match configs in sync I think.

Add DripAlpha app ID to match

---

.fastlane/Fastfile

Posts messages to Slack whenever Alpha, Beta or Production builds are uploaded to HockeyApp or App Store Connect respectively.
For transparency and easy reference.
Updated our webhook on CircleCI and moved it to the channel that @nnekab suggested.
Will look something like:

Add Slack messages for alpha, beta, production

---

Kickstarter-iOS/Views/Controllers/CheckoutViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletContentViewController.swift
Kickstarter-iOS/Views/Controllers/RewardPledgeViewController.swift
Library/PKPaymentAuthorizationViewController.swift
Library/ViewModels/RewardPledgeViewModel.swift
Library/ViewModels/RewardPledgeViewModelTests.swift

Disable `Discover` card for rewards of projects outside US and non-US users.
We are having problems to complete transactions when projects were funded on these conditions, and to avoid the transactions to fail again, as it's happening now, we are disabling Discover cards for projects outside US and non-US users.
For more details: 
https://trello.com/c/4heDPDAs/274-spike-apple-pay-legacy-issues

Discover card bug fix

---

Kickstarter.xcodeproj/project.pbxproj

The change I made in #397 wasn't correct in that it recursively searched `Frameworks/**` and all targets inherited from this. Instead we should specify the paths more granularly so that Frameworks like Prelude and Argo don't conflict on their shared Runes dependency.
So all targets still inherit the same search paths with `$(inherited)` but just more specifically.

Fix framework paths again 🙈

---

Kickstarter-iOS/Views/Controllers/BackerDashboardViewController.swift

This PR fixes a bug on which the user were not able to see saved projects from `BackerDashboardProjectsViewController`.
There is a `gestureRecognizer` on the view controller that was cancelling user interaction with the cell. UIGestureRecognizer has a property `cancelsTouchesInView`. This property causes `touchesCancelled:withEvent:` or `pressesCancelled:withEvent:` to the view. The default value of this property is `true`, and by setting it to `false`, we reenable the user interactions on the cell.
By setting `cancelsTouchesInView` to false.

Backer Saved projects cell bug fix

---

.circleci/config.yml
.fastlane/Fastfile
bin/fabric.sh

Adds a CircleCI job `refresh_app_store_dsyms` that runs on `alpha-dist-*` branches. This job runs the lane `refresh_dsyms`, which downloads the dSYMs from App Store Connect on the latest version, and uploads them to Crashlytics automatically.
We want Crashlytics to show symbolicated crashes so we can find and fix them more easily, and we want this to happen automatically.
The `refresh_dsyms` lane downloads the dSYM files from the latest release from App Store Connect. Then, it uploads these dSYM files using the `upload_symbols_to_crashlytics` action to Crashlytics. This will happen automatically and in parallel with `alpha-dist-*` builds, which are triggered with every merge into master.
Also adds the `FABRIC_BUILD_SECRET` key to the `Fabric.framework/run` script. Although it seems like …

Automatically refresh dSYMs and upload to Crashlytics

---

Kickstarter-iOS/DataSources/SettingsPrivacyDataSource.swift
Kickstarter-iOS/DataSources/SettingsPrivacyDataSourceTests.swift
Kickstarter.xcodeproj/project.pbxproj

Hide `Private profile` setting from creators.
If the user is a creator, the option to make to profile private shouldn't appear.
On the data source `load` function, we check if the user is a creator before configure the cells, hiding the Private Profile section if that's the case.

Hide private profile setting for creator

---

.fastlane/Fastfile

As the title says - using team name instead of team ID.
App Store Connect seems to be returning the team ID as an integer instead of a string. This could be a regression that they may fix but we can workaround it for now by using our team's name instead of ID. This might actually be a better way of doing this and potentially we should update the other commands too. I've left them alone for now given that they're still working correctly.
- Use `team_name` argument instead of `team_id`.
- Add `ITUNES_TEAM_NAME` environment var to our CircleCI config.

Use team name instead of team ID to download dsyms

---

Kickstarter.xcodeproj/project.pbxproj
Library/Koala/KoalaTrackingClient.swift

Logs our tracking events to Crashlytics.
It should be useful for debugging purposes to have a log of events that occurred leading up to a crash. We tried to do this before in #217 but it never seemed to work (events just never appeared in Hockey crash logs). I've used Crashlytics for this before on previous projects and it worked pretty well.
Replace Hockey log call with Crashlytics call.
https://docs.fabric.io/apple/answers/answers-events.html#custom-event

Log custom events to Crashlytics

---

Library/Environment.swift
Library/Koala/Koala.swift

Once again ensures that this property is only accessed on the main thread.
Turns out #456 didn't completely solve this property being accessed on background threads because `Koala` is sometimes instantiated from a background thread on environment changes. Xcode's main thread sanitizer has been flagging it occasionally.
Implement the following logic:
1. If on main thread at instantiation, set this var.
2. Else on instantiation set it asynchronously on main thread.
3. Continue to observe any changes to it on main thread.

Ensure preferredContentSizeCategory is accessed on the main thread

---

Kickstarter-iOS/Info.plist
Kickstarter.xcodeproj/project.pbxproj
Library/Koala/KoalaTrackingClient.swift

Uses the correct Crashlytics function to log "bread crumb" events in crash logs.
We were trying to do this using Answers and determined that it wasn't working. When I dug into investigating why that was I also found that that's not actually what we wanted 😄. Crashlytics provides a logging function for this very purpose, described [here](https://docs.fabric.io/apple/crashlytics/enhanced-reports.html#custom-logs).
Replaced the `Answers` line with the Crashlytics `CLSLogv` function.
Tested it by forcing a crash and it looks like this on Crashlytics:

Use correct function to log events in crash logs

---

Kickstarter-iOS/DataSources/PaymentMethodsDataSource.swift
Kickstarter-iOS/DataSources/PaymentMethodsDataSourceTests.swift
Kickstarter-iOS/Views/Controllers/PaymentMethodsViewController.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/mutations/PaymentSourceDeleteMutation.swift
KsApi/mutations/inputs/PaymentSourceDeleteInput.swift
Library/ViewModels/PaymentMethodsViewModel.swift
Library/ViewModels/PaymentMethodsViewModelTests.swift

Adds the ability to delete payment methods using standard iOS deletion gestures.
This is a continuation of the work done in #457 to allow users to delete payment methods. This branch is also based off the `feature-payment-methods` branch.
`UITableView` gives us most of this functionality for free so this was fairly straightforward to implement. I've also taken an optimistic UI approach here so the credit card will be removed immediately upon deletion and we will only show it again if an error occurs.
Some ways that we may want to iterate on this:
-  I think we might want to confirm deletion in some way, either through an alert _after_ swiping, but _before_ performing the deletion, or potentially displaying an undo button after animating it away but not committing the deletion.
- I've come …

Delete payment methods

---

Kickstarter-iOS/AppDelegate.swift
Library/Koala/Koala.swift
Library/Koala/KoalaTests.swift
Library/Koala/KoalaTrackingClient.swift

This once again tracks event breadcrumbs to Crashlytics.
- This was first attempted in #217 using Hockey. But that didn't work for unknown reasons (likely _this_ reason).
- It was then attempted again in #461 but that was incorrectly using Answers instead of Crashlytics as explained in #481.
- #481 however also failed because:
- it appears that a race condition with the initialization of Crashlytics itself was causing it to not log any events and just print a warning to the console.
- according to [this](https://stackoverflow.com/questions/48112623/issue-with-crashlytics-logging-when-using-crashlytics-in-a-dynamic-framework), using the logging function in a framework other than that in which Crashlytics was initialized, will cause it to fail.
This (really) should solve it once and for all …

Crashlytics breadcrumbs final final

---

Kickstarter-iOS/ViewModels/RootViewModel.swift
Kickstarter-iOS/ViewModels/RootViewModelTests.swift
Kickstarter-iOS/Views/Controllers/ActivitiesViewController.swift
Kickstarter-iOS/Views/Controllers/ActivitiesViewControllerTests.swift
Kickstarter-iOS/Views/Controllers/BackerDashboardViewController.swift
Kickstarter-iOS/Views/Controllers/DashboardViewController.swift
Kickstarter-iOS/Views/Controllers/DashboardViewControllerTests.swift
Kickstarter-iOS/Views/Controllers/DiscoveryViewController.swift
Kickstarter-iOS/Views/Controllers/LoginToutViewController.swift
Kickstarter-iOS/Views/Controllers/LoginToutViewControllerTests.swift
Kickstarter-iOS/Views/Controllers/RootTabBarViewController.swift
Kickstarter-iOS/Views/Controllers/SearchViewController.swift
Kickstarter-iOS/Views/Controllers/SearchViewControllerTests.swift

Fixes tab bar's tap again gesture to properly scroll top root level controllers.
Due to the fact our main controllers got more complex this functionality got lost in the process.
Explicitly conform to `TabBarScrollable` protocol and properly reference scroll view. The default protocol implementation works just fine for regular view controllers whose top view is `UIScrollView` and we're using custom override for more complex hierarchies.
| --- | --- |
| ![before-logged-out](https://user-images.githubusercontent.com/387596/47815267-26cbbd80-dd0d-11e8-90f0-d637268f6ce7.gif) | ![after-logged-out](https://user-images.githubusercontent.com/387596/47747669-1a306200-dc46-11e8-921e-701c243ba90a.gif) |
| ![before-logged-in](https://user-images.githubusercontent.com/387596/47815280 …

Reference scroll views properly per controller basis

---

Kickstarter-iOS/Views/Controllers/ChangeEmailViewController.swift
Kickstarter-iOS/Views/Controllers/SettingsAccountViewController.swift
Library/Koala/Koala.swift
Library/Koala/KoalaTests.swift
Library/ViewModels/ChangeEmailViewModel.swift
Library/ViewModels/ChangeEmailViewModelTests.swift
Library/ViewModels/ChangePasswordViewModel.swift
Library/ViewModels/ChangePasswordViewModelTests.swift
Library/ViewModels/SettingsAccountViewModel.swift
Library/ViewModels/SettingsAccountViewModelTests.swift

Adds tracking for the following events:
* Viewed Account
* Viewed Change Email
* Viewed Change Password
* Changed Email
* Changed Password
* Resent Verification Email 
Tracking the new settings screens #YOLO
Viewed events are triggered on `viewDidAppear` in order for us to being able to observe navigating to the screen repeatedly on the navigation stack.
Action events are pretty straightforward

Settings tracking vol 2

---

Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-iOS.xcscheme

Randomize test execution order
Now that Xcode 10 has added the ability to make test execution order random we should use this option to prove that tests are independent of each other.
Simply enable this option in scheme editor

Randomize test execution order

---

Kickstarter-iOS/AppDelegate.swift

Changing our global `tintColor` from grey to green, as per [this Trello card](https://trello.com/c/Rpi5qqft), in service of having our alert and action sheet text being green.
This also makes the Beta Tools bug icon (see screenshots) green. I think that's fine though as we don't ship that to production. If anything, it makes it clearer that the user is on the debug build.
- People have been [confused](https://trello.com/c/SMCUxucv) by the grey tint ("is it disabled?")
- Green is our 'brand' color to be used for primary actions
I paired with @dusi on this. We noticed we were already using `self.window?.tintColor` to serve the grey, so just modified to it the desired `ksr_green_700`.
Before | After
--- | ---
Other, non-pictured changed areas:
- Changing Beta Tools environment
- Changing …

Changed global tint color from grey to green

---

Kickstarter-iOS/DataSources/HelpDataSource.swift
Kickstarter-iOS/DataSources/SettingsAccountDataSource.swift
Kickstarter-iOS/DataSources/SettingsAccountDataSourceTests.swift
Kickstarter-iOS/DataSources/SettingsDataSource.swift
Kickstarter-iOS/Views/Cells/SettingsCurrencyPickerCell.swift
Kickstarter-iOS/Views/Controllers/SettingsAccountViewController.swift
KsApi/MockService.swift
Library/SettingsCellType.swift
Library/ViewModels/SettingsAccountViewModel.swift
Library/ViewModels/SettingsAccountViewModelTests.swift

Fixes the crash we were seeing related to the currency picker. This crash would happen if a user tried to show currency picker while the currency change was in progress causing the application to crash.
We really, really, really should ship Settings.
This workaround waits till the currency change requests is done before allowing presenting the currency picker again. This solution would ideally show an activity indicator but since we're planning on completely changing this we should be good for now.
| --- | --- |
| ![before](https://user-images.githubusercontent.com/387596/49550837-ceef1c00-f8a1-11e8-930c-a1f6302e811a.gif) | ![after](https://user-images.githubusercontent.com/387596/49550843-d6aec080-f8a1-11e8-8625-f899bc6bf4db.gif) |
For easy testing, please download and …

Prevent currency picker interaction during requests

---

.fastlane/Fastfile

Use `team_name` instead of `team_id` for `deliver`.
We did this in #462 for uploading dSYMs and should have also made the change for `deliver`. It turns out the team IDs on iTunes Connect changed at some point and it's more future-proof to use team name for this.
Change `team_id` -> `team_name` for `deliver`.

Use team name instead of team ID for deliver

---

KsApi/queries/UserQueries.swift
KsApi/queries/UserQueriesTests.swift

Removes old graphQL mutation queries and update unit tests to test the current queries.
To keep the code clean and to test code that we are actually using 😅

Removed deprecated queries, updated tests

---

Kickstarter-iOS/Views/Controllers/SettingsViewController.swift

Adds accessibility label to the dismiss button & fixes the minimum width of the button in order to follow HIG best practices for tappable elements (44x44 pts)
Better accessibility
Simply adding accessibility label (this will prevent from using the image name)
| --- | --- |
| <img width="782" alt="screen shot 2018-12-19 at 2 32 17 pm" src="https://user-images.githubusercontent.com/387596/50252468-f236c280-039b-11e9-946c-7f6c6ffcfc76.png"> | <img width="782" alt="screen shot 2018-12-19 at 2 33 59 pm" src="https://user-images.githubusercontent.com/387596/50252475-f7940d00-039b-11e9-868d-2575b45dcb06.png"> |
| <img width="785" alt="screen shot 2018-12-19 at 2 32 26 pm" src="https://user-images.githubusercontent.com/387596/50252482-ffec4800-039b-11e9-9cae-f97d3dd43609.png"> …

Accessibility - Settings - Dismiss button

---

Kickstarter-iOS/Views/Cells/SettingsAccountWarningCell.swift

Adds accessibility hint to the `Change email` cell in case the email is unverified.
Better reflects visual UI to Voice Over users
Simply adds `accessibilityHint`. This is so that the order of the reader is as follows: `Change email` - `Button` - `This email address is unverified`. This should be a suitable solution since the information is secondary.
on all the following: iOS 10, iOS 11 & iOS 12
with Voice Over turned ON

Accessibility - Settings - Change email status

---

KsApi/GraphSchema.swift
KsApi/models/Category.swift
KsApi/models/DiscoveryParams.swift
Library/Format.swift
Library/RefTag.swift

Updates conformance to `Hashable` protocol.
This is a required Swiftlint rule which is currently failing branches that are not up to date.
Replace `Hashable` conformance from `var hashValue: Int` to `func hash(into hasher: inout Hasher)`
https://nshipster.com/hashable/
https://github.com/apple/swift-evolution/blob/master/proposals/0206-hashable-enhancements.md

Update conformance to Hashable protocol to make Swiftlint happy

---

Kickstarter-iOS/Views/Controllers/ChangeEmailViewController.swift
Kickstarter-iOS/Views/Storyboards/Settings.storyboard

Groups current email title and value label into one accessible element.
This makes it easier for Voice Over to navigate and more human readable to digest.
Simply disabling accessibility on labels and using a container view as the accessible element.
Side note:
I've renamed some of the labels on the controller due to the lack of clarity they provided.
| --- | --- |
| <img width="494" alt="screen shot 2018-12-21 at 11 37 49 am" src="https://user-images.githubusercontent.com/387596/50360470-fc300100-0514-11e9-9ee8-bf4acb024edd.png"> | <img width="538" alt="screen shot 2018-12-21 at 11 36 57 am" src="https://user-images.githubusercontent.com/387596/50360625-811b1a80-0515-11e9-8e6f-1cfce66ee0b4.png"> |
on all the following: iOS 10, iOS 11 & iOS 12
with Voice Over turned ON

Accessibility - Settings - Change email - Current email

---

Kickstarter-iOS/ViewModels/RootViewModel.swift
Kickstarter-iOS/ViewModels/RootViewModelTests.swift
Kickstarter-iOS/Views/Controllers/BetaToolsViewController.swift
Kickstarter-iOS/Views/Controllers/RootTabBarViewController.swift
Kickstarter-iOS/Views/Controllers/SettingsAccountViewController.swift
Library/Notifications.swift
Library/ViewModels/SettingsAccountViewModel.swift
Library/ViewModels/SettingsAccountViewModelTests.swift

When a user changes their currency, we reload all of the tabs so there is no lag in showing project pledge amounts in the user's selected currency.
When we show a project, we first populate the pledge amount using the current `Project` object from the discovery feed. When a user changes their currency, unless we refresh the discovery feed, the `Project` object from discovery will have a "stale" currency until the "updated" currency is populated on the project page. This appears as a "lag" where the user will momentarily see pledge amounts in the old currency before seem them in their preferred currency.
Now, we refresh all the discovery feeds when users change their currency.
Combined the `languageChanged` notification into `userLocalePreferencesChanged`, which will now fire both when a …

[BUG] Regenerate tab VCs when user changes currency

---

Kickstarter-iOS/Views/Cells/SettingsPrivacyDeleteAccountCell.swift

Updates a11y of the `Delete my Kickstarter account` button to properly say it's a button
This tells users that they can perform an action on this element when focused.
Simply exposing the button instead of the label.
Test under the following conditions
👉 iOS 10, iOS 11 & iOS 12
👉Voice Over ON
👉 In order to test localization prefer to QA with one of the supported language set as the primary 📱 language

♿️ - Settings - Delete my Kickstarter account button

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
Library/Navigation.swift
Library/NavigationTests.swift

Ignores project preview links as these should be handled by mobile safari and not by the app itself.
We don't currently support project preview links in the app but because their URL structure matches a route in our `Navigation` enum the app attempts to open them. This fails and the user is stuck in the app when they should be redirected back out to mobile safari.
- Added a `projectPreview` case to `Navigation` so that we can be sure that a given URL is in fact a preview URL.
- If a match is found, we ignore it by returning `.failure`, thereby using the existing functionality to ignore unrecognized URLs.
https://trello.com/c/4GS7SNZ8

Ignore project preview deep-links

---

Kickstarter-iOS/Info.plist

This adds `ITSAppUsesNonExemptEncryption` to our `Info.plist` with the value of `false`.
Each time that we submit apps to the store we need to confirm that we do not use non-exempt encryption in our app. We only use TLS and make calls over HTTPS which are exempted forms of encryption and we will always answer _no_ to this question on App Store Connect. Adding this flag should mean that when we submit builds to the app store they will automatically be available for internal testing without having to log in and answer this question about encryption.
Edited the `.plist` and added the flag.
https://stackoverflow.com/a/43924708/2271759
https://help.apple.com/app-store-connect/#/devc3f64248f

Add ITSAppUsesNonExemptEncryption to Info.plist

---

Kickstarter-iOS/DataSources/SettingsPrivacyDataSource.swift
Kickstarter-iOS/Views/Cells/ProjectNotificationCell.swift
Kickstarter-iOS/Views/Cells/SettingsFollowCell.swift
Kickstarter-iOS/Views/Cells/SettingsNewslettersCell.swift
Kickstarter-iOS/Views/Cells/SettingsNewslettersTopCell.swift
Kickstarter-iOS/Views/Cells/SettingsPrivacyRecommendationCell.swift
Kickstarter-iOS/Views/Cells/SettingsPrivacyStaticCell.swift
Kickstarter-iOS/Views/Cells/SettingsPrivacySwitchCell.swift
Kickstarter-iOS/Views/Controllers/MessageBannerViewController.swift
Kickstarter-iOS/Views/Controllers/SettingsPrivacyViewController.swift
Library/SettingsSwitchCellType.swift
Library/ViewModels/DashboardProjectsDrawerViewModel.swift
Library/ViewModels/DashboardProjectsDrawerViewModelTests.swift
Library/ViewModels/DashboardViewModel.swift
Library/ViewModels/DashboardViewModelTests.swift
Library/ViewModels/SettingsPrivacyViewModel.swift
Library/ViewModels/SettingsPrivacyViewModelTests.swift

Fixes the accessibility of our Settings cells with `UISwitch` control.
This includes:
* Settings > Account > Privacy
* Settings > Notifications > Project notifications
* Settings > Newsletters
The intention is to simplify the amount of information we expose to VoiceOver reader. Our settings cells that have a `UISwitch` control currently expose multiple elements (label, switch control, header/footer). In order to make it easier for visually impaired users to navigate through settings we only want to expose the `UISwitch` control and provide enough context in form of a label or hint.
Since we're using custom cells we don't get the native behaviour for free. Normally (in order to support accessibility) a `UISwitch` control would be placed inside of a cell's `accessoryView`. This would result …

♿️ - Settings - Switch Toggle Rows 

---

Kickstarter-iOS/Views/Cells/SettingsNotificationCell.swift
Kickstarter-iOS/Views/Cells/SettingsNotificationPickerCell.swift
Library/SettingsNotificationCellType.swift
Library/ViewModels/SettingsNotificationCellViewModel.swift
Library/ViewModels/SettingsNotificationCellViewModelTests.swift

Improves the accessibility of the following rows
* Settings > Notifications > Manage project notifications
* Settings > Notifications > Email frequency
Making a11y great again
Using `accessibilityTraits` and `accessibilityLabel` + `accessibilityValue`
Test under the following conditions
👉 iOS 10, iOS 11 & iOS 12
👉Voice Over ON
👉 In order to test localization prefer to QA with one of the supported language set as the primary 📱 language

♿️ - Settings > Notifications - Manage project notifications + Email frequency

---

.fastlane/Fastfile

This ensures that the path that `fastlane gym` outputs to is always the same as the path that we try to read from.
When we run `fastlane gym` on CircleCI, we have an environment variable called `FL_OUTPUT_DIR` which is set to `output`. This causes any output that `fastlane` actions generate to be put under that path. So for example, `fastlane gym` will output to `./output/gym`. However, when we run this locally that environment variable is not set and so, because I initially tested this locally, I set it to look for the `ipa` file at `.` and not `./output/gym`. This has happened a couple of times before so I decided to try and prevent it going forward.
If we look at our `setup_circle_ci` command in our `Fastfile` it [constructs an environment …

Ensure gym output path is consistent

---

.circleci/config.yml
Makefile
bin/download_framework.sh

Improves our `Makefile` a wee bit by moving duplicated logic for downloading our Stripe and Fabric SDKs into a shared bash script.
We like to keep things DRY and this wasn't being very DRY at all. In the event that we download more frameworks this way during `make bootstrap` this will hopefully make that cleaner.
Extracted the logic that we were using into a shared bash script that receives arguments.
Note that I didn't do this for OpenTok, reasons being that we're likely to remove it soon and the additional complexity of it being a bzip'd tar ball made for a pretty gnarly script to handle that.

Reusable download framework script

---

.circleci/config.yml

Adds a step to all of our jobs in `circle.yml` that run tests that will pre-load the iOS simulator before running those tests.
We've had a bunch of jobs failing with an error that the simulator can't be found:
According to CircleCI it is sometimes useful to [pre-load](https://circleci.com/docs/2.0/testing-ios/#pre-starting-the-simulator) the simulator before running tests to avoid this.
- Added step to pre-load simulator in each job that runs tests.

Add CircleCI step to pre-load simulator before running tests

---

Configs/Secrets.swift.example
Kickstarter-iOS/Views/Controllers/AddNewCardViewController.swift
Library/Environment.swift
Library/ViewModels/AddNewCardViewModel.swift
Library/ViewModels/AddNewCardViewModelTests.swift
Library/ViewModels/PaymentMethodsViewModel.swift
Library/ViewModels/PaymentMethodsViewModelTests.swift

Fixes the following:
- table view should end editing when the user navigates to "Add New Card"
- success message banner should only display *after* the "Add New Card" screen has fully dismissed
🔴 NOTE: Also fixes a bug where switching from production -> staging didn't actually change the Stripe publishable key. This meant you sometimes couldn't add a test card in staging (because Stripe thought you were adding the card to production). Now the `StripePublishableKey` comes from the `Secrets` file. 
Tested on:
- SIM iPhone 5s 10.3.1
- SIM iPhone 7+ 11.4
- SIM iPhone X 12.1
- SIM iPad Pro 12.1

[Payment methods] Minor bug fixes

---

Kickstarter-iOS/Views/Controllers/SelectCurrencyViewController.swift

Should make the tests pass
We need failing tests .. NAAAAT
Please see inline comments..

Make the tests pass

---

Kickstarter-iOS/Views/Controllers/ChangePasswordViewControllerTests.swift
Kickstarter-iOS/Views/Controllers/PaymentMethodsViewController.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/models/DeletePaymentMethodEnvelope.swift
KsApi/models/DeletePaymentMethodEnvelopeTests.swift
KsApi/mutations/PaymentSourceDeleteMutation.swift
Library/ViewModels/PaymentMethodsViewModel.swift
Library/ViewModels/PaymentMethodsViewModelTests.swift

- Disables `Edit` button on `PaymentMethodsViewController` if there's no payment method on the list.
- To improve UX, we should disable the button, since it can't be used if there's no payment method to be edited.
- In order to make this happen, I had to change the `PaymentSourceDeleteMutation` to return the number of remaining cards and created a `DeletePaymentMethodEnvelope` model.
| With Payment Method | No Payment Method |
| --- | --- |
| <img width="300" alt="screen shot 2018-11-27 at 1 50 48 pm" src="https://user-images.githubusercontent.com/3709676/52646831-819ab680-2eb1-11e9-87b2-0f1e5e6bfcb2.png"> | <img width="300" alt="screen shot 2018-11-27 at 1 49 08 pm" src="https://user-images.githubusercontent.com/3709676/52646822-7e072f80-2eb1-11e9-98ea-af29c8bc27cd.png"> |

[Payment methods] Disable edit button if no payment methods

---

Kickstarter-iOS/Views/Controllers/AddNewCardViewController.swift
Kickstarter-iOS/Views/Controllers/PaymentMethodsViewController.swift
Library/ViewModels/PaymentMethodsViewModel.swift
Library/ViewModels/PaymentMethodsViewModelTests.swift

Refreshes payment methods properly
Previously if you have added a new card on iPad, the payment methods table would not refresh due to the way we present the modal. It relies on `UIViewController` lifecycle methods that are called differently when we present things using `.formSheet` modal presentation style.
Causes the view model to re-fetch on "Add New Card" modal success or dismissal.
on iPad..

[Payment methods] Refresh payment methods table view properly

---

Kickstarter-iOS/Views/Controllers/PaymentMethodsViewController.swift
Library/ViewModels/PaymentMethodsViewModel.swift
Library/ViewModels/PaymentMethodsViewModelTests.swift

See the title
Fixing iPad behaviour, caused duplicate calls on iPhone devices.
We've recently added the ability to re-fetch payment methods when the user returns from the `Add new payment method` modal (by submitting or dismissing). In order to consistently perform the fetch action we're using a delegate pattern (mostly because on iPad the view controller lifecycle events are called slightly different when presenting settings with `.pageSheet` presentation style). So where we previously relied on `viewWillAppear` these events worked on iPhones but not on iPads and in order to prevent from duplicate calls we now only cause fetching new data in `viewDidLoad` or explicitly by submitting & dismissing the `Add new payment method` modal or canceling the `Add new payment method` modal.
on iPhone …

[Payment methods] Refetch payment methods on viewDidLoad or explicitly (by delegate)

---

Library/ViewModels/SettingsNotificationsViewModel.swift
Library/ViewModels/SettingsNotificationsViewModelTests.swift

When the Email Frequency picker is opened and then Project Activity email notifications are disabled, the `Email Frequency` cell disappears, but the picker stays open. This PR makes sure the picker dismisses when the `Email Frequency` cell disappears after Project Activity email notifications are disabled.
Better UX, user should not be able to set the email frequency if they disabled Project Activity email notifications.
We check if user disabled the project activity email frequency and dismiss if they did. 
| --- | --- |
| ![dismiss-picker-fix](https://user-images.githubusercontent.com/11362005/52727867-25ed2d80-2f84-11e9-9af7-bc5512bac8d7.gif) |![dismiss-picker-fix-after](https://user-images.githubusercontent.com/11362005/52727942-4ddc9100-2f84-11e9-9da5-a51154ac4470.g …

Dismiss email frequency picker

---

Kickstarter-iOS/Views/Cells/CreditCardCell.swift
KsApi/models/UserCreditCard.swift
Library/ViewModels/CreditCardCellViewModel.swift
Library/ViewModels/CreditCardCellViewModelTests.swift

VoiceOver starts reading the credit card cell with the name of the card.
Better VoiceOver experience
What is obvious to non-visually impaired users by seeing the credit card icon should be conveyed to visually impaired users using VoiceOver.
"Simply" concatenating the card name and card name information.
with VoiceOver ON

[Payment methods] A11y - Credit card name

---

Kickstarter-iOS/Views/Controllers/PaymentMethodsViewController.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/models/DeletePaymentMethodEnvelopeTests.swift
KsApi/models/GraphUserCreditCard.swift
KsApi/models/GraphUserCreditCardTests.swift
Library/ViewModels/CreditCardCellViewModel.swift
Library/ViewModels/CreditCardCellViewModelTests.swift
Library/ViewModels/PaymentMethodsViewModel.swift
Library/ViewModels/PaymentMethodsViewModelTests.swift

- Makes `type` in `GraphUserCreditCard` optional, to support unknown credit card types.
- Adds error handling for fetching payment methods.

[Payment Methods] Support optional card type and error handling for payment methods

---

Kickstarter-iOS/Views/Controllers/AddNewCardViewController.swift
Kickstarter-iOS/Views/Controllers/ChangeEmailViewController.swift
Kickstarter-iOS/Views/Controllers/ChangePasswordViewController.swift

Fixes potential reference cycles caused by not using `[weak self]` in a closure that references `self`.
Because leaks are bad.

Fixing potential reference cycles

---

.github/PULL_REQUEST_TEMPLATE.md

Adds before/after table to the PR template under the `👀 See` section.
This should make it easier to provide before/after screenshots side by side.
| --- | --- |
| <img width="375" alt="screen shot 2019-02-19 at 11 53 08 am" src="https://user-images.githubusercontent.com/387596/53043276-fa16ef80-343c-11e9-8d50-52e5337b5d73.png"> | <img width="376" alt="screen shot 2019-02-19 at 11 52 55 am" src="https://user-images.githubusercontent.com/387596/53043266-f2574b00-343c-11e9-9b14-d77e01f22af5.png"> |

Add before/after table to the PR template

---

Kickstarter.xcodeproj/project.pbxproj
Library/HelpType.swift
Library/HelpTypeTests.swift

Uses link accessibility trait for each row that presents a website.
This should give visually impaired users more context to where is this action going to take them.
Simply decide on the row type and return either `.link` for actions that navigate the user to a website or `.button` for presenting the mail composer to contact support.
navigating to `Settings > Help`, VoiceOver reads the following cells like so

♿️ [Voice Over] Settings > Help Accessibility Traits

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/mutations/inputs/CreatePasswordInput.swift

Extend ServiceType (Service, MockService) with the mutation graph call that allows users to create a new password.
Needed for create password feature for Facebook users w/o a password.
**Testing Procedures to trigger call:**
Navigate to `Settings > Account` if you deleted your password successfully you should not see the `Change email` or `Change password` cells.
```
// SettingsAccountViewModel.swift
// SettingsAccountViewModelOutputs
// L: 25
var createPasswordSuccess: Signal<Void, NoError> { get }
var createPasswordFailure: Signal<String, NoError> { get }
// L: 177
public let createPasswordSuccess: Signal<Void, NoError>
public let createPasswordFailure: Signal<String, NoError>
//public init
// L: 79
let createPasswordOnLoad = self.viewDidLoadProperty.signal
.map { …
```

🔑 [Create Password] Extend ServiceType

---

.circleci/config.yml

Increases the timeout for tests running on CircleCI to 20 minutes.
We've been having some arbitrary timeouts while tests are running on some of our builds:
In the past these were _mostly_ resolved by increasing the timeout limit.
Added `no_output_timeout` for test steps in test jobs.
https://circleci.com/docs/2.0/configuration-reference/

Increase timeout for tests to 20 minutes

---

Library/Styles/BaseStyles.swift

Uses default (system) font for the navigation bar title in order to prevent from allowing resizing when the font size changes.
More native behaviour.
| --- | --- |
| <img width="504" alt="screen shot 2019-02-19 at 9 00 55 pm" src="https://user-images.githubusercontent.com/387596/53067547-7f27f600-3489-11e9-99df-c6a5641b878e.png"> | <img width="504" alt="screen shot 2019-02-19 at 8 59 09 pm" src="https://user-images.githubusercontent.com/387596/53067509-4daf2a80-3489-11e9-82c3-36fd5a0b62aa.png"> |

♿️ [Dynamic Type] Navigation bar title

---

.fastlane/Fastfile

Retrieves the Apple ID username for `match` from an environment variable instead of being hard-coded.
We've updated the Apple ID for our CI purposes and we would prefer to retrieve this value from an environment variable going forward. We do this elsewhere in our `Fastfile` so it makes sense to be consistent.
- Updated the var on CircleCI.
- Added it to our `match` arguments.

Use environment var for match username

---

Kickstarter-iOS/Views/Controllers/SelectCurrencyViewController.swift

Fixes a regression from the currency preferences UI refactor which re-introduced a bug that caused latency in seeing project pledge amounts in your preferred currency.
Re-adds the `.ksr_userLocalePreferencesChanged` notification on the `didUpdateCurrency` signal in `SelectCurrencyViewController`. This notification causes all the view controllers in `RootViewModel` to be regenerated.
Note both of these recordings were taken with the Network Link Conditioner set to "3G" to simulate slow connection.
| --- | --- |
| ![mlhqmbp66b](https://user-images.githubusercontent.com/3156796/53766180-294b4900-3ea0-11e9-983c-706792ce5643.gif) | ![fhf09ynwrq](https://user-images.githubusercontent.com/3156796/53766243-5697f700-3ea0-11e9-9828-df1522a7c2aa.gif) |

Add ksr_userLocalePreferencesChanged notification on didUpdateCurrency

---

Kickstarter-iOS/Views/LoadingBarButtonItemView.swift
Library/Styles/SettingsStyles.swift

Fixes a bug that prevented fonts in settings from resizing correctly with dynamic type. Also turns off font resizing on the `LoadingBarButtonItemView` since it's a navigation item.
A deep-dive done by @dusi into dynamic type within Settings identified a bug where several labels whose fonts were set using our custom `.ksr_()` functions were not resizing correctly when the font size was changed using the accessibility inspector. An investigation showed that this was due to the helper styling functions in `SettingsStyles.swift` capturing the current context which essentially cached the initial `preferredFont` instead of re-evaluating it every time `bindStyles` was called.
The solution was to convert the `SettingsStyles` helpers that are setting a font into a closure that takes a label and …

Settings Dynamic Type Fixes

---

Kickstarter-iOS/Library/UIImageView+URL.swift
Kickstarter-iOS/Views/Cells/DiscoveryPostcardCell.swift
Kickstarter-iOS/Views/Storyboards/DiscoveryPostcardCell.xib

Friend avatar was showing up as a rectangle. This PR corrects that and shows it as a circle.
Changed class to `CircleAvatarImageView` which makes the image circular.
| --- | --- |
|![img_ffb507d530d2-1 jpeg](https://user-images.githubusercontent.com/11362005/53820430-c6a68b80-3f39-11e9-9523-0f169ff6baa8.jpg)|![simulator screen shot - iphone 8 - 2019-03-05 at 19 30 38](https://user-images.githubusercontent.com/11362005/53847102-79e4a400-3f7d-11e9-8553-08d725c2ba94.png)|

Friend avatar corrected in Explorer

---

Kickstarter-iOS/Views/Controllers/AddNewCardViewController.swift
Kickstarter-iOS/Views/Controllers/ChangeEmailViewController.swift
Kickstarter-iOS/Views/Controllers/PaymentMethodsViewController.swift
Kickstarter-iOS/Views/Controllers/SelectCurrencyViewController.swift
Kickstarter-iOS/Views/Controllers/SettingsAccountViewController.swift
Kickstarter-iOS/Views/SelectCurrencyTableViewHeader.swift
Kickstarter-iOS/Views/SettingsFormFieldView.swift
Library/Styles/BaseStyles.swift
Library/Styles/SettingsStyles.swift
Library/ViewModels/DiscoveryFiltersViewModel.swift

Removes type check warnings by helping the compiler by explicitly setting types.
It's considered best practice to keep warnings down to minimum in order to prevent from warnings bankruptcy which usually causes more warnings to slip into the codebase unnoticed.
Our project build settings uses experimental build flag `-warn-long-function-bodies=1000` (that's 1000ms) to set a type evaluation threshold for the compiler. Every time compiler tries to infer Swift types its evaluation time is considered against this threshold. If it takes the compiler longer than 1000ms, Xcode will show a warning. More about the topic [here](http://khanlou.com/2016/12/guarding-against-long-compiles).
In general this is a good practice. It helps us identify code that could take longer to infer. Unfortunately it …

👩‍🔬 [Investment Day] Clean up compiler warnings

---

Kickstarter-iOS/Views/Storyboards/ProjectPamphlet.storyboard
Kickstarter-iOS/Views/Storyboards/Settings.storyboard

Allows some of our table views to display content below the virtual home indicator on iPhone X/XS and the new iPad Pros.
Following HIG
Simply updates bottom constraint to align to superview's bottom (instead of safe area's bottom).
This allows the content to be displayed below the virtual home indicator but also thanks to table view insets this will never lead to a state that would have content overlaid by the home indicator when the table view is scrolled all the way to the bottom.
| --- | --- |
| <img width="472" alt="Screen Shot 2019-03-18 at 10 28 14 AM" src="https://user-images.githubusercontent.com/387596/54550377-1f7a1900-4969-11e9-913a-3a1a5c91b41f.png"> |<img width="468" alt="Screen Shot 2019-03-18 at 10 28 07 AM" …

📐 Allow tables to display content bellow the virtual home indicator

---

Library/Koala/Koala.swift
Library/Koala/KoalaTests.swift
Library/ViewModels/CreatePasswordViewModel.swift
Library/ViewModels/CreatePasswordViewModelTests.swift

Adds tracking events and tests for the Create Password feature.

[Create Password] Event tracking & tests

---

Library/Koala/Koala.swift
Library/ViewModels/CreatePasswordViewModelTests.swift

Renames the create password events.

Renaming Create Password event

---

Kickstarter-iOS/DataSources/PledgeDataSource.swift
Kickstarter-iOS/DataSources/PledgeDataSourceTests.swift
Kickstarter-iOS/Views/Cells/PledgeRowCell.swift
Kickstarter-iOS/Views/Controllers/PledgeTableViewController.swift
Kickstarter-iOS/Views/Controllers/PledgeTableViewControllerTests.swift
Kickstarter-iOS/Views/Controllers/PledgeViewController.swift
Kickstarter-iOS/Views/Controllers/PledgeViewControllerTests.swift
Kickstarter.xcodeproj/project.pbxproj
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

Basic plumbing for the native checkout feature work
Includes:
- VC + Tests
- VM + Tests
- DataSource + Tests
This should be a starting ground for the follow up work that should make it easy for us to work on different pieces in parallel.
`Simply` creates a `PledgeViewController` that manages its child `PledgeTableViewController` which displays content in form of a table. The reason for wrapping up `PledgeTableViewController` in `PledgeViewController` is so that we can present alert banners or other fancy things. The reason for using `PledgeTableViewController` being a subclass of `UITableViewController` is in order for getting all the keyboard handling functionality & layout resizing for free.
The architecture closely follows `ProjectPamphletContentViewController`.
In order to being able …

💲 [Native Checkout] Plumbing

---

Kickstarter-iOS/Views/Cells/PledgeAmountCell.swift

Sets `UIStepper` images using a lens. 
In order to follow our patterns, we'd prefer to use a lens to set images on a `UIStepper` object.
Since we have previously not used `UIStepper` class in our project this PR is dependent on this work https://github.com/kickstarter/Kickstarter-Prelude/pull/93/files
1. Update submodules
Please make sure to run `make bootstrap` in order to properly update `Prelude` submodule
2. Make screen accessible from user flow
Go to `` and replace `goToRewardPledge` function with the following
```
fileprivate func goToRewardPledge(project: Project, reward: Reward) {
let vc = PledgeViewController.instantiate()
vc.configureWith(project: project, reward: reward)
let nc = UINavigationController(rootViewController: vc)
self.present(nc, animated: true)
}
```
3. Login on …

Set stepper images using a lens

---

Kickstarter-iOS/DataSources/PledgeDataSource.swift
Kickstarter-iOS/DataSources/PledgeDataSourceTests.swift
Kickstarter-iOS/Views/AmountInputView.swift
Kickstarter-iOS/Views/Cells/PledgeAmountCell.swift
Kickstarter-iOS/Views/Cells/PledgeShippingLocationCell.swift
Kickstarter-iOS/Views/Controllers/PledgeTableViewController.swift
Kickstarter.xcodeproj/project.pbxproj
Library/Styles/CheckoutStyles.swift
Library/Styles/CheckoutStylesTests.swift
Library/UIStackView+Tests.swift
Library/UIStackView.swift

Implements UI of the shipping location cell
In the same manner as we've added pledge amount cell we're continuing with shipping location cell.
Please note that this PR only considers visual appearance of the cell and that some values are hard coded + this work still misses user interaction.
This PR is the 1st out of 3 which will also address (passing correct data, formatting shipping amount correctly).
In order to being able to see the screen you can navigate to `ProjectPamphletContentViewController` and change the behaviour of `goToRewardsPledge` function to the following
```
let vc = PledgeViewController.instantiate()
vc.configureWith(project: project, reward: reward)
let nc = UINavigationController(rootViewController: vc)
self.present(nc, animated: true)
```
| …

💲[Native Checkout] Shipping Location Cell 1/3 (UI)

---

Kickstarter-iOS/Views/Cells/PledgeDescriptionCell.swift

Updates our way of inserting tappable links in `UITextView` by generating the `NSAttributedString` directly from HTML.
In #672 and #668 we explored a way to add links to `NSAttributedString` using `UITextView` by searching for specific phrases in that string and applying link attributes to those ranges.
While this is fine in and of itself, it may be problematic when we start to work with translations and try to search for phrases in translated strings. A safer route would be for the entire string to be translated at once and wrap the phrases we care about in anchor tags in good old fashioned HTML.
- Added a hard-coded `String` for now which I'll submit for translation if we're happy with this approach.
- Generated our `NSAttributedString` from that.
Still seems legit:
😕 This appears to be …

💲[Native Checkout] Use HTML string with anchor tags

---

Kickstarter-iOS/Views/Cells/PledgeDescriptionCell.swift
Kickstarter-iOS/Views/Controllers/PledgeTableViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletViewController.swift
Kickstarter-iOS/Views/Controllers/RewardsCollectionViewController.swift
Kickstarter-iOS/Views/Controllers/SheetOverlayViewController.swift

Removes any iOS 11 availability checks from the `feature-native-checkout` work.
We've deprecated iOS 10 🎉

Remove iOS 11 Availability Checks From Native Checkout

---

.circleci/config.yml

Removes Stripe SDK caching from our CircleCI config
This should have been removed in #658 as it is now downloaded by Carthage.

Remove Stripe SDK caching from .circleci/config.yml

---

Kickstarter-iOS/Views/Controllers/RewardsCollectionViewController.swift
Library/ViewModels/RewardsCollectionViewModel.swift
Library/ViewModels/RewardsCollectionViewModelTests.swift

Adds functionality for navigating to the `Pledge` screen when a reward is tapped from the `RewardsCollectionViewController`. Note that right now it's a simple `push` navigation, since we plan on implementing the custom transition in a separate item of work.
So we can finally have an end-to-end flow for the new native checkout experience ❇️ 
Overrides the reward collection view's `collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath)` function, and passes the selected index to the view model as an input. The view model then grabs the reward selected at the given index, and combines it with the project object and the optional `refTag` to pass as an output. The `goToPledge` output is observed and subsequently creates and pushes the `PledgeViewController`. …

💲[Native Checkout] Reward Selection (no animation)

---

Library/TestHelpers/TestCase.swift

Ensures that we only run tests and record screenshots on the iPhone 8 simulator.
If for whatever reason we need to run unit tests on a different device, we can just comment out this line.
It's happened once or twice in the past that we accidentally record a bunch of screenshots on the wrong device which results in thousands of new screenshots being committed to the repo. This is just a safety catch to help us prevent that.
Put a check at the top of `TestCase` `setUp()` function which is called before all tests run.

Ensure tests are only run on iPhone 8

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/ViewModels/RootViewModel.swift
Kickstarter-iOS/ViewModels/RootViewModelTests.swift
Kickstarter-iOS/Views/Controllers/ActivitiesViewController.swift
Kickstarter-iOS/Views/Controllers/RootTabBarViewController.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/models/ClearUserUnseenActivityEnvelope.swift
KsApi/models/ClearUserUnseenActivityEnvelopeTests.swift
KsApi/models/User.swift
KsApi/models/lenses/UserLenses.swift
KsApi/models/templates/UserTemplates.swift
KsApi/mutations/ClearUserUnseenActivityMutation.swift
Library/SharedFunctions.swift
Library/SharedFunctionsTests.swift
Library/ViewModels/ActivitiesViewModel.swift
Library/ViewModels/ActivitiesViewModelTests.swift

Adds the remaining functionality for badging in the app, in particular setting the badge value on the activities tab bar item when various events occur (see ACs below).
We're now receiving badges via push notification payloads and via the `User` model, this adds the necessary functionality to update the UI to accurately reflect those.
- Added inputs to `RootViewModel` so that we can update it when `applicationWillEnterForeground` and when the app is launched from background after having been updated with a badge value and a push notification is tapped.
- Added `ClearUserUnseenActivityMutation` to clear the count on the back-end when the activities tab bar item is selected.
- Added a localized string for the clamped `99+` plus string so that translators can move the `+` around if …

🦡 [App Badges] Update badge value on push and lifecycle events

---

Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
Kickstarter-iOS/Locales/de.lproj/Localizable.strings
Kickstarter-iOS/Locales/es.lproj/Localizable.strings
Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
Kickstarter-iOS/ViewModels/RootViewModel.swift
Kickstarter-iOS/ViewModels/RootViewModelTests.swift
Kickstarter-iOS/Views/Controllers/RootTabBarViewController.swift
Library/Strings.swift

- Adds the localized string for `99+` so that the `+` can be moved around/modified by translators.
- Displays the uncapped badge value when voice over is enabled.
iOS voice over natively reads badge value as "1 item", "2 items", "100 items", etc. This functionality was lost when we displayed the badge value as `99+` when it exceeded `99`, the screen reader would just read "ninety-nine plus". `UITabBarItem` does not provide access to its badge value view and digging through the view hierarchy for `_UIBadgeView` to add an accessibility hint seemed like the wrong approach.
Added an input to `RootViewModel` so that when voice over is enabled or disabled we can display the uncapped or capped badge value respectively.
Enabling and disabling voice-over - note the screen reader focus appearing at …

🦡 [App Badges] Improve voice-over support for badge value

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/Info.plist

Sets `FacebookAutoLogAppEventsEnabled` and `FacebookAdvertiserIDCollectionEnabled` to `false` in our `Info.plist`.
We want Facebook's SDK doing as little as possible in our app, currently we _only_ use it as a convenience for people to sign in and we do not want it logging anything or trying to use our app's advertising identifier.
Set the flags in the plist.
https://developers.facebook.com/docs/app-events/getting-started-app-events-ios/#auto-events

Disable Facebook event and advertiser ID collection flags

---

Kickstarter-iOS/ViewModels/HelpWebViewModel.swift
Kickstarter-iOS/Views/Cells/PledgeDescriptionCell.swift
Kickstarter-iOS/Views/Cells/PledgeSummaryCell.swift
Kickstarter-iOS/Views/Controllers/PledgeTableViewController.swift
Kickstarter.xcodeproj/project.pbxproj
Library/HelpType.swift
Library/ViewModels/PledgeSummaryCellViewModel.swift
Library/ViewModels/PledgeSummaryCellViewModelTests.swift

Adds functionality to open links that are tapped in the `PledgeSummaryCell`. This is one of the TODO items in #715.
When we construct the HTML to build the attributed string for the `UITextView` to display as tappable links, we derive these from the `HelpType`. The `UITextViewDelegate` passes us the `URL` that was tapped and we pass this to our view model for translation back to an `HelpType` which is the expected type for our `HelpWebViewController`.

💲[Native Checkout] Pledge Summary Cell Handle Links

---

Kickstarter-iOS/Views/Controllers/FeatureFlagToolsViewController.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/models/DebugData.swift
Library/AppEnvironment.swift
Library/AppEnvironmentTests.swift
Library/DebugData.swift
Library/Environment.swift

[This PR](https://github.com/kickstarter/ios-oss/pull/705) added support for toggling local feature flags to make it easier to test feature flagged... features 😄. One issue with that PR was that because feature flags are stored in the `Config` object, and the object is refreshed on `ApplicationWillEnterForeground`, our feature flag settings would get reset if you background the app. This could lead to a confusing debugging experience - this PR fixes that issue by "caching" the debug feature flag settings.
See "What".
Store debug settings in `AppEnvironment` and always prefer to take the debug settings, when updating the config.
Notice how backgrounding the app doesn't reset our feature flag setting:

Persist Debug Feature Flags

---

Kickstarter-iOS/Views/PledgeCTAContainerView.swift
Library/PledgeStateCTAType.swift
Library/ViewModels/PledgeCTAContainerViewViewModel.swift
Library/ViewModels/PledgeCTAContainerViewViewModelTests.swift

Fixes `Dynamic Type` issues
Please see inline comments
Please see inline comments

💲[Native Checkout] Project Pledge States UI - UI Fixes

---

Kickstarter-iOS/Views/Cells/PledgeAmountCell.swift
Kickstarter.xcodeproj/project.pbxproj
Library/CharacterSet.swift
Library/CharacterSetTests.swift
Library/ViewModels/PledgeAmountCellViewModel.swift
Library/ViewModels/PledgeAmountCellViewModelTests.swift

Exactly what the title says
We don't want users on iPads or with hardware keyboards to being able to input anything other than digits and decimal separator (localized)
Simply comparing input string to whether it's a numeric or decimal separator (based on `Locale`) and only allowing text field to proceed or not if it validates properly.
On iPad (with SW or HW keyboard connected) or on iPhone with HW keyboard connected (i.e. SIM) try the following input
smaller than 10 will set the text field value to `10` and dismiss keyboard

💲[Native Checkout] Disable non-numeric, non-decimal separator input for the amount

---

Kickstarter-iOS/Views/Controllers/ProjectPamphletViewController.swift
Kickstarter-iOS/Views/PledgeCTAContainerView.swift

Seems like we've mistakenly removed action from the CTA button so this PR re-adds it in order for us to navigate to the checkout workflow.
Please note this also cleans up (removes) now unused property that was previously left out.

💲[Native Checkout] Re-enable the CTA button action

---

LICENSE
NOTICE.md

Updates our `LICENSE` and `NOTICE.md`.
These seemed a little out of date.
- Incremented the year in `NOTICE.md` (when will markdown give us `Date()`?)
- Added 1Password license
- Added Curry license
- Added Runes license
- Updated AlamofireImage license
- Updated Argo license
- Removed Firebase license
- Updated ios-snapshot-test-case license
- Updated ReactiveSwift GitHub URL
- Added Stripe GitHub URL

Update OSS licenses

---

Kickstarter-iOS/Views/Controllers/CheckoutNavigationController.swift
Kickstarter-iOS/Views/Controllers/PledgeViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectNavigatorViewController.swift
Kickstarter-iOS/Views/Controllers/RewardsCollectionViewController.swift
Kickstarter-iOS/Views/Transitions/RewardPledgePopTransitionAnimator.swift
Kickstarter-iOS/Views/Transitions/RewardPledgePushTransitionAnimator.swift
Kickstarter.xcodeproj/project.pbxproj

The initial plumbing for the transition from `RewardCollectionViewController` to `PledgeViewController`.
Decided to break this up into its own PR to make reviewing easier.
- Added `CheckoutNavigationController` which will be the `UINavigationController` subclass for Checkout and can be extended to perform additional animations if necessary.
- Added `RewardPledgePushTransitionAnimator` and `RewardPledgePopTransitionAnimator`. I believe it makes sense to split these into their own animators but am open to refactoring down the line.
This approach is largely inspired by this great series of blog posts: https://devsign.co/notes/navigation-transitions-iii
**Note:** Currently there are no animations and to prove that the correct code paths are being called the push and pop animations will …

💲[Native Checkout] Reward->Pledge Transition Plumbing

---

Library/SharedFunctions.swift
Library/SharedFunctionsTests.swift
Library/ViewModels/ChangeEmailViewModelTests.swift
Library/ViewModels/ChangePasswordViewModelTests.swift
Library/ViewModels/LoginViewModelTests.swift

Last week, we've done some refactoring and broke `1Password` extension functionality in progress. This PR should revert that to the fixed state.
We've introduced semantic changes to our APIs in #731 from `ksr_isOSVersionAvailable` to `ksr_is1PasswordSupported`. We used this API to decide whether to show or hide `1Password` button on screens that provide credentials input. The semantical changes were unfortunately not identical and resulted in negated output 🤦‍♂ So in order for us to properly hide/show the `1Password` button we had to fix the call site.
(Remember, we only want to show `1Password` button on iOS 11 devices with `1Password` app installed)
**Example**
What previously was this
```swift
if ksr_isOSVersionAvailable(12) { /* hides the button */ }
else { /* shows the button …
```

Revert 1Password button hiding logic

---

Kickstarter-iOS/Views/Controllers/ProjectPamphletViewController.swift
Kickstarter-iOS/Views/Storyboards/ProjectPamphlet.storyboard
Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

Fixes the jaggy animation when showing project screen modally.
Hiding the status bar in landscape mode on iPad causes the modal presentation to cause a weird jump. This happens because we're hiding the status bar in landscape even though it's the default thing on iPhone.
| --- | --- |
| <img width="535" alt="Screen Shot 2019-07-12 at 9 34 38 PM" src="https://user-images.githubusercontent.com/387596/61167244-e86bdc80-a4f0-11e9-8ce4-18945ba60ce0.png"> | <img width="535" alt="Screen Shot 2019-07-12 at 9 55 07 PM" src="https://user-images.githubusercontent.com/387596/61167251-f7528f00-a4f0-11e9-8306-cf46001432cf.png"> |
| (there should be no change) | (there should be no change) |
| <img width="535" alt="Screen Shot 2019-07-12 at …

👩‍🔬 [Investment Day] - Project detail - modal presentation

---

Kickstarter-iOS/Views/Controllers/ProjectPamphletViewController.swift
Kickstarter-iOS/Views/PledgeCTAContainerView.swift
Library/ViewModels/PledgeCTAContainerViewViewModel.swift
Library/ViewModels/PledgeCTAContainerViewViewModelTests.swift
Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

Adds an activity indicator to indicate a loading state to the user while the full project is being fetched from the server.
We can't determine the pledge CTA view's state until we have the full project, so instead of showing a blank view we show an activity indicator commonly used to signify content that is being loaded. Once the full project has fetched from the server, we hide the activity indicator and fade in the pledge CTA view with its correct state.
Since the project is fetched from the `ProjectPamphletViewModel`, we need to pass the loading info to the `PledgeCTAView` through it's configuration function. This PR extends the configuration `value` passed into the `PledgeCTAView` into a tuple containing a `Project` object and an `isLoading` `Bool` to communicate the loading state of …

💲[Native Checkout] Activity Indicator for the Pledge View

---

KsApi/ServerConfig.swift

Updates our `local` config graphQL endpoint, which was incorrect before.
So we can run the app against the `local` environment and hit the graphQL endpoint successfully.
Just updated the endpoint.
*Test running the app against the `Local` environment*
Run the app after running `./bin/dev` on the `kickstarter` web repo;
Using the debug menu, change to the `Local` environment;
To test that graphQL requests are working, open the Categories menu;
*You should see the categories load successfully*.

Fix local config graphQL endpoint

---

KsApi/Service.swift

Forces the user agent for all requests to be our custom user agent which has the format:
`"\(app)/\(bundleVersion) (\(model); iOS \(systemVersion) Scale/\(scale))"`
As defined [here](https://github.com/kickstarter/ios-oss/blob/master/KsApi/ServiceType.swift#L515).
Our `Completed Checkout` tracking event has been broken on iOS for some time due to that call being made in a webview via an AJAX request rather than a standard request which we could modify by intercepting the `NSURLRequest` object.
By injecting the custom user agent the back-end will track the request as being a native app request.
Added what appears to be a common workaround for this which is to set a value in `UserDefaults` for `UserAgent` (note: no hyphen).
Charles Proxy screenshots testing on simulator:
| Before 🐛 | After …

🐞[Bug] Force UserAgent value in AJAX requests

---

Library/Koala/Koala.swift
Library/Koala/KoalaTests.swift
Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift
Library/ViewModels/RewardCardContainerViewModel.swift
Library/ViewModels/RewardCardContainerViewModelTests.swift

Please refer to PR https://github.com/kickstarter/ios-oss/pull/784 for the review.
First release events that add tracking events and tests for checkout events in the project page and reward page.

Checkout release events clean

---

Kickstarter-iOS/Views/Controllers/ProjectNavigatorViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletViewController.swift
Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

Fixes the `Back this project` button not doing anything when deep-linking with the native checkout feature flag enabled.
In a moment of confusion when I did this work before I used the `delegate` to present the `RewardsCollectionViewController`. This was unnecessary.
- Moved the presentation to the `ProjectPamphletViewController`.
- Removed `goToDeprecatedRewards` as it serves no purpose 🤦‍♂ 
Easiest way to test this is to make the following changes to these two files:
This will make it easy to test that the view model is deep-linking that URL structure correctly.

Fix "back this project" when deep-linking

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift

Updates config every time a user logs in or logs out (in addition to launching the app or coming back to the app from background).
We've noticed that the config would only refresh after the app has been backgrounded and brought back to foreground. This caused some confusion when logging in as a different user and logging out because the config wasn't properly updated unless the app was backgrounded and brought back to foreground again. This PR fixes that and should always make sure that the config is always up to date even without leaving the app.
Very straightforward, please see the code.
In order to properly test this you'll have to observe your device connection with `mitm` tool like `Charles proxy` or `mitmproxy` (there's a guru card with instructions on how to set this up).

Update config when the session starts and ends

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphSchema.swift
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/mutations/CreateApplePayBackingMutation.swift
KsApi/mutations/inputs/CreateApplePayBackingInput.swift
KsApi/mutations/inputs/CreateApplePayBackingInputTests.swift
Library/Format.swift
Library/FormatTests.swift

Adds the `createApplePayBacking` mutation and mutation input object, with tests. Also, in preparation for sending formatted amounts to the mutation, I've added a new currency formatter that formats currency amounts into doubles with the correct number of fraction digits. This formatting function isn't in use in this PR, but will be used in Part II of this work.
To allow users to pledge using  Apple Pay without going through the legacy API routes.
Adds `CreateApplePayBackingMutation` and `CreateApplePayBackingInput`. Also adds `decimalCurrency(for amount:)` that formats `Double`s into currency strings that can be sent to the API as an input parameter.
Note: this mutation cannot be tested with the existing code. It will be tested in a follow up PR once we integrate the Apple Pay button with …

[Apple Pay] Part 1 - Create Apple Pay Backing Mutation

---

Kickstarter-iOS/Views/Controllers/DeprecatedRewardPledgeViewControllerTests.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletContentViewControllerConversionTests.swift
Kickstarter-iOS/Views/RewardCardContainerViewTests.swift
KsApi/models/Reward.swift
KsApi/models/RewardTests.swift
KsApi/models/lenses/RewardLenses.swift
KsApi/models/templates/ProjectTemplates.swift
KsApi/models/templates/RewardTemplates.swift
Library/ViewModels/DeprecatedRewardCellViewModel.swift
Library/ViewModels/DeprecatedRewardCellViewModelTests.swift
Library/ViewModels/DeprecatedRewardPledgeViewModelTests.swift
Library/ViewModels/RewardCardViewModel.swift
Library/ViewModels/RewardCardViewModelTests.swift

- Shows Rewards converted minimum based on the value of `convertedMinimum` returned by the API.
- This allows us to have one source of truth and avoids the calculation of conversions to be done on the client side.
- Added a new property `convertedMinimum` to our Reward model.
- Changed logic to present the value of that property instead of calculating conversion value based on project conversion rate.
- Updated tests.

[NT-164] Consume Rewards converted minimum from v1

---

Kickstarter-iOS/Views/Controllers/ProjectPamphletContentViewControllerConversionTests.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletContentViewControllerTests.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletViewControllerTests.swift
KsApi/models/Project.swift
KsApi/models/lenses/Project.StatsLenses.swift
KsApi/models/lenses/ProjectLenses.swift
KsApi/models/templates/ProjectStatsTemplate.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift

- Shows converted total pledged based on the value of `convertedPledgedAmount` returned by the API on the Project Page.
- This allows us to have one source of truth and avoids the calculation of conversions to be done on the client side.
- Added a new property `convertedPledgedAmount` to our Project model.
- Changed logic to present the value of that property instead of calculating conversion value based on project conversion rate.
- Updated tests.

[NT-259] Consume v1 converted total pledged on Project Page

---

Kickstarter-iOS/Views/Controllers/PledgePaymentMethodsViewController.swift
Kickstarter-iOS/Views/Controllers/PledgeViewController.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/MockService.swift
KsApi/ServerConfig.swift
KsApi/Service+RequestHelpers.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/mutations/CreateApplePayBackingMutation.swift
KsApi/mutations/inputs/CreateApplePayBackingInput.swift
KsApi/mutations/inputs/CreateApplePayBackingInputTests.swift
Library/CreateApplePayBackingInput+Constructor.swift
Library/CreateApplePayBackingInputConstructorTests.swift
Library/EnvironmentType.swift
Library/Format.swift
Library/FormatTests.swift
Library/PKPaymentRequest+Helpers.swift
Library/PKPaymentRequestHelpersTests.swift
Library/ViewModels/AddNewCardViewModel.swift
Library/ViewModels/DeprecatedRewardPledgeViewModel.swift
Library/ViewModels/PledgePaymentMethodsViewModel.swift
Library/ViewModels/PledgePaymentMethodsViewModelTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

The feature branch containing all of the work integrating Apple Pay into the new Pledge screen.
Note: all this code has already gone through review.
PRs included:
#832 
#828

[NT-15] Users may pledge with Apple Pay

---

Kickstarter-iOS/Views/Controllers/PledgeViewController.swift
Kickstarter-iOS/Views/Controllers/RewardsCollectionViewController.swift
KsApi/mutations/inputs/CreateApplePayBackingInput.swift
KsApi/mutations/inputs/CreateApplePayBackingInputTests.swift
Library/CreateApplePayBackingInput+Constructor.swift
Library/CreateApplePayBackingInputConstructorTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

Passes through the `refTag` from the project page all the way to the `createApplePayBacking` request.
So we can track the referrer on Apple Pay backings.
Passes the `RefTag` from the project page to the `PledgeViewController`, which then passes it as part of the mutation input for the `createApplePayBacking` mutation. The `refTag` is always optional.
To test Apple Pay transactions, you must run the app on a device that is Apple Pay capable.

[NT-261] Pass refParam with Apple Pay backings

---

KsApi/mutations/CreateBackingMutation.swift

The structure of the `Checkout` object that the `createBacking` mutation uses has changed, which broke deserialization of the response for the `createBacking` mutation. Adding the missing fields fixes the issue.
Luckily I think this has exposed an area of improvement for how we build graph mutations. There needs to be a way to indicate the relationship between a mutation and it's expected response object - right now we don't test for this, which is why this change could be added without failing any tests or sounding any red flags. It's good that we're now aware of this and can work on a solution to prevent this from happening in the future.
Adds the two missing fields to the `CreateBackingMutation`.
Pledging works again:

Add missing fields to createBacking mutation

---

Kickstarter-iOS/Views/Controllers/PledgeViewController.swift
Library/ViewModels/ChangeEmailViewModel.swift
Library/ViewModels/ChangePasswordViewModel.swift
Library/ViewModels/PledgeAmountViewModel.swift
Library/ViewModels/PledgeAmountViewModelTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

If a user enters incorrect pledge amount (bellow `min` or above `max`) and taps the `Apple Pay` button we now show an alert with more instructions.
Since Apple is not fond of disabling `Apple Pay` button we have to have a way of local validation of the input when user goes through `Apple Pay` path.
Simply checking the input & its min, max values when evaluating the `Apple Pay` button tap logic.
Please note that this PR is mostly tests since we're now passing more values in the `amount` tuple so our tests suite had to be updated to account for those.
On device that supports `Apple Pay` (has `Apple Pay` setup in the `Wallet.app`) go to the new pledge screen and

[NT-329] Show alert when using invalid pledge amount with Apple Pay

---

Library/ViewModels/FeatureFlagToolsViewModel.swift
Library/ViewModels/FeatureFlagToolsViewModelTests.swift

#877 has recently broken the way we can toggle feature flags ON and OFF so this PR fixes that.
The toggling was previously broken due to sorting only being applied to the data source (not the actual data being sorted).
`reloadWithData` did get the sorted array while `updateConfigWithFeatures` did not ... therefore when the data was fetched from the server in un-sorted order it would cause weird behaviour (the data displayed would not reflect the data being toggled ON/OFF).
This PR should fix that by both applying sort to `updateConfigWithFeatures` as well as adding tests to cover this case.
In order to test this we should test both scenarios. For that please put the following code in `FeatureFlagToolsViewModel.swift` on line `46`.
Since the feature toggles are returned in random order you …

[NT-409] Fix issue with feature flags ordering

---

Kickstarter-iOS/Views/Controllers/PledgeAmountViewController.swift
Library/ViewModels/PledgeAmountViewModel.swift
Library/ViewModels/PledgeAmountViewModelTests.swift

Before the stepper step value was being incremented by the minimum amount that can be pledged to the reward. Now step value is set to `1.0`
This is a bug fix.
Removed the `stepperStepValue` output as it is no longer set to the minimum value.
| --- | --- |
|![before-increment-fix](https://user-images.githubusercontent.com/11362005/67042216-6b569180-f0f5-11e9-8cb8-20459ab3ddd6.gif)|![increment-fix](https://user-images.githubusercontent.com/11362005/67042226-727d9f80-f0f5-11e9-9945-8d5ded28f748.gif)|
The pledge amount should increment by 1 currency unit (e.g. tapping + on the stepper increases my pledge from $10 to $11).

[NT- 401] Pledge increment fix

---

Kickstarter-iOS/Views/Cells/RewardCell.swift
Kickstarter-iOS/Views/Cells/SettingsFollowCell.swift
Kickstarter-iOS/Views/Cells/SettingsPrivacyDeleteAccountCell.swift
Kickstarter-iOS/Views/Cells/SettingsPrivacyRecommendationCell.swift
Kickstarter-iOS/Views/Cells/SettingsPrivacyRequestDataCell.swift
Kickstarter-iOS/Views/Cells/SettingsPrivacySwitchCell.swift
Kickstarter-iOS/Views/Controllers/FeatureFlagToolsViewController.swift
Kickstarter-iOS/Views/Controllers/ManagePledgeSummaryViewController.swift
Kickstarter-iOS/Views/Controllers/PledgeAmountViewController.swift
Kickstarter-iOS/Views/Controllers/PledgeContinueViewController.swift
Kickstarter-iOS/Views/Controllers/PledgeDescriptionViewController.swift
Kickstarter-iOS/Views/Controllers/PledgeSummaryViewController.swift
Kickstarter-iOS/Views/Controllers/RewardsCollectionViewController.swift
Library/ViewModels/RewardsCollectionViewModel.swift

- Makes viewModels explicitly conform to their respective protocols.
- As pointed by @dusi , by doing that we avoid classes to access viewModels properties directly, making the access possible strictly by `inputs`.
- Searched for viewModels failing to follow that pattern and replaces `let viewModel = ViewModel()` with `let viewModel: ViewModelType = ViewModel()`.

[NT-453] [Investment Day] - Fix ViewModels protocols conformance

---

Kickstarter-iOS/Views/Controllers/PledgeViewControllerTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

Fixes a crash on `PledgeViewController` when the devices is rotated or the dynamic type size is changed.
Because crashes are bad.
This crash was due to some strange async-like behavior when parsing an html string using:
```
NSMutableAttributedString(
data: Data(string.utf8),
options: [
.documentType: NSAttributedString.DocumentType.html,
.characterEncoding: String.Encoding.utf8.rawValue
],
documentAttributes: nil
)
```
We're not super sure what's actually the root cause of this issue, since during debugging we were able to see that this call was happening on the main thread. What we observed was that parsing an html string would actually cause a subsequent call to `traitCollectionDidChange` to occur in what would appear to be an infinite loop. Debouncing the trigger to the …

[NT-400] Pledge View attributedString crash fix

---

Library/Format.swift
Library/ViewModels/PledgeCTAContainerViewViewModel.swift
Library/ViewModels/PledgeCTAContainerViewViewModelTests.swift

Users can now view their pledge amount correctly if they pledged w/ a decimal value.
Some background context on why the change is needed.
`func formattedPledge(amount: Double, project: Project) -> String`  formats the backing amount. If the user backed with a whole amount we drop the decimal places.
| --- | --- |
|![Simulator Screen Shot - iPhone Xs - 2019-10-24 at 15 32 10](https://user-images.githubusercontent.com/11362005/67518792-78363080-f673-11e9-8e55-51ba367d0dc8.png)|![Simulator Screen Shot - iPhone Xs - 2019-10-24 at 15 28 33](https://user-images.githubusercontent.com/11362005/67518540-f8a86180-f672-11e9-9cc4-5f2bd6be1035.png)|

[NT-241]  Decimal Pledge Amount  in Manage Pledge CTA Fix

---

Kickstarter-iOS/Views/Controllers/ManagePledgeViewController.swift
Library/ViewModels/ManagePledgeViewModel.swift
Library/ViewModels/ManagePledgeViewModelTests.swift

User can now contact the creator.
Backers can get questions regarding their pledge/rewards answered by creators.

[NT-451] Contact Creator Flow

---

Kickstarter-iOS/Library/SharedFunctionsTests.swift
Library/CreateApplePayBackingInputConstructorTests.swift
Library/CreateBackingConstructorTests.swift
Library/SharedFunctions.swift

Allows us to update our backing to No Reward.
A bug existed on the back-end which was preventing this. That has since [been fixed](https://github.com/kickstarter/kickstarter/pull/17818) and this updates the app to support it.
Pass a relay ID of `0` when updating to No Reward.

[NT-488] Allow users to update to No Reward

---

Kickstarter-iOS/Views/LoadingButton.swift

Fixes a small bug which left our button title empty after the loader was hidden.
This was just a small oversight in #892.
Fixed what was essentially just a copy-paste error.
| --- | --- |
| <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/67822051-50343c00-fa7c-11e9-8352-7ea35b22959d.png"> | <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/67821978-1c591680-fa7c-11e9-8007-ad29a1a0fe60.png"> |

[NT-394] Fix loading button title restoration

---

Kickstarter-iOS/Views/Controllers/PledgeDescriptionViewController.swift

Fixes a app-freezing bug in the simulator when adjusting text size using the accessibility inspector in _Manage pledge_ views.
Although this didn't appear to be happening on device we do often adjust text sizes with the inspector and this affects our development workflow. Also this seemed to point out something problematic in the layout and warranted further investigation.
- Added a `guard` clause to prevent calculating the thumbnail size when `PledgeDescriptionViewController` is hidden.
We hide `PledgeDescriptionViewController` when we are in any of the _Manage pledge_ flows other than _Choose another reward_. When this view is hidden it's not necessary to try to calculate the thumbnail size.

[NT-498] Prevent app freezing with accessibility inspector

---

Library/Koala/Koala.swift
Library/Koala/KoalaTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

Improvements in monitoring user behavior for v1 checkout. This tracks update payment methods.
We now have the `Update Payment Method Button Clicked` event.

[NT-486] Tracking event for Update Payment Method

---

Kickstarter-iOS/Locales/de.lproj/Localizable.strings
Kickstarter-iOS/Locales/es.lproj/Localizable.strings
Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
Library/Strings.swift
Library/ViewModels/PledgeStatusLabelViewModel.swift
Library/ViewModels/PledgeStatusLabelViewModelTests.swift

Continues the work in #934 and adds the strings that would be seen on `ManagePledgeViewController` to describe the `Backing.Status` in a creator context.
It is possible for a creator to see this information when navigating to a backing via their dashboard.
Added strings and tests!

[NT-532] Add backing status strings for creator context

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
KsApi/lib/Route.swift

- Ensures that `identifierForVendor` is set in our visitor cookie before fetching the config.
- Adds a `no_cache` query param to the request that fetches the config to ensure that it is not cached.
We've found that in some scenarios, logging out in particular, we refresh the config without a visitor cookie being set. This causes unexpected behaviour in the way our A/B experiments work as the back-end depends on the identifier in this cookie in order to place the user into the experimental or control group.
We've also noticed that we are sometimes receiving `304 Not Modified` responses to our requests for the user config. We always want a fresh config when we request one.
- Moved the code that sets our visitor cookie to just before we fetch the user config.
- I added a test to ensure that …

[NT-581] Re-set visitor cookie before fetching config

---

Library/Extensions/Feature+Helpers.swift
Library/Extensions/Feature+HelpersTests.swift
Library/Feature.swift
Library/ViewModels/FeatureFlagToolsViewModel.swift

Adds the `ios_go_rewardless` feature flag to our beta tools menu.
Allows us to feature-flag the upcoming _Go Rewardless_ editorial campaign.
- Added the flag to the back-end in https://github.com/kickstarter/kickstarter/pull/18139.
- Added it to our `Feature` `enum`.

[NT-589] Add ios_go_rewardless feature flag to beta tools

---

.circleci/config.yml
bin/danger.sh

Does not run Danger on PRs from external contributors.
We received an external contribution recently and the CircleCI workflow that runs Danger is failing because it does not have access to `DANGER_GITHUB_API_TOKEN`.
- Moved the command that we previously used to execute Danger into a bash script and updated it so that it will not run if this environment variable is not available.
- This is the solution described in Danger's docs for not exposing environment vars - https://danger.systems/guides/troubleshooting.html#i-want-to-only-run-danger-for-internal-branches
- CircleCI also recommends [explicitly disabling](https://circleci.com/docs/2.0/oss/#pass-secrets-to-builds-from-forked-pull-requests) passing of secrets to builds that run on forks.

[NT-620] Skip danger for external contributors

---

Kickstarter-iOS/DataSources/DiscoveryProjectsDataSourceTest.swift
Kickstarter-iOS/Views/Cells/DiscoveryEditorialCell.swift
Kickstarter-iOS/Views/Controllers/DiscoveryPageViewController.swift
Kickstarter-iOS/Views/Controllers/EditorialProjectsViewController.swift
Library/RefTag.swift
Library/ViewModels/DiscoveryEditorialViewModel.swift
Library/ViewModels/DiscoveryEditorialViewModelTests.swift
Library/ViewModels/DiscoveryPageViewModel.swift
Library/ViewModels/DiscoveryPageViewModelTests.swift

Fills in the navigation from `DiscoveryEditorialCell` -> `DiscoverPageViewController` -> `EditorialProjectsViewController` -> `DiscoverPageViewController` -> `ProjectNavigatorViewController` and ensures that the correct `RefTag` makes it through to the end.
Continuation of the works for our Go Rewardless editorial campaign.
- Updated delegate methods to pass `DiscoveryParams.TagID` value.
- Inferred the `RefTag` from `DiscoveryParams` as it had been done before.
- Updated tests.

[NT-593] Editorial Project Navigation

---

Library/Koala/Koala.swift
Library/Koala/KoalaTests.swift
Library/ViewModels/DiscoveryPageViewModel.swift
Library/ViewModels/DiscoveryPageViewModelTests.swift

#📲 What
Adds required tracking to the editorial header feature.
So we can track how this feature performs.
- adds `Editorial Card Clicked` tracking event when the editorial header on the Discovery screen is tapped
- cleans up our usage of the `Config` in `Koala`
- added missing tests for `current_variant` default properties
- added `enabled_feature_flags` to the `defaultProperties` for better tracking of features controlled via feature flag
N/A
N/A

[NT-621] Editorial header tracking

---

KsApi/models/Project.swift
KsApi/models/ProjectTests.swift
KsApi/models/User.swift
KsApi/models/UserTests.swift
Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift
Library/ViewModels/ProjectNavBarViewModel.swift
Library/ViewModels/ProjectNavigatorViewModel.swift
Library/ViewModels/ProjectNavigatorViewModelTests.swift
Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

Cleans up our project events, properties and tests to align with new requirements.
So that we're sending only what is needed for analytics purposes.
Lots of moving around and renaming things, deleting un-used props, and adding better test coverage.
N/A
N/A
The following properties are part of the `projectProperties` group, and are sent with all `Project` events:

[NT-688] Project events & properties clean up

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift
Library/UIDeviceType.swift

#📲 What
Adds clean user properties and session properties, with tests.
Part of the data cleanup project.
- cleans up `defaultProperties` and rename to `sessionProperties`
- adds `userProperties` to decouple user props from session props
Now, instead of having user properties in the `defaultProperties` function, we build them separately and join all properties together with:
```
let props = self.sessionProperties()
.withAllValuesFrom(userProperties())
.withAllValuesFrom(eventProperties)
```
Note that unfortunately, we're not in a good place to test some of the session properties that don't have mocks. I've made a note and filed a separate tech debt ticket to address this so we can be sure to test all session properties in the near future.
N/A
N/A
Verify that the following session …

[NT-645] Clean user properties & session properties

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift
Library/ViewModels/DiscoveryFiltersViewModelTests.swift
Library/ViewModels/DiscoveryPageViewModelTests.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift
Library/ViewModels/SettingsAccountViewModelTests.swift

Updates some of the naming of certain props to reflect latest changes from insights team. Also adds white-listing on "clean" events, so that only white-listed events are sent to the data lake.
More event cleanup and ensuring that only clean events go to the data lake.
N/A
N/A
Testing white-listing:
Testing discovery props changes:

[NT-707] Naming changes and white-listing clean events

---

Library/Tracking/TrackingClientConfiguration.swift
Library/Tracking/TrackingClientConfigurationTests.swift

Prepares requests sent to our Data Lake tracking endpoint with authentication headers.
Pass the request to our `Service.preparedRequest()` function before returning it to the client.
Inspect requests in Charles:

[NT-692] Prepare Data Lake Request with auth headers

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift
Library/ViewModels/RootViewModelTests.swift

Renames some props, consolidates others that were essentially duplicate.
More cleanup following sync with Product.

[NT-645] More tweaks to property names and cleanup

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift

Adds `category` and `subcategory` `id`s to project properties, and removes `rewards_count` and `updates_count` since we don't have that data at the point of tracking – we'll add these back in the near future.
Clean up of tracking events.
More in-depth discussion of the change or implementation.

[NT-645] Adding category_id and removing rewards and updates counts

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
Library/Extensions/Feature+Helpers.swift
Library/Extensions/Feature+HelpersTests.swift
Library/Feature.swift

Adds `language` and `logged_in` custom properties as well handling `ios_qualtrics` feature flag.
We need additional custom properties in order to do more granular filtering for Qualtrics intercepts. We only want to show surveys to logged in, English-language users.
- Added the custom properties.
- Added the feature flag.
- Added tests.

[NT-717] Add Qualtrics custom properties and feature flag

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift
Library/ViewModels/DeprecatedRewardPledgeViewModelTests.swift
Library/ViewModels/RewardCardContainerViewModel.swift
Library/ViewModels/RewardCardContainerViewModelTests.swift

#📲 What
Adds pledge properties as per the new specs.
Event cleanup.
Created a new `pledgeProperties` function to match the updated specs.
N/A
N/A
When testing events, make sure the environment variable `KOALA_TRACKING` is set to `true`.
Testing `No Reward`
Navigate to any project, and select the "No reward" option from the rewards carousel. In the console, you should see the event `Select Reward Button Clicked` tracked with the following properties:
Testing `Reward`
Navigate to any project, and select a reward option from the rewards carousel that not `No reward`. In the console, you should see the event `Select Reward Button Clicked` tracked event with the following properties:

[NT-719] Pledge properties

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift
Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

Updates the logic of when the `Project Page Viewed` event fires so that we can track all project properties.
Previously, we were firing the `Project Page Viewed` event right when the project page is configured. Because we prefix the `fetchProject` request with a partial project object, the `Project Page Viewed` event was being sent with incomplete `projectProperties`. 
Now, we wait for the `fetchProject` request to complete with the full project object before we track the `Project Page Viewed` event -- this allows us to send the event with all project properties.
Shuffling around the view model logic for the `Project Page Viewed` event.
Make sure you have the `KOALA_TRACKING` environment variable set to `true`
- `project_rewards_count` // should not be zero
- `project_updates_count`
- …

[NT-721] Updating Project Page Viewed event timing

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/Library/Optimizely+OptimizelyClientType.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
Kickstarter.xcodeproj/project.pbxproj
Library/OptimizelyLogLevelType.swift

Configures the Optimizely SDK's log level based on the bundle type. For debug builds, the log level is `.debug`, which gives us as much debugging information as possible. For release builds, the log level is set to `.error` which is the highest possible log level, only logging severe errors.
To prevent excessive logging on release builds.
Added an additional output type `KSROptimizelyLogLevel` to the `configureOptimizely` output which will either be `.debug` or `.error` depending on the main bundle type.
N/A
N/A

Configure OptimizelyLogLevel based on bundle type

---

Kickstarter-iOS/Views/Controllers/ProjectNavigatorViewController.swift

Disables our custom dismissal of the project modal on iOS 13.
This behaviour appears to be broken on iOS 13, views are positioned incorrectly and after dismissal the screen just goes blank. While there may be other ways to work around this, the built-in modal behaviour on iOS 13 works well and is arguably an improvement on what we have. I think that the easiest approach is to keep our current behaviour for iOS 12 and to disable it for 13+.
- Return `nil` for the animator object on iOS 13.
- Don't call the view model input with the panning gesture values on iOS 13.
| iOS 13 with custom animation 🐛 | iOS 12 (current behaviour) | iOS 13+ 🦋 |
| ![2020-01-09 13 27 47](https://user-images.githubusercontent.com/3735375/72106312-ffdf2300-32e3-11ea-922b-3db99e0def57.gif) | <img …

[NT-777] Fix project modal dismissal

---

Kickstarter.xcodeproj/project.pbxproj
Library/Equatable+Helpers.swift
Library/EquatableHelpersTests.swift
Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

- Fixes the navigation from the cta button on Project Page (errored state) to the ManagePledgeViewController.
- This was part of the requirements on this [ticket](https://kickstarter.atlassian.net/browse/NT-635).
The button wasn't firing because we were only checking if the `PledgeStateCTAType` was `.viewBacking` or `manage`. To fix that, we now also check if the button state is equal to  `.fix`.
If you have an errored pledge, select the project with an errored pledge and tap the `Manage` button.
If you don't have an errored pledge:
Select one of your successful and backed project. With Charles, add a breakpoint to intercept the response when the Project Page is presented (v1/projects) and change the backing status to errored. Tap the `Manage` button.

[NT-635] CTA fix button navigation

---

Kickstarter-iOS/Info.plist

Disables dark mode support in the app.
We're not supporting dark mode yet and opting out of support fixes a number of visual bugs that would otherwise be seen.
Added the `UIUserInterfaceStyle` key to our `Info.plist` file with a value of `Light` which forces the app to always be shown in _light_ mode.

[NT-791] Disable dark mode

---

Library/OptimizelyClientType.swift
Library/OptimizelyClientTypeTests.swift
Library/TestHelpers/MockOptimizelyClient.swift
Library/ViewModels/PledgeCTAContainerViewViewModel.swift
Library/ViewModels/PledgeCTAContainerViewViewModelTests.swift

Ensures that for admin users we call `getVariationKey(experimentKey:userId:attributes:)` instead of `activate(experimentKey:userId:attributes:)`.
`activate(experimentKey:userId:attributes:)` records an impression on Optimizely affecting our experiment groups and costing us money.
- Added `getVariationKey(experimentKey:userId:attributes:)` to `OptimizelyClientType`.
- Added a means to test this via `MockOptimizelyClient`.
[Optimizely docs](https://docs.developers.optimizely.com/full-stack/docs/get-variation-swift)

[NT-806] Ensure that getVariationKey is called for admin users

---

KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/ServiceTypeTests.swift

Adds the device identifier to our prepared request headers for requests to v1 endpoints and GraphQL queries/mutations.
In order to properly attribute our _Completed Checkout_ server-side events to Optimizely experimental variants, we need to send the `device_distinct_id` to the server so that Optimizely tracking calls can be made using the `device_distinct_id` instead of the user's ID.
Added a header, `Kickstarter-iOS-App-UUID` which will be set using the device's `identifierForVendor` value.
**Note:** As mentioned in #1044, according to the Apple [docs](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor), the `identifierForVendor` _can_ be `nil` but this is only when the device has been restarted and not yet unlocked. There should not be any scenario in …

[NT-780] Add device identifier to prepared request headers

---

Library/Tracking/TrackingClientConfiguration.swift
Library/Tracking/TrackingClientConfigurationTests.swift

Updates the value of `partition-key` in the record dictionary for our DataLake tracking client.
Instead of just using a random UUID for this value we would like to use the user's ID (when available), the device identifier if the user's ID is not available, and a random UUID as a fail-safe value.
**Note:** As per the Apple [docs](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor), the `identifierForVendor` can only sometimes be `nil` if the device has not yet been unlocked. This probably only affects apps that access this value in the background but seeing as this can potentially be `nil` we coalesce using a non-nil `UUID` string.
Updated the partition key value to coalesce from user ID through to `identifierForVendor` and lastly `UUID().uuidString`.

[NT-814] Partition key value precedence

---

Kickstarter-iOS/Alpha.entitlements
Kickstarter-iOS/Beta.entitlements
Kickstarter-iOS/Debug.entitlements

- Adds staging and native.dev to our list of Associated domains.
- This is part of the work to set up deep/universal links on test environments.
- Related [PR](https://github.com/kickstarter/kickstarter/pull/18615)
- [JIRA ticket](https://kickstarter.atlassian.net/browse/NT-728)
- Adding `staging.kickstarter.com` and `native.dev.kickstarter.co￼m` to `Alpha.entitlements` and `Debug.entitlements` plists.
- This will be tested once we are ready for emails coming from staging/test environments.

[NT-728] Adds staging and native.dev as Associated domains

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift

We're removing any user props that could potentially give us data that is not up to date, in favor of sending that data from the backend.
We want to populate the user attributes directly from the db instead of relying on the client to have the most up-to-date user information. As a result, we don't need the clients to send these user properties anymore.
Just delete them!

[NT-830] Removing user props

---

Kickstarter-iOS/ViewModels/UpdateViewModel.swift
Kickstarter-iOS/ViewModels/UpdateViewModelTests.swift

Fixes a bug where we were incorrectly displaying prelaunch projects in the app when they were accessed through a link in a project update.
A few months ago we added the "prelaunch" feature to project pages on web. Since native apps don't support prelaunch project pages, we updated our universal link handling for project links to check whether the project was a prelaunch project, and if it was, we send the user to mobile web instead of opening the project page in the app.
However, we missed adding this check in the `UpdateViewController`, which supports opening project links natively in the app. This meant that it was possible for a user to tap on a prelaunch project link from a project update and be presented with an incomplete project page natively.
We now check whether the project is a …

[NT-783] Send prelaunch project links to safari instead of opening in the app

---

Kickstarter-iOS/Views/PledgeCTAContainerView.swift
Library/OptimizelyClientType.swift
Library/TestHelpers/MockOptimizelyClient.swift
Library/ViewModels/PledgeCTAContainerViewViewModel.swift
Library/ViewModels/PledgeCTAContainerViewViewModelTests.swift
Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

Sends user attributes with Optimizely's `activate` and `getVariation` functions so that we can segment experiments based on user attributes.
We might want to take advantage of Optimizely's experiment segmentation to bucket users into variations based on their user attributes. In order to do this, we need to send the user attributes with the `activate` and `getVariation` functions.

[NT-883] Send user attributes with Optimizely's "activate" function

---

Kickstarter-iOS/ViewModels/UpdateViewModel.swift
Kickstarter-iOS/ViewModels/UpdateViewModelTests.swift

Fixes a bug found during UAT of #1054 and simplifies our logic around handling internal/external links for project updates.
During UAT we discovered prelaunch project links were sometimes doing nothing when tapped.
@ifbarrera and I refactored all of the `.zip` signals to make this logic easier to understand. It seems that what was happening before is that tapping multiple links caused the `.zip`'d signals to emit in an unexpected manner. By changing these signals to determine whether the URL being tapped is internal/external early on and then carrying the navigation action through the chain we were able to correct this.

[NT-783] Simplify internal/external link behaviour in updates

---

Kickstarter-iOS/Views/Controllers/DashboardProjectsDrawerViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletContentViewControllerTests.swift
Kickstarter-iOS/Views/Controllers/SettingsPrivacyViewController.swift
Kickstarter-iOS/Views/RewardCardContainerViewTests.swift
Library/SharedFunctions.swift
Library/ViewModels/DashboardViewModel.swift
Library/ViewModels/PledgeCTAContainerViewViewModel.swift
Library/ViewModels/PledgePaymentMethodsViewModel.swift
Library/ViewModels/ProjectActivityBackingCellViewModel.swift
Library/ViewModels/ProjectPamphletContentViewModel.swift
Library/ViewModels/UpdateDraftViewModel.swift

Replaces instances of `.filter { ... }.first` with `first(where: { ... })`.
This is just a simple optimization to not do unnecessary work when picking the first item from collections. In the case of `filter` the entire collection is traversed and each element is evaluated against the condition whereas `.first(where:)` stops once it finds a match and returns that element.
Replaced use of `filter` with `first(where:)` where it made sense. 
For example, there are some places where we do something like:
```swift
.compactMap { $0 as? UIPageViewController }.first
```
This could be replaced with:
```swift
.first { $0 is UIPageViewController } as? UIPageViewController
```
I felt that the sacrifice in readability and no material performance gain here didn't justify making those sorts of changes. …

[NT-858] Replace .filter { ... }.first with .find(where: { ... })

---

Kickstarter-iOS/Views/Controllers/PledgeContinueViewController.swift
Kickstarter-iOS/Views/Controllers/PledgePaymentMethodsViewController.swift
Kickstarter-iOS/Views/Transitions/SheetOverlayTransitionAnimator.swift

- Fixes the presentation of the `SheetOverlayTransitionAnimator` on iOS 13 so that the view extends beyond the safe area.
- Uses default modal presentation on iOS 13 for the login and add new card modals during checkout.
This was a regression noticed after updating to iOS 13. The default modal presentation style is sufficient in 2 of 3 places that we use the `SheetOverlayViewController`, however for the presentation of the `PledgeShippingLocationViewController` we still need it for the custom vertical offset behaviour.
- Fixed the frame sizes in `SheetOverlayTransitionAnimator`.
- Added `#available` checks for iOS 13 to default to the built-in modal for that OS version.
| iOS 12 | iOS 13 | iOS 13 login |
| ![image](https://user-images.githubusercontent.com/3735375/74393 …

[NT-796] Fix sheet overlay on iOS 13

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift

Tracks the `DataLakeWhiteListedEvent.projectPagePledgeButtonClicked` event for `.seeTheRewards` and `.viewTheRewards` in addition to the `.pledge` CTA state.
We weren't tracking this event in experimental variants, this corrects that.
Moved the necessary cases around in the switch statement where this was handled.

[NT-647] Track event for experimental variants

---

Kickstarter-iOS/Views/Controllers/ProjectPamphletViewController.swift
Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

Pops the `ProjectPamphletViewController`'s navigation stack to root after a project is backed.
**Note:** This is based off #1072's branch.
Now that we are presenting the checkout flow from the project campaign details in #1072, once the thanks page is presented and dismissed we want the user to land back on the project page and not the campaign details page. If they exit out of the checkout flow earlier than completion then we do want them to return to the campaign details page.
We were already observing the `projectBacked` notification in order to refresh the project after backing. We've now repurposed this signal to pop the navigation stack.
| --- | --- |
| ![2020-02-19 16 22 56](https://user-images.githubusercontent.com/3735375/74888973-708e4c00-5334-11ea-9bf3-885 …

[NT-876] Pop ProjectPamphlet to root after project is backed

---

Library/ViewModels/ProjectDescriptionViewModel.swift
Library/ViewModels/ProjectDescriptionViewModelTests.swift

Hides the _back this project_ button for project creators.
Creators are not allowed to back their own projects.
Added in a line to the logic that hides this view that includes checking that the current user is not the creator of the project.

[NT-872] Hide back this project button for project creators

---

Kickstarter-iOS/Views/Cells/ProjectPamphletMainCell.swift
Kickstarter-iOS/Views/LoadingButton.swift
Kickstarter-iOS/Views/Storyboards/ProjectPamphlet.storyboard
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift

Adds a loading state to the `readMoreButton` in `ProjectPamphletMainCell` while the `Project` is refreshed in the second variant of `projectCampaignExperiment`.
In the second variant we need to know that the rewards have been loaded in order to present them from the campaign details view.
- Changed `readMoreButton` to be a `LoadingButton`.
- Added an output that sets `isLoading` to `true` if a project's rewards are empty.
| Variant1 | Variant2 |
| --- | --- |
| ![2020-02-21 11 38 57](https://user-images.githubusercontent.com/3735375/75065982-d3035b80-549e-11ea-8136-f21209f059dd.gif) | ![2020-02-21 11 39 51](https://user-images.githubusercontent.com/3735375/75066040-ec0c0c80-549e-11ea-82f8-b8b7b2372b4c.gif) |
Easiest way to test is to just hard-code the return value from …

[NT-912] Read More Button Loading State

---

Kickstarter-iOS/DataSources/ProjectPamphletContentDataSource.swift
Kickstarter-iOS/DataSources/ProjectPamphletContentDataSourceTests.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletContentViewController.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphSchema.swift
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/models/ProjectCreatorDetailsEnvelope.swift
KsApi/models/ProjectCreatorDetailsEnvelopeTests.swift
Library/ViewModels/ProjectPamphletContentViewModel.swift
Library/ViewModels/ProjectPamphletContentViewModelTests.swift

Adds a query for us to fetch some additional project creator details from GraphQL when a project page loads.
**Note:** This emits what we expect to need to configure the cell that will display this data, that is the `ProjectCreatorDetailsEnvelope` result and an `isLoading` boolean to indicate whether we are still fetching the results.
As part of an experiment that we are running we would like to display some additional data to surface trust indicators to users. These values are not available from the v1 API so we are fetching them from GraphQL.
- Added `ProjectCreatorDetailsEnvelope`.
- Added `fetchProjectCreatorDetails` to `ServiceType`.
- Added some types to `ProjectPamphletContentViewModel` to improve the frequently changing interface of its datasource loading output.
- Updated …

[NT-930] Add Project Creator Details Query and VM outputs

---

Library/OptimizelyClientType.swift
Library/ViewModels/PledgeViewModelTests.swift

Adds a `user_distinct_id` attribute to Optimizely events ~~for admins~~ in the staging environment.
**Note:** If merged this is a patch on `release-4.3.0`.
We are hoping that this will assist us in verifying that the data we are sending to Optimizely is being received correctly. Currently we are seeing data in Optimizely's dashboard but we are not able to connect it to a specific session/event. By adding the `distinct_id` ~~for admins~~ in staging we hope to test this without compromising user anonymity in production.
- Added `user_distinct_id` when:
- The `EnvironmentType` is _not_ `production`.
- The `BundleType` is _not_ `release`.
- ~~The user's `isAdmin` value is `true`.~~

[NT-941] Add distinct_id to Optimizely attributes for admins

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
Kickstarter-iOS/Views/Controllers/LandingPageViewController.swift
Library/KeyValueStoreType.swift
Library/SharedFunctions.swift
Library/ViewModels/LandingPageViewModel.swift
Library/ViewModels/LandingPageViewModelTests.swift

- It adds the logic to only show `LandingPageViewController` on the first app session **_and_** if the user part of `variant-1` or `variant-2` of the Optimizely `native_onboarding_series_new_backers` experiment.
- This is the last part of the Landing Page work.
[JIRA ticket](https://kickstarter.atlassian.net/browse/NT-871)
- Created the `goToLandingPage` output on the AppDelegateViewModel that emits the experiment variants to determine if the LandingPage should be presented.
- Added the `hasSeenLandingPage` to the KeyValueStore in order to keep track if the user has seen the landing page.
- Added tests

[NT-871] (3/3) Landing page first session

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Library/OptimizelyClientType.swift
Library/SharedFunctions.swift

In order to access experiment variants in the `AppDelegateViewModel`, we need an input for when the OptimizelyClient has been updated in the `AppEnvironment`, among other things.
This PR adds some of that shared functionality that we need on multiple feature branches to reduce duplication of work and merge conflicts.
There are no user-facing changes here, just exposing functions and adding an input to be used on other feature branches.

Adds required inputs for Optimizely experiments running on app launch

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift

- Adds a logic to handle deeplinks.
- We still want to show the Landing Page if eligible users with `variant-1` or `variant-2` open the app through deeplink. In this case, we will show the Landing Page and redirect them to Discovery after dismissing the screen. 
- Added a filter so `deeplink` signal only emits if `shouldGoToLandingPage` is false.
- Added tests
In order to test this, follow the steps:
1. Build the app on a device in the release configuration
2. Set Launch setting to `Wait for executable to be launched`
3. Comment out the the switch statement on line 1117 and simply return `true`
4. Click a link from email / google to open the app through deeplink

[NT-978] Landing page deeplink handling

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift

Updates the dispatch interval for the `DefaultEventDispatcher` on Optimizely to 5 seconds to reduce likelihood of backend race condition.
The default dispatch interval on the `DefaultEventDispatcher` used by Optimizely to dispatch events and impressions was 60 seconds. This caused a race condition where sometimes the Kickstarter Ruby backend would attempt to send conversion event for an experiment whose "impression" hadn't been dispatched yet from the iOS SDK. By reducing the dispatch interval we hope to mitigate this race condition.
- Added the `dispatchTimeInterval` as part of the `configureOptimizely` output.
- set this value to 5 seconds
- added a test

[NT-980] Updating the Optimizely events dispatch interval

---

Kickstarter-iOS/Views/Controllers/LandingPageViewController.swift
Library/ViewModels/LandingPageCardType.swift

- Change the color of the logo on the Landing Page.
- Changed the order of the cards 
To match the designs on [Figma](https://www.figma.com/file/C3gkbRATsDy0vFIUk3Cf8D/FTB%3A-Landing-Screen-Experiment?node-id=0%3A1)
| --- | --- |
| ![Simulator Screen Shot - iPhone 11 Pro - 2020-02-24 at 17 39 41](https://user-images.githubusercontent.com/3709676/76560094-d030d080-6476-11ea-91c5-d31ec26d759f.png) | ![Simulator Screen Shot - iPhone 11 Pro - 2020-03-12 at 15 29 38](https://user-images.githubusercontent.com/3709676/76560028-a4154f80-6476-11ea-831d-9303a17b6a7f.png) |

[NT-892][NT-893] - UI tweaks

---

Kickstarter-iOS/Locales/de.lproj/Localizable.strings
Kickstarter-iOS/Locales/es.lproj/Localizable.strings
Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
Library/Strings.swift

Translations for experiment copy.
So users can read the copy in their preferred language.

[NT-991] Creator string translates

---

Cartfile
Cartfile.resolved
Kickstarter-iOS/Views/Cells/FindFriendsFacebookConnectCell.swift
Kickstarter-iOS/Views/Controllers/LoginToutViewController.swift

Upgrades the Facebook SDK to v6.2.0, which fixes an iOS 13 bug where users were unable to log in or sign up using Facebook.
Users need to be able to log in/signup using Facebook.
- Updated the Cartfile to specify `6.2.0` as the `facebook/facebook-objc-sdk` version, and then ran `carthage update facebook-objc-sdk`
- removed references to `loginBehaviour` in the Facebook `loginManager` since they deprecated that configuration:

[NT-1011] Upgrade Facebook SDK

---

Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

- Tracks the `Project Page Viewed` event on Optimizely.
- This event was missing and we need it before releasing the next build.
[JIRA ticket](https://kickstarter.atlassian.net/browse/NT-885)
- On `ProjectPamphletViewModel`, a signal `freshProjectRefTagAndCookieRefTag` was created to make sure the same properties are being sent to both Optimizely and DataLake.
- Added tests

[NT-885] Added Project Page Viewed event

---

Library/SharedFunctions.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift

Fixes a tracking event that wasn't being sent to Optimizely when `Read more about this campaign` was tapped.
Tracking this event is necessary for our metrics.
The bug was that we were checking if `project.personalization.isBacking` was `false`. In this case `isBacking` can also be `nil` so comparing a `nil` value to `false` fails. We could coalesce this `nil` to `false` but I figured we can also just check to see whether the actual `backing` property is `nil` for the same result.
Place yourself in variant 1 or 2 for `native_project_page_campaign_details`. Open Charles Proxy.

[NT-877] Read more about this campaign tracking bugfix

---

Kickstarter-iOS/DataSources/CategorySelectionDataSource.swift
Kickstarter-iOS/DataSources/CategorySelectionDataSourceTests.swift
Kickstarter-iOS/Views/Cells/CategoryPillCell.swift
Kickstarter-iOS/Views/Controllers/CategorySelectionViewController.swift
Kickstarter-iOS/Views/Controllers/DiscoveryPageViewController.swift
Library/KSCache.swift
Library/OptimizelyClientType.swift
Library/ViewModels/CategoryPillCellViewModel.swift
Library/ViewModels/CategoryPillCellViewModelTests.swift
Library/ViewModels/CategorySelectionViewModel.swift
Library/ViewModels/CategorySelectionViewModelTests.swift
Library/ViewModels/DiscoveryPageViewModel.swift
Library/ViewModels/DiscoveryPageViewModelTests.swift

Caches categories selected during the onboarding flow in NSCache. Also refactors how we keep track of selected categories by passing in the whole `Category` object into the cells so they can be passed back with the delegate callback. This improves performance because we don't have to iterate through nested arrays.
The `CuratedProjectsViewController` needs to be configured with an array of `KsApi.Category`s. This is because the `DiscoveryParams` object which is used to populate the query parameters of the `/discover` requests takes a `Category` object instead of a `categoryId`.
When presenting the `CuratedPrjoectsViewController` from the explore screen, we need to pass in an array of previously selected `Category` objects. This array will now come from an `NSCache`.
- cache the selected …

[NT-1019] Cache selected categories in NSCache

---

Library/ViewModels/LoadingButtonViewModel.swift
Library/ViewModels/LoadingButtonViewModelTests.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift

Addresses a bug in which the _read more_ button in our `native_project_page_campaign_details` experiment would sometimes not show the loading indicator correctly.
This button is meant to display a loading indicator until the `Project` has been refreshed and hydrated with its rewards.
Removed some problematic `skipRepeats()` that were preventing the button from being put back into a loading state after the cell was reused by the table view.
Using link conditioner, charles, airplane mode, or your favourite method of breaking your internet connectivity, put yourself in variants 1 or 2 of the `native_project_page_campaign_details` experiment. Navigate to a project.

[NT-912] Experimental read more button loading bugfix

---

Kickstarter-iOS/Views/Controllers/ActivitiesViewController.swift
Library/ViewModels/ActivitiesViewModel.swift
Library/ViewModels/ActivitiesViewModelTests.swift

#📲 What
Removes some code that was making a network request for an incomplete feature. This feature is currently being developed [on a feature branch.](https://github.com/kickstarter/ios-oss/tree/feature-errored-pledges), and should never have been merged into master.
Because we shouldn't be making network requests for data that is not being used.
Deleted the unused code. This code will be re-added as part of the complete feature when the `feature-errored-pledges` branch merges.

[NT-983] Removing unused errored backings code

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift
Library/Tracking/TrackingHelpers.swift
Library/ViewModels/ManagePledgeViewModel.swift
Library/ViewModels/ManagePledgeViewModelTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

We add tracking events: `Manage Pledge Button Fixed`, `Fix Pledge Button Clicked`, `Pledge Submit Button Clicked`
The events are added to monitor the fixing errored pledges feature.
ToDo

[NT-214] Fix pledge tracking events

---

Kickstarter-iOS/Views/Controllers/CategorySelectionViewController.swift
Kickstarter-iOS/Views/Controllers/CuratedProjectsViewController.swift
Library/TestHelpers/MockOptimizelyClient.swift
Library/ViewModels/CategorySelectionViewModel.swift
Library/ViewModels/CategorySelectionViewModelTests.swift
Library/ViewModels/LandingViewModel.swift
Library/ViewModels/LandingViewModelTests.swift

Adds a few Optimizely tracking events to the category personalization flow.
So we can evaluate the effectiveness of the feature in helping new users find projects they'll be interested in.
- adds `Get Started Button Clicked` event
- adds `Continue Button Clicked` event
- adds `Skip Button Clicked` event
To force the category personalization flow to present on app launch, comment out the body of the `shouldSeeCategoryPersonalization()` function in `AppDelegateViewModel.swift` and instead `return true`.

[NT-886] Category Personalization Experiment Tracking

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Library/OptimizelyClientType.swift
Library/OptimizelyClientTypeTests.swift
Library/OptimizelyExperiment.swift
Library/ViewModels/LandingPageViewModel.swift
Library/ViewModels/PledgeCTAContainerViewViewModel.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift
Library/ViewModels/ProjectDescriptionViewModel.swift
Library/ViewModels/ProjectPamphletContentViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletViewModel.swift

- Adds `Temporary Checkout Completed` to be sent to Optimizely once a checkout completes.
- Refactors some of our Optimizely tracking functions to reduce repetition at callsites.
- There are currently _reasons_ that the `Checkout Completed` event is not tracking correctly from the back-end. We are using this event as a temporary workaround for _reasons_.
- Decided to tidy up these functions to instead get user-related info from the environment and to also not _require_ some arguments. This tidies up most of the callsites.
- Added the event and tags.
- Refactored some code.
Example JSON that is posted to Optimizely for this event:
```json
"snapshots": [
{
"events": [
{
"tags": {
"category": "Publishing",
"checkout_amount": 1,
"project_user_has_watched": false,
"revenue": 130, …
```

[NT-1023] Add Temporary Checkout Completed event

---

Kickstarter-iOS/DataSources/ProjectSummaryCarouselDataSource.swift
Kickstarter-iOS/DataSources/ProjectSummaryCarouselDataSourceTests.swift
Kickstarter-iOS/Views/Cells/ProjectPamphletMainCell.swift
Kickstarter-iOS/Views/Cells/ProjectSummaryCarouselCell.swift
Kickstarter-iOS/Views/ProjectSummaryCarouselView.swift
Kickstarter-iOS/Views/Storyboards/ProjectPamphlet.storyboard
Kickstarter.xcodeproj/project.pbxproj
Library/ViewModels/ProjectSummaryCarouselViewModel.swift
Library/ViewModels/ProjectSummaryCarouselViewModelTests.swift

Adds the UI and basic data source for the Project Summary Carousel experiment.
**Note:** Subsequent PRs will retrieve the items from GraphQL, add detail to the cells and also perform the max height calculations.
We are planning to run an experiment to display horizontally scrollable project summary cells on the project page.
- Added a collection view to the `ProjectPamphletMainCell`.
- Restructured the view to allow this collection view to scroll edge-to-edge.
- Added a basic data source which will be updated when we are retrieving the summary items from GraphQL.
Uncomment lines 111-112 in `ProjectPamphletMainCell` to populate the datasource and display empty cells.

[NT-1040] Project Summary Carousel UI

---

Kickstarter-iOS/DataSources/DiscoveryProjectsDataSource.swift
Kickstarter-iOS/DataSources/ThanksProjectsDataSource.swift
Kickstarter-iOS/Views/Cells/DiscoveryPostcardCell.swift
Kickstarter-iOS/Views/Controllers/ProjectNavBarViewController.swift
Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift
Library/ViewModels/ProjectNavigatorViewModel.swift
Library/ViewModels/WatchProjectViewModel.swift
Library/ViewModels/WatchProjectViewModelTests.swift

Adds the whitelisted `Watch Project Button Clicked` event that fires when the "Watch" button is tapped either on the discover cards or in the project page.
So we can track when users tap the "Watch" button in Amplitude.
- adds `Watch Project Button Clicked` event to the datalake whitelisted events enum
- updates the naming of the tracking function, adds project properties, optionally discovery properties, and context location
- in `WatchProjectViewModel`, the event will be queued immediately when the user taps the button (previously we would wait for the request to succeed before tracking)
Make sure you have the `KOALA_TRACKING_ENABLED` environment variable enabled while testing.

[NT-1032] Watch Project Button Clicked Event

---

Library/Tracking/Koala.swift

Whitelists fix pledge tracking events for the DataLake.
We were only tracking these events on Koala before and now they can be tracked on DataLake.
Added events to `DataLakeWhiteListedEvent`

[NT-1072] Whitelist fix pledge tracking events for data lake

---

Kickstarter-iOS/Views/Controllers/CategorySelectionViewController.swift
Kickstarter-iOS/Views/Controllers/LandingViewController.swift
Kickstarter-iOS/Views/Layouts/PillLayout.swift

Fixes a bug that was causing the category selection screen to "jump" when the user selects more than 5 categories.
Because the jumpy behavior wasn't ideal when selecting categories.
The "jumpiness" that was observed when the user selects more than 5 categories was a result of the collection view's `contentInset` being updated to accommodate for the larger height of the button container view. As it turns out, updating a collection view's `contentInset` causes `invalidateLayout` to be called on the collection view layout, which essentially re-draws the entire collection view, losing the users current content offset and causing the perceived "jump".
In order to prevent `invalidateLayout` from being called, we override `invalidateLayout` in our custom `PillLayout` class, and only allow the …

[NT-1119] Category selection screen content inset bug

---

Kickstarter-iOS/Alpha.entitlements
Kickstarter-iOS/Beta.entitlements
Kickstarter-iOS/Debug.entitlements
Kickstarter-iOS/Release.entitlements
Kickstarter-iOS/Views/Controllers/LoginToutViewController.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/extensions/NSURLSession.swift
KsApi/models/AccessTokenEnvelope.swift
KsApi/models/SignInWithAppleEnvelope.swift
KsApi/models/SignInWithAppleEnvelopeTests.swift
KsApi/models/templates/SignInWithAppleEnvelopeTemplates.swift
KsApi/mutations/SignInWithAppleMutation.swift
KsApi/mutations/inputs/SignInWithAppleInput.swift
Library/Tracking/Koala.swift
Library/ViewModels/LoginToutViewModel.swift
Library/ViewModels/LoginToutViewModelTests.swift

- Adds the `signInWithApple` mutation to the codebase.
** Note: ** This PR only contains the mutation. It doesn't fetch the user from v1, thus doesn't login into our Environment. This will be done in the second part of this work.
- This work is part of the Sign-In With Apple epic. The mutation will allow users to login using the `Sign in with Apple` functionality.
[JIRA ticket](https://kickstarter.atlassian.net/browse/NT-867)
- Added the Sign in with Apple capability
- Created the `SignInWithAppleInput` containing `appId`, `firstName`, `lastName`, and `authToken` (provided by Apple)
- Created the `SignInWithAppleEnvelope` to be decoded once graphQL returns a value
- A new `didSignInWithApple` output was created.
- Added tests
To test this, change the environment to `Development`

[NT-867] (1/2) Sign in with apple mutation

---

Kickstarter.xcodeproj/project.pbxproj
Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-Framework-iOS.xcscheme
Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-iOS.xcscheme
Kickstarter.xcodeproj/xcshareddata/xcschemes/KickstarterUITests.xcscheme
Kickstarter.xcodeproj/xcshareddata/xcschemes/KsApi.xcscheme
Kickstarter.xcodeproj/xcshareddata/xcschemes/Library-iOS.xcscheme
Library/ShareContext.swift

Silences some Xcode warnings in 11.4.
I find it best to just open a PR to address this rather than folks fixing them in separate PRs resulting in merge conflicts.
Addressed the warnings which were for duplicate file references and updating to recommended project settings.

[NT-1180] Silence Xcode warnings

---

Kickstarter-iOS/Views/Controllers/LandingPageViewController.swift
Kickstarter-iOS/Views/Controllers/LandingViewController.swift
Kickstarter-iOS/Views/Controllers/LoginToutViewController.swift
Kickstarter-iOS/Views/Controllers/PledgeViewController.swift
Kickstarter-iOS/Views/ProcessingView.swift
Kickstarter.xcodeproj/project.pbxproj
Library/ViewModels/LoginToutViewModel.swift
Library/ViewModels/LoginToutViewModelTests.swift

Adds the "Processing" full-screen loader view to the Login/Signup screen, and presents the loader view while the sign-in-with-apple and user requests are in flight. We will also show the loader when the login with Facebook request is in flight.
So that we can give some indication to the user that something is happening after they authenticate with Apple and Facebook.
- made a protocol and protocol extension `ProcessingViewPresenting` where the showing/hiding functions will live
- conformed both `PledgeViewController` and `LoginToutViewController` to `ProcessingViewPresenting`
- the `isLoading` output already existed in `LoginToutViewModel`, but wasn't being used. This PR couples the `isLoading` output to the `signInWithApple` mutation, as well as the `fetchUser` request
- added VM tests
- …

[NT-1136] Add "Processing" loader to Login/Signup Screen

---

Library/OptimizelyExperiment.swift
Library/ViewModels/ProjectPamphletContentViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift

Coalesces optional `OptimizelyExperiment.Variant?` values to `.control`.
We've received a handful of bug reports in which the _read more about the campaign_ button is missing on the project page. We suspect this might occur if the Optimizely client fails to initialize and the `skipNil()` on the signal that configures the button causes it to never emit.
Coalesced `nil` values to `.control` in functions where we return an optional value for the variant.

[NT-1175] Coalesce experimental variants to control

---

Library/OptimizelyClientType.swift
Library/OptimizelyClientTypeTests.swift
Library/OptimizelyExperiment.swift
Library/TestHelpers/MockOptimizelyClient.swift
Library/ViewModels/DiscoveryPageViewModel.swift

Adds a set of "Optimizely Properties" that will be sent with certain events to the data lake.
We want to be able to analyze experiment results in Amplitude. As part of this work, we will send some Optimizely data along with certain events to the data lake, to be passed forward to Amplitude from there. This PR adds the `optimizelyProperties()` function that will generate these properties to be sent with desired events.
- adds `optimizelyProperties` function, which calls `getVariation` on all known experiments. If `getVariation` throws an error, we report the variant as "unknown" for that experiment
- adds tests for `optimizelyProperties`
- adds tests for our helper `getVariation` function that didn't have tests previously
N/A
N/A
The `optimizelyProperties` function isn't being used …

[NT-1162] Add OptimizelyProperties

---

Kickstarter-iOS/Alpha.entitlements
Kickstarter-iOS/Beta.entitlements

Removes Sign In With Apple entitlement from our Enterprise provisioning profiles.
I noticed that our most recent merge to `master` failed to distribute a beta build because of this value in the provisioning profile. Sign In With Apple is not supported by Enterprise accounts which our Alpha and Beta profiles belong to. I should have noticed this up when I reviewed #1165 🤦‍♂️ 
Removed the entitlement from Alpha and Beta profiles.

[NT-735] Remove Apple Sign In from enterprise profiles

---

Kickstarter-iOS/Views/Controllers/ActivitiesViewController.swift
Kickstarter-iOS/Views/Controllers/BackerDashboardProjectsViewController.swift
Kickstarter-iOS/Views/Controllers/CuratedProjectsViewController.swift
Kickstarter-iOS/Views/Controllers/DashboardViewController.swift
Kickstarter-iOS/Views/Controllers/DiscoveryPageViewController.swift
Kickstarter-iOS/Views/Controllers/MessagesViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectActivitiesViewController.swift
Kickstarter-iOS/Views/Controllers/SearchViewController.swift
Kickstarter-iOS/Views/Controllers/ThanksViewController.swift
Kickstarter-iOS/Views/Controllers/UpdateViewController.swift

Presents the project page modal fullscreen on iPad.
This was a request from our iPad users.
Updates each place that we present `ProjectNavigatorViewController` to have a `fullScreen` `modalPresentationStyle`.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/3735375/81623142-9cefbc80-93a7-11ea-84a9-0a846efe3ba8.png" /> | <img src="https://user-images.githubusercontent.com/3735375/81623091-7d589400-93a7-11ea-801d-f62abc8ad3b0.png" /> |
Project modals are presented fullscreen on iPad in all of the following places while iPhone presentation remains unchanged:

[NT-1210] Present Project modal fullscreen on iPad

---

Kickstarter-iOS/DataSources/ActivitiesDataSource.swift
Kickstarter-iOS/DataSources/ActivitiesDataSourceTests.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/Views/Cells/ActivityErroredBackingsCell.swift
Kickstarter-iOS/Views/Controllers/ActivitiesViewController.swift
Kickstarter-iOS/Views/Controllers/ManagePledgeViewController.swift
Kickstarter-iOS/Views/Controllers/ManagePledgeViewControllerTests.swift
Kickstarter-iOS/Views/Controllers/PledgeAmountViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletViewController.swift
KsApi/models/GraphBacking.swift
KsApi/models/GraphBackingTests.swift
KsApi/models/User.swift
KsApi/models/lenses/UserLenses.swift
KsApi/models/templates/GraphBackingTemplates.swift
KsApi/queries/UserQueries.swift
KsApi/queries/UserQueriesTests.swift
Library/ViewModels/ActivitiesViewModel.swift
Library/ViewModels/ActivitiesViewModelTests.swift
Library/ViewModels/ManagePledgeViewModel.swift
Library/ViewModels/ManagePledgeViewModelTests.swift
Library/ViewModels/PledgeAmountSummaryViewModel.swift
Library/ViewModels/PledgeAmountSummaryViewModelTests.swift
Library/ViewModels/RootViewModel.swift
Library/ViewModels/RootViewModelTests.swift

- Adds errored pledges to the badge count shown on the activities tab.
- Presents the `ManagePledgeViewController` from `ActivitiesViewController` when fixing an errored pledge.
- Refreshes the current user after `ManagePledgeViewController` completes.
**Note:** There is some additional work to be done to show a loading state for `ManagePledgeViewController`, currently the view might appear and be unpopulated briefly until the data loads. This work will also ensure that the project and graph backing producers are correctly combined/zipped.
This is a continuation of the work to allow a user to fix their errored pledges. We currently display a badge count for unseen activities, this count will now include the amount for errored pledges (if any).
- Added `erroredBackingsCount` to `User`.
- …

[NT-650, NT-1135, NT-1052] Add Errored Pledges to badge count

---

Kickstarter-iOS/Views/Controllers/PledgeViewController.swift

Fixes a bug in iOS 12 where presenting a VC from the pledge screen caused the scroll view insets to be reset to zero, which caused the pledge button container to overlap some content near the bottom of the screen.
This was a strange one. For some reason on iOS 12.4, presenting a VC on top of a scroll view with its `contentInsetAdjustmentBehavior` set to `automatic` (the default), caused the content insets to abruptly be reset back to zero when the presented VC is dismissed. Strangely, examining the `contentInsets` after the dismissal showed that the `adjustedContentInsets` were still correctly set, but visually the scroll view appeared to have an `adjustedContentInset` of `.zero`. Setting the `contentInsetAdjustmentBehavior` on the `rootScrollView` to `.zero` seemed to fix the issue, but …

[NT-1256] iOS 12 pledge screen scroll view insets bug

---

Kickstarter-iOS/Views/Controllers/LoginToutViewController.swift
Kickstarter.xcodeproj/project.pbxproj
Library/OptimizelyClientType.swift
Library/OptimizelyClientTypeTests.swift
Library/OptimizelyFeature.swift
Library/TestHelpers/MockOptimizelyClient.swift
Library/ViewModels/LoginToutViewModel.swift
Library/ViewModels/LoginToutViewModelTests.swift

Adds an `ios_sign_in_with_apple` feature flag that acts as a killswitch (hides the button if enabled).
We will soon roll out Sign In With Apple in our next release and we would just like to be able to turn this off if necessary via a feature flag.
- Added `ios_sign_in_with_apple_killswitch` feature flag on Optimizely.
- Add behaviour to hide the Sign In With Apple button if this feature is `enabled`. If it is `disabled` or missing,  the button will be shown.
| Killswitch `enabled` 🟢  | Killswitch `disabled` 🔴 | Killswitch _missing_ 💭 |
| <img width="584" alt="image" src="https://user-images.githubusercontent.com/3735375/82378947-e9a44a80-99da-11ea-81de-440f03ea09a4.png"> | <img width="584" alt="image" src="https://user-images.githubusercontent.com/3735375/82378755-96ca9 …

[NT-1257] Sign In With Apple Killswitch Feature Flag

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift
Library/ViewModels/DiscoveryPageViewModel.swift
Library/ViewModels/DiscoveryPageViewModelTests.swift
Library/ViewModels/ThanksViewModel.swift
Library/ViewModels/ThanksViewModelTests.swift

Adds the "Project Card Clicked" event when a project is selected from discovery or the thanks page.
So we can track what projects users are navigating to from various locations.
- add the `Project Card Clicked` event to the data lake whitelist
- fire the event when a project is clicked from discovery
- fire the event when a project is clicked from the Thanks page

[NT-1015] Project Card Clicked Event

---

Library/ProjectActivityItemProvider.swift
Library/ProjectActivityItemProviderTests.swift
Library/ViewModels/ShareViewModel.swift

Fixes broken shared project links in some messaging apps.
We noticed that some URLs weren't being shared correctly in some apps, for example Telegram:
This appears to be due to a space character being incorrectly prepended to the beginning of the URL.
Updated the code that constructs this string to instead use the `joined(separator:)` function rather that multi-line string interpolation.

[NT-1236] Fix share URLs in messaging apps

---

Library/ViewModels/LoginToutViewModel.swift
Library/ViewModels/LoginToutViewModelTests.swift

Fixes an bug which caused the processing view to never dismiss after logging in via Apple Sign In from the profile tab.
A number of things are happening all at once here:
- Apple Pay Sign In event completes.
- User object is refreshed.
- User is logged into the environment.
- Notifications are posted for the app to update its state.
- Processing view is dismissed.
Once the notifications are posted about the user login state having changed our `RootViewModel` recreates all of the VCs and sets them again on the tab bar. This was causing the `LoginToutViewController` to be deallocated before the observing closure could execute and hide the processing view.
One way of solving this would be to have another input on the view model to inform of the processing view having been dismissed. Another …

[NT-1299] Apple Sign In Processing View dismissal bugfix

---

Library/OptimizelyClientType.swift
Library/TestHelpers/MockOptimizelyClient.swift
Library/ViewModels/CategorySelectionViewModel.swift
Library/ViewModels/CategorySelectionViewModelTests.swift
Library/ViewModels/DiscoveryPageViewModel.swift
Library/ViewModels/DiscoveryPageViewModelTests.swift
Library/ViewModels/LandingPageViewModel.swift
Library/ViewModels/LandingPageViewModelTests.swift
Library/ViewModels/LandingViewModel.swift
Library/ViewModels/LandingViewModelTests.swift
Library/ViewModels/PledgeCTAContainerViewViewModelTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift
Library/ViewModels/ProjectDescriptionViewModel.swift
Library/ViewModels/ProjectDescriptionViewModelTests.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift
Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

Send the Optimizely client events through the app
Sending events to Optimizely's dashboard through the DataLake proved to have issues and the short term solution is to send those events through the client SDK. 
- Reverted changes in this PR: https://github.com/kickstarter/ios-oss/pull/1205
- Event information can be found here: https://kickstarter.atlassian.net/browse/NT-1317

[NT-1317] Send Optimizely Events with the SDK

---

Kickstarter-iOS/Library/QualtricsTypes.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/Views/Controllers/BetaToolsViewController.swift
KsApi/ServerConfig.swift
Library/AppEnvironment.swift
Library/EnvironmentType.swift
Library/OptimizelyClientType.swift
Library/ViewModels/BetaToolsViewModel.swift

Allows one to enter a custom HQ environment in debug tools.
**Note:** I was unable to test this as the HQ environments appeared to be down at the time.
This has been a requirement from time-to-time so no better time to add it than the present!
- Added a `custom` `EnvironmentType` with an associated value which we use to construct the HQ url.
- Added a text prompt when selecting this `EnvironmentType` to capture the value.
| Prompt | Configured |
| --- | --- |
| <img height="584" alt="image" src="https://user-images.githubusercontent.com/3735375/84840443-63d4e880-aff4-11ea-81b1-bd429a196d2b.png"> | <img src="https://user-images.githubusercontent.com/3735375/84840474-7cdd9980-aff4-11ea-9a08-a840fe159ced.png" height="584" /> |

[NT-1359] Allow custom HQ environment in debug tools

---

.circleci/config.yml
.fastlane/Fastfile
Makefile

Updates our CircleCI configuration to distribute an alpha build from feature branches.
This will assist us in our UAT process when merging to feature branches not yet merged into the master branch.
- Added a wildcard branch for triggering alpha builds on `/.*feature.*/`.
- Updated the description of alpha builds to include the branch name.

[NT-1404] Distribute alpha builds from feature branches

---

.fastlane/Fastfile

- Improves readability of the branch name for our automatic alpha build distributions.
- Reverts the notes changes for non-alpha builds (that is betas built from master).
In order to surface the feature that the branch represents, the name is carried through to the release notes. This can be a little hard to parse though, so instead of seeing something like `alpha-dist-NT-1140-feature-add-ons-phase-1-4150311a067050f98361c7aff4749a336d28330c`, we're stripping out the `alpha-dist-` prefix (used to trigger an alpha build), and the commit hash (used for uniqueness), this leaves the branch name easier to read as `NT-1140-feature-add-ons-phase-1`.
Added some ruby string replacement.

[NT-1404] Improve branch name in release notes

---

Library/ViewModels/ManagePledgeViewModel.swift
Library/ViewModels/ManagePledgeViewModelTests.swift
Library/ViewModels/RewardCardViewModel.swift

Bugfixes from UAT testing on Manage Pledge View:
- Some summary data was not correctly displayed when viewing the pledge as a creator.
- Add-on rewards were shown twice in the list.
Due to the two different back-ends that we are retrieving data from for this view the structure differs and has to be handled differently depending on the creator/backer context.
I've made some in-line code comments to explain.
Create a project with add-ons and back it as a different user.

[NT-1296, NT-1297] Manage Pledge view info bugfixes

---

Kickstarter-iOS/Views/Controllers/ManagePledgeViewControllerTests.swift
Library/ViewModels/PledgeAmountSummaryViewModel.swift
Library/ViewModels/PledgeAmountSummaryViewModelTests.swift

Fixes a bug from #1236 which caused the pledge total to be shown as `0.00` for the No Reward type.
No Reward is a special type that we use for a 'fake' reward that allows a backer to contribute to a project without receiving a reward. This type has no minimum and our code was expecting to display the reward's minimum as the pledge amount whereas in the case of No Reward, the bonus support amount is the pledge amount.
Updated `PledgeAmountSummaryViewModel` to use the bonus support amount as pledge amount in the case of No Reward type.
| --- | --- |
| <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/86063819-8fa69400-ba20-11ea-962b-be21256ba1f8.png"> | <img width="545" alt="image" …

[NT-1405] Use bonus support as total for No Reward

---

Kickstarter-iOS/Views/Controllers/RewardAddOnSelectionViewController.swift

Adds a basic header and title label to `RewardAddOnSelectionViewController`.
This is a continuation of #1243 to get us started on building this view for add-ons selection.
Added the necessary subviews and set the label text.
**Note:** I will open a PR for the strings to be translated and link it here.
| Before 🐛 | After 🦋 | Blended layers 🍭 |
| ![image](https://user-images.githubusercontent.com/3735375/86187561-e8ddf880-baf0-11ea-993c-0bece2872648.png) | ![image](https://user-images.githubusercontent.com/3735375/86187481-bf24d180-baf0-11ea-8054-edd335a8ec09.png) | ![image](https://user-images.githubusercontent.com/3735375/86187924-e62fd300-baf1-11ea-8253-7be2a0386d09.png) |

[NT-1366] Add header UI to add-ons selection view

---

Kickstarter-iOS/DataSources/RewardAddOnSelectionDataSourceTests.swift
Kickstarter-iOS/Views/Cells/RewardAddOnCell.swift
Kickstarter-iOS/Views/Controllers/PledgeShippingLocationViewController.swift
Kickstarter-iOS/Views/PillsView.swift
Kickstarter-iOS/Views/RewardAddOnCardView.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphSchema.swift
KsApi/models/ManagePledgeViewBackingEnvelope.swift
KsApi/models/ManagePledgeViewBackingEnvelopeTests.swift
KsApi/models/Reward+ManagePledgeView.swift
KsApi/models/Reward+RewardAddOnSelectionView.swift
KsApi/models/Reward.swift
KsApi/models/RewardAddOnSelectionViewEnvelope.swift
KsApi/models/RewardAddOnSelectionViewEnvelopeTests.swift
KsApi/queries/ManagePledgeViewQueries.swift
KsApi/queries/ManagePledgeViewQueriesTests.swift
KsApi/queries/RewardAddOnSelectionViewQueries.swift
KsApi/queries/RewardAddOnSelectionViewQueriesTests.swift
Library/SharedFunctions.swift
Library/Styles/Colors.swift
Library/Styles/Fonts.swift
Library/ViewModels/PillCellViewModel.swift
Library/ViewModels/RewardAddOnCardViewModel.swift
Library/ViewModels/RewardAddOnCardViewModelTests.swift
Library/ViewModels/RewardAddOnSelectionViewModel.swift
Library/ViewModels/RewardAddOnSelectionViewModelTests.swift
Library/ViewModels/RewardCardViewModelTests.swift
bin/ColorScript/Resources/Colors.json

Adds the UI elements to the `RewardAddOnCell` which we added in #1246.
**Note:** Interaction with the cell (adding to reward) will be added in a subsequent PR.
These cells are similar to the standard `RewardCell` shown in the rewards carousel but differ enough to warrant a separate view.
- Brought over most of the UI elements from `RewardCardView` and updated/renamed them where necessary.
- Added `PillsView` which is a manual implementation of the the pills collection view that we have used elsewhere. We've found that sizing the collection view has been problematic and I wanted to see if doing this manually would improve things. So far it seems to be working well.
- Added VM and tests.
| --- | --- |
| <img width="545" alt="image" …

[NT-1368] Reward Add-On Card UI

---

Kickstarter-iOS/Views/Controllers/RewardAddOnSelectionViewController.swift
Kickstarter-iOS/Views/PillsView.swift

- Fixes the font size for the add-ons selection view header.
- Minor tweak to the `PillView` `backgroundColor` which fixes visual artifact see in _before_ screenshot below.
The font size didn't match the designs.
Updates the font and color 🎨 
| --- | --- |
| <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/87456408-bede0900-c5bb-11ea-9c7b-7724dcfd7a67.png"> | <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/87456314-9524e200-c5bb-11ea-84b3-eac69a149cdc.png"> |

[NT-1366] Add-Ons Header Font Size Fix

---

Library/Tracking/Koala.swift
Library/ViewModels/ActivitiesViewModel.swift
Library/ViewModels/ActivitiesViewModelTests.swift

Adds the event `Manage Pledge Button Clicked` when tapping manage on an errored pledge in the activities feed.
This is a tracking event that we still needed to add for fixing errored pledges.
Added the event and tests.

[NT-214] Add Tracking Event on Tapping Manage in Activity Feed

---

Kickstarter-iOS/Views/Controllers/PledgeAmountViewController.swift
Kickstarter-iOS/Views/Controllers/PledgeViewController.swift
KsApi/GraphSchema.swift
KsApi/models/Reward+ManagePledgeView.swift
KsApi/models/Reward+RewardAddOnSelectionView.swift
KsApi/models/Reward.swift
KsApi/models/RewardAddOnSelectionViewEnvelope.swift
KsApi/models/RewardAddOnSelectionViewEnvelopeTests.swift
KsApi/models/RewardTests.swift
KsApi/models/lenses/RewardLenses.swift
KsApi/models/templates/RewardAddOnSelectionViewEnvelopeTemplate.swift
KsApi/models/templates/RewardTemplates.swift
KsApi/queries/RewardAddOnSelectionViewQueries.swift
KsApi/queries/RewardAddOnSelectionViewQueriesTests.swift
Library/ViewModels/PledgeAmountViewModel.swift
Library/ViewModels/PledgeAmountViewModelTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/RewardAddOnSelectionViewModel.swift
Library/ViewModels/RewardAddOnSelectionViewModelTests.swift

Allows the selected base reward and its add-ons to have dissimilar shipping costs.
Previously the assumption was made that the shipping cost would be the same across the base reward and all of its add-ons. This is not the case and this PR addresses that.
- Update logic in `PledgeViewModel` and `RewardAddOnSelectionViewModel`.
- Display individual add-on shipping cost in `RewardAddOnCardView`.
- Add an optional `shippingRules` array to our `Reward` model.
- This data is only deserialized from GraphQL.
- Included some fixes to `PledgeAmountViewModel` to ensure pledges are within the max amount.

[NT-1450] Allow Dissimilar Shipping Cost for Add-Ons

---

Kickstarter-iOS/Views/Cells/RewardCell.swift
Kickstarter-iOS/Views/RewardCardContainerView.swift
Library/ViewModels/RewardCardViewModel.swift
Library/ViewModels/RewardCardViewModelTests.swift
Library/ViewModels/RewardCellViewModel.swift
Library/ViewModels/RewardCellViewModelTests.swift

- Adds the "You backed" label to the currently backed reward card.
- Adds the "Add-ons" tag to rewards that have add-ons.
This better surfaces information to backers that they have backed a particular reward and whether a reward had add-ons.
Added the UI elements and behaviour to hide/show the information with tests.
| --- | --- |
| <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/88740033-f3d87880-d0f0-11ea-8a55-37c5e124eee2.png"> | <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/88739929-a52ade80-d0f0-11ea-9729-d0ac19d51c0d.png"> |

[NT-1401] Reward Card UI updates

---

Kickstarter-iOS/Views/Controllers/ManagePledgeViewController.swift
Library/ViewModels/RewardsCollectionViewModel.swift
Library/ViewModels/RewardsCollectionViewModelTests.swift

Updates the string `Choose another reward` to `Edit reward`. This is seen in the Manage Pledge context menu as well as the rewards carousel title when navigating from the manage pledge context.
**Note:** This string has been added for translation and will be update along with other strings once translations have come back.
**Also note:** Editing the reward for a backing that has add-ons will be supported in an upcoming PR.
We're improving our nomenclature around this with the introduction of add-ons.
Updated the strings and added them for translation.
| --- | --- |
| <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/88850764-a87da300-d1a0-11ea-8d7e-2d19e6c510db.png"> | <img width="545" …

[NT-1443] Choose another Reward -> Edit Reward

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift
Library/ViewModels/ThanksViewModelTests.swift

Updates our tracking property `checkout_bonus_amount_usd` to be a decimal currency `String` rather than an `Int` representing the amount in USD cents.
This was the actual requirement, I implemented it in cents because I assumed it was the same as `checkout_revenue_in_usd_cents`.
Updated this to behave like the other decimal amounts in our `checkout_` tracking properties.

[NT-1391] Change Bonus Amount in USD to decimal currency

---

Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

Removes rounding of the tracking property `checkout_bonus_amount_usd`.
This value should not have been rounded.
Removed the rounded modifier.

[NT-1457] Remove Bonus Support Amount Rounding

---

Kickstarter-iOS/Views/Controllers/RewardsCollectionViewController.swift
Library/ViewModels/RewardsCollectionViewModel.swift
Library/ViewModels/RewardsCollectionViewModelTests.swift

Displays a prompt when editing a reward that previously had add-ons selected.
Selecting a new reward might affect the add-ons that a backer selected before and we would like to inform them of this during the edit flow.
Updated `RewardsCollectionViewModel` to display a prompt when selecting a reward under these circumstances:
- Reward has add-ons, project is not backed, navigates to add-on selection without prompt.
- Reward has add-ons, project is backed with add-ons, triggers prompt before add-on selection.
- Reward does not have add-ons, project is not backed, navigates to pledge without prompt.
- Reward does not have add-ons, project is backed with add-ons, triggers prompt before pledge.

[NT-1416] Edit Add-Ons Reward Alert

---

Kickstarter-iOS/Views/Controllers/PledgeShippingLocationViewController.swift
Kickstarter-iOS/Views/Controllers/PledgeViewController.swift
Kickstarter-iOS/Views/Controllers/RewardAddOnSelectionViewController.swift
Library/ViewModels/RewardAddOnSelectionViewModel.swift
Library/ViewModels/RewardAddOnSelectionViewModelTests.swift

Refreshes the shipping location selector on `RewardAddOnSelectionViewController` when the user pulls to refresh.
The shipping locations are fetched in a separate call to the reward add-ons so if one of these calls fail the user should have the opportunity to recover from that.
- Updated `RewardAddOnSelectionViewModel` to reconfigure the `PledgeShippingLocationViewController` when the user pulls to refresh.
- The `PledgeShippingLocationViewController` is now also hidden when it is in an errored state.
Turn on airplane mode or use Charles proxy to cause the shipping locations to fail.

[NT-1473] Reload Shipping Selector on Error

---

Library/ViewModels/PledgeAmountViewModel.swift

Fixes the amount displayed for the maximum pledge amount validation message.
This amount is initially set to `0` and then updated by the delegate. In some situations there was a race condition between the initial amount and the delegate causing the amount to remain at `0`.
Fixed the race condition by cancelling the initial value signal once we've received an amount from the pledge view.

[NT-1452] Maximum Pledge Amount Fix

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift
Library/Tracking/MockTrackingClient.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift
Library/ViewModels/RewardAddOnSelectionViewModel.swift
Library/ViewModels/RewardAddOnSelectionViewModelTests.swift
Library/ViewModels/ThanksViewModelTests.swift

Adds some required tracking for add-ons.
This will allow us to learn more about how backers use this feature and hopefully inform some of our decisions moving forward.
Added two tracking events:
`Add-Ons Continue Button Clicked`
`Add-Ons Page Viewed`
Added several checkout properties:
`checkout_add_ons_count_total`
`checkout_add_ons_count_unique`
`checkout_add_ons_minimum_usd`
`checkout_bonus_amount_usd`
`checkout_reward_minimum_usd`
`checkout_shipping_amount_usd`

[NT-1480] Tracking for Add-ons

---

Kickstarter-iOS/Views/RewardAddOnCardView.swift
Library/ViewModels/RewardAddOnCardViewModel.swift
Library/ViewModels/RewardAddOnCardViewModelTests.swift

Adds haptics to the `UIStepper` control on `RewardAddOnSelectionView`.
This is in keeping with the haptics that we have for the similar `UIStepper` control on our `PledgeViewController` and helps to communicate minimum, selection and maximum to the user while they are interacting with the control.
Updated `RewardAddOnSelectionViewModel` to generate the necessary signals when the stepper is at zero, within the selectable range or at the maximum.
During add-on selection, Iincrement and decrement the quantity stepper:

[NT-1486] Add-on Selection Card Haptics

---

Library/ViewModels/RewardsCollectionViewModel.swift
Library/ViewModels/RewardsCollectionViewModelTests.swift

Fixes a bug which would sometimes caused navigation to not work correctly when a backer edits their reward and selected a new reward.
This bug was caused by the behaviour of `Signal.zip`. `zip` emits when all of its signals have emitted at least once and then emits each time all of the signals have emitted again. In the situation where the user dismissed the alert by cancelling the last selected reward ID would remain in the buffer and the following time that they tapped _yes_ to continue it would incorrectly navigate to the wrong reward.
Rearranged the signals to make use of `takeWhen` instead of `zip`.
The ACs from #1269:
Also:

[NT-1416] Navigation bugfix

---

Library/ViewModels/PledgeAmountViewModel.swift
Library/ViewModels/PledgeAmountViewModelTests.swift

Fixes a bug that resulted in the bonus amount when editing a reward not being passed through correctly when editing to back a new reward.
Our check was too specific, we were checking to see that the reward was backed but we in fact only care that the project has been backed.
Updated the `guard` statement and added a test.

[NT-1492] Bonus Amount Editing Bugfix

---

KsApi/models/graphql/adapters/Backing+GraphBacking.swift
Library/ViewModels/ManagePledgeSummaryViewModel.swift
Library/ViewModels/ManagePledgeSummaryViewModelTests.swift
Library/ViewModels/ManagePledgeViewModel.swift
Library/ViewModels/ManagePledgeViewModelTests.swift

Hides the shipping line item displayed on the Manage Pledge View based on the base reward's shipping preference.
When editing a reward from one that has shipping to one without the back-end erroneously sends back shipping information for the backing which we were displaying at the client. This is a workaround to prevent that from happening.
We are now inspecting whether shipping is enabled for the backing's base reward before displaying the shipping line item.
| --- | --- |
| <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/92177852-2a8f6600-edf6-11ea-86e9-aca24bf05220.png"> | <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/92177474-6d9d0980-edf5-11ea-94c4-fcebd0ecec0c.png"> |

[NT-1493] Hide Shipping in Manage View Based on Base Reward

---

Kickstarter-iOS/Views/Controllers/PledgeShippingLocationViewController.swift
Kickstarter-iOS/Views/ShimmerLoadingViews/PledgeShippingLocationShimmerLoadingView.swift

Hides the shimmer loading effect for the shipping amount during add-ons selection.
We do not display an amount on this view so the shimmer creates the expectation that a value will be shown there.
Exposed the property for the placeholder and set its `alpha` to `0` when the amount label is hidden.
| --- | --- |
| <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/92290115-d48af300-eec7-11ea-89d3-ab9cd832aac3.png"> | <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/92290033-8970e000-eec7-11ea-86f4-2503eedce621.png"> |

[NT-1425] Hide Shipping Amount Shimmer During Add-ons Selection

---

Library/ViewModels/RewardAddOnCardViewModel.swift
Library/ViewModels/RewardAddOnCardViewModelTests.swift

Rounds up the converted amount displayed on add-on cards.
This is rounded up on the regular reward card shown in the rewards carousel and we were seeing `$0` values in some cases where the converted amount was below `$1`, for example `MX$10` is currently less than `US$1`.
Added rounding _up_ for this value without decimals.
| --- | --- |
| <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/92665102-89535480-f2ba-11ea-8d8c-5ff0337022d6.png"> | <img width="545" alt="image" src="https://user-images.githubusercontent.com/3735375/92664274-61fb8800-f2b8-11ea-94bb-6f478fd451d3.png"> |

[NT-1508] Round Up Converted Amount On Add-on Card

---

Kickstarter-iOS/AppDelegate.swift

Causes Optimizely configuration to timeout after 3 secs.
We have received some user reviews mentioning a blank Explore view when they launch the app. We're also noticing a very high number of errors being logged for Optimizely failing to initialize. We believe this may be timing out and causing the Explore view to take very long to load because of the way that we wait for Optimizely to be configured before activating the experiment needed to show the correct project cards in Explore.
Added a timeout interval of 3 seconds to `OptimizelyClient`'s `start(resourceTimeout:completion:)` function.
Optimizely [docs](https://docs.developers.optimizely.com/full-stack/docs/initialize-sdk-objective-c#section-asynchronous-initialization).

[NT-1513] Reduce Optimizely Configuration Timeout

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/Views/Cells/ProjectPamphletMainCell.swift
Kickstarter-iOS/Views/Controllers/ProjectDescriptionViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletContentViewController.swift
Library/OptimizelyExperiment.swift
Library/ViewModels/ProjectDescriptionViewModel.swift
Library/ViewModels/ProjectDescriptionViewModelTests.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift

Removes the `native_project_page_campaign_details` A/B experiment that we were running with Optimizely.
We're no longer running this experiment and have reverted to the `control` experience.
- Removed the experiment.
- Removed any code affected by this experiment.
Original PR for this experiment:
#1081

[NT-1504] Remove Project Page Campaign Details Experiment

---

.fastlane/Fastfile

Fixes a regression introduced in #1279 which caused our App Store dSYMs refreshing to stop working on CI.
Each time that we merge to master, when our beta app is distributed, we refresh the latest dSYMs from the App Store to ensure that Crashlytics always has them for re-symbolicating crashes.
The changes that were made in the above-mentioned PR caused this to stop working.
Added the necessary Fastlane action back to upload the dSYMs to Firebase Crashlytics.
https://docs.fastlane.tools/actions/download_dsyms/
http://docs.fastlane.tools/actions/upload_symbols_to_crashlytics

Fix refreshing of dSYMs on CircleCI

---

KsApi/queries/UserQueries.swift
KsApi/queries/UserQueriesTests.swift

Fixes a regression in our user account settings which caused changing user settings to error.
Why indeed. The refactor in #1263 introduced some changes that added a non-nil property `uid` to `GraphUser`. The various queries we have that fetch data for our user settings views make use of `GraphUser` but those queries unfortunately hadn't been updated to include the `uid` property resulting in `GraphUser` in those contexts failing to deserialize.
Added `GraphUser.baseQueryProperties` to `UserQueries`.

Fix User Settings Regression

---

Kickstarter-iOS/Views/Controllers/PledgeShippingLocationViewController.swift
Library/ViewModels/RewardAddOnCardViewModel.swift
Library/ViewModels/RewardAddOnCardViewModelTests.swift
Library/ViewModels/RewardAddOnSelectionViewModel.swift
Library/ViewModels/RewardAddOnSelectionViewModelTests.swift

- Filters add-ons from the list for selection when they are unavailable either by way of a timebased or quantity limit. Add-ons are always shown during editing when previously backed.
- Adds a small fix for haptics on the stepper.
- During UAT we found that we were able to select add-ons for backing even though they might be unavailable. This resulted in unexpected behaviour.
- Haptics were being triggered on cell configuration but should only emit when adjusting the stepper.
- Added availability checking and tests.
- Updated the logic for haptics and updated the test.

[NT-1533] Filter Add-Ons From List When Unavailable

---

.circleci/config.yml

Reduces our CircleCI config by ~200 lines by grouping jobs that are similar with a few variables that change.
@yatriks and I started improving the verbosity of this config in #1143 and figured it would be good to reduce it even further, it makes the file easier to understand and maintain.
Identified jobs that were similar except for a couple of variable parts which we turned into environment variables.

Reduce CircleCI config verbosity

---

Kickstarter-iOS/Views/Controllers/CancelPledgeViewController.swift
Library/ViewModels/CancelPledgeViewModel.swift
Library/ViewModels/CancelPledgeViewModelTests.swift

We are displaying a loading spinner within the Cancel pledge button while the API call is processing. 
This behavior is currently implemented on the `Pledge` and `Confirm` buttons.
We replace the `UIButton` with a `LoadingButton` within the `CancelPledgeViewController`, provide functionality within the view model to observe the cancellation event and appropriately render either the buttons title or loading spinner.

[NT-542] Replace UIButton on CancelPledgeViewController with LoadingButton

---

KsApi/models/graphql/adapters/Backing+GraphBacking.swift
KsApi/models/graphql/adapters/Backing+GraphBackingTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

On the "Update Pledge" screen, when the user has pledged for no reward, the "Pledge" line item will be hidden. Similarly, on the "Change Payment Method" screen, when the user has pledged for no reward, the "Pledge" line item will be hidden.
When a user pledges for no reward, there was previously redundancy in the way we present the pledge amount.
Added some logic to a couple of our view models that determine whether there is a reward before determining the set up of their respective view controllers.

[NT-1543][NT-1544] Update Pledge and Change Payment Method stackview behavior updates

---

KsApi/extensions/DateFormatter+ISOFormatter.swift
KsApi/models/graphql/adapters/Reward+GraphRewardTests.swift

Fixes an issue where the estimated delivery date was incorrect on `ManagePledgeViewController`.
We were using the incorrect date format for our date formatter when deserializing this date from GraphQL. We have different date formats used in various places, some are timestamps, some are ISO8601, but in this particular case the date is `YYYY-MM-DD` which `NSDateFormatter` converts as `yyyy-MM-dd`.
Updated the configuration of the date formatter used to convert this date string.
| Reward selected | Manage Pledge |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3735375/94193183-de6b9a80-fe64-11ea-88d4-9c60acd39b67.png) | ![image](https://user-images.githubusercontent.com/3735375/94193231-f3e0c480-fe64-11ea-8802-59907b7a294b.png) |

[NT-1550] Fix ISO Date Format

---

Library/ViewModels/RewardCardViewModel.swift
Library/ViewModels/RewardCardViewModelTests.swift

When specifying a quantity of add-ons, we use `# x add-on name` on both the Pledge screen and the View/Manage Pledge screen. On the Pledge screen, we hide `# x` when # is > 1, but we don’t do that on the View/Manage screen
Consistency within view controllers that display similar information.
All of the work is done in the `RewardCardViewModel`. We're doing a check on the quantity of the add-on which was updated.

[NT-1495] Update logic for quantity attributed text in RewardCardView

---

Library/SharedFunctions.swift
Library/ViewModels/RewardCardContainerViewModel.swift
Library/ViewModels/RewardCardContainerViewModelTests.swift
Library/ViewModels/RewardsCollectionViewModel.swift
Library/ViewModels/RewardsCollectionViewModelTests.swift

Fixes two bugs with regards to the availability of rewards:
1. If a reward is both timebased and limited we were allowing users to back rewards if either of these conditions passed, for example someone could back a timebased reward, that was also limited, that had expired but had a remaining positive quantity.
2. We were allowing users to tap through on reward cards even when unavailable under certain conditions.
Users should not be able to back rewards in these situations and we also did not have sufficient back-end fail-safes to prevent this.
1. Fixed the logic that determines the availability of rewards.
2. Shared the rewards carousel navigation filtering behaviour.
3. Updated tests.

[NT-1559] Reward Availability Bugfixes

---

Library/SharedFunctions.swift
Library/SharedFunctionsTests.swift
Library/ViewModels/RewardCardContainerViewModel.swift
Library/ViewModels/RewardCardViewModel.swift
Library/ViewModels/RewardsCollectionViewModel.swift
Library/ViewModels/RewardsCollectionViewModelTests.swift

Allows backers to edit an expired reward with add-ons.
Fixes a bug from #1309. Rewards should be editable if they've expired and have add-ons.
Fixed the logic for this and added tests.

[NT-1565] Backers Can Edit an Expired Reward with Add-Ons

---

KsApi/lib/TryDecodable.swift
KsApi/lib/TryDecodableTests.swift
KsApi/models/Update.swift
KsApi/models/UpdateTests.swift
Library/SharedFunctionsTests.swift

First step to remove Argo dependency
With **Swift.Codable** introduction there is no need to carry around **Argo** lib for JSON parsing 
[RFC](https://github.com/kickstarter/rfcs/blob/master/rfcs/0069-native-deprecate-argo.md)
**tryDecodable** function
Extended test coverage for tryDecodable function
- Added tests for primitive data types
- Added tests for missing key and key type mismatch
**Update.UrlsEnvelope** and **Update.UrlsEnvelope.WebEnvelope** converted to **Swift.Codable** 
- added test cases for missing key and key type mismatch

[NT-1575] Argo Decodable Function

---

Library/SharedFunctions.swift
Library/SharedFunctionsTests.swift
Library/ViewModels/RewardAddOnSelectionViewModel.swift
Library/ViewModels/RewardAddOnSelectionViewModelTests.swift
Library/ViewModels/RewardsCollectionViewModel.swift

Currently, backers are able to see rewards and add-ons with future start dates and back them. We want to conditionally render these options for selection only when the appropriate time has been reached.
Currently, rewards and add-ons with start dates in the future are being shown as available for backing. These should be hidden from view until the start date set by the creator.
We're filtering in the `RewardAddOnSelectionViewController` and `RewardCollectionViewController` based on a date check.

[NT-1584][NT-1588] Handling rewards and add ons with future start dates

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/Service+DecodeHelpers.swift
KsApi/Service+RequestHelpers.swift
KsApi/ServiceTests.swift
KsApi/models/ErrorEnvelope.swift
Library/SharedFunctionsTests.swift

`Service+DecodeHelpers` extracted from `Service+RequestHelpers` and added `Swift.Decodable` overloads
Extended tests cases for both `Argo` and `Swift.Decodable` functions
`Service+RequestHelpers` is a part of Argo removal process. It is required to make it work with `Swift.Decodable` models
`Service+DecodeHelpers` extracted from `Service+RequestHelpers` and added `Swift.Decodable` overloads.

[NT-1576] Added test cases for service ext decode API

---

Kickstarter-iOS/AppDelegate.swift
Library/ViewModels/DiscoveryViewModel.swift
Library/ViewModels/DiscoveryViewModelTests.swift

There have been reports that user's are seeing blank screens on discover. We've tracked down this issue to an issue with Optimizely. The fix was to reduce the amount of time the app will wait for Optimizely to initialize. After the fix we were still noticing issues with discover.
User's are unable to access the discover page to view projects. Reproducing this was difficult until a user mentioned that their NextDNS VPN was causing it to not work. Testing on a physical device indicated that it was indeed causing blank screens on iOS. 
Another way to test for this is by setting the optimizely key to an empty string. When this happens the sdk is unable to download the datafile and thus cannot configure the sdk. The fix is to call the failed to configure sdk signal when this happens and also …

NT-1631: Blank Screen on Discover

---

Library/Extensions/Feature+Helpers.swift
Library/Extensions/Feature+HelpersTests.swift
Library/Feature.swift
Library/ViewModels/FeatureFlagToolsViewModelTests.swift

Before we begin the heavy lifting for the email verification work, we'll need to put the work behind feature flags to prevent incomplete work or bugs from being exposed in any future releases. We've added two feature flags to the project after setting them up on Flipper.
Feature flags are a commonly used paradigm in software development that allow you to modify system behavior without changing the code explicitly. The email verification feature work is split into smaller pieces that will be incrementally developed and released as they are completed. The feature flags we've added here will ensure that any new releases prior to the completion of the feature will not introduce unexpected behavior for our current users.
The following two flags were added to the project:
- …

[NT-1644][NT-1645] Adding email verification feature flags

---

Kickstarter-iOS/AppDelegate.swift

We noticed an influx of reports from Support Dev that suggested deeplinking was no longer working for users. It appears we introduced a regression recently and this PR provides the fix.
The push notifications are designed to take the user directly into the relevant point in the application. When deeplinking doesn't work as expected, the user is simply taken into the app and loses context of what the notification was meant for.
In the `userNotificationCenter: didReceive` delegate method we were not handling the response. It looks like when we [removed the Qualtrics SDK](https://github.com/kickstarter/ios-oss/commit/f6a6d8dec8890d29b8b291750be8fa19624d6494#diff-2b5cc9e2481b28948ced1e33f97217f053db9fd9c2de5070819b45ff03463369L483) we introduced a regression and removed the view model …

[NT-1670] Deeplink users when selecting a remote notification

---

Kickstarter-iOS/Views/Cells/PledgeExpandableHeaderRewardCell.swift
Kickstarter-iOS/Views/Cells/PledgeExpandableHeaderRewardHeaderCell.swift

Fixes an issue that was causing the reward title on the pledge view to sometimes be clipped.
This is not the expected behaviour and hampers the experience.
Set the property `insetsLayoutMarginsFromSafeArea` to `false` for both of the cell's root stackviews in this table view. Sometimes when the cell is scrolled beyond the safe area of the view and performs a layout pass it does so incorrectly insetting its layout margins from the safe area. Setting this property to `false` prevents this from happening. I was not able to reproduce the issue after setting this to `false` but could consistently do so with it being `true` (default).
https://developer.apple.com/documentation/uikit/uiview/2891101-insetslayoutmarginsfromsafearea
| --- | --- |
| …

[NT-1494] Fix for Pledge View Reward Title Being Cut Off

---

Kickstarter-iOS/Library/SharedFunctions.swift
Kickstarter-iOS/Views/Controllers/EmailVerificationViewController.swift
Kickstarter-iOS/Views/Controllers/LoginViewController.swift
Kickstarter-iOS/Views/Controllers/SignupViewController.swift
Library/SharedFunctions.swift
Library/SharedFunctionsTests.swift
Library/ViewModels/LoginViewModel.swift
Library/ViewModels/LoginViewModelTests.swift
Library/ViewModels/SignupViewModel.swift
Library/ViewModels/SignupViewModelTests.swift

Before dismissing the login or sign up view controllers we need to push an interstitial UI for email verification onto the navigation stack. The work is behind a feature flag and given the user successfully logs in (within the context of login or account creation) we should show the email verification UI before the tab bar is rendered.
This PR continues the work for our email verification flow. It represents the connection between our `User` and UI/UX interactions.
Login and account creation rely on `NotificationCenter` to dismiss the view controllers after the user has successfully logged in. In between login and view controller dismissal, the email verification work is plugged in. Specifically in the `LoginViewController` and `SignUpViewController`.

[NT-1661][NT-1662] Connect Login and Signup Flow to Interstitial UI

---

Library/Tracking/Koala.swift
Library/Tracking/KoalaTests.swift
Library/ViewModels/EmailVerificationViewModel.swift
Library/ViewModels/EmailVerificationViewModelTests.swift

Adds event tracking for `EmailVerificationViewController`.
This will help us to gain insights into how this feature is being used when the app is live.
Added two new events:
`Verification Screen Viewed`
`Skip Verification Button Clicked`

[NT-1655] Email Verification Event Tracking

---

Kickstarter-iOS/Views/Controllers/EmailVerificationViewController.swift
Library/ViewModels/EmailVerificationViewModel.swift
Library/ViewModels/EmailVerificationViewModelTests.swift

Requests that the verification email is re-sent upon `EmailVerificationViewController`'s view loading.
When users are shown this view we want to ensure that they have a fresh verification email in their inbox.
Wired up the `viewDidLoad` signal to the same code as the re-send button and added in a boolean to decide whether or not to show the success message.

[NT-1679] Re-send Verification Email on View Loading

---

KsApi/models/Backing.swift
KsApi/models/BackingTests.swift

There is a decoding error within our `Backing` model object that is causing an error in our pledge view. We are currently expecting a `Bool` to be returned for our `backer_completed_at` key but the server is actually providing an `Int`. This PR includes a bit of logic to map these different types.
This bug is preventing backers from viewing their pledge/reward. The footer will show an error and a Retry button because of the decoding failure. 
The expected behavior is a button that says `View Your Pledge` and once the user selects it they can view the details of their pledge/reward.
In our `Backing` object, we included a line to map the value of an existing timestamp to a boolean.

[NT-1692] "Mark as received" causes View Pledge to error

---

Library/ViewModels/SurveyResponseViewModel.swift
Library/ViewModels/SurveyResponseViewModelTests.swift

Fixes a bug in `SurveyResponseViewModel` which was causing survey response submission to fail on iOS 14.
In the time of iOS 12 and iOS 13, a bug existed in `WKWebView` which would produce a `nil` `httpBody` property on `URLRequest`. This was problematic for us because we would intercept these requests in order to inject our authentication headers before submitting the form data in the web view. A workaround was introduced in #975 to do this which thus expected the `httpBody` to be `nil` however it no longer is on iOS 14 as it seems Apple or the WebKit team have fixed this bug (although I can't find a source to confirm this).
Added another path to handle the request which does not require the `httpBody` to be `nil` and in this case does not evaluate the JavaScript as a workaround.
Some …

[NT-1599] Survey Response Bugfix

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/models/Backing.swift
KsApi/models/BackingTests.swift
KsApi/models/ProjectActivityEnvelope.swift
KsApi/models/ProjectActivityEnvelopeTests.swift

Fixes two decoding bugs that were found in `MessageThread` and `ProjectStatsEnvelope`.
These are regressions that were introduced in #1323.
- `MessageThread` was expecting an array type for the incorrect key. Updated the key and added a test.
- `ProjectStatsEnvelope` needed a `CodingKeys` `enum` in order to decode the snake_cased `more_activities` key.

[SD-345] MessageThread and ProjectStatsEnvelope Decoding Bugfixes

---

Kickstarter.xcodeproj/project.pbxproj
Makefile
bin/carthage.sh

- Updates our `bin/carthage.sh` script so that when run locally arguments will be passed through and our `Carthage` directory won't be cached.
- Fixes the issue that the PR #1360 raised.
- When running Carthage builds locally we typically need this behavior and it's inconvenient to have to edit the script each time.
- It turns out that Xcode 12.3 requires that our project includes the `VALIDATE_WORKSPACE` value in our project configuration, but this value does not need to be `YES` as it was set in #1360. See: https://stackoverflow.com/a/65354762/2271759
Made the changes described above.

[NT-1725] Fix Tests And Only Cache Frameworks on CI

---

KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/lib/Route.swift

While documenting [a list of the API requests](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/908525614/Native+API+Documentation) currently being made in the project, we determined a few of our REST API methods were no longer in use. It's presumable that during the shift from REST to GraphQL they may have been left behind. 
This is the first step in an eventual update of how we're handling our API interactions on iOS. Ideally, sometime later in 2021 we can add on to this work by investigating further re-factoring of some REST endpoints to GraphQL.
Updated the following files:
- `Route.swift`
- `Service.swift`
- `ServiceType.swift`
- `MockService.swift`

[NT-1734] Remove unused REST API references

---

KsApi/models/Reward.swift
KsApi/models/graphql/adapters/Reward+GraphRewardTests.swift
Library/OptimizelyClientType.swift
Library/OptimizelyClientTypeTests.swift
Library/SharedFunctions.swift
Library/TestHelpers/MockOptimizelyClient.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/UIDeviceType.swift
Library/ViewModels/DiscoveryPageViewModelTests.swift
Library/ViewModels/PledgeCTAContainerViewViewModelTests.swift
Library/ViewModels/PledgeViewModelTests.swift
Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift
Library/ViewModels/ThanksViewModelTests.swift

As part of our ongoing initiative to implement `Segment` and replace our legacy tracking clients, we begin here with some renaming of old events. The Insights team has provided us with a set of properties and the contexts they belong to; this PR is one of many upcoming extensions to the addition of Segment.
Our events and their respective tracking clients are present everywhere in this project. It's important that we break down all these tasks into manageable bits. Each phase of work will be represented by anywhere from one to three tickets.
A lot of the work is in our `KSRAnalytics` file and the tests that make use of it.

[EP-149] Rename Properties (Phase One)

---

Cartfile
Cartfile.resolved
Configs/Secrets.swift.example
Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
KsApi/ServiceType.swift
KsApi/ServiceTypeTests.swift

Adding Perimeter X SDK into the project.
Due to some recent security incidents we are using `Perimeter X` to bolster the authorization info we provide in our http headers.

Add PerimeterX SDK

---

Library/Extensions/Feature+Helpers.swift
Library/Extensions/Feature+HelpersTests.swift
Library/Feature.swift
Library/Tracking/Segment.swift
Library/ViewModels/FeatureFlagToolsViewModelTests.swift

Adding a feature flag for Segment and implementing it within out Analytics client.
This is simply an additional layer of control on the clients behavior in our environments.
- Added the flag on Flipper
- Decoding it on iOS
- Implementing it into the `Segment` client

[NT-1760] Adding feature flag for segment

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/PledgeViewModelTests.swift

When a user clicks the "Pledge" button we're currently firing an event labeled `Pledge Submit Button Clicked`. In this PR we are updating both the event name and the properties we send along with it.
This is an addition to our ongoing initiative to move forward from our legacy tracking and over to Segment.

[EP-226] CTA Clicked (pledge_submit)

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/CommentsViewModel.swift
Library/ViewModels/CommentsViewModelTests.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift
Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift
Library/ViewModels/ProjectUpdatesViewModel.swift

Updating the event that is called when a `Project` is viewed on native iOS. In addition, we are including functionality that will trigger an event when the Campaign, Updates or Comments associated with a given project, are viewed.
Continuing to extend our Segment implementation and flesh out our new analytics client.

[EP-230] Page Viewed (project)

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/PledgeCTAContainerViewViewModelTests.swift

"Project Page Pledge Button Clicked" event is updated to CTA Clicked with pledge_initiate context
Convert DataLake event to Segment event

[EP-225] CTA Clicked (pledge_initiate)

---

Library/SharedFunctions.swift
Library/SharedFunctionsTests.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/RewardsCollectionViewModel.swift
Library/ViewModels/RewardsCollectionViewModelTests.swift

This PR includes an update to tracking we're currently using in the Rewards carousel. When a reward is selected, we are tracking a handful of properties associated with the context.
Continuing phase one of our Segment implementation.

[EP-227] CTA Clicked (reward_continue)

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/RewardsCollectionViewModel.swift
Library/ViewModels/RewardsCollectionViewModelTests.swift

Adding a new `Page Viewed` event that fires when the Rewards Carousel is opened.
This PR is part of our continuing efforts to move away from our legacy analytics platform and toward a full Segment implementation.

[EP-231] Page Viewed (rewards)

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/WatchProjectViewModel.swift
Library/ViewModels/WatchProjectViewModelTests.swift

CTA Clicked (watch_project)
Segment Integration
More in-depth discussion of the change or implementation.
1. Move related Watch context to a new Enum `WatchContext`
2. Added a new parameter to `trackWatchProjectButtonClicked` (`watchContext`). This allows tracking for watch and unwatch project.
3. More tests to include `unwatch` context.

[EP-245] CTA Clicked (watch_project)

---

Library/Feature.swift
Library/ViewModels/FeatureFlagToolsViewModel.swift
Library/ViewModels/FeatureFlagToolsViewModelTests.swift

When a developer would like to enable a feature flag in the app, the selection is not linked to the right feature. We filter the enabled features on the client, however do not update the filtered list but the full list
An additional step to filter the features based on the enabled client side features is added

Feature Flag Enable Fix

---

KsApi/models/Project.swift
KsApi/models/ProjectTests.swift
KsApi/models/lenses/ProjectLenses.swift
KsApi/models/templates/ProjectTemplates.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift

Decoding tags from the API request for a given project and sending that with our existing project properties, to Segment.
Phase 2 segment implementation

[EP-364] Adding project_tags

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

Added a track event for when update pledge screen is viewed.
There are two ways to get to `Update Pledge Screen`, either from `Manage Pledge` or `Update Reward`.
Phase 3 of segment implementation

[EP-323] Page Viewed (update_pledge)

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

Extending the event tracking functionality of our `PledgeViewModel` to handle a `Page Viewed` event specifically for when the payment method is changed.
Phase 3 Segment implementation

[EP-319] Page Viewed (change_payment)

---

Library/SharedFunctions.swift
Library/SharedFunctionsTests.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift
Library/ViewModels/ProjectPamphletViewModel.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift
Library/ViewModels/RewardsCollectionViewModelTests.swift
Library/ViewModels/ThanksViewModelTests.swift

Remove the following event properties and their related tests.
- checkout_amount
- checkout_bonus_amount
- checkout_shipping_amount
- context_timestamp
- project_category_id
- project_goal
- project_location
- project_static_usd_rate
- project_subcategory_id
- session_apple_pay_device
- session_cellular_connection
- session_enabled_features
- session_mp_lib
- session_referrer_credit
- session_wifi_connection
- user_country
Base on the feedback from QA for Phase 1 event tracking, some of the event  properties sent to Segment are not needed.

[EP-399] QA Phase 1 Remove Properties

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift

Send a CTA clicked event when the "Read more about the campaign" is clicked to view campaign details
Part of phase 3 iOS Native events tracking

[EP-283] CTA Clicked (campaign details)

---

Kickstarter.xcodeproj/project.pbxproj
Library/TimeInterval+ISO8601Date.swift
Library/TimeInterval+ISO8601DateTests.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/PledgeViewModelTests.swift
Library/ViewModels/ThanksViewModelTests.swift

Add a new extension that converts TimeInterval to ISO 8601 Date and Time  Format.
Update `checkout_reward_estimated_delivery_on `, `project_deadline `, and `project_launched_at ` to send ISO 8601 Date Time format to Segment. 
Based on the feedback from QA Phase 1 event tasks, `checkout_reward_estimated_delivery_on `, `project_deadline `, and `project_launched_at ` are sending their values as `TimeInterval` .

[EP-402] QA phase 1 fix time properties

---

KsApi/models/templates/ProjectTemplates.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift

Add some new properties to User, Session and Project property groups
Event Project Phase 1 QA additions

[EP-400] QA Phase 1 Add properties

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift

Fix conversion for `goal_usd` and `current_amount_pledged_usd` properties by deriving their values from project properties that use `fx_rate` for conversion rather than `static_usd_rate`
Part of phase_1 Segment events QA

[EP-403] Fix Conversion Properties

---

Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-iOS.xcscheme
KsApi/models/PaymentType.swift
Library/SharedFunctions.swift
Library/SharedFunctionsTests.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/UIDeviceType.swift
Library/ViewModels/LoginToutViewModelTests.swift
Library/ViewModels/PledgeViewModelTests.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift
Library/ViewModels/ThanksViewModelTests.swift

Fixing properties after phase one of Segment QA. Some of these are smaller changes like changing the type whereas some are updates to where we get the values from.
Updates after receiving QA feedback for phase one of our Segment implementation.

[EP-401] Fix properties (phase one)

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift

Remove the following properties from segment.
- session_device_distinct_id
- session_device_manufacturer
- session_device_model
- session_os_version
- session_screen_width
- session_user_agent
Based on feedback from QA on Phase 2 tickets, some Segment event properties aren't needed.

[EP-439] QA Phase 2 - Properties to remove

---

KsApi/models/User.swift
KsApi/models/UserTests.swift
KsApi/models/lenses/User.StatsLenses.swift
KsApi/models/lenses/UserLenses.swift
KsApi/models/templates/User.StatsTemplates.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift

Change how we send `launched_project_count` and `created_project_count` for User Properties to Segment.
The api returns created_project_count, this is the count of the project that you've created, but on segment user_created_project_count  definition is different, to get the value you'll need created_project_count from api + draft_project_count  from the api, while `launched_project_count` on segment  is `created_project_count` from the api.

[EP-404] QA Phase 1 Fix User Properties

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
Kickstarter-iOS/ViewModels/UpdateViewModel.swift
Kickstarter-iOS/ViewModels/UpdateViewModelTests.swift
KsApi/models/Project.swift
KsApi/models/graphql/GraphBackingTests.swift
KsApi/models/graphql/GraphProject.swift
KsApi/models/graphql/ManagePledgeViewBackingEnvelopeTests.swift
KsApi/models/graphql/RewardAddOnSelectionViewEnvelopeTests.swift
KsApi/models/lenses/ProjectLenses.swift
KsApi/models/templates/ProjectTemplates.swift
KsApi/models/templates/graphql/GraphProjectTemplates.swift
Library/Tracking/KSRAnalyticsTests.swift

Currently, we're using the field `prelaunch_activated` to determine the display logic of prelaunch deeplinks. We want to change this logic to check `display_prelaunch` instead. 
We will need to add a new field `displayPrelaunch` to capture this field from the project payload.
Any instances using `prelaunch_activated` for display logic will need to be updated to use `display_prelaunch` instead.
We're making this change after noticing some discrepancies with the response from the web. This, paired with some changes to the backend logic, should ensure we're all on the same page.

[NT-1822] Switch prelaunch display logic to use display_prelaunch field from v1 API

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/EmptyStatesViewModelTests.swift
Library/ViewModels/RootViewModelTests.swift

- Updating some properties related to the `Explore projects` button on the activity tab.
- Sending an event for when the `Home` tab is selected from the tab bar navigation.
Event: CTA Clicked
Property Groups: Context Properties, Session Properties, User Properties
context_cta = discover
context_page = activity_feed
context_location = [null]
Event: CTA Clicked
Property Groups: Context Properties, Session Properties, User Properties
context_cta = discover
context_location = global_nav
This is a refinement based on QA feedback from our insights team. The point of these properties is to draw a very specific context to each event. This PR includes updates to the context properties, specifically.

[EP-459] QA CTA Clicked (discover) phase two

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
Kickstarter-iOS/Views/Cells/ProjectPamphletMainCell.swift
Kickstarter-iOS/Views/Controllers/ProjectDescriptionViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectPamphletContentViewController.swift
Library/ViewModels/ProjectDescriptionViewModel.swift
Library/ViewModels/ProjectDescriptionViewModelTests.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModelTests.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

Page viewed for project was tracked in two places. 
Moved the one for campaign section context into Project Description screen when the content loads.
Add RefTag as part of the Config Data sent to ProjectDescription screen.
This is part of phase 1 Events QA.

[Ep-458] QA Page Viewed (Project) Phase 1

---

KsApi/px/PerimeterXClient.swift

Fixes beta builds on CircleCI.
This slipped through because, during development, KsApi is imported with `@testable`. The visibility of this type needed to in fact be `public`.
Updates the type's visibility.

Fix Beta Builds

---

.circleci/config.yml

Disables `refresh_app_store_dsyms` in our CI pipeline.
Refreshing dSYMs in this way is something we do in the event that Apple recompiles our app using bitcode. This is not something that has happened to my knowledge and, if it were to happen, would be quite infrequent. The purpose of refreshing the dSYMs is to download the latest from App Store Connect and upload them to Crashlytics to assist with resymbolication of crash logs. Some more info here: https://github.com/kickstarter/ios-oss/pull/420
We're disabling this because Apple updated the App Store Connect API to require 2FA authentication which presents an interactive prompt during our CI builds which we're not around to respond to.
Until Fastlane provides a way for us to include an API key in the relevant Fastlane command we're …

[NT-1856] Disable Refreshing dSYMs on CircleCI

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift

Retains the feature flag toggles that we set in our debug menu between app launches.
This makes our development workflow easier so that we don't have to remember to enable feature flags each time the app launches while we're testing.
When the app starts up it restores its config from storage, I've added a function to give the values retrieved from storage precedence over the incoming values.
Note that this means the toggles that we have in the app will always override those that are coming in from the back-end. In order to reset the debug toggles and receive the values from the back-end we will need to delete the app and install it again.

[NT-1850] Retain Debug Feature Flag Values For Non-Release Builds

---

Configs/Secrets.swift.example
Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
Library/Tracking/IdentifyingTrackingClient.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/MockTrackingClient.swift
Library/Tracking/Segment.swift
Library/Tracking/TrackingClient.swift
Library/Tracking/TrackingClientType.swift

- Moves our configuration of Segment to be after the `AppEnvironment` is set up.
- Enables and disables all Segment tracking by feature flag.
- Tidies up our protocols that we were using before to mock and feature flag tracking.
- We had a race condition in that we were instantiating Segment's `Analytics` during the instantiation of the `AppEnvironment` and therefore could not inspect the environment at the same time. Moving this makes more tests possible.
- Previously we were feature-flagging the `track`, `identify`, etc methods but Segment would still track app lifecycle events. It turns out Segment provides `disable()` and `enable()` functions to completely disable/enable tracking which we are now using instead.
- Note: Segment is _disabled_ by default and enabled by the feature flag …

[NT-1851] Enable/Disable Segment By Feature Flag

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/px/MockPerimeterXTypes.swift
KsApi/px/PerimeterXClient.swift
KsApi/px/PerimeterXTypes.swift

In a previous refactor (#1427) we encountered a Swift bug and implemented a workaround for that. Thinking about this more I think this would be a better approach and coincidentally noticed that it also helps to reduce noise in our console logs.
Although sometimes necessary it's preferred to avoid awkward workarounds for language/platform bugs as far as possible.
Also, upon investigating I discovered that the earlier refactor had also caused duplicate symbol warnings in the console log which, while somewhat innocuous in this case, is also preferable to avoid:
- Moved target membership around so that only KsApi imports `PerimeterX`.
- Updated the `PerimeterXBlockResponseType` to have a simple function which receives a `UIViewController` on which to display the captcha.

[NT-1858] Remove PerimeterXWrapper workaround

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift

Adds the user subscriptions to our analytics `identify` call.
We will carry these properties through to Segment and Braze so that we can manage push/email subscriptions based on these values.
Added the subscriptions to the traits dictionary that's passed to `identify`.
```json
{
"traits": {
"anonymousId": "70A0938F-99E2-4C29-9A32-12C4999B0E64",
"backed_projects_count": 43,
"created_projects_count": 0,
"is_creator": false,
"name": "Justin Swart",
"notify_mobile_of_backings": true,
"notify_mobile_of_comments": true,
"notify_mobile_of_follower": true,
"notify_mobile_of_friend_activity": true,
"notify_mobile_of_messages": true,
"notify_mobile_of_post_likes": true,
"notify_mobile_of_updates": true,
"notify_of_backings": false,
"notify_of_comment_replies": true,
"notify_of_comments": true, …
```

[NT-1843] Add Subscriptions To Identify Call

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/SignupViewModel.swift
Library/ViewModels/SignupViewModelTests.swift

- Convert `Sign up Submit Button Clicked` Event to a CTA Clicked event
- Supply a `TypeContext` based on newsletter subscription to the the CTA event.
- Add a test for the analytics event method that tracks signup submit button clicked.
This is part of phase 6 of Segment event tracking.
1. Launch and App and navigate to Sign up screen, that's if you're not already logged in.
2. Enter a name, email address and a password so that the Sign up button is enabled
3. You can also toggle the newsletter switch
3. Once the Sign up button it's enabled, tap it
4. Verify that a CTA event shows up in Segment debugger with these properties
```
"event": "CTA Clicked"
"context_cta": "sign_up_submit"
"context_page": "sign_up",
"context_type": "subscription_true" or "subscription_false" (depending on …
```

[EP-282] CTA Clicked (sign_up_submit)

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/PledgePaymentMethodsViewModel.swift
Library/ViewModels/RootViewModelTests.swift
Library/ViewModels/WatchProjectViewModel.swift

- Remove `page` parameter in `track` function inside KSRAnalytics.
- default `page` in `contextProperties()` function to `other` for some events that Product/Insight hasn't defined `page_context` for.
We previously had `page` as a parameter in our `track` function as well as `contextProperties()` function. This is not necessary as we need all of our `Context Properties` to be in on function called `contextProperties()`

[EP-450] context_page = other

---

Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-iOS.xcscheme
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift

Add `context_page` = `other` when user clicks on Search Tab from Creator Dashboard Tab
This is a continuation of our Segment Integration.
- Navigate to Creator's Dashboard Tab
- Switch to Search Tab 
- Verify on Segment debugger that 
> `context_page` = `other`
> `context_cta` = `search`
> `context_location` = `global_nav`

[EP-491] QA CTA Clicked Search

---

Kickstarter.xcodeproj/project.pbxproj
Library/KeyValueStoreType.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsIdentityData.swift
Library/Tracking/KSRAnalyticsIdentityDataTests.swift
Library/Tracking/KSRAnalyticsTests.swift

Reduces the amount of times that we call `identify` on our analytics client.
We incur costs per API calls on Segment and data points on Braze so we want to reduce unnecessary `identify` calls and only send deltas of user traits to reduce the amount of data points that are updated. Traits are cumulative so sending the deltas is acceptable and by design.
I've added a `KSRAnalyticsIdentityData` type which we use to perform the necessary comparisons. This type is also encoded and decoded into user defaults so that it's persisted between app sessions.
TBD. All of the traits are always shown on the Segment debugger - we may have to debug this using Charles Proxy.
By placing this print statement in the code we can see that it is only sending through the delta that I am toggling:

[NT-1866] Reduce Analytics Identify Calls

---

.slather.yml
Kickstarter.xcodeproj/project.pbxproj
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsIdentityData.swift
Library/Tracking/KSRAnalyticsIdentityDataTests.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/Tracking/Segment.swift
Library/Tracking/Vendor/BrazeDebounceMiddleware.swift

Updates our analytics `identify` call to always send all traits to Segment while de-duping the traits send to Braze using the middleware class provided by Braze.
In #1452 we did some work to reduce the amount of identify calls due to the nature of our billing with Segment being per API call. We initially thought that this would cause Segment to only sent the deltas on to Braze but it appears that it always sends all of the traits that it has in its cache. Adding the middleware is the intended solution for this and inserts a step between Segment's identify call and the data being sent on to Braze during which these traits are de-duped.
- Added the `BrazeDebounceMiddleware` class and configured the Segment client with it.
- Removed the de-duplication from the traits that we send to …

[NT-1873] Implement BrazeDebounceMiddleware

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
Library/Navigation.swift
Library/NavigationTests.swift

Allows us to enable a push notification setting from an in-app message dialogue sent from Braze.
We are making use of in-app messages from Braze to inform users of new notifications that they may wish to subscribe to.
- Implement the `ABKURLDelegate` `handleAppboyURL(_:from:withExtras)` function which receives the URL from the in-app message button tap.
- Parse the URL through a `Navigation` deep-link.
- Update the currently logged in user and send a `PUT` request to the `/v1/users/self` endpoint.
https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/in-app_messaging/customization
Go to your user's notification settings, disable the push notification for mobile marketing updates (top of the list). Enable the Braze feature flag in the debug menu.

[NT-1870] Enable Notification Setting From In-App Message

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/PledgeViewModelTests.swift
Library/ViewModels/ProjectPamphletViewModelTests.swift

Sends the user ID property as a `String` instead of an `Int`.
@lauriestark found that there were data anomalies related to the user ID property in Amplitude and upon investigation it seems that this property is being flagged as a violation for not being a `String`.
Also, we _do_ send this property as a `String` when we call `identify` because that does not accept an `Int`. It seems reasonable to assume that these data types should be the same but I've opened this PR for us to test and discuss as I have limited context of this project thus far. @singhhari should advise.
Wrapped the user ID in a `String` and updated tests.
Screenshot of violation in Segment debugger:
Source: https://app.segment.com/kickstarter/protocols/violations/ios/track

[NT-1884] Send User ID as String in User Properties

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphSchema.swift
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/models/Comment.swift
KsApi/models/CommentsEnvelope.swift
KsApi/models/graphql/GraphComment.swift
KsApi/models/graphql/GraphCommentTests.swift
KsApi/models/graphql/GraphCommentsEnvelope.swift
KsApi/models/graphql/GraphCommentsEnvelopeTests.swift
KsApi/models/graphql/adapters/Comment+GraphComment.swift
KsApi/models/graphql/adapters/Comment+GraphCommentTests.swift
KsApi/models/graphql/adapters/CommentsEnvelope+GraphCommentsEnvelope.swift
KsApi/models/graphql/adapters/CommentsEnvelope+GraphCommentsEnvelopeTests.swift
KsApi/models/templates/graphql/GraphCommentTemplates.swift
KsApi/models/templates/graphql/GraphCommentsEnvelopeTemplates.swift
KsApi/queries/CommentsQueries.swift
KsApi/queries/CommentsQueriesTests.swift
Library/ViewModels/CommentsViewModel.swift

Adds new types for fetching comments from GraphQL along with code that adapts these types for presentation in the app.
**Note:** We intend to migrate to Apollo in the near future to get away from the complexity of adding new types like this.
We're bringing threaded comments to the app and going forward all of our networking will be done via GraphQL instead of our legacy v1 REST API.
- Added new `CommentsEnvelope` and `Comment` types along with their corresponding GraphQL types for deserialization and adapter code to transform between these types.
- Added tests.
- Added entry points in our `ServiceType` for executing this query.

[NT-1891] Add GraphQL Root Comments Types and Query

---

Kickstarter-iOS/Alpha.entitlements
Kickstarter-iOS/Beta.entitlements
Kickstarter-iOS/Debug.entitlements
Kickstarter-iOS/Release.entitlements
Kickstarter.xcodeproj/project.pbxproj
Library/Navigation.swift
Library/NavigationTests.swift

Adds new domains that we will use for universal links in emails.
**Note:** Blocked until the domains are correctly configured.
We're using these new domains when sending emails from Braze.
Added the 3 new domains to our entitlements and `Navigation.swift` and updated tests.
Once these domains have been configured with the `apple-app-site-association` file then we should be able to tap links in emails that have any of the following domains.

[NT-1889] Add Domains For Universal Links From Emails

---

Kickstarter-iOS/Views/Storyboards/DeprecatedComments.storyboard

While deprecating our old `Comment` namespace there were some old Storyboard identifiers that were not automatically updated with Xcodes renaming tool. This is leading to an unfortunate crash on launch of the empty state of our comments.
It appears the rename tool will only rename file, class and struct names/references. Storyboard identifiers need to be manually updated.

[NT-1966] Fixing empty state cell Storyboard identifier

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
KsApi/px/PerimeterXClient.swift
KsApi/px/PerimeterXClientTests.swift

Ensures that the notification that triggers the PerimeterX dialogue is always posted on the main thread.
In #1427 we made some changes which triggers the PerimeterX Captcha using a `Notification` rather than reaching out directly to the app's `Window` for display purposes. It's possible that this wasn't implemented quite correctly and may be causing some intermittent crashes due to the response object being passed across threads.
Ensure that the notification is always posted and handled on the main thread.

[NT-1981] Post PX Notification On Main Thread

---

Library/ViewModels/CommentsViewModel.swift
Library/ViewModels/CommentsViewModelTests.swift

Updates the delays for emitting comments in `retrying`, `retrySuccess` and `successful` states during retrying. This will be implemented in a separate PR by @moderateepheezy.
We want to delay these transitions in order to show the visual indicator to users.
Updated the delay values and related tests.

[NT-2007] Update Comment State Delays

---

Library/Paginate.swift
Library/PaginateTests.swift
Library/ViewModels/SearchViewModel.swift
Library/ViewModels/SearchViewModelTests.swift

Updates our pagination function to emit errors in anticipation of needing this for handling paging errors for comments.
**Note:** This just modifies the `paginate` function, we will make use of this in an upcoming PR for comments paging.
We have historically not done any error handling for pagination and we've decided to bring this improvement to threaded comments.
Modified `paginate` to return an additional `Signal` that can emit an `Error` without causing the existing value signal to error.

[NT-2020] Update Paginate Function To Emit Errors

---

Library/ViewModels/CommentComposerViewModel.swift
Library/ViewModels/CommentsViewModel.swift
Library/ViewModels/CommentsViewModelTests.swift

Allows us to retry and post comments in a non-blocking manner (up to a reasonable limit).
We found that if we were attempting to retry multiple comments at once, newer retries wouldn't start until older ones had completed. Also, tapping cells repeatedly while blocked in this way would result in duplicate comments being created due to post being called multiple times once the thread was unblocked.
- Changed to a `.concurrent` `flatMap` strategy allowing us to specify an amount of concurrent operations to run on the queue. 
- I've set this to `3` which seemed like a reasonable amount to me but we could consider a higher number if necessary.
- Also added some duplication filtering to prevent against retrying the same comment while its request is already in flight. …

[NT-2033] Allow Concurrent Retrying/Posting Of Comments

---

Library/AppEnvironment.swift
Library/AppEnvironmentTests.swift
Library/KeyValueStoreType.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift

We noticed that when opening the app when the user is logged in, the app does not identify the user. This is due to the app identifying the user while the segment feature is disabled. We store the identify data even if the identify calls fail due to the feature flag disabling the integration. When the feature flag is then enabled, the app does not identify users because it had values stored in user defaults when in reality it has never identified the user. 
After syncing with Paulo, we've decided to allow multiple identify calls if we can be sure that the user is identified when the app opens. 
The stored analytics identify data is removed in favor of comparing old and new user values. This will force the app to identify on app open since the old user value is nil and the new user value …

[NT-2046] Allow multiple identify calls for logged in users

---

Kickstarter-iOS/Views/Cells/CommentCell.swift
Kickstarter-iOS/Views/Controllers/CommentsViewController.swift
Library/ViewModels/CommentCellViewModel.swift
Library/ViewModels/CommentCellViewModelTests.swift
Library/ViewModels/CommentsViewModel.swift
Library/ViewModels/CommentsViewModelTests.swift

Fix a bug where tapping the comment cell goes to a comment thread.
Only the View replies and Reply buttons should allow a user to navigate to a thread – not tapping anywhere on the comment cell

[NT-2070] UX – Comment cell shouldn't be tappable

---

KsApi/mutations/PostCommentMutationTests.swift
KsApi/mutations/inputs/PostCommentInputTests.swift

Add test for `PostCommentMutation` when replying a comment.
Some background context on why the change is needed.

[NT-1936] GraphQL - Post a reply

---

Library/ViewModels/CommentCellViewModel.swift
Library/ViewModels/CommentCellViewModelTests.swift

Reply button not showing on comments the user is the creator or a collaborator of the project.
* Creators and Collaborators should be able to reply to comments on their projects even if they are not backing. Currently that's not happening as the reply button is hidden for creators and collaborators until they back.
| --- | --- |
| <img width="560" src="https://user-images.githubusercontent.com/4386218/123863346-65343300-d921-11eb-9307-41128bc39002.png"> | <img width="560" src="https://user-images.githubusercontent.com/4386218/123863493-93b20e00-d921-11eb-9ae9-2c48f21434ce.png"> |
1. Log in with paulomcg@icloud.com / KSR2021
2.  Go to the dashboard tab
3. View THE project
4. Go to comments
5. Reply button should show because …

[NT-2034] UI – Reply button not showing for creators/collaborators

---

Kickstarter-iOS/Views/Controllers/CommentsViewControllerTests.swift
Library/Styles/CommentCellStyles.swift

This PR introduces a decoration around links in a comment, and also enables links to be tappable. 
Currently, links in a comment are not tappable and they appear like regular text. We want a new UX where links in comments are decorated and users can tap the link and be redirected to a web browser.
Added the following modifiers to `commentBodyTextViewStyle`
```
|> \.isEditable .~ false
|> \.isSelectable .~ true
|> \.isUserInteractionEnabled .~ true
|> \.dataDetectorTypes .~ .link
```
Test with https://staging.kickstarter.com/projects/re-uprefills/help-us-build-a-community-low-waste-refill-shop-in-oakland

[NT-2042] UI – Handle URLs in comments

---

KsApi/extensions/ApolloClient+RAC.swift
KsApi/extensions/ApolloClient+Singleton.swift
KsApi/models/graphql/adapters/Comment+GraphComment.swift

Fixes two regressions introduced in #1538:
- Pull-to-refresh was clearing posted comments.
- Comments weren't showing the correct author badge.
- The Apollo client uses in-memory caching by default, when we pulled to refresh it was not making a new request to the back-end to fetch the first page again but instead reading from cache.
- In our initial implementation at the point of deserialization we were decomposing the author ID, this needed to also happen for the new `CommentFragment`.
- Disabled all caching on Apollo requests for now until we decide how we want to use this.
- Added decomposition for the author ID.

[NT-2094] Fix Root Comments Regressions

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphAPI.swift
KsApi/Service.swift
KsApi/fragments/BackingFragment.graphql
KsApi/fragments/CategoryFragment.graphql
KsApi/fragments/CommentFragment.graphql
KsApi/fragments/CountryFragment.graphql
KsApi/fragments/CreditCardFragment.graphql
KsApi/fragments/LocationFragment.graphql
KsApi/fragments/MoneyFragment.graphql
KsApi/fragments/ProjectFragment.graphql
KsApi/fragments/RewardFragment.graphql
KsApi/fragments/UserFragment.graphql
KsApi/models/CommentsEnvelope.swift
KsApi/models/graphql/adapters/Comment+GraphComment.swift
KsApi/models/graphql/adapters/CommentsEnvelope+GraphCommentsEnvelope.swift
KsApi/models/graphql/adapters/CommentsEnvelope+GraphCommentsEnvelopeTests.swift
KsApi/queries/FetchBackingQuery.graphql

Adds the fragments that we will need to fetch a `Backing` for the Manage Pledge View.
**Note:** Ignore changes to `GraphAPI.swift` as this is generated by Apollo.
This is part of our migration to Apollo, we will add the implementation in a subsequent PR.
- Took the query created by the `managePledgeViewProjectBackingQuery(withBackingId:)` function and broke it up into several fragments.
- Ran the code generation on these fragments to update `GraphAPI`.
- Updated the code generation script to use `GraphAPI` as a namespace to disambiguate some type names.

[NT-2071] Add Backing Query Fragments

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphAPI.swift
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/fragments/ProjectFragment.graphql
KsApi/fragments/RewardFragment.graphql
KsApi/models/ProjectAndBackingEnvelope.swift
KsApi/models/graphql/adapters/Backing+BackingFragment.swift
KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
KsApi/models/graphql/adapters/Project+ProjectFragment.swift
KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
KsApi/models/graphql/adapters/Project.Category+CategoryFragment.swift
KsApi/models/graphql/adapters/Project.Category+CategoryFragmentTests.swift
KsApi/models/graphql/adapters/Project.Country+CountryFragment.swift
KsApi/models/graphql/adapters/Project.Country+CountryFragmentTests.swift
KsApi/models/graphql/adapters/Reward+RewardFragment.swift
KsApi/models/graphql/adapters/Reward+RewardFragmentTests.swift
KsApi/models/graphql/adapters/User+UserFragment.swift
KsApi/models/graphql/adapters/User+UserFragmentTests.swift
Library/ViewModels/ManagePledgeViewModel.swift

Continues the migration of fetching the data for the Manage Pledge View from our legacy GraphQL queries to Apollo using fragments.
We are using Apollo for GraphQL moving forward.
Added the remaining required fragments, adapters and tests.

[NT-2072] Update Manage Pledge View To Use Apollo Query

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphAPI.swift
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/fragments/RewardFragment.graphql
KsApi/fragments/ShippingRuleFragment.graphql
KsApi/models/graphql/adapters/Project+FetchAddOnsQueryData.swift
KsApi/models/graphql/adapters/Project+FetchAddOnsQueryDataTests.swift
KsApi/models/graphql/adapters/Reward+RewardFragment.swift
KsApi/models/graphql/adapters/Reward+RewardFragmentTests.swift
KsApi/models/graphql/adapters/ShippingRule+ShippingRuleFragment.swift
KsApi/models/graphql/adapters/ShippingRule+ShippingRuleFragmentTests.swift
KsApi/queries/FetchAddOnsQuery.graphql
Library/ViewModels/RewardAddOnSelectionViewModel.swift

Updates the data being fetched in `RewardAddOnSelectionViewModel` to use Apollo.
Continuation of our migration to Apollo.
- Added the `FetchAddOns` query.
- Adapted the data returned to `Project`.

[NT-2073] Migrate Reward Add-On Selection Query To Apollo

---

KsApi/GraphAPI.swift
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/queries/FetchAddOnsQuery.graphql
Library/ViewModels/RewardAddOnSelectionViewModel.swift

Excludes expanded shipping rules for digital-only rewards.
When fetching add-ons, if we pass in a `nil` location ID, all possible locations are returned. This returns all possible shipping locations in the known universe and can cause the response to time out.
Added a [directive](https://graphql.org/learn/queries/#directives) to our query to make this property conditional.

[NT-2073] Don't Fetch Expanded Shipping Rules For Digital-Only Rewards

---

.circleci/config.yml
bin/apollo-schema-download.sh

Adds a step to our builds on CircleCI so that the latest GraphQL schema on staging is downloaded.
Downloading the schema ahead of the build will ensure that if there are breaking changes, the app will fail to compile and we'll be afforded the opportunity to catch those sorts of issues earlier.
Added a script that installs the Apollo CLI client and then runs it to download the schema from staging.

[NT-2074] Download GraphQL Schema During CI Builds

---

.fastlane/Fastfile

Adds a step to our Fastlane configuration to upload dSYMs to Firebase after delivering builds to the App Store.
A regression was introduced in #1432 which caused dSYMs to stop being automatically uploaded to Firebase Crashlytics during our CI builds. Instead of splitting this part out into its own lane, we prevented the entire lane from executing which was not the correct approach.
By not having these dSYMs on Firebase we are unable to see resymbolicated crashes.
Moved the `upload_symbols_to_crashlytics` command to run just after the `deliver` command. This ensures that any builds uploaded to the App Store also have their dSYMs uploaded to Firebase Crashlytics.

[NT-2137] Upload dSYMs During App Store Delivery

---

KsApi/GraphAPI.swift
KsApi/fragments/ProjectFragment.graphql
KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
KsApi/models/graphql/adapters/Project+FetchAddOnsQueryDataTests.swift
KsApi/models/graphql/adapters/Project+ProjectFragment.swift
KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift

`MemberData` is currently not being fetched from GraphQL and we need the various properties of this object for the `ProjectFragment`. It doesn't seem like our GraphQL `Project` object currently supports any of the properties other than `collaboratorPermissions` so that is what we will add in this PR.
Part of our native comment threading feature involves the use of permissions for determining whether a collaborator can comment or not. Moreover, with the migration toward Apollos GraphQL client we are updating our fragments and ensuring they are both reusable and bug free when used elsewhere.
Added the `collaboratorPermissions` field to our `ProjectFragment` and extended our adapter to take a given `CollaboratorPermission` from GraphQL and turn it into a `Project.MemberData.Permission` type. …

[NT-2114] Adding collaboratorPermissions to ProjectFragment

---

Library/Tracking/Segment.swift

Enables Segment by default.
We discovered that push notifications that were received while the app was backgrounded would open and follow their deep-links. However, when the app was freshly launched from a push notification, those deep-links would just do nothing.
It turns out that this is because we call run this line in our `application(_:didFinishLaunchingWithOptions:)`:
```swift
SEGAppboyIntegrationFactory.instance()?.saveLaunchOptions(launchOptions)
```
This causes Segment to save the `launchOptions` dictionary for processing later on by Braze.
However, during our configuration of Segment and Braze, we also immediately _disable_ Segment. We do this so that it can later be enabled by our feature flag configuration and immediately disabling it also ensures that we don't track any app …

[NT-2040] Enable Segment By Default

---

Kickstarter-iOS/Library/WebViewController.swift

While debugging an issue regarding the accountability webview not rendering, @DeMarko discovered that URL navigation was not working as expected within our webviews. In particular, iOS does not respond to a tapped URL when the target frame is blank. This PR addresses that issue by implementing a `WKUIDelegate` method on the `WebViewController` class.
An unresponsive UI is a poor user experience and so is not throwing an explicit error when something is not working. In this case, we are tackling the root cause of the unresponsiveness by enabling a webview to open another link within itself.
Implement the `WKUIDelegate` method with the following signature: `webView(webView, createWebViewWith, for, windowFeatures)`. We are specifically checking if the `targetFrame` is nil (blank on web) and …

Handling target = blank for webview URL navigation in WKUIDelegate.

---

KsApi/models/Backing.swift
KsApi/models/graphql/adapters/Backing+BackingFragment.swift
KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
KsApi/models/graphql/adapters/Backing+GraphBacking.swift
KsApi/models/lenses/BackingLenses.swift

When updating a backing through our `Manage Pledge` flow, we rely on a GraphQL mutation to submit the update. In the situation where a payment method errors out, we flag the user within the `Activity` tab to fix their pledge. There are a number of checks that occur on the backend to ensure this process goes smoothly; one, in particular, involves verifying the amounts of the pledges are the same. We accidentally introduced a bug in a [previous PR](https://github.com/kickstarter/ios-oss/pull/1556) that casts the `shippingAmount` as an `Int` instead of a `Double` or `Float`, like the response returns. In this PR we are updating the type casting to more reflect a money type and throw in some tests for good measure.
This bug was directly affecting our payments pipeline, which is a critical …

[NT-2165] Fix for incorrect type casting on shippingAmount within Backing+BackingFragment

---

bin/apollo-schema-download.sh

Quick PR correcting missing headers from our schema download step.
Somehow, the changeover from production to staging (data re-seed) on Aug 5/6 2021 caused the script to fail to download the schema on CI.
This fix seems to correct the issue.

Add Apollo Schema Download CI Step Headers

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift

We've been encountering some issues with the `identify` method of the Segment client. In particular, the events don't seem to be propagating to Segment, resulting in some gaps in our events. It appears that in [this PR](https://github.com/kickstarter/ios-oss/pull/1515) we were patching an issue with multiple identify calls by determining if the user has changed in between calls but that resulted in a newer bug. What seems to be occurring, now, is the `identify` method being called successfully and subsequently returning early, resulting in the event not occurring at all. It's tough to determine what specifically is occurring but debugging suggests the SDK is doing some work behind the scenes to cancel an event from firing if it's called in succession twice (and returning early the second …

[NT-2183] Enabling identify calls from our analytics client.

---

Cartfile
Cartfile.resolved

iOS 15 is introducing new breaking changes for Braze and push notifications. Braze has emailed us that we should upgrade to their latest SDK to make sure we are able to support the new iOS 15 features.
Updated `Cartfile` and `Cartfile.resolved`.

[NT-2186] Upgrading dependency version for Braze.

---

KsApi/extensions/ApolloClient+RAC.swift
KsApi/models/ErrorEnvelope.swift

In the case of an outright request failure, our GraphQL client is sending an error prefixed with the string "JSONDecoder decoding error" which is useful for developers but not for a user of the application. This PR includes an update to remove that prefix and add a print statement above it in our `fetch` and `perform` method so we still keep the debugging utility of knowing what the error is specifically throwing.
GraphQL differs from a standard REST API in a number of ways including the way errors are thrown. A standard REST API will throw an http status code that suggests what the issue is, whereas GraphQL will return a `200` but include an error message, within its response. We are handling these legitimate errors in our `success` block but our `failure` block (which runs when there …

[NT-2160] Making error response human readable in the case of request failure.

---

KsApi/extensions/ApolloClient+RAC.swift

We're switching the type of `ErrorEnvelope` being send in the `failure` block of our ApolloClients `perform` and `fetch` method. The reason we're switching these is so the error message the user is seeing is human readable.
The new error type defaults to a string of "Something went wrong." when we catch an obscure error. This is far more useful to the user than what our API or system may occasionally send back.

[NT-2160] Switching error envelope type in failure block of ApolloClient+RAC

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/Views/Controllers/SettingsNotificationsViewController.swift
Kickstarter-iOS/Views/Controllers/SettingsViewController.swift
Library/AppEnvironment.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/SettingsNotificationsViewModel.swift

A previously introduced bug resulted in Segments identify method being called too many times. This was a result of our use of a `willSet` that fired each time `loggedInUser` was set. The fix wasn't as simple as checking if the older user == new user because of what appears to be a specific limitation of the SDK. We've re-factored where we call identify into specific locations in the application within this PR.
The identify call is one of the core methods in the Segment SDK and we want to ensure we are not spamming the method and introducing noise into our analytics. By specifically calling identify in choice locations we are ensuring a more refined set of results being sent to Segment.
- Resetting the segmentClient in `AppEnvironment.logout`
- Calling `identify` in when the current user …

[NT-2183] Segment identify call fix

---

Kickstarter-iOS/DataSources/CommentRepliesDataSource.swift
Kickstarter-iOS/DataSources/CommentRepliesDataSourceTests.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
Kickstarter-iOS/Views/Controllers/CommentRepliesViewController.swift
Kickstarter-iOS/Views/Controllers/CommentRepliesViewControllerTests.swift
Kickstarter-iOS/Views/Controllers/CommentsViewController.swift
KsApi/models/PushEnvelope.swift
KsApi/models/PushEnvelopeTests.swift
KsApi/models/lenses/PushEnvelopeLenses.swift
Library/Navigation.swift
Library/NavigationTests.swift
Library/ViewModels/CommentRepliesViewModel.swift
Library/ViewModels/CommentRepliesViewModelTests.swift

One of the final pieces to our deep link integration with comment threading is the ability to take a user to a specific reply. We're using the replyId as a query parameter and scrolling the table view to a particular index, if the replyId matches.
This is part of our larger goal to drive engagement with deeplinks. This should be something we incorporate into all new feature releases. A good gameplan would probably be to release the feature, add analytics support and then finish it off with a supporting deeplink.
Most of the work involving deeplinks is done in two files: `AppDelegateViewModel.swift` and `Navigation.swift`. It's in these two files that we parse the route, determine the relevant query parameters and subsequently navigate the user to the correct point in the stack.
I used the …

[NTV-13] Supporting deep links to a specific reply.

---

Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

Adding a `CTA Clicked` analytics event for whenever the "I Understand" button is tapped in the `RiskMessagingViewController`.
It's important for us to monitor the effectiveness of our experiment. Given the proximity to the point of checkout, the analytics will give us an understanding if the risk messaging is leading to revenue drops or anything else unexpected.
- Adding a new event to `KSRAnalytics`
- Updating the `PledgeViewModel` to account for the `RiskMessagingViewController`s `confirmButton` being tapped.
- Updating some older events to respond specifically to the `submitButtonTappedSignal` and `applePayButtonTappedSignal`.

[NTV-156] Adding Segment analytics events for Risk Messaging confirm button

---

KsApi/GraphAPI.swift
KsApi/fragments/RewardFragment.graphql
KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
KsApi/models/graphql/adapters/Project+FetchProjectQueryDataTests.swift
KsApi/models/graphql/adapters/Reward+RewardFragment.swift
KsApi/models/graphql/adapters/Reward+RewardFragmentTests.swift
KsApi/mutations/templates/query/FetchAddOnsQueryTemplate.swift
KsApi/mutations/templates/query/FetchProjectQueryTemplate.swift

While testing, @paulomcg found that we are missing the add-ons selection step in the checkout process. This is because the `Reward` object was always passing in `false` to the `hasAddons` property of `Reward` model.
It wasn't completely within the scope of `Project` model, but due to relationships created previously through `v1/projects` endpoint, this flag is now important to both show the **Addons** pill and guide the user through the **Addons** step if the reward has addons.
Added this property to the `RewardFragment` and adjusted the `Rewards+RewardsFragment` to check if there are nodes and `hasAddons` will be `true` if its not empty.
```
allowedAddons {
__typename
nodes {
__typename
id
}
}
```
| --- | --- |
| <img …

[Unticketed] Put Back Add Ons Selection To Checkout

---

Library/ViewModels/PledgeViewModel.swift

This is a quick fix to correct an issue with our `pledge_confirm` event. We were previously sending a value of `credit_card` for all payment types whether is was `Pay With Apple` or not and this PR will correct that.
Our insights team needs accurate data in order to correctly interpret and take action on our analytics data.
Combining an additional signal to the `pledgeSubmitEventsSignal` in the `PledgeViewModel`.

[NTV-156] Fixing pledge_confirm events apple_pay/credit_card property values

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/Views/Controllers/CommentRepliesViewController.swift
Kickstarter-iOS/Views/Controllers/CommentRepliesViewControllerTests.swift
Kickstarter-iOS/Views/Controllers/CommentsViewController.swift
Library/ViewModels/CommentRepliesViewModel.swift
Library/ViewModels/CommentRepliesViewModelTests.swift
Library/ViewModels/CommentsViewModel.swift
Library/ViewModels/CommentsViewModelTests.swift

We were made aware of a bug that was introduced to our comment threading feature which is being corrected in this PR. In particular, we were sending the wrong relayId when posting replies. Until the web team informed us recently, we were sending `Project-{id}` for all new replies even if they were Updates. An Update should be sending a relayId of `Freeform-Post-{id}`. Now we are checking if this reply is occurring in a Update or not before dynamically sending the commentableId.
Because we are setting the reply comments commentable type to Project, it's triggering errors everyday in our "new reply notiification" emails which only support project comment replies at the moment.
Passing the `Update` when we set up the `CommentRepliesViewController` and `CommentRepliesViewModel`. We then …

[NTV-180] Sending commentableId based on value of updateProperty in CommentRepliesViewModel

---

KsApi/GraphAPI.swift
KsApi/fragments/ProjectFragment.graphql
KsApi/models/ExtendedProjectProperties.swift
KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
KsApi/models/graphql/adapters/Project+FetchProjectQueryData.swift
KsApi/models/graphql/adapters/Project+FetchProjectQueryDataTests.swift
KsApi/models/graphql/adapters/Project+ProjectFragment.swift
KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
KsApi/mutations/templates/query/FetchAddOnsQueryTemplate.swift
KsApi/mutations/templates/query/FetchProjectQueryTemplate.swift

Last minute bug fix for release `4.15.0`.
With 3/4 % of pledges coming from this reward tier, its' important we support it in every release.
Pretty straightforward, thanks @Arkariang for the tip of making the project minimum pledge the minimum of the no-reward pledge. 
- Added `minPledge` to `ProjectFragment` under `extendedProjectProperties` because it wasn't in the v1 model.
Also updated the `Project+FetchProjectQueryData.swift` file to include the `minimum` and `convertedMinimum` fields of the no reward reward.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/4282741/135334660-f157dc11-5f36-4b7b-b244-e50fcc938347.png" width="300"> | <img src="https://user-images.githubusercontent.com/4282741/135333604-09d …

[Unticketed] No Rewards Reward Added To Rewards Selection Screen

---

KsApi/GraphAPI.swift
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/fragments/ProjectFragment.graphql
KsApi/models/graphql/adapters/Backing+BackingFragment.swift
KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
KsApi/models/graphql/adapters/Project+FetchProjectQueryData.swift
KsApi/models/graphql/adapters/Project+FetchProjectQueryDataTests.swift
KsApi/models/graphql/adapters/Project+ProjectFragment.swift
KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
KsApi/models/graphql/adapters/Project.Country+CountryFragment.swift
KsApi/models/graphql/adapters/Project.Country+CountryFragmentTests.swift
KsApi/models/lenses/CountryLenses.swift
KsApi/mutations/templates/query/FetchAddOnsQueryTemplate.swift
KsApi/mutations/templates/query/FetchProjectQueryTemplate.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/ProjectPamphletViewModel.swift

Earlier last week it was brought to our attention that projects created in countries that set their project currency to something different than their country's currency.
Obviously this is a big issue and effects pledging volume as evidenced in this large [project](https://www.kickstarter.com/projects/shortcutlabs/flic-twist-the-wireless-dial-for-your-smart-home?ref=bgtrbl&token=e1d08d69).
https://kickstarter.atlassian.net/browse/NTV-284 contains the exact problem and this [document](https://kickstarter.atlassian.net/wiki/spaces/~294637594/pages/1840840709/Price+Display+Errors+on+iOS.) investigates the full scope of the issue.
**Part 1**
In the first part of this fix, noticed that we were simply getting the project's country code, looking it up in our `Project.Country` enum's `all` and …

[NTV-284] - Currency Display Differences Between Android and iOS

---

Kickstarter-iOS/Views/ProjectNavigationSelectorView.swift

Found a minor bug wrt newer iPhones that have a "safe area" which should be deducted from the layout margins when relcalculating the leading and width constraint for the `selectedBorderBottomView`
Before 🦋 
https://user-images.githubusercontent.com/4282741/143498586-53e5f854-9f2b-42d7-9480-5dc1f7f39260.mp4
After 🐛 
https://user-images.githubusercontent.com/4282741/143498292-6f63f4e2-184f-4cd4-b6c0-48bf6a67a3f5.mp4

[Unticketed] Fix Navigation Selector On Newer iPhones with Safe Area

---

Kickstarter-iOS/Views/Cells/HTML Parser/TextViewElementCell.swift
Library/ViewModels/HTML Parser/TextViewElementCellViewModel.swift
Library/ViewModels/HTML Parser/TextViewElementCellViewModelTests.swift

Up to this point, the text elements that were rendered as links we not functional.
Now they are and externally link to a Safari browser.
Links need to work for them to be useful to the user.
Turns out setting a prelude style font (ex. `.ksr_callout`) to the TextView's font property via the style interferes with the textviews' rendering of the text on the first pass. Removing all font related styles from the `TextViewStyle` fixed this issue.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/4282741/150885858-afa16adc-a102-45ae-a93f-7d9cee3a74b1.gif" width="300"> | <img src="https://user-images.githubusercontent.com/4282741/150885591-92beae94-7887-461b-8f1a-e5be52e2c329.gif" width="300"> |

[NTV-358] Added External Links To Text Elements

---

Kickstarter-iOS/DataSources/ProjectPageViewControllerDataSource.swift
Kickstarter-iOS/DataSources/ProjectPageViewControllerDataSourceTests.swift
Kickstarter-iOS/Views/Cells/HTML Parser/ExternalSourceViewElementCell.swift
Kickstarter-iOS/Views/Controllers/ProjectPageViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectPageViewControllerTests.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/lib/HTML Parser/Element+Helpers.swift
KsApi/lib/HTML Parser/HTMLParserTests.swift
KsApi/lib/HTML Parser/HTMLRawText.swift
KsApi/lib/HTML Parser/Templates/HTMLParserTemplates.swift
KsApi/lib/HTML Parser/View Elements/ExternalSourceViewElement.swift
KsApi/models/graphql/adapters/Project+ProjectFragment.swift
KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
Library/ViewModels/HTML Parser/ExternalSourceViewElementCellViewModel.swift
Library/ViewModels/HTML Parser/ExternalSourceViewElementCellViewModelTests.swift

Final piece of content for the Campaign tab before cleaning up the overview tab. [Story](https://kickstarter.atlassian.net/browse/NTV-188).
Add parity to Android Campaign tab.
`WKWebView` handles the rendering of external source `iframe` content. The parser will also find `src` embedded in iframe class's `src` attribute. Also resetting the content height and web view content to zero and empty respectively when `didEndDisplay`  is called.
Before 🐛
https://user-images.githubusercontent.com/4282741/156661077-aa12a08c-7b20-40f4-892e-7c119defbb66.mp4
After 🦋
https://user-images.githubusercontent.com/4282741/156663668-9c85a64b-0288-4d8b-b323-4d4a848492e9.mp4
- There are rotation issues with external elements.
- Thumbnail previews missing for kickstarter …

[NTV-343] External Source Cell

---

Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
Kickstarter-iOS/Views/Cells/HTML Parser/ExternalSourceViewElementCell.swift
Kickstarter-iOS/Views/Cells/HTML Parser/VideoViewElementCell.swift
Kickstarter-iOS/Views/Controllers/ProjectPageViewController.swift
Kickstarter-iOS/Views/Controllers/VideoViewController.swift
Library/Notifications.swift
Library/ViewModels/HTML Parser/ExternalSourceViewElementCellViewModel.swift
Library/ViewModels/HTML Parser/ExternalSourceViewElementCellViewModelTests.swift
Library/ViewModels/ProjectPageViewModel.swift
Library/ViewModels/ProjectPageViewModelTests.swift

A few minor issues were found in testing the external sources. Namely:
- media playback should pause when scrolled away or the app is backgrounded.
- sometimes on iPad/iPhone, playing an external source then rotating the device and exiting full screen causes the player to float above a part of the page. Persists even if scrolled back to its' original cell. Need to ensure rotation works for inline/fullscreen webview that is playing content and resumes its correct place in the table view.
Just some odds and ends need fixing.
Right now we're using a new notification called `ksr_applicationDidEnterBackground` that will alert the `VideoViewController` and the `ProjectPageViewController` if the app enters a background state. Added functionality to pause playing `AVPlayer` content, but that …

[NTV-424] Fix External Source Bugs

---

Kickstarter-iOS/DataSources/ProjectPageViewControllerDataSource.swift
Kickstarter-iOS/DataSources/ProjectPageViewControllerDataSourceTests.swift
Kickstarter-iOS/Views/Cells/HTML Parser/VideoViewElementCell.swift
Kickstarter-iOS/Views/Controllers/ProjectPageViewController.swift
Library/Styles/HTMLViewElementStyles.swift
Library/ViewModels/HTML Parser/VideoViewElementCellViewModel.swift
Library/ViewModels/HTML Parser/VideoViewElementCellViewModelTests.swift
Library/ViewModels/ProjectPageViewModel.swift

To gain parity with Android and Web on the player thumbnail, we need to add a thumbnail image to each native video player.
Use an observer on the `AVPlayer` to listen for the `timeControlStatus` property which changes when any change to the player occurs. Only needs to happen once and the observer is removed along with the thumbnail image.
Loads images from the network asynchronously, just using the same technique as image urls from `ImageViewElement`.
If the thumbnail gets loaded in time, the cell get has a thumbnail, if not it will be there when the cell reloads (only shows if seek position is 0)
Before 🐛
https://user-images.githubusercontent.com/4282741/158492040-fca08901-d158-4fc9-98ed-05f1867de22f.mp4
After 🦋 …

[NTV-428] Add Thumbnail Images to Video Player Component

---

Kickstarter-iOS/Views/Cells/HTML Parser/ImageViewElementCell.swift

Quick fix to the images ticket to resolve a gap in image scaling.
After a little investigation, realized the `contentView` `margins` account for `Style(6)` in total, was previously using `Style(3)` as max width of image.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/4282741/158881106-ea832ed3-85bb-431a-83e4-63665caa3425.png" width="300"> | <img src="https://user-images.githubusercontent.com/4282741/158880656-980685bb-935d-4784-a030-46ad872fd792.png" width="300"> |

[NTV-341] Image Scale Gap Fix

---

Kickstarter-iOS/Views/Cells/ProjectPamphletMainCell.swift
Kickstarter-iOS/Views/Controllers/ProjectPageViewController.swift
Kickstarter-iOS/Views/Controllers/VideoViewController.swift

A bug was found when the overview tabs' video was playing and the tab was switched.
Don't want a constantly playing video when the user is focused on another part of the page.
Normally our `VideoViewControllerDelegate` works outward from the `VideoViewController` within the `ProjectPamphletMainCell` to the view controller and then the navigation bar, passing along the status of the video playback.
So we can't communicate down to the cell using the same delegate. We need to do that because `ProjectPageViewController` has the signal that is updated when the tabs are changed.
`VideoViewControllerPlaybackDelegate` calls down to the cell's video play to pause if the tabs are switched away from the overview tab.
Before 🐛
https://user-images.githubusercontent.com/4282741/159797822-fc06678d-3888-4 …

[NTV-453] Overview Tab Video Pause When Tabs Are Switched

---

Kickstarter-iOS/DataSources/ProjectPageViewControllerDataSource.swift
Kickstarter-iOS/DataSources/ProjectPageViewControllerDataSourceTests.swift
Kickstarter-iOS/Views/Controllers/ProjectPageViewController.swift
Library/ViewModels/ProjectPageViewModel.swift
Library/ViewModels/ProjectPageViewModelTests.swift

[NTV-452] Ensure Images With No Caption Action A Clickable Link

---

Kickstarter-iOS/Views/Controllers/ProjectPageViewController.swift
Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Library/Styles/BaseStyles.swift

Due to a recent change building against iOS 15 instead of iOS 14 (using Xcode 13 now) We noticed this issue:
It appears according to this [post](https://developer.apple.com/forums/thread/682420), iOS 15 changes the state of the navigation bar to have `standardAppearance` and `barTintColor` is no longer applied. By creating `UINavigationBarAppearance` object, we can set the `UINavigationBar`'s `standardAppearance` and `scrollEdgeAppearance` to be the same value, which sets the `backgroundColor` of the navigation bar to `white`.
Before 🐛 
https://user-images.githubusercontent.com/4282741/164311439-c353aa9d-6772-4de2-8db2-f60e16ad1bf2.MP4
After 🦋
https://user-images.githubusercontent.com/4282741/164326693-cbb58572-d6a1-4c7f-a8d9-498a2a23ed2b.MP4

[NTV-532] Navigation Bar Issue Related To iOS 15

---

Kickstarter-iOS/Views/Controllers/ProjectPageViewController.swift
Kickstarter-iOS/Views/Controllers/ProjectPageViewControllerTests.swift
Kickstarter-iOS/Views/OverlayView.swift

So on the newest beta build (16505550) we found that zooming an image and letting it return to its normal size caused the scroll view to shift in place and had the effect of hiding the image and it was zoomed in.
Simply turning off scrolling when the gesture begins and turning it back on when the gesture ends caused this issue. So not doing that (2 lines of code) prevented this issue from re-curring. It was never necessary to do this in the first place because the overlay view prevent any interaction with the scroll view will the image was being zoomed in/out.
Also commented out two flakey tests that consistently failed to pass CI and caused hours of wait time.
Before 🐛 
https://user-images.githubusercontent.com/4282741/165131764-96754ba9-f1cf-4541-aaa4-05ccc7f0e148.MP4
After 🦋 …

[NTV-533] Image Zoom Failing Fix

---

Kickstarter-iOS/Views/Cells/HTML Parser/ExternalSourceViewElementCell.swift

We found in the latest beta (16505550) a host of issues related to links to being activated from the player. Turned out to be fairly simple fix based on this [post](https://developer.apple.com/forums/thread/117073):
> Embedded video works as expected
> 
> Soundcloud - link to “Play on Soundcloud” doesn’t work but listen in browser does (but only if you click it). Is there any way of changing this treatment or is it set by soundcloud? Is there anything we can do to make the link to Soundcloud work (or remove it)?
> 
> Bandcamp embed plays, but none of the links work (buy, share, or link to title name)
> 
> YouTube plays, but automatically goes to a full screen without selecting that option. Links out to YouTube also don’t work.
> 
> Vimeo plays, but also immediately goes to a full screen …

[NTV-343] Fix External Links Not Working Inside Player

---

Kickstarter-iOS/Views/Controllers/RewardPledgeNavigationController.swift

Simliar to the fix [here](https://github.com/kickstarter/ios-oss/pull/1684), one spot that was missed was `RewardPledgeNavigationController`. So adding that in here. Did a global search for `barTintColor` and no other `UINavigationController`'s seem to affected, so confirming this is the fix for all navigation bars app-wide.
@hadia Thanks for finding this!
Broken navigation bars are unsightly and give the impression of a broken app. Also pretty sure this would fail Apple's review process.
These issues only seem apparent in the actual device, not the simulator, so that is why tests didn't fail.
Similar fix the linked PR above.
Before 🐛 
https://user-images.githubusercontent.com/4282741/167486840-dca412ad-7977-4a5e-9f0e-96c484a32580.mp4
After 🦋 …

[Unticketed] Rewards Navigation Controller Broken Navigation Bar

---

Library/ViewModels/ProjectPageViewModel.swift

As detailed in the ticket, if the user was scrolling in the campaign tab and starts the backing flow, logs in before pledging, the app crashes. Need to prevent this as it is a common flow from project to pledging.
The `prefetchImageUrls` signal was called whenever a notification was sent after the user session started.
This prefetch would eventually end up updating the datasource, but because the `userSessionStarted` signal resets the active tab to Overview, that caused a crash in the datasource, because the Campaign tab values were cleared.
The fix was a simple check to see if the existing tab was Campaign before the `prefetchImageUrls` passed its data to the view controller.
Before 🐛 
https://user-images.githubusercontent.com/4282741/169423103-6da85f4b-163c-4fe4-bc2f-66c9902a382f.mp4 …

[NTV-541] Crash Fix After Backing From Campaign Tab

---

Kickstarter.xcodeproj/project.pbxproj

In the previous release `5.3.0` we forgot to update the `main` branch with `5.3.0` before pushing up the `release-5.3.0` branch (where the marketing version was updated).
This is a small pr to correct that inconsistency before running `make sync` which will bring `ios-private`'s `master` branch to be up to date with `ios-oss` `main`.

Update Marketing Version From 5.2.1 to 5.3.0

---

Kickstarter.xcodeproj/project.pbxproj
Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

The new Stripe framework fixes a bug where 4.7 inch screens launched in landscape do not appear unless rotated. Very minor.
We would ideally like to support all orientations for all phones natively
Stripe upgraded their framework.
Before 🐛
https://user-images.githubusercontent.com/4282741/187983754-3e617f2d-5154-4bea-855f-a4538bd8ce65.mp4
After 🦋
https://user-images.githubusercontent.com/4282741/187983737-f9cce534-ba15-4a86-9a2a-0142051f0b67.mp4

[Unticketed] Updated Stripe Framework

---

Cartfile
Cartfile.resolved
Kickstarter.xcodeproj/project.pbxproj
Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

As part of our migration to SPM from Carthage to support M1 builds.
Relevant context [here](https://app.getguru.com/card/TzA8Rpac/-Carthage-to-Swift-Package-Manager-Migration-2022).
Before:
`Cartfile` (.resolved reflects same changes)
```
binary "https://raw.githubusercontent.com/Appboy/appboy-ios-sdk/master/appboy_ios_sdk_full.json" == 4.3.2
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" "7.4.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json" "7.4.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseInAppMessagingBinary.json" "7.4.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json" "7.4.0"
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBin …
```

[NTV-614] Firebase Binaries To SPM

---

Cartfile
Cartfile.resolved
Kickstarter-iOS/AppDelegate.swift
Kickstarter.xcodeproj/project.pbxproj
Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

As part of  our Carthage -> SPM migration we need to migrate AppCenterDistribute
Checkout  this [Guru Card](https://app.getguru.com/card/TzA8Rpac/-Carthage-to-Swift-Package-Manager-Migration-2022) for more details  
- Remove the dependencies from Cartfile and Cartfile.resolved and add them to Package.resolved
- Update usage in `AppDelegate`. As of version [4.4.0](https://github.com/Microsoft/AppCenter-SDK-Apple/releases), the `AppCenter.setCustomProperties` API was removed. 
- Minimum version to 4.0.0
- Resolve any merge conflicts

[WEB-739] Migrates AppCenterDistribute to SPM

---

Cartfile
Cartfile.resolved
Kickstarter.xcodeproj/project.pbxproj
Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

As part of our Carthage -> SPM migration we need to migrate PerimeterX
Checkout  this [Guru Card](https://app.getguru.com/card/TzA8Rpac/-Carthage-to-Swift-Package-Manager-Migration-2022) for more details  
- Remove the dependencies from Cartfile and Cartfile.resolved and add them to KsApi target
- Minimum version to 1.13.9
- Resolve any merge conflicts

[WEB-742] Migrates PerimeterX to SPM

---

Kickstarter.xcodeproj/project.pbxproj

Turns out our last PerimeterX upgrade to SPM caused on device launch crash ([beta build](http://y84x.mjt.lu/lnk/CAAAA1AqzvAAAAAAAAAAAAS4X6oAAAA6pnMAAAAAAAvpOQBjMgyTmWtnPACNQka85QFT_9Tg5gAL-7Q/1/cMJs_VxWN247qu8-d1MBZA/aHR0cHM6Ly9pbnN0YWxsLmFwcGNlbnRlci5tcy9vcmdzL0tpY2tzdGFydGVyTmF0aXZlL2FwcHMvS2lja0JldGEvcmVsZWFzZXMvNDg2P3NvdXJjZSYjeDNEO2VtYWlsJnRpZCYjeDNEOzJOMXU5OGR0S0M#x3D;email&tid=2N1u98dtKC)) because of `@rpath/Library/PerimeterX.framework` was not found. Although the only framework that referenced it with `import PerimeterX` was `KsApi`, the Library framework somehow needed it. Felt it safest to include within the library target as well until a more thorough investigation could be done.

[Unticketed] PerimeterX Beta Build 5.4.0 (16642229) Crash

---

Cartfile
Cartfile.resolved
Carthage-xcfilelist/app-input-files.xcfilelist
Carthage-xcfilelist/app-output-files.xcfilelist
Carthage-xcfilelist/library-input-files.xcfilelist
Carthage-xcfilelist/library-output-files.xcfilelist
Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/AppDelegateViewModel.swift
Kickstarter-iOS/Library/BrazeTypes.swift
Kickstarter-iOS/Library/SharedFunctions.swift
Kickstarter.xcodeproj/project.pbxproj
Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

As part of our Carthage -> SPM migration we need to migrate Appboy-iOS-SDK (AppboyKit) and its dependency SDWebImage
Checkout  this [Guru Card](https://app.getguru.com/card/TzA8Rpac/-Carthage-to-Swift-Package-Manager-Migration-2022) for more details  
- Remove the dependencies from Cartfile and Cartfile.resolved and add them to main and Library targets
- Minimum version to 4.3.2
```
AppDelegate.swift
import Appboy_iOS_SDK -> import AppboyKit
AppDelegateViewModel.swift
import Appboy_iOS_SDK -> import AppboyKit
BrazeTypes.swift
import Appboy_iOS_SDK -> import AppboyKit
SharedFunctions.swift
import Appboy_iOS_SDK -> import AppboyKit
```
**Important to Note**
While testing, neither pns or in-app pns came through after this library was changed over. To rule out any certifcate signing issues …

[WEB-741] Appboy SDK to Braze SDK in SPM

---

Kickstarter-iOS/Features/LoginTout/Controller/LoginToutViewController.swift
KsApi/models/User.swift
KsApi/models/UserTests.swift

Noticed a small regression in [web-666](https://github.com/kickstarter/ios-oss/pull/1755/files#diff-5dc87b11382b334c49b55e40127334addd07f9e644760491481746b017a87369R14) where `User.needsPassword` was documented as being non-optional in the v1 swagger [docs](https://staging.kickstarter.com/admin/api-docs/index.html) but in other v1 calls that return a user object the field is missing entirely.
Example:
`/v1/discover?client_id=1HP13YYFC4N278H30RJYKPAQR3H8KK4SF6IWI0JPXHPRP46VWN&currency=USD&sort=magic`
```
"creator": {
"id": 357970774,
"name": "Rebecca Lemme",
"slug": "actsofmatter",
"is_registered": null,
"is_email_verified": null,
"chosen_currency": null,
"is_superbacker": null,
"avatar": {
"thumb": "https://ksr-ugc.imgix.net/",
"small": "https://ksr-ugc.imgix.net/",
"medium": …
```

[Unticketed] user needs_password not returned in v1/discover/ creator

---

Library/ViewModels/RootViewModel.swift

A crash was found during 5.6.0 regression testing when switching tabs after logging and then out of a creator account. More info [here](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/edit-v2/2210562056)
This is an index out of range crash when selecting a new tab.
When a creator logs out our RootTabBar immediately updates its tabs/indices. There is a bit of a race condition where the RootViewModel attempts to set athe`prevSelectedTabBarItem` property before it recognizes that the user is no longer a signed in creator. Since creators see 1 more tab than logged out or backers (5 in total), the last selected item is technically out of range. 
Added 
`guard index < data.items.count else { return tabBarItemLabel(for: data.items[0]) }` 
to`prevSelectedTabBarItem`'s signal chain to …

[NTV-636] Regression: Crash when logging out of creator account and switching tabs 5.6.0

---

.circleci/config.yml

ENV-ize CircleCI IAM role ARN so it can be used in both ios-* repos

ENV-ize AWS role ARN

---

Kickstarter-iOS/Features/OptimizelyFeatureFlagTools/Controller/OptimizelyFeatureFlagToolsViewControllerTests.swift
Library/OptimizelyClientTypeTests.swift
Library/OptimizelyFeature+Helpers.swift
Library/OptimizelyFeature+HelpersTests.swift
Library/OptimizelyFeature.swift
Library/ViewModels/OptimizelyFeatureFlagToolsViewModel.swift
Library/ViewModels/OptimizelyFeatureFlagToolsViewModelTests.swift

This PR makes the necessary code changes to add a new 'Consent Management' feature flag. 
With iOS 14.5+, iPadOS 14.5+, we need to receive member's permission through the Apple's AppTrackingTransparency framework in order to track them or access their device’s advertising identifier.
This flag will gate the work that will be done to implement this.
More details around this initiative can be found [here](https://kickstarter.atlassian.net/wiki/spaces/NEW/pages/2225766401/iOS+Consent+Management)
Boilerplate code that adds a new case to the `OptimizelyFeature` enum and then a helper function that checks user defaults before returning the value from the `Optimizely` SDK. Finally a case for the new `consentManagementEnabled` feature case in `OptimizelyFeatureFlagTools` 
Optimizely Feature Flag …

[WEB-861] Consent Management feature flag

---

Library/OptimizelyClientTypeTests.swift
Library/OptimizelyFeature+Helpers.swift
Library/OptimizelyFeature+HelpersTests.swift
Library/OptimizelyFeature.swift
Library/ViewModels/OptimizelyFeatureFlagToolsViewModel.swift
Library/ViewModels/OptimizelyFeatureFlagToolsViewModelTests.swift

This PR makes the necessary code changes to add a new 'Facebook Conversions API' feature flag. 
With iOS 14.5+ Apple requires members to grant permission for apps to track them or access their device’s advertising identifier. This means that facebook app members can choose to "Ask app not to track".
If they do this, the facebook pixel that KS uses won't send or receive tracking data. Instead, we'll need to use their Conversions API to track and send events ourselves. 
More details around this initiative can be found [here](https://kickstarter.atlassian.net/wiki/spaces/NEW/pages/2231762945/iOS+Facebook+Conversion+API)
Boilerplate code that adds a new case to the `OptimizelyFeature` enum and then a helper function that checks user defaults before returning the value from the `Optimizely` …

[WEB-669] Facebook Conversions API Feature Flag

---

.fastlane/Fastfile

Reverts kickstarter/ios-oss#1771 to update branch name so it propagates to `ios-private`

Revert "attempt to fix Fastlane S3 access"

---

.fastlane/Fastfile

removed aws env vars, propogates to `ios-private`

[Unticketed] AWS Secret Key Env Vars Removal From Fastfile

---

Kickstarter-iOS/AppDelegateViewModel.swift
Kickstarter-iOS/AppDelegateViewModelTests.swift
Kickstarter-iOS/Info.plist
Kickstarter.xcodeproj/project.pbxproj
Library/Tracking/ATTrackingAuthorizationStatus.swift

Presents Apple's AppTransparencyFramework [dialog](https://developer.apple.com/app-store/user-privacy-and-data-use/#:~:text=Learn%20more-,Asking%20Permission%20to%20Track,-With) on app didFinishLaunching.
With iOS 14.5+ you need to receive the user’s permission through the AppTrackingTransparency framework in order to track them or access their device’s advertising identifier. 
We need to meet this requirement in order to ethically track facebook ads related data. 
context around our [consent management initiative](https://kickstarter.atlassian.net/wiki/spaces/NEW/pages/2225766401/iOS+Consent+Management)
context around our [facebook conversions api initiative ](https://kickstarter.atlassian.net/wiki/spaces/NEW/pages/2231762945/iOS+Facebook+Conversion+API)that will be gates by this …

[WEB-862] AppTrackingTransparency Authorization

---

Kickstarter.xcodeproj/project.pbxproj

beta and release are failing on ci because provisioning profile names are not mapping to their provisioning profiles on ios-certificates via fastlane match.

Updated Provisioning Profiles on XCode Project File To Allow FastLane Match To Run Distribution Build

---

Kickstarter.xcodeproj/project.pbxproj

Fixing a provisioning profile issue where the project file `.pbxproj` file doesn't contain the right provisioning profile for Release. Previously was `Development`, now it's `AppStore`. 
We need it set up this way so that Fastlane Match will be able to connect the schema with the certs and provisioning profiles in `ios-certificates` repo.

Added Correct Provisioning Profile for iTunes Build Release 5.6.1

---

Kickstarter-iOS/Features/LoginTout/Controller/LoginToutViewController.swift

A regression was found during 5.6.1. testing where the FB deprecation flow was being triggered at every fb login, rather than only when the FF is on and the user needs a password.
We only want to present this flow when the feature flag is enabled _and_ members need a password set on their account.
The `guard` statement in `LoginToutViewController line: 196` is disregarding the `needsPassword` check on the user object. Currently, it is storing the value in a variable and essentially checking that it is is not null rather than the value itself.
We don’t need to extract the value into the variable, so we can simplify this check into a more straightforward if/else like this:
```
if featureFacebookLoginDeprecationEnabled() && accessTokenEnv.user.needsPassword == true { …
```

[WEB-958] FIX: FB Deprecation (Set a password) flow disregarding guard statement

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/AppDelegateViewModel.swift
Kickstarter-iOS/AppDelegateViewModelTests.swift
Kickstarter.xcodeproj/project.pbxproj
Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Library/Tracking/Segment.swift

We noticed in-app notifications were broken (or not appearing) in release 5.6.1.
Needed to fix those. 
Strangely two different instances of `SEGAppboyIntegrationFactory` were being created when calling `instance()` on that class. Somehow this caused in-app notifications not to show up.
Created one instance of `SEGAppboyIntegrationFactory` inside the `Analytics` `configuredClient` function and pass it back out to be configure in the `AppDelegate`. (Previously passing it into the function).
Also it seems like segment-appboy-ios is pinning Appboy_iOS_SDK to `4.5.1` now, so let's use it's dependency instead of doing the pinning on our own.

[NTV-647] Braze In-App Notification Fix

---

Kickstarter.xcodeproj/project.pbxproj
Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Just a quick one here to update the dependency of `appboy-segment-ios` wrt this [issue](https://github.com/Appboy/appboy-segment-ios/issues/67). They fixed the crash scenario occuring for in-app notifications and this is the updated dependency `Appboy_iOS_SDK` going from `4.5.1` to `4.5.4`.

[Unticketed] Update Segment Appboy Dependency

---

Kickstarter-iOS/Features/Dashboard/Controller/DashboardViewControllerTests.swift
Kickstarter-iOS/Features/DashboardProjects/Views/FundingGraphView.swift
Kickstarter-iOS/Features/DashboardProjects/Views/FundingGraphViewTests.swift
Kickstarter-iOS/Library/CookieRefTagFunctions.swift
KsApi/models/Project.swift
KsApi/models/lenses/Project.DatesLenses.swift
KsApi/models/lenses/ProjectLenses.swift
Library/Tracking/KSRAnalytics.swift
Library/ViewModels/BackerDashboardProjectCellViewModel.swift
Library/ViewModels/DashboardFundingCellViewModel.swift
Library/ViewModels/DashboardFundingCellViewModelTests.swift
Library/ViewModels/DiscoveryPostcardViewModel.swift
Library/ViewModels/DiscoveryPostcardViewModelTests.swift
Library/ViewModels/DiscoveryProjectCardViewModel.swift
Library/ViewModels/ManagePledgeViewModel.swift
Library/ViewModels/MostPopularSearchProjectCellViewModel.swift
Library/ViewModels/PledgeSummaryViewModel.swift
Library/ViewModels/ProjectActivityLaunchCellViewModel.swift
Library/ViewModels/ProjectActivitySuccessCellViewModel.swift
Library/ViewModels/ProjectPamphletCreatorHeaderCellViewModel.swift
Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Library/ViewModels/RewardAddOnCardViewModel.swift
Library/ViewModels/RewardCardViewModel.swift

As outlined in this [ticket](https://kickstarter.atlassian.net/browse/WEB-999) we needed to update our existing project model `deadline` and `launchedAt` properties to optional instead of non-optional.
Reason is because the prelaunch pages do not have those fields populated in GQL and the existing project page works off of GQL not v1.
Obviously this isn't the final version of the prelaunch, but necessary to get the latest data for the eventual page UI.
As stated above, we need the `deadline` and `launchedAt` dates to be non-optional for those fields to be populated in order for the guard check to pass in `Project+ProjectFragment` `dates`
Did a project search for both properties and found instances of their use. In cases where optionals where being returned already, just needed to add the …

[WEB-999] Prelaunch Dates Blockers

---

Kickstarter.xcodeproj/project.pbxproj

This is the release from 5.7.0 to Main.
The reason we are doing this so early and not the first week of April is because Apple will not let us submit apps that are not built with Xcode 14 after April. [Source](https://developer.apple.com/ios/submit/).

Release 5.7.0 to Main

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphAPI.swift
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/fragments/UserMemberStatusFragment.graphql
KsApi/models/UserEnvelope.swift
KsApi/models/graphql/GraphUserMemberStatus.swift
KsApi/models/graphql/GraphUserMemberStatusTests.swift
KsApi/models/graphql/adapters/User+UserFragment.swift
KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelope.swift
KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelopeTemplates.swift
KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelopeTests.swift
KsApi/queries/FetchUserMemberStatus.graphql
Library/ViewModels/BackerDashboardViewModel.swift
Library/ViewModels/BackerDashboardViewModelTests.swift
Library/ViewModels/RootViewModel.swift

On the latest build noticed a weird UI break with inconsistent number of tabs in the dashboard leading to a black background for creators and collaborators.
We are going to remove the creator dashboard in the future (for something like 3000 users), but for now we support that side of things so we shouldn't introduce regressions there.
There was no `isCollaborator` field in GQL (unlike `isCreator`) UserFragment we already have, so had to create a new query, fragment, GraphUser adapter and test them all.
The new call is chained within `BackerDashboardViewModel` you'll see even if it fails the GraphUser data is propogated without `GraphUserMemberStatus`
Before 🐛 
https://user-images.githubusercontent.com/4282741/229403649-e439c69c-cc66-426c-b457-6fd67c68e5f7.mp4
After 🦋 …

[Unticketed] UI on the Creator Dashboard Breaking

---

Kickstarter-iOS/SharedViews/PledgeCTAContainerView.swift
KsApi/GraphAPI.swift
KsApi/models/graphql/WatchProjectResponseEnvelope.swift
KsApi/models/graphql/adapters/WatchProjectResponseEnvelope+UnwatchProjectMutation.Data.swift
KsApi/models/graphql/adapters/WatchProjectResponseEnvelope+UnwatchProjectMutation.DataTest.swift
KsApi/models/graphql/adapters/WatchProjectResponseEnvelope+WatchProjectMutation.Data.swift
KsApi/models/graphql/adapters/WatchProjectResponseEnvelope+WatchProjectMutation.DataTests.swift
KsApi/models/templates/graphql/WatchProjectResponseEnvelopeTemplates.swift
KsApi/mutations/UnwatchProject.graphql
KsApi/mutations/WatchProject.graphql
KsApi/mutations/templates/mutation/WatchProjectMutationTemplate.swift
Library/PledgeStateCTAType.swift
Library/ViewModels/PledgeCTAContainerViewViewModel.swift
Library/ViewModels/PledgeCTAContainerViewViewModelTests.swift
Library/ViewModels/ProjectPageViewModel.swift
Library/ViewModels/ProjectPageViewModelTests.swift
Library/ViewModels/WatchProjectViewModel.swift
Library/ViewModels/WatchProjectViewModelTests.swift

We noticed that prelaunch page watch count was not being accurately update after saving/unsaving the project.
Matching Android functionality. Also makes more sense to show the new follower count after following a project.
Modified the `.graphql` files for `Unwatch` and `Watch` project to include `watchesCount`.
Updated the envelope to have this property after getting it back from the mutation data.
The `PledgeStateCTAType` has a new property within the `prelaunch` enum case for `watchesCount`.
We merge the new pledge state with `watchesCount` to the `watchesCountText` in `PledgeCTAContainerViewViewModel` which was previously just using the project it was configured with for that text.
All the other signals/notifications should be the same, it's just about keeping track of the …

[MBL-703] Prelaunch Page Watch Count Update

---

Kickstarter-iOS/Features/DashboardDeprecationBanner/DashboardDeprecationView.swift

Updates the date shown in the creator dashboard deprecation banner.
Users should have an accurate notice of when this feature will be removed.
The banner has already been built and the existing date is formatted correctly. So, all we need to is update the date being passed in.
| --- | --- |
| <img src="https://github.com/kickstarter/ios-oss/assets/110618242/d8a8f4fc-359b-4eae-9d0f-6b425cfbc5cf" width="200"/> | <img src="https://github.com/kickstarter/ios-oss/assets/110618242/246d0006-baf5-4b70-9b6b-3e017e720c67" width="200"/> |

[MBL-888] Update Creator Dashboard Deprecation Date

---

KsApi/lib/HTML Parser/HTMLParserTests.swift
KsApi/lib/HTML Parser/Templates/HTMLParserTemplates.swift
KsApi/lib/HTML Parser/View Elements/TextComponent.swift
KsApi/lib/HTML Parser/View Elements/ViewElementType.swift
Library/ViewModels/HTML Parser/TextViewElementCellViewModel.swift
Library/ViewModels/HTML Parser/TextViewElementCellViewModelTests.swift

There's been a change on the web to support a new parser called `CKEditor` and it supports additional header tags. Previously we supported only `h1`. Now we support `h1`, `h2`, `h3`, `h4`, `h5`, `h6`.
As stated above, we would eventually need to add new elements/HTML tags supported by more modern project creation tools.
Pretty straightforward, taking a look at the Android [pull request](https://github.com/kickstarter/android-oss/pull/1835) that does the exact same thing. Used the font sizes for reference so they should be the same size on both platforms.
Might be nice to screenshot test all the supported HTML components one day...thinking when we remove the parser and get good support for `story` properties on the `ProjectFragment` we can look into this.
| --- | --- …

[MBL-943] Add Additional Header Support to HTML Parser

---

Kickstarter-iOS/AppDelegateViewModel.swift
Kickstarter-iOS/AppDelegateViewModelTests.swift

We currently try to parse all braze links as deep links. This is a simple change that looks at the link itself to determine if it's a deep link or not. Deep links are handled the same as before; other links will now open in Safari instead of doing nothing.
Note that this does not try to parse the braze info to see if the link was intended to be opened in web or not.
External links from braze notifications are currently broken; nothing happens if the user tries to click on them.
[JIRA bug](https://kickstarter.atlassian.net/browse/ADHOCREQ-106)
[Screencast after fix](https://github.com/kickstarter/ios-oss/assets/6799207/9af4d689-73c7-42d5-b1dd-8cea482f932f)

[ADHOCREQ-106] Redirect to safari for braze links that aren't deep links

---

.circleci/config.yml
Kickstarter.xcodeproj/project.pbxproj

Updates the CircleCI config to use the M1 resources instead of x86.
- Additionally, at the moment Apollo only targets x86 so this also installs Rosetta in CI
CircleCI is retiring the MacOS x86 resource types.
- [CirleCI m1 resource class](https://circleci.com/docs/configuration-reference/#macos-execution-environment)
- [CirleCI orb for installing Rosetta](https://support.circleci.com/hc/en-us/articles/17402023738651-Installing-Rosetta-on-Apple-Silicon-M1-executors) 
Also note there is a performance improvement, but also a cost increase with moving to M1. The cost is ~2x the x86 cost.
| Before 🐛 | After 🦋 | What |
| avg 55 min | 31 min | Total build time |

[INF-1630] use m1 resource class

---

.circleci/config.yml
Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphAPI.swift
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/models/FetchProjectsEnvelope.swift
KsApi/models/graphql/adapters/FetchProjectsEnvelope+FetchBackerProjectsQueryData.swift
KsApi/models/graphql/adapters/FetchProjectsEnvelope+FetchBackerProjectsQueryDataTests.swift
KsApi/queries/FetchBackerProjectsQuery.graphql
KsApi/queries/templates/FetchBackerProjectsQuery.json
KsApi/queries/templates/FetchBackerProjectsQueryDataTemplate.swift
KsApi/queries/templates/FetchBackerProjectsQueryRequestForTests.graphql_test

Add a new GraphQL query to power the "backed" and "saved" tabs on the Profile page. This will replace the v1 discover API call on the same page.
- Replace another usage of API v1 in the app
- The 'saved' and 'backed' counts on this page can get out of sync with the actual results list. By porting this to GraphQL, we can include the `totalCount` in the same query, which will let me fix this issue.
- This query isn't currently integrated (that will come in a future PR), so the only acceptance criteria is passing tests.
- `FetchProjectsEnvelope_FetchBackerProjectsQueryDataTests` are currently _not_ passing, because `Project.project(from: fragment, currentUserChosenCurrency: nil)` fails when attempting to parse the test data. I could use some help debugging this - the error I get back is 
``` …
```

MBL-988: Add GraphQL query FetchBackerProjectsQuery to replace v1 API calls on backer dashboard

---

.circleci/config.yml
.gitignore
Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-Framework-iOS.xcscheme

CircleCI runs snapshot tests. However, if a snapshot test fails, we had no way of _seeing_ that failed test. This will make debugging test failures on CircleCI easier. 
`swift-snapshot-testing` will automatically saved failed screenshots to a directory defined by the environment variable `SNAPSHOT_ARTIFACTS`. I added that variable, and also added a `save_artifacts` step to our build pipeline.
Here's an example of uploaded artifacts, from a copy of this PR that I forced to fail:
https://app.circleci.com/pipelines/github/kickstarter/ios-oss/4281/workflows/c037a3a3-fd45-4d62-ac8b-5a5a29b02f96/jobs/52311/artifacts
It's worth noting that these changes will also affect your local machine. See this test report:
```
failed - Snapshot "lang_de_device_phone4_7inch" does not match reference.
@− …
```

Store failed snapshots in Failed_Snapshot_Tests/ and save as artifacts

---

.circleci/config.yml

Use a shallow `git clone`, instead of a full `git clone`, when downloading our app code in CircleCI.
We have a long and storied git history. If you peek at your `.git` repo locally, you'll notice it's over 3GB of data. Downloading this extra 3GB significantly slows down the `checkout` step in CircleCI, as well as our later caching steps`persist_workspace` and `attach_workspace`.
[A shallow clone](https://git-scm.com/docs/git-clone) only clones the most recent git history, instead of the _entire_ history. This vastly reduces the size of the `.git` repo. By reducing the repo size, we speed up the rest of the job. 
Shallow clones do have some limitations - you can't switch branches on a shallow clone, or push. However, we don't perform any git commands on CircleCI, so a shallow clone is …

[MBL-1006] Use shallow clone to speed up build times

---

.circleci/config.yml

Increase the our shallow fetch depth.
Danger, which we use to run `swift-format` and check PR size, doesn't play nicely with shallow clones. By increasing our shallow clone depth, we can get Danger to work but keep the speedup we get from the shallow clone.

Increase shallow fetch depth to 100, to make Danger work

---

Kickstarter-iOS/Features/Comments/Views/Cells/CommentCell.swift
Kickstarter-iOS/Features/Comments/Views/Cells/RootCommentCell.swift
Kickstarter-iOS/Features/Comments/Views/CommentCellHeaderStackView.swift
Kickstarter-iOS/Features/Comments/Views/ViewRepliesView.swift
Kickstarter-iOS/Features/Messages/Views/Cells/MessageCell.swift
Kickstarter-iOS/Features/ProjectPage/Views/Cells/ProjectPamphletMainCell.swift

Fix accessibility for comments and messages by splitting the cells into accessibility components. The header/username is annotated as a button when the feature flag is enabled. The accessibility hint for the username button on the project page is removed.
Ideally we should add a "Opens user menu" accessibility hint instead, but that will need to wait until we have such a string translated.

[MBL-1021] Fix user blocking voiceOver

---

Kickstarter-iOS/Features/ReportProject/ReportProjectFormView.swift
Kickstarter-iOS/Features/ReportProject/ReportProjectInfoView.swift
Kickstarter-iOS/SharedViews/LoadingBarButtonItem.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/combine/CombineTestObserver.swift
KsApi/combine/Signal+Combine.swift
KsApi/extensions/ApolloClient+RAC.swift
KsApi/extensions/MockGraphQLClient.swift
Library/ViewModels/ReportProjectFormViewModel.swift
Library/ViewModels/ReportProjectFormViewModelTests.swift

This removes ReactiveSwift from `ReportProjectFormViewModel`. As part of that change, I also did some refactoring, to take advantage of as much brevity as I could squeeze out of that change.
This is one of our experiments in moving the app off of ReactiveSwift. The goal here is twofold:
1. Learn more about what that might look like, and how we'd have to architect things
2. Make sure that we can actually ship a Combine + SwiftUI feature without something going terribly wrong
Because I had to make a lot of architectural choices here, I'm leaving a lot of comments in the code. Take a look and let me know if you agree or disagree! This is all part of figuring out how we want to use Combine in the future.
You'll need to turn on the Report Projects feature flag (either in the code directly, or …

MBL-1014: Replace ReactiveSwift in ReportProjectFormViewModel with Combine

---

Kickstarter-iOS/Features/ChangeEmail/Controller/ChangeEmailView.swift
Kickstarter-iOS/Features/ReportProject/ReportProjectFormView.swift
Kickstarter-iOS/SharedViews/LoadingBarButtonItem.swift
Library/ViewModels/ChangeEmailViewModelSwiftUIIntegrationTest.swift
Library/ViewModels/ReportProjectFormViewModel.swift

This refactors `LoadingBarButtonItem` to take a closure.
This pattern more closely follows how Apple handles save actions (e.g. in the `Button` class), which will make our code a little bit more canonical.

    MBL-1039: Refactor LoadingBarButtonItem to take a closure instead of a binding for save actions

---

Kickstarter-iOS/Features/Comments/Controllers/CommentRepliesViewController.swift
Kickstarter-iOS/Features/Comments/Controllers/CommentsViewController.swift
Kickstarter-iOS/Features/MessageBanner/Controller/MessageBannerViewController.swift
Kickstarter-iOS/Features/Messages/Controller/MessagesViewController.swift
Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
Library/UIAlertController.swift
Library/ViewModels/CommentRepliesViewModel.swift
Library/ViewModels/CommentsViewModel.swift
Library/ViewModels/MessagesViewModel.swift
Library/ViewModels/ProjectPageViewModel.swift

1. Presents a confirmation alert when "Block this user" is selected from the block user action sheet
2. Presents a success or fail Message Banner when tapping block in this new alert. This isn't wired up to an API or anything yet. This behavior is hardcoded for now.
Rather than sending a blocking request from the action sheet, we're going to use this confirmation alert pattern so that we can provide extra information and double-check that they want to block a user. 
The key areas are:
- Comments
- CommentReplies
- ProjectPage
- Messages
I'm taking advantage of the existing MessageBannerViewController that we use elsewhere in the app to display API response success and error banners. This means that each ViewController, except ProjectPage, needs to conform to …

[MBL-1036] Block User Popup + Banner Message

---

Kickstarter-iOS/Features/Discovery/Controller/DiscoveryPageViewController.swift
Library/Notifications.swift
Library/ViewModels/CommentRepliesViewModel.swift
Library/ViewModels/CommentsViewModel.swift
Library/ViewModels/DiscoveryPageViewModel.swift
Library/ViewModels/DiscoveryPageViewModelTests.swift
Library/ViewModels/MessagesViewModel.swift
Library/ViewModels/ProjectPageViewModel.swift

Once you block a user, anywhere in the app, the Discover page will be refreshed.
Once you've blocked someone, we want to stop showing that person's content. Refreshing the Discover page means that we'll re-fetch the list of projects, filtering out any projects by blocked users.
If I throw in a`logEvent()`, it indicates that my signal is hooked up correctly, but I don't think it's actually refreshing the page like I would expect. I could use a little help debugging this behavior to make sure it's working properly.

MBL-1029: Refresh Discover page after a user is blocked

---

Kickstarter-iOS/Features/Comments/Controllers/CommentRepliesViewController.swift
Kickstarter-iOS/Features/Comments/Controllers/CommentsViewController.swift

If a user is blocked, comments are reset - refetched and the user is jumped back to top. If a user is blocked from the `CommentRepliesViewController`, they're navigated back to the main `CommentsViewController`.
Note: I did consider refetching comments in place instead, but getting it to work with pagination seemed tricky, so I'm clearing state instead for now. If we have time, it would be nice to revisit this approach and try to let the user keep their place in our comments.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1026)

Refresh comments when a user is blocked

---

Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
Kickstarter-iOS/Locales/de.lproj/Localizable.strings
Kickstarter-iOS/Locales/es.lproj/Localizable.strings
Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
Library/Strings.swift
Library/UIAlertController.swift
Library/ViewModels/CommentCellViewModelTests.swift

Pull in translated strings and use them in the block user flow.

[NO TICKET] Update Block User Strings

---

Kickstarter.xcodeproj/project.pbxproj

The crashlytics script needs to be run last in the build phases; otherwise it breaks the build.

Reorder build phases so firebase crashlytics is last

---

Kickstarter-iOS/Features/Comments/Controllers/CommentRepliesViewController.swift
Kickstarter-iOS/Features/Comments/Controllers/CommentsViewController.swift
Kickstarter-iOS/Features/Messages/Controller/MessagesViewController.swift
Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
KsApi/MockService.swift
KsApi/mutations/inputs/BlockUserInput.swift
Library/ViewModels/CommentRepliesViewModel.swift
Library/ViewModels/CommentRepliesViewModelTests.swift
Library/ViewModels/CommentsViewModel.swift
Library/ViewModels/CommentsViewModelTests.swift
Library/ViewModels/MessagesViewModel.swift
Library/ViewModels/MessagesViewModelTests.swift
Library/ViewModels/ProjectPageViewModel.swift
Library/ViewModels/ProjectPageViewModelTests.swift

Now that the block mutation has been [added](https://github.com/kickstarter/ios-oss/pull/1890), let's implement it.
So we can block users!
We are letting users block someone from the following places:
- Project Page
- Message Threads
- Comments & Comment Replies
When we call this mutation via `AppEnvironment.current.apiService.blockUser...` either an error will occur or it'll be successful. So, in each view model, I've set up an output for each case that will in turn present a success or error message banner. 
We currently don't have the error messages that we can receive from the backend translated and localized so for now we are showing a generic "This didn't work" message. Not ideal. Showing a more useful message like, "You can only block someone that doesn't have a live project you …

[MBL-1024] Wire Up Block User Mutation

---

.codecov.yml

Disable inline annotations from Codecov in Github PRs.
The team agreed that these annotations are more annoying than they are helpful. While they can be disabled easily in Github, it's a small distraction we don't need.
The same coverage information is still posted in the Codecov summary in the PR.
Here's an example of this change in action: https://github.com/kickstarter/ios-oss/pull/1898
You'll note that there are complaints in the Codecov summary, but not inline.

MBL-1074: Disable Github annotations in .codecov.yml

---

Kickstarter-iOS/Features/Messages/Controller/MessagesViewController.swift
Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift

If a user is already blocked, we'll revert to old behavior (clicking on the username on the project page opens the creator page immediately and clicking usernames elsewhere has no effect.)
Note: this required no changes in comments, since that was already checking for blocked users.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1075)

[MBL-1075] Prevent blocking for users that are already blocked

---

Kickstarter-iOS/SharedViews/LoadingBarButtonItem.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/Publisher+Service.swift
KsApi/Service.swift
Library/ViewModels/ReportProjectFormViewModel.swift

Add two custom operators for API patterns that (I expect) will be fairly common in Combine.
As part of the SwiftUI migration work, we want to establish some repeatable patterns for the future. When I ported `ReportProjectFormViewModel` to be completely in Combine, I left two somewhat confusing operations - a way to map fetch results, and a way to handle API failures without cancelling the pipeline. I wanted to make a cleaner interface for these two patterns, since I assume they'll pop up again.

MBL-1016: Add custom operators for common API patterns

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/combine/CombineTestObserver.swift
KsApi/extensions/MockGraphQLClient+CombineTests.swift
KsApi/extensions/MockGraphQLClient.swift
Library/ViewModels/ReportProjectFormViewModelTests.swift

* Add handling for failures in MockGraphQLClient code
* Add observation for failures to CombineTestObserver
This was another `//TODO` I left myself in the initial `ReportProjectFormViewModel` refactor.

MBL-1016: Add handling for failures in MockGraphQLClient

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/models/ExportDataEnvelope.swift
KsApi/models/ExportDataEnvelopeTests.swift
KsApi/models/lenses/ExportDataEnvelopeLenses.swift
Library/ViewModels/SettingsRequestDataCellViewModelTests.swift

This is a cleaner way to handle any future server changes; I just didn't understand decoders well enough to to this initially. The actual behavior (unknown strings default to `.unknown` and anything that can't be parsed as a string throws an error) remains the same.

Stop using rawState in exportDataEnvelope

---

Kickstarter-iOS/Features/Messages/Storyboard/Messages.storyboard
Library/ViewModels/MessagesViewModel.swift
Library/ViewModels/MessagesViewModelTests.swift

Disables the Reply bar button in message threads if the message participant has been blocked. 
If we don't think this should go out with 5.11.0 I can avoid cutting a new build and this can go out in the next release. I think we can get it in though.
We'll be stopping communication between users when one has been blocked.
MessagesViewModel has a `replyButtonIsEnabled` signal that I've updated to emit `true` only when there are messages _and_ the participant isn't blocked.

[MBL-1095] Disable Message Reply Button When User Is Blocked

---

Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
Kickstarter-iOS/Features/ProjectPage/Views/ProjectPageNavigationBarViewTests.swift
Library/Tracking/KSRAnalytics.swift
Library/Tracking/KSRAnalyticsTests.swift
Library/ViewModels/CommentRepliesViewModel.swift
Library/ViewModels/CommentRepliesViewModelTests.swift
Library/ViewModels/CommentsViewModel.swift
Library/ViewModels/CommentsViewModelTests.swift
Library/ViewModels/MessagesViewModel.swift
Library/ViewModels/MessagesViewModelTests.swift
Library/ViewModels/ProjectPageViewModel.swift
Library/ViewModels/ProjectPageViewModelTests.swift
Library/ViewModels/WatchProjectViewModelTests.swift

Adding a new `trackBlockedUser` segment event around in our user blocking flow.
[Event definition doc](https://kickstarter.atlassian.net/wiki/spaces/IN/pages/2548301877/User+Blocking+Flow) from the insights team
I also included an unrelated property name update here that is just a cleanup.
This flow doesn't have any analytic events, and we want to know how useful users find this feature and how often they use it.
I've added this new event in `KSRAnalytics`, as well as tests in `KSRAnalyticsTests`
It is then used in these view models:
1. ProjectPageViewModel
2. MessagesViewModel
3. CommentsViewModel & CommentRepliesViewModel
No UI updates

[MBL-1031] User Blocking Analytics

---

Kickstarter-iOS/Features/MessageThreads/Controller/MessageThreadsViewController.swift
Kickstarter-iOS/Features/Messages/Controller/MessagesViewController.swift

Refreshes `MessageThreadsViewController` after successfully blocking a user within a message.
Blocking a user through messages doesn’t update the UI until it’s manually refreshed. 
**Steps to reproduce**
1. Block user from messages
2. Get automatically navigated back to inbox
3. Click back in on message thread and see no difference
4. Go back to inbox, pull to refresh, click on message thread again. Notice that message thread now says user is blocked
In other parts of this flow we use the `.ksr_blockedUser` notification to update other parts of the app. For this case, the simpler approach is to use the existing refresh functionality in `MessageThreadsViewModel`.
- Added a callback, `var dismissedAfterBlockingUserHandler: (() -> Void)?`, in `MessagesViewController`
- When a user …

[MBL-1093] Messages don't refresh when a user is blocked

---

Kickstarter-iOS/Features/Comments/Controllers/CommentRepliesViewController.swift
Kickstarter-iOS/Features/Comments/Controllers/CommentsViewController.swift
Kickstarter-iOS/Features/Messages/Controller/MessagesViewController.swift
Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
Kickstarter-iOS/Features/ProjectPage/Views/Cells/ProjectPamphletMainCell.swift

Fix [this crash](https://console.firebase.google.com/u/0/project/kickstarter-ios/crashlytics/app/ios:com.kickstarter.kickstarter/issues/e328c5b10cd249143c0846f18587c92f?time=last-twenty-four-hours&versions=5.11.0%20(1702566)&types=crash&sessionEventKey=b69cc5f5cd214edc928e1bb5f75d22d9_1899936616456567754) found in 5.11.0.
To duplicate, try blocking a user from the Comments screen while you're using an iPad in Landscape mode.
At least reading the crash log, it sounds like that when you present a `UIAlertController` on an iPad in a navigation controller, it _forces_ it to be presented as a popover. However, our check `IsIPad` checked the horizontal size class of the view controller. Because we present the comment view controllers in a modal screen - which _isn't the full width_ - the …

MBL-1128: Fix crash when trying to block a user while using an iPad

---

Kickstarter.xcodeproj/project.pbxproj

Create a release branch, update the marketing version, and merge it back into `main`. Note all the deletions of `5.11.0` in there - that was me deleting target overrides, so that the global Project setting will be the marketing version for all target.
For release 5.12.0.

Update marketing version to 5.12.0

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/combine/CombineTestObserver.swift
KsApi/combine/CombineTestObserverTests.swift

This makes `CombineTestObserver` equivalent to `TestObserver`. Heck, I even just copy-pasted some code over, because it worked fine!
When we write new view models in Combine, we'll want to test them. This means that, if we're porting code, we can re-use the same (or write very similar) tests.

MBL-1017: Add features to CombineTestObserver

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/PKCE.swift
KsApi/PKCETest.swift

Added a utility for PKCE verification.
PKCE is part of the native apps flow for oAuth - we create a secret (the code verifier) and a challenge (a hashed version) which gets sent to the server. This is used to verify that every step of the oAuth flow is legit. Later in the flow, the client has to prove that it was the one that generated the hash by providing the original secret.
For more, see: https://www.oauth.com/oauth2-servers/mobile-and-native-apps/authorization/
I used [this example code](https://kickstarter.atlassian.net/browse/MBL-1168), as well as the documentation above.
I'd like to add more tests to this, which I'll coordinate with Isa on the Android side. These tests are just to make sure the code is running.

  MBL-1157: Create PKCE code for code verifier and code challenge

---

Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/RemoteConfigFeatureFlagToolsViewControllerTests.swift
Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
Library/RemoteConfig/RemoteConfigFeature+HelpersTests.swift
Library/TestHelpers/TestCase.swift
Library/ViewModels/RemoteConfigFeatureFlagToolsViewModel.swift

Remove boilerplate from our feature flag code.
1. I was about to add a new feature, and the amount of copy-paste was bothering me.
2. This particular copy-pasted code seemed really easy to make mistakes in. We have tests for it, but those tests were also easy to put mistakes in! 
Note the test runs for the three commits below - I did the code cleanup _first_, waited for the tests to pass, and then did the test cleanup. Just to ensure I didn't break both the code and tests simultaneously.

Clean up RemoteConfigFeature+Helpers and RemoteConfigFeatureFlagToolsViewModel

---

Library/ViewModels/RemoteConfigFeatureFlagToolsViewModelTests.swift

This is a follow up to my PR #1924, making one more test future-proof.
Adding feature flags is unnecessarily difficult, requiring a lot of copy-paste. This is one more place we shouldn't have to paste a new flag.

Make RemoteConfigFeatureFlagToolsViewModelTests resistant to adding new features

---

Library/ViewModels/SettingsDeleteOrRequestCellViewModel.swift

Update the url to use the language code for the current locale. We're doing this instead of a translatable string because this is how they construct urls on web, so they explicitly ask translators to not translate urls.
[JIRA](https://kickstarter.atlassian.net/browse/MBL-1146)

[MBL-1146] Update transcend privacy url to use current locale

---

Kickstarter-iOS/Features/PaginationExample/PaginationExampleView.swift
Kickstarter-iOS/Features/PaginationExample/PaginationExampleViewModel.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/MockService.swift
KsApi/Service+RequestHelpers.swift
KsApi/Service.swift
KsApi/ServiceType.swift
Library/Paginator.swift
Library/PaginatorTests.swift

This adds a new class, `Paginator`, inspired by our existing `paginate` method. `Paginator` is designed to fill the same functionality, but in a way that integrates neatly with SwiftUI and Combine-based code.
When we move over to SwiftUI and Combine, we'll need an easy way to page through long lists of API results.
Originally I wanted to create a 1-for-1 re-write of `paginate` in Combine. The nice thing about the original `paginate` method is that it's _stateless_, nothing but a bunch of pure functions. However, I spent a significant amount of time trying to duplicate it, and was unable to make any traction. Writing stateless functional code is significantly more challenging (to me at least), and I don't think the benefits of its elegance outweigh the difficult I had modifying and …

MBL-1016: Create Paginator for pagination in SwiftUI/Combine

---

Kickstarter-iOS/AppDelegate.swift
Library/OAuth.swift

1. Stop logging remote configuration errors to Crashlytics when a user boots the app with no connectivity.
2. Log when OAuth setup fails.
This is to take better advantage of our non-fatal error logging in Crashlytics. Removing a noisy error, adding one I care about.

Add a nonfatal error; delete another nonfatal error

---

Kickstarter.xcodeproj/project.pbxproj

Explicitly link Prelude as part of the build phases for Kickstarter-Framework.
One of our more persistent (and annoying) build issues is this linker error, in which it fails to link to Prelude: 
My best guess (based on a little reading and this helpful [StackOverflow](https://stackoverflow.com/questions/56855766/xcode-build-fails-due-to-undefined-symbol-swift-force-load-swiftuikit) post) is that Xcode is sometimes clever enough to resolve these dependencies automatically, but not consistently. Note that for our other targets, we also have libraries (including Prelude) explicitly linked, so it seems probable that this was just an omission.
Adding this resolved that particular instance of that Prelude linker error that was I was seeing. Hopefully this reduces the overall number of linker …

Explicitly add Prelude to Link Libraries phase of Kickstarter-Framework

---

Kickstarter.xcodeproj/project.pbxproj
Kickstarter.xcodeproj/xcshareddata/xcschemes/Library-iOS.xcscheme
Library-Keychain-iOSTests/Library_Keychain_iOSTests.swift
Library/Keychain.swift
Library/KeychainTests.swift

This PR adds `Keychain.swift`, which contains a utility methods for interacting with the system keychain.
Currently we store our authentication tokens in `UserDefaults`, which is insecure. As part of migrating to OAuth, both iOS and Android want to use their equivalent system keychains, which is the correct/recommended implementation for login data.
This is the first step in that - writing code that allows us to actually interact with the keychain.

 MBL-1161: Add code to handle storing/retrieving/deleting Keychain items 

---

Kickstarter-iOS/AppDelegate.swift
Library/Tracking/Segment.swift

Track push notifications by telling braze/appboy when they're opened.
Note: In order to do this smoothly, `Appboy.sharedInstance()` is moved out of the helper function we had it in. I've verified that the shared instance that exists in that helper is different from the one that exists in AppDelegate (but within each file, they're consistent). I'm not sure why that's the case, but I'd theorize it has something to do with different targets or the helper function being static or that it lives within a SEG class and is itself a SEG class. In any case, moving these lines of code out means that `Appboy.sharedInstance()` is consistent from when we add it to the configuration to when we need it for reporting push notifications.
(In the original commit, I stored appboyHelper instead to make it …

[MBL-1147] Track push notifications

---

Library/Paginator.swift

In our beta build (and probably release build, though I didn't check), having an assert inside a guard block with no other return causes the build to not compile. I'm not 100% sure, but I think the assert gets optimized out or at least doesn't crash the binary in these cases.

Add a return after the assert

---

Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-iOS.xcscheme

Force you to select the correct build schema when running tests via Xcode.
Say you have an arbitrary target selected, and you try and run some tests by hitting the play button. In this example, I'm trying to run a test in `Library-iOS-Tests`, and I have the `Kickstarter-iOS` target selected, because I was running the app.
You might be treated to this linker error. However, look closely - why is it trying and failing to build `KsApiTests`? 
This is odd - while `Library-iOS` depends on `KsApi`, `Library-iOS-Tests` does NOT depend on `KsApiTests`.
Looking into the dependency graphs, and it looks like the app is trying to build `Kickstarter-iOS`, and then as part of that, it _included_ `KsApiTests`. That is also odd. First, why is it building `Kickstarter-iOS` instead of just `Library-iOS` …

Update build schema to force you to select correct target when building tests

---

Kickstarter.xcodeproj/project.pbxproj

This change does the same thing as #1942, except it adds it to Library-iOS.
I noticed the same linker error applying to this library while running tests for Library-iOS.

Explicitly add Prelude to Link Libraries phase of Library-iOS

---

Library/AppEnvironment.swift
Library/AppEnvironmentTests.swift

Remove a switch in the code that checks for a legacy OAuth token.
As part of OAuth (or as a fast follow), we're going to swap the apps over to save our OAuth tokens in the keychain. I noticed while poking around our login code that we have this very, very old migration. I look at the commit 9e53ab9 where this was added, and it was back in 2016. If I'm reading our tags right, it was shipped around version 3.0.2, which is so old it's not even tracked in Firebase.
I think it's resoundingly safe to delete this, and it will make the code cleaner when we add a _new_ migration for the _new_ way to store OAuth tokens. 
Worst case scenario is that someone upgrading from a truly ancient version of the app will have to log in again. 🤷‍♀️

Remove old legacyOauthToken code (from 2016)

---

Kickstarter-iOS/Features/LoginTout/Controller/LoginToutViewController.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/lib/Route.swift
KsApi/models/OAuthTokenExchange.swift
Library/OAuth.swift
Library/OAuthTests.swift

This implements the MVP of login with OAuth. 
It works like this:
1. Open a web authentication session
2. If it completes successful, the website redirects to a URL which includes a tempoary authorization code
3. We exchange that code and a secret for the real OAuth token
4. We use that OAuth token to fetch the user's information
5. ...and then save that to the app environment login. 
We are porting the app to use OAuth via a web authentication session to improve security.
This snazzy demo!
https://github.com/kickstarter/ios-oss/assets/146007185/19803d96-04c0-4e1c-b596-c9527bc63d8e

MBL-1159: Exchange temporary token for OAuth token and login

---

KsApi/MockService.swift
KsApi/Service+RequestHelpers.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/ServiceTypeTests.swift
KsApi/lib/Route.swift
Library/OAuth.swift

Send OAuth tokens only in the request headers, not in the request parameters.
This is a security concern which we wanted to address with the MVP of OAuth. Moving the authorization parameters into headers is a best practice.
See: https://github.com/kickstarter/kickstarter/pull/26425 and https://github.com/kickstarter/kickstarter/pull/26432
Note that this isn't behind any flags. The server change to accept the OAuth token in the headers was made globally, for all V1 requests, and already applied for GraphQL. We decided a ramp-up would be difficult, due to how deep the headers are buried in our networking stack, and of limited use, compared to testing this change manually.
Also note that we are sometimes sending _redundant headers_, like both `Authorization` and `X-Auth` with the OAuth …

MBL-1214: Send OAuth token only in headers, not in request parameters

---

Library/Navigation.swift
Library/NavigationTests.swift
Library/RefInfo.swift

Add a deeplink url to the RefInfo struct. This is captured for deeplink opens to anything in the project page. Once the attribution event is ready, this will be included there.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1220)

[MBL-1220] Add deeplink url to refInfo when opening proj page

---

Kickstarter-iOS/Features/LoginTout/Controller/LoginToutViewController.swift
Library/ViewModels/LoginToutViewModel.swift

Remove the sign up button (and change the login button text) when OAuth is turned on.
Users who want to sign up will go through the web-based sign up flow, using the same web view as login.
OAuth off:
OAuth on:

MBL-1233: Consolidate login and signup buttons when OAuth is enabled

---

Kickstarter-iOS/Features/LoginTout/Controller/LoginToutViewController.swift
Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
Kickstarter-iOS/Locales/de.lproj/Localizable.strings
Kickstarter-iOS/Locales/es.lproj/Localizable.strings
Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
Library/Strings.swift

Change the string I'm using for a button.
This should have its own translation, instead of using the translation for the similar button in Discover.
We'll have to update the strings files once the translations percolate through the system.

MBL-1233: Use correct string for 'Sign up or Log in' button

---

Kickstarter.xcodeproj/project.pbxproj
Library/AppEnvironment.swift
Library/AppEnvironmentTests+OAuthInKeychain.swift
Library/AppEnvironmentTests.swift

Store the OAuth token in the keychain, instead of in user defaults. Additional code moves the old token out of defaults and into the keychain if you were already logged in.
Leaving the token in user defaults is insecure. 
We store the OAuth token per-user, using a pseudo-account-name like `kickstarter_12345` for user with id `12345`. The change is gated behind a feature flag, and hopefully fairly robust to any keychain failures or exceptions.

MBL-1161: Read and store OAuth token from keychain

---

Kickstarter-iOS/AppDelegateViewModel.swift
Kickstarter-iOS/AppDelegateViewModelTests.swift
Library/AppEnvironment.swift

Fix `AppEnvironment.current.currentUserEmail`, which did not appear to be correctly saving the currently logged-in user's e-mail.
We need the user's e-mail on the Thanks page for post-campaign backings. I noticed that we had this `currentUserEmail` property on `Environment`, but it wasn't working correctly. I did some digging and I figured it's because the signal is being deallocated before the value is set.
An interesting question is why `currentUserEmail` isn't just part of `currentUser`. Apparently the V1 `User` object doesn't appear to have an e-mail attached to it, and the e-mail is coming from GraphQL, instead. It's a bit messy but I wanted to keep this change fairly low-profile instead of doing more refactoring.

MBL-1211: Rewire current user email in AppEnvironment/AppDelegateViewModel

---

Kickstarter-iOS/Features/ThanksProjects/Controller/ThanksViewControllerTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift
Library/ViewModels/ThanksViewModel.swift
Library/ViewModels/ThanksViewModelTests.swift

Pass the pledge total into the thank you page.
The new string for post-campaign backings on the thank-you page will reference the pledge amount, so we need it in the view model.

MBL-1211: Pass down pledge total to thank you page for new page copy

---

Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
Kickstarter-iOS/Locales/de.lproj/Localizable.strings
Kickstarter-iOS/Locales/es.lproj/Localizable.strings
Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
Library/Strings.swift
Library/ViewModels/ThanksViewModel.swift
Library/ViewModels/ThanksViewModelTests.swift

Adds new copy to the thank you page for post-campaign pledges.

MBL-1211: Add new thank-you page copy for post-campaign pledges

---

Library/OAuth.swift

Add an analytics event to the OAuth login workflow.
We want to be able to track some basic health metrics for logins; unfortunately this is hard because now most of the relevant events are logged _in the webview_ and not via the app. This adds back one of the missing events so we can hopefully get some statistics.

Add tracking event for logins/signups that happen via OAuth

---

Kickstarter-iOS/Features/LoginTout/Controller/LoginToutViewController.swift
Library/OAuth.swift
Library/OAuthTests.swift

Check if redirect was canceled.
Otherwise, if the user cancels somewhere inside the webview, we would show an error message, which looks a little silly.
https://github.com/kickstarter/ios-oss/assets/146007185/2a073c11-be58-4217-9385-f29c608d19b6

MBL-1268: Check for 'canceled' param in login redirect

---

Kickstarter-iOS/Features/ConfirmDetails/Controllers/ConfirmDetailsViewController.swift
Kickstarter-iOS/Features/RewardAddOnSelection/Controller/RewardAddOnSelectionViewController.swift
Kickstarter-iOS/Features/RewardsCollection/Controller/RewardsCollectionViewController.swift
Kickstarter.xcodeproj/project.pbxproj
Library/ViewModels/ConfirmDetailsViewModel.swift
Library/ViewModels/ConfirmDetailsViewModelTests.swift

Part 1 in the breakdown of adding a new [Confirm Details Screen](https://www.figma.com/file/sFfDKxlJ2tiuq1xgIsaoiI/Late-Campaign-Backings?type=design&node-id=73-5208&mode=design&t=30TTqFlNfFrutqCM-0)
When a user selects an option in the rewards screen, navigate to the new screen. 
- To keep these PRs small, the new view controller, right now, only displays the shipping location selector and pledge/bonus steppers. See the [designs](https://www.figma.com/file/sFfDKxlJ2tiuq1xgIsaoiI/Late-Campaign-Backings?type=design&node-id=73-5038&mode=design&t=30TTqFlNfFrutqCM-0) for reference.
This screen will allow backers to confirm their pledge info before reaching the final checkout screen. This allows us to call PCP validation mutations before creating stipe intents and initializing the payment …

[MBL-1208] Part 1: Initial ConfirmDetailsViewController | Shipping Location + Pledge/Bonus Steppers

---

KsApi/GraphAPI.swift
KsApi/fragments/CreditCardFragment.graphql
KsApi/fragments/UserStoredCardsFragment.graphql
KsApi/models/DeletePaymentMethodEnvelopeTests.swift
KsApi/models/graphql/GraphUserTests.swift
KsApi/models/graphql/UserCreditCardsTests.swift
KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
KsApi/models/graphql/adapters/UserCreditCards+UserFragmentTests.swift
KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelopeTemplates.swift
KsApi/mutations/templates/fragment/CommentFragmentTemplate.swift
KsApi/mutations/templates/fragment/UserFragmentTemplate.swift
KsApi/mutations/templates/mutation/CreatePaymentSourceMutationTemplate.swift
KsApi/mutations/templates/mutation/DeletePaymentSourceMutationTemplate.swift
KsApi/mutations/templates/query/FetchAddOnsQueryTemplate.swift
KsApi/mutations/templates/query/FetchProjectFriendsQueryTemplate.swift
KsApi/mutations/templates/query/FetchUserBackingsQueryTemplate.swift

Add `stripeCardId` to `UserStoredCardsFragment`
From the ticket:
> When we end up calling Stripe.confirmPayment to process late pledges, we need to pass in a [paymentMethodId](https://stripe.dev/stripe-ios/stripe/documentation/stripe/stppaymentintentparams/paymentmethodid). This is accessible to us via the stripeCardId field that we can get in the UserStoredCardsFragment.
For the example IDs in all the templates in the tests, I used test cards I had on staging and pulled their IDs from GraphQL.

MBL-1226: Add stripeCardId to UserStoredCardsFragment and CreditCardFragment

---

Kickstarter-iOS/Features/LoginTout/Controller/LoginToutViewController.swift
Kickstarter-iOS/Features/LoginTout/Controller/LoginToutViewControllerTests.swift
Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
Library/ViewModels/LoginToutViewModel.swift
Library/ViewModels/LoginToutViewModelTests.swift

1. Make the old login, old sign up, and new OAuth "signup or login" buttons reactive.
2. Make the default value of the `featureLoginWithOAuthEnabled` true.
1. One copy of our login screen is created as a root view of the app - in the Profile tab in the tab bar. This copy of the screen was always getting the _first_ (ie cached or default value) of `featureLoginWithOAuthEnabled()`. This means it was never updating, even after new values of the OAuth feature flag loaded.  Fixing this bug ensures we can correctly use the feature flag for OAuth, in case we need to ramp down.
2. If the remote config hasn't loaded yet, we want to show the new flow, not the old flow.

Fix regressions found in the login with OAuth flow

---

Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
Kickstarter-iOS/Locales/de.lproj/Localizable.strings
Kickstarter-iOS/Locales/es.lproj/Localizable.strings
Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
Library/PKPaymentRequest+Helpers.swift
Library/PKPaymentRequestHelpersTests.swift
Library/Strings.swift

Update the payment total string in ApplePay for post campaign pledges.
It says "Pay Kickstarter (if funded)" by default. For PCP, it can just say "Pay Kickstarter".

MBL-1181: Update ApplePay payment total string for post campaign pledges

---

Kickstarter-iOS/AppDelegate.swift

Add a 0.5 second delay before presenting our push notification permission dialog.
When you sign in with OAuth, this permission dialog was showing up only rarely. I dug into the code and found that we were calling everything correctly, but the popup was disappearing, somehow.
My best guess is that something internal is dismissing both the web authentication screen and, since it happens at the same time, the push notification dialog. Adding a short delay before presenting the push notification dialog solves this problem, and doesn't feel any different as a user.
https://github.com/kickstarter/ios-oss/assets/146007185/82705da9-2ac1-4010-94ef-b31c6065266b

Add short delay before presenting push notification dialog

---

Kickstarter-iOS/Features/ReportProject/ReportProjectFormView.swift
Kickstarter-iOS/Features/ReportProject/ReportProjectInfoView.swift
KsApi/GraphAPI.swift
KsApi/GraphQLFiles.xcfilelist
KsApi/graphql-schema.json
KsApi/models/graphql/adapters/GraphAPI.CreateFlaggingInput+CreateFlaggingInputTests.swift
KsApi/mutations/inputs/CreateFlaggingInput.swift
KsApi/mutations/inputs/CreateFlaggingInputTests.swift
Library/ReportProjectInfoListItem.swift
Library/ViewModels/ReportProjectFormViewModel.swift
Library/ViewModels/ReportProjectFormViewModelTests.swift
bin/find-graphql-files.sh

* Add graphql-schema.json to dependency list for Apollo update script
* Change type of CreateFlaggingInput from GraphAPI.FlaggingKind to GraphAPI.NonDeprecatedFlaggingKind
Ingerid encountered this issue in a CircleCI build. Looks like we were running the Apollo update script on Circle, and it was making changes to `GraphAPI.swift` which broke her build. This fixes both the change to the schema, as well as makes sure that future updates to the schema will correctly cause a re-run of the Apollo build script.

Fix CircleCI error caused by GraphQL change to GraphAPI.FlaggingKind

---

Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PostCampaignPledgeRewardsSummaryViewController.swift
Library/ViewModels/ConfirmDetailsViewModel.swift

When pledging with no reward, `CreateCheckout` fails
There is technically a reward ID that is sent in this case that the backend won't recognize
When no rewards are selected set rewardIDs to an empty array. The backend expects this.

[NO TICKET] Create Checkout Fails When Pledging With No Reward

---

Kickstarter.xcodeproj/project.pbxproj
Library/ViewModels/PaymentSourceSelected.swift
Library/ViewModels/PledgePaymentMethodsViewModel.swift
Library/ViewModels/PledgePaymentMethodsViewModelTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

Refactor `PaymentSourceSelected` to be an `enum`, instead of a `struct`.
For `MBL-1123`, I'm adding another type of payment source to `PledgeViewModel`. We start to create `PaymentIntent` secrets, which are a separate kind of client secret from our existing `SetupIntent` secrets. 
Before, the different between payment types was modeled by storing the payment source ID and a boolean, which flagged whether or not the string was a stripe token or a Kickstarter ID. 
After, this is modeled as an enum, so that it should be much clearer what kind of payment source we're passing around the codebase. As a bonus, this actually deleted a few lines of redundant code, since it makes the plumbing a little simpler.
When I finish this ticket, we'll have an enum like this:
```
public enum …
```

MBL-1123: Refactor PaymentSourceSelected to be an enum

---

Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewControllerTests.swift
Kickstarter-iOS/Features/PledgeView/Controllers/PledgeViewController.swift
Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift
Library/ViewModels/PledgePaymentMethodsViewModel.swift
Library/ViewModels/PostCampaignCheckoutViewModel.swift

Make "continue" button launch the login flow. Payment methods sheet should be hidden in logged out case and show up again once the user is logged in.
This makes the checkout VC a delegate of the pledge CTA and implements methods other than those corresponding to the "pledge" and "apple pay" buttons.
Note: This still hasn't added the extra warning to the pledge CTA. Since that can probably be added without touching the checkout VC, I'm going to do that in another pr to minimize merge conflicts.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1210)

[MBL-1210] Fix logged out and login flow for post campaign checkout

---

Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
Kickstarter-iOS/Features/PledgePaymentMethods/Views/Cells/PledgePaymentMethodCell.swift
Library/ViewModels/PledgePaymentMethodCellViewModel.swift
Library/ViewModels/PledgePaymentMethodCellViewModelTests.swift
Library/ViewModels/PledgePaymentMethodsViewModel.swift
Library/ViewModels/PledgePaymentMethodsViewModelTests.swift

Refactor `PledgePaymentMethodsViewModel` to use `PaymentSourceSelected`, instead of managing separate values for a `selectedSetupIntent` and a `selectedCreditCard`. 
For MBL-1123, I need to pass the final selected value (whether it's from a `SetupIntent`, a `PaymentIntent` or an existing `CreditCard`) back to the delegate of the `PledgePaymentMethodsViewController`. This refactor makes that significantly easier - we'll be able to keep the declarative nature of the screen, but be explicit about what kind of payment method is selected.
The alternative would be to keep some kind of state in the `PledgePaymentMethodsViewController` that indicated whether or not it should use a `SetupIntent` or a `PaymentIntent`, and that felt messy in a different way.

MBL-1123: Refactor PledgePaymentMethodsViewModel to use PaymentSourceSelected

---

Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
Library/ViewModels/PaymentSourceSelected.swift
Library/ViewModels/PledgePaymentMethodsViewModel.swift
Library/ViewModels/PledgePaymentMethodsViewModelTests.swift
Library/ViewModels/PledgeViewModel.swift
Library/ViewModels/PledgeViewModelTests.swift

Rename `PaymentSourceSelected.paymentSourceId` to `.savedCreditCard`
This makes it slightly clearer what is actually being saved in the enum.

Rename PaymentSourceSelected.paymentSourceId to .savedCreditCard

---

Kickstarter-iOS/Features/PaymentMethods/Controller/PaymentMethodSettingsViewController.swift
Kickstarter.xcodeproj/project.pbxproj
Library/ViewModels/PaymentMethodSettingsViewModel.swift
Library/ViewModels/PaymentMethodSettingsViewModelTests.swift

Rename `PaymentMethodsViewModel` to `PaymentMethodSettingsViewModel`.
This clarifies that `PaymentMethodSettingsViewModel` belongs to `PaymentMethodSettingsViewController` and is distinct from the Pledge flow.

Rename PaymentMethodsViewModel to PaymentMethodSettingsViewModel

---

Kickstarter-iOS/Features/PledgeView/Views/PledgeViewCTAContainerView.swift
Kickstarter-iOS/Features/RewardAddOnSelection/Controller/RewardAddOnSelectionViewController.swift
Kickstarter-iOS/Features/RewardsCollection/Controller/RewardsCollectionViewController.swift
Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
Kickstarter-iOS/Locales/de.lproj/Localizable.strings
Kickstarter-iOS/Locales/es.lproj/Localizable.strings
Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
Library/PledgeViewContext.swift
Library/Strings.swift
Library/Tracking/TrackingHelpers.swift
Library/ViewModels/ConfirmDetailsViewModel.swift
Library/ViewModels/PledgeViewCTAContainerViewModel.swift
Library/ViewModels/RewardsCollectionViewModel.swift

Update pledge CTA by adding a separate context for late pledges and showing the "pledge immediately" string in a late pledge context.
Note: the bolding is currently a little off. I have a pr that fixes that submitted but not yet in staging, so this will be fixed the next time we make strings.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1288)
| Logged out | Logged in (new string) |
| --- | --- |
| ![image](https://github.com/kickstarter/ios-oss/assets/6799207/7e0a3beb-b8f3-4242-8f4a-1cb43c0acbd6) | ![image](https://github.com/kickstarter/ios-oss/assets/6799207/036ffd21-041e-42af-917f-30e6bff2c2a5) |

[MBL-1288] Update pledge CTA

---

Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift
Kickstarter.xcodeproj/project.pbxproj
Library/PKPaymentRequest+Helpers.swift
Library/PKPaymentRequestHelpersTests.swift
Library/ViewModels/PostCampaignCheckoutViewModel.swift
Library/ViewModels/PostCampaignCheckoutViewModelTests.swift

Add ApplePay into post-campaign pledge controller
This is another piece we needed before we can set up the final checkout call - we'll need ApplePay parameters (i.e. the token) to complete the payment.
Example with a plain pledge:
Example with shipping and a reward:

MBL-1285: Add ApplePay into post-campaign pledge controller

---

Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift
KsApi/models/graphql/adapters/GraphAPI.ApplePay+ApplePayParams.swift
Library/ViewModels/PostCampaignCheckoutViewModel.swift

Implement `CompleteOnSessionCheckoutMutation` for new and existing cards in the late-pledge flow
This is the last mutation call required to actually complete the pledge! 
This PR is _intentionally_ incomplete, to keep the changes a bit more manageable. Follow-up PRs will do the following:
- Implement `CompleteOnSessionCheckoutMutation` for ApplePay
- Route successful transactions to the Thanks page
- Route unsuccessful transactions back to the Select Reward page

MBL-1285: Implement CompleteOnSessionCheckoutMutation for new and existing cards

---

Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift
Library/ViewModels/PostCampaignCheckoutViewModel.swift

Navigates To Thank You Page On Successful Late Pledge
So we can formally thank users for their pledge, show them verification, and suggest other projects to them
Using data we already have in the PostCampaignCheckoutViewModel, gather the data needed for the Thanks Page.
I can't remove backings rn and only have 2 accounts that I used to test already so I can't screen record this.

Navigate To Thank You Page On Successful Late Pledge

---

Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift
KsApi/models/graphql/adapters/GraphAPI.ApplePay+ApplePayParams.swift
Library/PKPaymentRequestHelpersTests.swift
Library/ViewModels/PostCampaignCheckoutViewModel.swift
Library/ViewModels/PostCampaignCheckoutViewModelTests.swift

MBL-1285: Integrate ApplePay into Post-Campaign Checkout, using `STPApplePayContext`.
This is the last remaining piece to complete the "happy path" for late-pledge payments.
I chose to swap from directly using `PKPaymentAuthorizationViewController` to `STPApplePayContext`, which is a Stripe wrapper around `PKPaymentAuthorizationViewController`. The advantage of `STPApplePayContext` is that it handles creating the payment method, associating it with the payment intent, _and_ confirming the payment, saving us from making extra calls to Stripe and adding extra complexity to our view model. See [their documentation here](https://docs.stripe.com/apple-pay).

MBL-1285: Integrate ApplePay into Post-Campaign Checkout

---

Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift

Revert banner changes as we want to start the checkout flow over from the beginning if checkout goes wrong, and the confirm checkout VC is designed to create the checkout id.
Hopefully we'll restructure this for a better user experience in the future, but for now, this was the flow that eng across platforms decided on.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1305)

[MBL-1305] Revert banner changes

---

Kickstarter-iOS/Features/RewardAddOnSelection/Controller/RewardAddOnSelectionViewControllerTests.swift
KsApi/GraphAPI.swift
KsApi/fragments/RewardFragment.graphql
KsApi/models/Reward.swift
KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
KsApi/models/graphql/adapters/Reward+RewardFragment.swift
KsApi/models/graphql/adapters/Reward+RewardFragmentTests.swift
KsApi/models/lenses/RewardLenses.swift
KsApi/models/templates/RewardTemplates.swift
KsApi/mutations/templates/query/FetchAddOnsQueryTemplate.swift
KsApi/mutations/templates/query/FetchProjectRewardsByIdQueryTemplate.swift
Library/ViewModels/RewardAddOnSelectionViewModel.swift
Library/ViewModels/RewardAddOnSelectionViewModelTests.swift

Use the GraphQL field `isAvailable` to filter visible add-ons
Our existing implementation did not take late pledges into account, so it was filtering out add-ons that were actually still available for late pledges. I spoke with @zan-rosenthal and apparently the gold-standard solution is to use the `available` field from GraphQL.
Most of this PR is updating plumbing to get `available` into `Reward`.

MBL-1316: Use isAvailable to filter visible add-ons

---

Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift
Library/ViewModels/PostCampaignCheckoutViewModel.swift
Library/ViewModels/PostCampaignCheckoutViewModelTests.swift

Show processing view while payment is processing. This prevents further user interaction until it's dismissed.
Note: It's very important that we make sure that regardless of how checkout goes/where it fails, the processing view will get dismissed. It will lock the app otherwise. The original pledge VC ties the processing view to specific API calls, but we can't do that for post campaign pledges, since we require multiple different API calls to finish the payment flow. Please help me double check that there aren't edge cases that would leave the processing screen up indefinitely!
Note: The processing screen does hide immediately once apple pay is dismissed - I have no idea why the gif is showing it weird.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1307)
| Pledge flow | Apple pay …

[MBL-1307] Show processing view while payment is processing

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphQLSelectionSet+String.swift
Library/ViewModels/PostCampaignCheckoutViewModelTests.swift

Add a convenience initializer `init(jsonString:)` to `GraphQLSelectionSet`
This makes it easier to create new GraphQL Data objects in test environments.

Add init(jsonString:) to GraphQLSelectionSet

---

Library/ViewModels/PostCampaignCheckoutViewModel.swift
Library/ViewModels/PostCampaignCheckoutViewModelTests.swift

Pledge Button enabled state needs to rely on successfully creating a new payment intent for pre-existing cards or when a new card is successfully created and selected.
Creates separate inputs for existing and new cards allowing the pledge button to respond to either scenario mentioned above.

[MBL-1328] Update Pledge Button Enabled Signals

---

Library/ViewModels/PostCampaignCheckoutViewModelTests.swift

Adding more test coverage around some outputs
safety is not guaranteed

[MBL-1352] Backfill Tests In PostCampaignViewModel

---

Library/ViewModels/PostCampaignCheckoutViewModel.swift
Library/ViewModels/PostCampaignCheckoutViewModelTests.swift

Re-fetch stored cards after login.
If you weren't logged in the first time you accessed the late pledge page, we never fetched your stored cards. This means that, when you tapped on submit, one of the prerequisites was missing and your pledge would never complete.
I created [a ticket ](https://kickstarter.atlassian.net/browse/MBL-1347) for us to resolve the 500, which is due to where we call Checkout vs. where we call Login.

MBL-1338: Re-fetch stored cards after login

---

Library/ViewModels/ConfirmDetailsViewModel.swift

Send all copies of each reward to the backend. Note that this doesn't fix the bonus support being weird, but that matches a web bug that backend/web people are already working on.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1339)
| --- | --- |
| ![Screenshot 2024-04-04 at 2 29 58 PM](https://github.com/kickstarter/ios-oss/assets/6799207/4e504de7-9f11-422a-9959-5441cd09836e) | ![Screenshot 2024-04-04 at 2 32 31 PM](https://github.com/kickstarter/ios-oss/assets/6799207/e95d1421-95ce-495c-885a-1b4561085341) |
| ![Screenshot 2024-04-04 at 2 30 06 PM](https://github.com/kickstarter/ios-oss/assets/6799207/1d17c891-e4ab-4356-9570-491db3158e41) | ![Screenshot 2024-04-04 at 2 32 40 PM](https://github.com/kickstarter/ios-oss/assets/6799207/c241b058-5aa0-4f4e-9c52-33467 …

[MBL-1339] Include multiple copies of add-ons if selected

---

Kickstarter-iOS/Features/Discovery/Views/Cells/DiscoveryPostcardCell.swift
Kickstarter-iOS/Features/Discovery/Views/Cells/DiscoveryProjectCardCell.swift
Kickstarter-iOS/Features/ProjectPage/Views/ProjectPageNavigationBarView.swift
Library/Styles/ButtonStyles.swift
Library/Styles/DiscoveryStyles.swift

Neither Scott nor I have been able to reproduce this crash. However, according to the crash logs, it's happening when the `DiscoveryPostcardCell`'s save button's accessibility label is set using prelude. I'm not sure if this change will actually fix the crash, but hopefully if it doesn't, it'll get us more info.
Note: if prelude accessibility labels + iPads + iOS 17.4 is actually the problem, we should start seeing this crash other places in our codebase once this version of it is fixed. If that happens, we'll at least know how to fix it going forward.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1315)

[MBL-1315] Move save button styling off prelude

---

Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PostCampaignPledgeRewardsSummaryTotalViewController.swift
Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PostCampaignPledgeRewardsSummaryViewController.swift

Call `bindStyles` in `viewDidLoad`. We usually swizzle view controllers to call `bindStyles` on `viewWillAppear` and `traitCollectionDidChange`, but for some reason, on iOS 16, neither of these trigger `bindStyles` for this class. I think embedding a view controller's view in a different view controller is preventing `viewWillAppear` from triggering it, but I'm not sure why `traitCollectionDidChange` calls `bindStyles` on iOS 17 but not on iOS 16. Regardless of why, calling `bindStyles` in `viewDidLoad` fixes the problem and seems significantly safer.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1334)
| --- | --- |
| ![image](https://github.com/kickstarter/ios-oss/assets/6799207/6b865a36-3a81-43e3-aeb2-b6986f54c44a) | …

[MBL-1334] Bind styles when PostCampaignPledgeRewardsSummaryTotalViewController loads

---

Kickstarter-iOS/Features/PaymentMethods/Controller/PaymentMethodSettingsViewController.swift
Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift

We currently show a "Something went wrong" error banner if a user decides to cancel adding a card through the 3DS prompt. This removes that banner.
Note: "Something went wrong" banner still shows as part of the payment flow if a user uses a saved 3DS card for checkout and cancels there. 
[Jira](https://kickstarter.atlassian.net/browse/MBL-1362)
| --- | --- |
| ![Simulator Screen Recording - iPhone 15 Pro Max - 2024-04-11 at 14 04 13](https://github.com/kickstarter/ios-oss/assets/6799207/efeb92da-4a3c-4f05-941e-8679e05c58b1) | ![Simulator Screen Recording - iPhone 15 Pro Max - 2024-04-11 at 14 11 51](https://github.com/kickstarter/ios-oss/assets/6799207/6a16e510-59d1-4a19-850f-bbc24638d89a) |

[MBL-1362] If user cancels adding new card, don't show error banner

---

Library/ViewModels/PledgePaymentMethodsViewModelTests.swift

Add additional tests to `PledgePaymentMethodsViewModel`.
I added quite a bit of new code to that view model to handle `PaymentIntent`s instead of `SetupIntent`s, these tests exercise those pathways. They're largely copied versions of existing tests.

MBL-1290: Add tests for PaymentIntent pathway in PledgePaymentMethodsViewModel

---

Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift
Library/ViewModels/PostCampaignCheckoutViewModel.swift

Do not create a Stripe token after `ApplePayContext` creates a Stripe PaymentMethod.
In production, this causes Stripe to return an error in the `createToken` endpoint, which breaks our ApplePay flow. Instead, we will ignore the `token` field and `applePayParams` field in our mutation, treating an ApplePay transaction like a regular credit card transaction.

MBL-1372: Don't call createToken after ApplePayContext completes

---

Library/ViewModels/TwoFactorViewModelTests.swift

Remove example data that includes a real-looking Kickstarter address and password.
Reported as possible security leak.

MBL-1375: Change example data in TwoFactorViewModelTests

---

Kickstarter-iOS/Features/BackerDashboardProjects/Controller/BackerDashboardProjectsViewController.swift
Library/ViewModels/BackerDashboardProjectsViewModel.swift
Library/ViewModels/BackerDashboardProjectsViewModelTests.swift

Fix a missing loading spinner on `BackerDashboardProjectsViewController`.
I noticed this while fixing other bugs - the spinner was frequently missing, and it made the loading feel much slower than it effectively was.
- Change `viewWillAppear` to `viewDidAppear` to fix a warning about using the refresh controller while off screen
- Add extra `endRefreshing()` call to `viewDidDisappear`, per a suggestion from StackOverflow. Seems like the refresh controller is strangely sensitive to view lifecycle methods, and this fixes the problem.

Fix missing spinner on BackerDashboardProjectsViewController

---

Kickstarter.xcodeproj/project.pbxproj
Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Updates min version to 7.10.0 up to next major version 7.11.0 (Latest).
[Main reference for what's going on](https://github.com/kickstarter/ios-oss/pull/2045)
But, Apple requires us to give reasons for using certain APIs. Reasons that need to be added to a Privacy Manifest file (added in that PR ☝️ )
One of the APIs that our app is missing a reason for is `NSPrivacyAccessedAPICategoryFileTimestamp`. 
We aren't actually using this API internally, Kingfisher is.
Kingfisher added privacy support for Apple's new requirement in 7.10.0. So, by updating the version we're using we should now be meeting the requirement.
- I'm not certain that we don't still need to include a reason for how the 3rd party is using this API as well, but we've reached out to apple support for clarification. For now …

[MBL-1358] Update Kingfisher

---

KsApi/GraphAPI.swift
KsApi/models/graphql/adapters/FetchProjectsEnvelope+FetchBackerProjectsQueryData.swift
KsApi/models/graphql/adapters/FetchProjectsEnvelope+FetchBackerProjectsQueryDataTests.swift
KsApi/queries/FetchMySavedProjectsQuery.graphql
KsApi/queries/templates/FetchMySavedProjectsQuery.json
KsApi/queries/templates/FetchMySavedProjectsQueryRequestForTests.graphql_test

Use `projects` GraphQL search query to fetch saved projects, instead of using `me { savedProjects } `.
The `savedProjects` attached to the `me` query uses a specific, hardcoded sort methodology, which doesn't work for the apps. We need the saved projects to be sorted by end date (descending).
This is a slightly imperfect solution. The `projects` search query doesn't return buried projects, which would otherwise show up in your saved projects. However, it _does_ show late pledge projects, in the correct order, which was the primary motivation for swapping this endpoint from V1 to GraphQL. Since the old V1 endpoint _also_ didn't show buried projects, this is not a regression.

MBL-1381: Use Projects query instead of UserSavedProjectsConnection for saved projects

---

Kickstarter-iOS/Features/Search/Controller/SearchViewControllerTests.swift
Library/ViewModels/BackerDashboardProjectCellViewModel.swift
Library/ViewModels/BackerDashboardProjectCellViewModelTests.swift

Check both `displayPrelaunch` and `prelaunchActivated` flags on `Project` before showing `"Coming Soon"` in the project status.
When I swapped this page to use GraphQL, it started returning values in `displayPrelaunch` and `prelaunchActivated` which were formerly `nil`. This caused the status badges to be incorrect.
On a little digging, the existing logic to check for prelaunch status didn't make sense:
- `prelaunchActivated` refers to whether the prelaunch page is available 
- `displayPrelaunch` is true if the project has not actually launched yet 
I surmised that checking for both, not either, is the correct behavior.
I kept the behavior that checks the launch date - turns out that is used for detecting prelaunch projects fetched via `/v1/discover` i.e. search.
I checked this by …

MBL-1371: Only show 'Coming Soon' if project is actually pre-launch

---

Kickstarter-iOS/PrivacyInfo.xcprivacy

Removes an extra, empty, item key from the new privacy manifest.

[NO TICKET] Privacy Manifest Fix

---

Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
Kickstarter.xcodeproj/project.pbxproj
Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Library/KSRStripeLink.swift
Library/KSRStripeLinkTests.swift
Library/TestHelpers/Stripe+PaymentMethod.swift
Library/ViewModels/PaymentMethodSettingsViewModel.swift
Library/ViewModels/PledgePaymentMethodsViewModel.swift

Implement Stripe Link for iOS.
Stripe Link allows backers to store their card information with Stripe, and then auto-complete it when they use the Stripe payment sheet in Kickstarter. We're implementing this because it's a nicer user experience in checkout.
When Stripe Link returns, it gives us payment display information specific to Stripe Link - i.e. it was giving us a the Link icon and the label "Stripe Link". 
To work around this, Stripe suggested we fetch the underlying payment method associated with the link, which allows us to grab the last four digits of the card and its card image. This makes Stripe Link function the way a manually added card does, and looks better in our UI.
https://github.com/kickstarter/ios-oss/assets/146007185/5c1f5b79-22ec-405f-9b23-0ddb8cef99bc

MBL-1390: Add Stripe Link

---

Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PostCampaignPledgeRewardsSummaryViewController.swift
Kickstarter-iOS/Features/PledgePaymentMethods/Views/Cells/PostCampaignPledgeRewardsSummaryCell.swift

In the summary view for late pledge confirmation,
- Fix missing price information when the title ran over
- Fix multi-line title tables 
- Clean up some Prelude
Long add-on names would break the summary view:
Here's the same project, fixed:
Here's an example of it working, with a very long hard-coded string:
As well as working with the largest font size:

MBL-1374: Handle long add-on names on late pledge confirmation page

---

Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Library/TestHelpers/Stripe+PaymentMethod.swift
Library/ViewModels/PledgePaymentMethodsViewModel.swift

Turn on Stripe Link.
This is _much_ simpler now that the payments sheet has been refactored, and since we also decided to nix feature flags for Stripe Link! All we need to do is upgrade the Stripe SDK and pass in the user's e-mail address.

MBL-1390: Re-enable Stripe Link

---

Library/ViewModels/PaymentMethodSettingsViewModel.swift
Library/ViewModels/PledgePaymentMethodsViewModel.swift

Add e-mail address to log in to Stripe Link from the payment settings page.
We made the decision that, since we can't turn Stripe Link off in the app at all, we will fully support it in both the Pledge flow, and in Account Settings. This is a slight divergence from the web, which doesn't show Link in Account Settings.
Without this change, Stripe Link is visible, but does not automatically log in the user if they have an existing Stripe Link account.

MBL-1390: Log in to Stripe Link on Payment settings page, too

---

Library/ViewModels/PledgePaymentMethodsViewModel.swift
Library/ViewModels/PledgePaymentMethodsViewModelTests.swift

Don't change the selection on the Payments sheet if the newly added card is disabled.
Now that we're saving cards immediately, it's possible to add a card that's not available for the current project. The previous logic would try and select the card, even if it was unavailable; this short-circuits that edge case. Fixing this prevents a bunch of unfortunate behavior as documented in the ticket.

MBL-1550: Don't change selected card when unavailable card is added to payment methods

---

Kickstarter-iOS/AppDelegateViewModel.swift
Kickstarter-iOS/Features/Activities/Controller/ActivitiesViewController.swift
Kickstarter-iOS/Features/SurveyResponse/Controller/SurveyResponseViewController.swift
Library/Navigation.swift
Library/NavigationTests.swift
Library/ViewModels/SurveyResponseViewModel.swift
Library/ViewModels/SurveyResponseViewModelTests.swift

Configure survey webview using a url string instead of an entire SurveyResponse object. This allows us to open deeplinks to new surveys as well as old surveys.
I'm reconstructing the url here using the current host and the path from the deeplink; I thought this had a good balance of being clear as well as definitely working. (I often do `ksr:// `deeplinks for testing, for example, and these would not be displayable in the webview directly if we were just using `.absoluteString` on the raw deeplink.)
[Jira](https://kickstarter.atlassian.net/browse/MBL-1553)
Note: This pr does not fix push notifications, which will be fixed in a later pr.
Once push notifications depend on the url as well, I'll follow up to see if we can just delete the user survey path.

[MBL-1553] Configure survey webview with url instead of SurveyResponse object

---

Kickstarter-iOS/AppDelegateViewModel.swift

Make sure the survey view controller is created on the main thread. When I added the url support, I accidentally skipped this step when we created the view controller directly from the url. I'm not sure why this crash didn't show up in the simulator 🤷

[MBL-1553] Make sure surveyVC is created on the main thread

---

Library/ViewModels/SurveyResponseViewModel.swift

Allow js requests to render in our survey webview. This is needed in order for users to be able to add new addresses.
| Before 🐛 | After 🦋 | Entire flow |
| ![Simulator Screen Recording - iPhone 15 Pro Max - 2024-06-25 at 12 34 21](https://github.com/kickstarter/ios-oss/assets/6799207/f521ac56-9483-4c4e-8546-1575d59309a2) | ![Simulator Screen Recording - iPhone 15 Pro Max - 2024-06-25 at 12 30 28](https://github.com/kickstarter/ios-oss/assets/6799207/b73088b8-e877-4b8e-b578-63a1f8a39847) | ![Simulator Screen Recording - iPhone 15 Pro Max - 2024-06-25 at 12 36 13](https://github.com/kickstarter/ios-oss/assets/6799207/f59b85c0-c3df-4753-97c8-94f2b0e1027e)|

Allow js requests from stripe

---

Kickstarter-iOS/AppDelegateViewModel.swift
Kickstarter-iOS/AppDelegateViewModelTests.swift
KsApi/models/PushEnvelope.swift
KsApi/models/lenses/PushEnvelopeLenses.swift

Allow new surveys to be opened from push notifications by using the url path provided instead of relying on the survey response id.
New surveys don't have a unique id.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1554)
No screen recording of this because push notifications are a pain to work with, but I've verified that it works for new surveys and that push notification for old surveys have the exact same data format.

[MBL-1554] Fix survey push notifications for new surveys

---

Kickstarter-iOS/Features/MessageBanner/Controller/MessageBannerViewController.swift
Kickstarter-iOS/Features/Messages/Controller/MessagesViewController.swift
Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
Kickstarter-iOS/Features/PledgeView/Controllers/PledgeViewController.swift
Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift
Kickstarter-iOS/Library/PledgeViewControllerMessageDisplaying.swift

Don't dismiss the post campaign VC if there's an error caused by trying to add a new card.
Note: There are other categories of errors that also don't need to dismiss the VC (for example, if a user fails to authenticate a 3DS card). However, because we're currently planning to combine our checkout flows and get rid of the "confirm details" page, I didn't think it was worth spending a lot of extra time on this now. 
Needing to restart checkout in these cases is a little annoying.
I refactored the messageBannerView to optionally be in charge of dismissing the vc. That way, we can decide if the error should lead to dismissing the VC when a specific error is displayed to the user.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1422)
| --- | --- |
| ![Simulator …

[MBL-1422] Handle errors without always dismissing

---

KsApi/GraphAPI.swift
KsApi/graphql-schema.json
KsApi/models/graphql/adapters/ShippingRule+ShippingRuleFragment.swift

Regenerate graphql-schema and update the shipping rule adaptor since a [recent change](https://kickstarter.slack.com/archives/C411RRLCQ/p1720032215685699) broke our tests (only when run on the main branch).
Note: I'm not that comfortable with graphQL changes yet so I wasn't sure if the change itself could cause problems for us in prod. I did check on our shipping rule in prod and in staging and I didn't see any errors. It looks like the change is backwards compatible in the app.
[circleCI error](https://app.circleci.com/pipelines/github/kickstarter/ios-oss/5441/workflows/001889aa-cc3e-4293-a742-519f8ddd20da/jobs/56639)

Regenerate graphql-schema and update shippingRule adapter

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphAPI.swift
KsApi/graphql-schema.json
KsApi/models/CreateCheckoutEnvelope.swift
KsApi/models/CreateCheckoutEnvelopeTests.swift
KsApi/mutations/CreateCheckout.graphql
KsApi/mutations/CreateCheckoutMutation.swift
KsApi/mutations/inputs/CreatePaymentIntentInput.swift
KsApi/mutations/inputs/CreatePaymentIntentInputTests.swift
Library/StripeIntentService.swift
Library/TestHelpers/MockStripeIntentService.swift
Library/ViewModels/ConfirmDetailsViewModel.swift
Library/ViewModels/ConfirmDetailsViewModelTests.swift
Library/ViewModels/PostCampaignCheckoutViewModel.swift
Library/ViewModels/PostCampaignCheckoutViewModelTests.swift

Exposes `backingId` in our `CreateCheckout` GraphQL Mutation Response in order to pass it to `CreatePaymentIntent`.
As a backer, if my late pledge checkout errors, the payment should be reversed or the checkout rescued asynchronously (handled by Rosie (backend) if `backingId` is present)
- Expose `backingId` in `CreateCheckout.graphql`
- Pass newly exposed `backingId` to `CreatePaymentIntent` GraphQl call
No visible changes

[MBL-1616] Send backingId to CreatePaymentIntent for late pledges

---

Library/ViewModels/ManagePledgeViewModel.swift

Removes 'Update Pledge' From Manage Pledge Options Menu
Users will be able to manage and make changes to their pledge in the pledge redemption flow now, rendering this menu option redundant. 
Taking this opportunity to clean it up.
When the menu options get collected in `ManagePledgeViewModel.actionSheetMenuOptionsFor(...)` we can filter out the `.updatePledge` option if the feature flag is on.
I added a `TODO` to remind us that we can remove this option from the options struct when the feature has completed and we start cleaning up the feature flag.
|  flag **off** |  flag **on** |
| --- | --- |
| ![old](https://github.com/user-attachments/assets/5e1cf048-16e6-4eb4-94f8-68a2e50dc128) | ![new](https://github.com/user-attachments/assets/b229a911-20c9 …

[MBL-1608] Remove 'Update Pledge' From Manage Pledge Options Menu

---

KsApi/GraphAPI.swift
KsApi/fragments/PPOCardFragment.graphql
KsApi/graphql-schema.json

Updates the GraphQL schema, after a recent change removed the `tags` field in favor of the `flags` struct.
Builds are broken because this field existed previously.
Ran `bin/apollo-schema-download.sh` and re-ran the app to trigger the Apollo code gen.
[CircleCI failures](https://app.circleci.com/pipelines/github/kickstarter/ios-oss/5572/workflows/dde34f01-12d2-4f8d-b8ba-4f17044b838b/jobs/57159)
Build should pass.

Update GraphQL schema to use flags for PPO items

---

Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
Library/ViewModels/PledgeShippingLocationViewModel.swift

Makes sure the shimmer view loads while the shipping dropdown fetches it's locations.
Without this the dropdown appears empty and visually stutters once the locations have loaded.
- Update the view model's isLoading property so that it automatically starts loading when the no checkout at shipping feature flag is enabled.
- The current behavior will start loading if the passed in reward has shipping enabled. 
This only applies to the existing flow where the dropdown is on the AddOns screen. 
Not that it's on the Rewards screen the behavior is different in that we aren't passing in a reward.
hard to see the before, but with slower internet it's pretty bad.
| --- | --- |
| ![no-shimmer](https://github.com/user-attachments/assets/34c3cfc5-9544-4076-91d0-50678f2a1408) | …

[NO TICKET] Shipping Dropdown Loading State

---

Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCreator.swift
Kickstarter.xcodeproj/project.pbxproj

This PR implements the project creator view for the card view for pledged projects, as well as the relevant subviews. It adds a view model to cover handling actions like tapping buttons and sending the creator a message.
Connecting to real data will come in a future PR.
Views are implemented as SwiftUI views, broken up into a few pieces, including individual flags, a project details view, a creator summary view, an address summary view, and buttons. Where possible, views used existing styling functions but did not use Prelude.
Snapshot testing is already complete and will be included in the card view PR.
[Figma](https://www.figma.com/design/r0WKSECmMTCJTSKQskt2SQ/Backed-Projects-Dashboard?node-id=722-8194&t=rpm5RzgK15wT9Peu-0)
Should support Dynamic Type and VoiceOver, but that hasn't …

[MBL-1458 pt 3] Add project creator for PPO

---

Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectDetails.swift
Kickstarter.xcodeproj/project.pbxproj

This PR implements the project detail summary view for the card view for pledged projects, as well as the relevant subviews. It adds a view model to cover handling actions like tapping buttons and sending the creator a message.
Connecting to real data will come in a future PR.
Views are implemented as SwiftUI views, broken up into a few pieces, including individual flags, a project details view, a creator summary view, an address summary view, and buttons. Where possible, views used existing styling functions but did not use Prelude.
Snapshot testing is already complete and will be included in the card view PR.
[Figma](https://www.figma.com/design/r0WKSECmMTCJTSKQskt2SQ/Backed-Projects-Dashboard?node-id=722-8194&t=rpm5RzgK15wT9Peu-0)
Should support Dynamic Type and VoiceOver, but that …

[MBL-1458 pt 4] Add project details for PPO

---

Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOAddressSummary.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOCardStyles.swift
Kickstarter.xcodeproj/project.pbxproj

This PR implements the address summary for the card view for pledged projects, as well as the relevant subviews. It adds a view model to cover handling actions like tapping buttons and sending the creator a message.
Connecting to real data will come in a future PR.
Views are implemented as SwiftUI views, broken up into a few pieces, including individual flags, a project details view, a creator summary view, an address summary view, and buttons. Where possible, views used existing styling functions but did not use Prelude.
Snapshot testing is already complete and will be included in the card view PR.
[Figma](https://www.figma.com/design/r0WKSECmMTCJTSKQskt2SQ/Backed-Projects-Dashboard?node-id=722-8194&t=rpm5RzgK15wT9Peu-0)
Should support Dynamic Type and VoiceOver, but that hasn't been …

[MBL-1458 pt 2] Add address summary for PPO

---

Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
Kickstarter-iOS/Features/RewardAddOnSelection/Controller/RewardAddOnSelectionNoShippingViewController.swift
Kickstarter-iOS/Features/RewardAddOnSelection/Controller/RewardAddOnSelectionViewController.swift
Kickstarter-iOS/Features/RewardsCollection/Controller/RewardsCollectionViewController.swift
Kickstarter-iOS/Features/RewardsCollection/Controller/WithShippingRewardsCollectionViewController.swift
Library/ViewModels/RewardAddOnSelectionNoShippingViewModel.swift
Library/ViewModels/WithShippingRewardsCollectionViewModel.swift

Removes Redundant `featureNoShippingAtCheckout` Checks
Also does a quick fix for an issue found in QA for the Stripe Sheet not showing on `NoShippingPledgeViewController`.
The `ProjectPageVIewController` determines whether to start the "No Shipping At Checkout" flow or the current flow in Production. 
We have unnecessary `if featureNoShippingAtCheckout()` conditions in the "No Shipping At Checkout" View Controllers. 
Since they'll never be shown when the flag is disabled, I'm removing them. They should never have been here tbh. 
This all cleanup work. 
Goes through each of these VCs and removes unused code and unnecessary feature flag checks:
- WithShippingRewardsCollectionVC + RewardsCollectionVC
- RewardAddOnSelectionNoShippingVC + RewardAddOnSelectionVC

[MBL-1684] Remove Redundant No Shipping At Checkout Feature Flag Checks

---

Kickstarter.xcodeproj/project.pbxproj
Library/ViewModels/NoShippingConfirmDetailsViewModel.swift
Library/ViewModels/NoShippingConfirmDetailsViewModelTests.swift

Use the bonus amount that's passed in to the confirm details page to initialize the stepper.
Note: This also adds tests for the no shipping confirm details vm, since these were missing. I'm skipping the "continue" button test since I think it's probably related to [MBL-1687](https://kickstarter.atlassian.net/browse/MBL-1687) and should be fixed as part of that work. In order to see changes to the copied test file, review commit by commit.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1681)
| --- | --- |
| ![Simulator Screen Recording - iPhone 15 Pro Max - 2024-09-04 at 12 26 53](https://github.com/user-attachments/assets/7ec9faad-e9f2-422d-97c9-74fd026dffbe) | ![Simulator Screen Recording - iPhone 15 Pro Max - 2024-09-04 at 12 25 …

[MBL-1681] Fix confirm details bonus

---

Library/ViewModels/ManagePledgeViewModelTests.swift
Library/ViewModels/WithShippingRewardsCollectionViewModel.swift

Uses the filtered rewards by location list to scroll to the selected reward via the 'Edit Reward' option in our Manage Pledge flow.
this is the list the app uses when in our No Shipping At Checkout Flow.
Adds the `filteredByLocationRewards` list to the `scrollToBackedRewardIndexPath` signal and chooses the right list to use based on if that list is empty or not.

[MBL-1690] Crash When Selecting 'Edit Reward' Option In Manage Pledge Flow

---

Library/ViewModels/ConfirmDetailsViewModel.swift
Library/ViewModels/NoShippingConfirmDetailsViewModel.swift
Library/ViewModels/NoShippingConfirmDetailsViewModelTests.swift

We accidentally introduced a bug where the late pledge flow can't be completed because the location id isn't correctly transformed to a string. This fixes that bug and the "no shipping" test that I thought might be related that ended up not being related after all.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1687)
| With flag off | With flag on |
| --- | --- |
| ![Simulator Screen Recording - iPhone 15 Plus - 2024-09-05 at 12 59 12](https://github.com/user-attachments/assets/ec882e5b-3380-4c38-9245-2e9e8a98823a) | ![Simulator Screen Recording - iPhone 15 Plus - 2024-09-05 at 13 01 18](https://github.com/user-attachments/assets/7a5fce77-f595-4341-bc7b-e626e07acde9) |

[MBL-1687] Fix continue button on confirm details page not working #2147

---

Library/SharedFunctions.swift
Library/SharedFunctionsTests.swift
Library/ViewModels/NoShippingPledgeViewModel.swift
Library/ViewModels/NoShippingPostCampaignCheckoutViewModel.swift
Library/ViewModels/RewardAddOnCardViewModel.swift

When editing reward and selecting the same reward with additional+new add-ons, estimated shipping doesn't include the cost for all the new add-ons. 
We need to display the correct total estimated shipping 
Include the selected quantities in the calculations in `SharedFunctions.estimatedShippingText()`
update tests
If the base reward's estimated shipping is `$1-$10`
and the selected add-on estimated shipping is `$1-$5`
If the backer selects 2 of the add-ons, the total estimated shipping should be `$3-$20`

[MBL-1719] Include Selected Reward Quantities In Total Estimated Shipping Range

---

Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift

Our `PledgePaymentMethodsViewController` has an assert to make sure it's only presented in the pledge flow. The no shipping late pledge flow was missing from the assert, so I'm adding it in.
Note: Since asserts like this default to true in production, there's no impact on our current release.

Add NoShippingPostCampaignCheckoutViewController to payment methods assert

---

Kickstarter-iOS/Features/FindFriends/Controller/FindFriendsViewController.swift

- Moved the call to `setNavigationBarHidden` from `viewWillAppear` to `viewDidAppear` in the "Follow Friends" screen.
The change was needed to fix an issue where the `UINavigationBar` was overlaying the content of the "Follow Friends" screen when running the app on a device with iPadOS 18 and Xcode 16.
This issue appears to be caused by layout changes introduced in iPadOS 18, where the tab bar is now at the top of the screen. By calling `setNavigationBarHidden` in `viewDidAppear` instead of `viewWillAppear`, we ensure that the layout has been fully constructed, which prevents the `UINavigationBar` from incorrectly overlaying the content.
The `setNavigationBarHidden` function was moved from `viewWillAppear` to `viewDidAppear` so that the layout is fully built before manipulating the …

[MBL-1738] iPadOS 18 - Navbar overlay issue in "Follow Friends" screen

---

Kickstarter-iOS/Features/PaginationExample/PaginationExampleViewModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOContainerViewController.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOContainerViewModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOEmptyStateView.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOEmptyStateViewTests.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOView.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOViewModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOViewModelTests.swift
Kickstarter.xcodeproj/project.pbxproj
Library/PagedContainer/PagedContainerViewController.swift
Library/PagedContainer/PagedContainerViewModel.swift
Library/Paginator.swift
Library/PaginatorTests.swift

Implements most of the logic for navigation events in the PPO view model and the tab bar integration. 
Each user interaction was added to the PPOViewModel separately, with separate subjects to represent each type of user interaction. This will let us handle navigation events and analytics separately. 
A `PPONavigationEvent` enum was added to represent different locations the user might navigate to. Then, the individual subjects are mapped to their respective navigation events, and those get merged into a navigationEvents publisher. 
Contextual information for routing locations (e.g. which project was backed) and handling of routing will be added once we connect this to a navigation service in MBL-1451).
Unit tests were added to cover these inputs and their navigation events.
All tests …

[MBL-1501] PPO view model navigation events

---

.fastlane/beta-changelog.rb

Update `beta-changelog.rb` to using `File.exist` instead of `File.exists`, as the latter no longer exists in Ruby 3.3. 
I think this will unblock the beta build getting uploaded. The full Ruby error also includes a warning to aws-sdk-core about a change that's happening in Ruby 3.4, but I'm ignoring this for now. I think the fix for that warning is to update our aws gem versions, but I'd rather not do that without understanding what they're doing so I can test the changes properly, and I don't expect a ruby warning to break the script.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1780)
- I'm not testing that the beta build works before merging this pr, since I'm not sure how. (I tried creating a pr in the private repo instead, but it looks like the beta build only gets created …

[MBL-1780] Remove deleted method from our beta changelog

---

Kickstarter-iOS/Features/PledgeView/Controllers/NoShippingPostCampaignCheckoutViewController.swift
Library/ViewModels/NoShippingPostCampaignCheckoutViewModel.swift
Library/ViewModels/NoShippingPostCampaignCheckoutViewModelTests.swift

Handle errors in the late pledge flow without a confirm details page by just showing an error banner (not dismissing the vc). The error banner will persist if the error happens when creating the checkout. If it's an error that happens in a part of the flow the user can retry (after hitting "pledge" or adding a new card) the banner disappears.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1613)

[MBL-1613] Handle errors for late pledges without dismissing the view controller

---

Library/ViewModels/SurveyResponseViewModel.swift
Library/ViewModels/SurveyResponseViewModelTests.swift

Allowlist all requests from `*.stripe.com`, `*.stripe.network`, or `stripecdn.com` in the survey/backing details webview.
The webview got stuck in an infinite loading state earlier today. I'm not sure if it's related to our policy not allowing some of these requests through, but it definitely might be. I noticed `m.stripe.network` requests that we were blocking when I was debugging earlier. [Aidan did a little digging and found that there's also `m.stripe.com` and `r.stripe.com` domains on the checkout page](https://kickstarter.slack.com/archives/C06EKGN4MHU/p1729019704602539?thread_ts=1729007161.056579&cid=C06EKGN4MHU).
I let this idle for a while and noticed `stripecdn.com` requests as well, for invisible captchas, so I've added those as well. It required reformatting the helper …

Allowlist all stripe requests, not just stripe elements

---

Kickstarter-iOS/Features/RewardsCollection/Controller/WithShippingRewardsCollectionViewController.swift
Library/ViewModels/WithShippingRewardsCollectionViewModel.swift

We currently hide all rewards until the shipping location selector is done loading. If there aren't any shippable rewards, unhide the rewards immediately.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1783)

[MBL-1783 Unhide rewards immediately if there's no shippable rewards

---

Kickstarter.xcodeproj/project.pbxproj
Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Updates the Firebase package to 11.4.0.
Fixing a crash apparently due to Firebase SDK being out of date.
Did the upgrade to 11.4 and made sure it built. Sanity checked against the [release notes](https://firebase.google.com/support/release-notes/ios#11.4.0) and didn't see anything breaking between 11.4.0 and 10.11.0 that affects us. Building for release works, and different Firebase systems appear to be activating.

Update Firebase to 11.4.0

---

Kickstarter-iOS/Features/PledgeView/Controllers/NoShippingPledgeViewController.swift
Library/ViewModels/NoShippingPledgeViewModel.swift
Library/ViewModels/NoShippingPledgeViewModelTests.swift

We need to include shipping when paying with apple pay, even when the "no shipping at pledge" flag is on. This adds that back in.
I think the shipping was intentionally deleted back when we didn't understand how pledge redemption would work, and since there are so many different pledge flows (and apple pay is tricky to test) we missed it during testing.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1824)
| --- | --- |
| ![Simulator Screen Recording - iPhone 16 Pro Max - 2024-10-23 at 15 02 03](https://github.com/user-attachments/assets/2090f5ef-48ab-4372-b73b-2170ab5057a5) | ![Simulator Screen Recording - iPhone 16 Pro Max - 2024-10-23 at 14 58 55](https://github.com/user-attachments/assets/76c78421-0455-48d3-8ad8-9ddda5aeb1ac) |

[MBL-1824 Include shipping in apple pay charge

---

Kickstarter-iOS/Features/PledgeView/Controllers/NoShippingPledgeViewControllerTests.swift
Kickstarter-iOS/Features/PledgeView/Controllers/NoShippingPostCampaignViewControllerTests.swift
Kickstarter-iOS/Library/SharedFunctionsTests.swift
Library/SharedFunctions.swift
Library/SharedFunctionsTests.swift

This PR makes sure that estimated shipping on reward cards is updated based on the selected shipping location. Specifically for when the reward has a "Ships anywhere in the world" preference _and_ has shipping rules set for specific countries.
Existing logic was written assuming that unrestricted shipping rewards would only have shipping costs for the rest of the world. It turns out they can also have shipping costs for specific countries.
This means that a reward can have an "unrestricted" shipping preference with shipping rules for "Rest of World" _and_ other specific countries.
We need to check first to see if the reward has a shipping rule matching the selected location ID.
If it _doesn't _and_ the reward has an unrestricted shipping preference, use the shipping rule with an id of 1. …

[MBL-1891] Estimated Shipping Doesn't Update On Location Dropdown Change 

---

KsApi/GraphAPI.swift
KsApi/fragments/UserFragment.graphql
KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
KsApi/models/graphql/adapters/User+UserFragment.swift
KsApi/mutations/templates/fragment/CommentFragmentTemplate.swift
KsApi/queries/templates/FetchMyBackedProjectsQuery.json
KsApi/queries/templates/FetchMySavedProjectsQuery.json

The `ppoHasAction` field caused basically all graphQL fetches to fail for logged out users. (They probably only fail if we're fetching a user, but ex fetching a project includes a user fetch because of the project creator.) In order to unblock the build, we'll just delete this field from graphQL.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1930)
[Jira for next steps (currently blocked since the notification dot is broken)](https://kickstarter.atlassian.net/browse/MBL-1931)
| --- | --- |
| ![Simulator Screen Recording - iPhone 16 Pro Max - 2024-12-10 at 15 28 31](https://github.com/user-attachments/assets/645270b9-cd11-4ddb-af68-1a5e2ecb9fb9) | ![Simulator Screen Recording - iPhone 16 Pro Max - 2024-12-10 at 15 26 …

[MBL-1930] Delete ppoHasAction from UserFragment

---

KsApi/graphql-schema.json
KsApi/models/graphql/adapters/GraphAPI.CreateBackingInput+CreateBackingInput.swift
KsApi/models/graphql/adapters/GraphAPI.CreateBackingInput+CreateBackingInputTests.swift
KsApi/mutations/inputs/CreateBackingInput.swift
KsApi/mutations/inputs/CreateBackingInputTests.swift
Library/CreateBackingConstructorTests.swift
Library/CreateBackingInput+Constructor.swift
Library/ViewModels/NoShippingPledgeViewModel.swift
Library/ViewModels/PledgeViewModel.swift

Updates the `CreateBackingInput` GraphQL object to support its new `incremental: Bool?` property.
Actual implementation will be done separately in [mbl-1853](https://kickstarter.atlassian.net/browse/MBL-1853).
This flag will let the backend know if backers have selected the Pledge Over Time option at checkout. 
- Updated GraphAPI.swift via our apollo script
- Updates the existing adapters and structs to include this new property.
- Passes `false` to call points for now since implementation will be done in [mbl-1853](https://kickstarter.atlassian.net/browse/MBL-1853)
Tested that the new property is being sent as false in when attempting a crowdfund pledging:

[MBL-1852] Update CreateBackingInput

---

Kickstarter-iOS/Features/PledgeView/Controllers/NoShippingPledgeViewControllerTests.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphAPI.swift
KsApi/queries/BuildPaymentPlanQuery.graphql
Library/TimeInterval+ISO8601Date.swift
Library/TimeInterval+ISO8601DateTests.swift
Library/ViewModels/BuildPaymentPlanQueryTestData.swift
Library/ViewModels/ManagePledgeViewModel.swift
Library/ViewModels/NoShippingPledgeViewModel.swift
Library/ViewModels/NoShippingPledgeViewModelTests.swift
Library/ViewModels/PledgePaymentIncrement+GraphAPI.swift
Library/ViewModels/PledgePaymentIncrement+GraphAPITests.swift
Library/ViewModels/PledgePaymentPlansAndSelectionData+GraphAPI.swift
Library/ViewModels/PledgePaymentPlansAndSelectionData+GraphAPITests.swift

Hook up the `BuildPaymentPlanQuery` to the new PLOT UI.
This means PLOT will start showing live data, instead of mock data.
* I created some helpers (plus tests) to map between the GraphAPI response object and @jovaniks view model objects. While I didn't write an intermediary envelope object, those helpers serve a similar role. As an aside, I've been noticing that Apollo/GraphQL objects are painful to test, which is a downside to avoiding envelope objects. 
* I had to update our ISO8061 date formatter to work in both directions, since we need to parse dates.
* I removed some fields we weren't using from the `PledgePaymentIncrement` fragment.
https://github.com/user-attachments/assets/d7eb3348-d5ce-4b18-b99a-2a7c03924b25

MBL-1838: Wire up PLOT query to UI in no-shipping checkout flow

---

Kickstarter.xcodeproj/project.pbxproj
Library/ViewModels/NoShippingPledgeViewModel.swift
Library/ViewModels/PLOTPledgeViewModel.swift
Library/ViewModels/PLOTPledgeViewModelTests.swift

Move all PLOT logic out of `NoShippingPledgeViewModel` and into its own view model, `PLOTPledgeViewModel`.
The complexity of checkout is a significant thorn in our side. Moving the PLOT logic out of the main pledge VM and into its own accomplishes three things:
1. Moves us a small step closer to checkout being modular, shorter, and easier to understand.
2. Allows us to integrate PLOT into other branches of checkout, if necessary.
3. Makes PLOT easier to test.
The PLOT VM is fairly simple - this is mostly copy-pasted from `NoShippingPledgeViewModel`. It follows the same structure as our other view models, with one notable exception: it takes its inputs as signals passed during `init`, instead of having an input function like a view model linked directly to a View Controller. 
Implementing …

Move PLOT logic out of NoShippingPledgeViewModel and into its own VM

---

Library/ViewModels/NoShippingPledgeViewModel.swift
Library/ViewModels/NoShippingPledgeViewModelTests.swift
Library/ViewModels/PLOTPledgeViewModel.swift
Library/ViewModels/PLOTPledgeViewModelTests.swift

Disable pledge button while PLOT is loading, for projects that have PLOT enabled.
Prevents people from pledging with the default option (pledge in full) until they have the option of selecting PLOT. Seems likely to cause bugs if we don't do this.

MBL-1946: Disable pledge button while PLOT is loading

---

Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCardModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectDetails.swift
Library/Format.swift
Library/FormatTests.swift

Following up on PR comments in #2198, this PR adds a currency formatter to Format.swift to turn a `GraphAPI.MoneyFragment` into a localized string. 
Being able to format the `GraphAPI.MoneyFragment` in a consistent and tested way is good
A new API was added which takes a `GraphAPI.MoneyFragment` and formats it using a `NumberFormatter` similar to our other currency formatters. Tests were added to generate a few strings from different fragments in different currencies and locales.
This API is nullable, because if the fragment is invalid, we should not show an incorrect string. Since this is the case, it made sense to update how this was used in backings dashboard. This check was moved to the `PPOProjectCardModel` constructor which already turns a bunch of other GraphQL data into the model …

[MBL-1878] Add GraphAPI.MoneyFragment currency formatter

---

Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCard.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCardModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCardModelTests.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCardViewModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCardViewModelTests.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOContainerViewController.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOContainerViewModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOStyles.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOView.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOViewModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOViewModelTests.swift
Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
Kickstarter-iOS/Locales/de.lproj/Localizable.strings
Kickstarter-iOS/Locales/es.lproj/Localizable.strings
Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphAPI.swift
KsApi/fragments/PPOBackingFragment.graphql
Library/Extensions/Publisher+Helpers.swift
Library/Paginator.swift
Library/PaginatorTests.swift

This PR adds support for letting a user handle 3DS authentication via Stripe.
Stripe won't process some transactions otherwise.
When the user taps the "authorize card" button, I added a loading indicator to the button and updated the enum cases to include a way to turn that loading indicator off.
Then I added fetching the client secret from GraphQL and passing that through the enum case for triggering 3DS authentication.
With those pieces in place, I updated PPOViewModel to call Stripe's authentication check. In debug mode, this is simulated for ease of testing. When the callback completes, the app informs the user that the call has either succeeded or failed. This was done with a touched up version of the MessageBannerView that already existed and had some basic hookups in the …

[MBL-1491] [MBL-1663] Handle 3DS authentication with informational snackbar

---

Kickstarter-iOS/Features/PledgedProjectsOverview/PPOContainerViewController.swift
Library/Extensions/ServerFeature+Helpers.swift
Library/ViewModels/RootViewModel.swift
Library/ViewModels/RootViewModelTests.swift

We're no longer using server features to control PPO, and only relying on Remote Config. This PR removes the server feature check and code that implements it.

[MBL-1995] Disable server feature flag and only rely on remote config

---

Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCard.swift

Adds a tap handler for the project details view in PPO to show the project details. Must've gotten merged out at some point.

[MBL-1994] Add tap gesture handler for PPO project details

---

Library/ViewModels/ActivitiesViewModel.swift
Library/ViewModels/RootViewModel.swift

Since PPO will live right next to activities, it feels redundant to show the same information in both places. We will still show surveys in both places, however, at least while some surveys show in Activity without being available in PPO.
[Jira](https://kickstarter.atlassian.net/browse/MBL-1996)
| --- | --- |
| ![image](https://github.com/user-attachments/assets/ca758108-f062-4f4b-baef-3984074bf559) | ![image](https://github.com/user-attachments/assets/6f32d945-c158-417e-b13d-908cd33a0551) |
- We will likely want to hide surveys as well, once all surveys are available as part of PPO, but that's been removed from this ticket.
- If we decide to only roll out to superbackers after all, this change will need to be rolled back, too.

[MBL-1996] Don't fetch errored pledges if PPO is enabled

---

Kickstarter-iOS/Features/ManagePledge/Controllers/PledgeOverTimePaymentScheduleViewController.swift

Keeps the Terms of Use button on the Payment Schedule of the Manage Pledge screen from disappearing when the web view that it launches is dismissed.
After launching the terms of use web view, this button disappears after dismissing it. 
This is only happening on a physical device, and the theory is that since the terms of use button is the only element that does not have a height constraint, it gets compressed (it's height set to 0) when the layout updates upon closing the web view.
This is difficult to verify, but the solution below seems to have resolved it.
Sets the `setContentCompressionResistancePriority` on the terms of use button.

[MBL-2006] PLOT Terms of Use Button Disappearing On Manage Pledge Screen

---

KsApi/GraphAPI.swift
KsApi/queries/BuildPaymentPlanQuery.graphql
Library/ViewModels/BuildPaymentPlanQueryTestData.swift
Library/ViewModels/PledgePaymentPlansAndSelectionData+GraphAPITests.swift

`projectIsPledgeOverTimeAllowed` was removed from backend, this breaks our builds. This PR removes that field, as it appears to no longer be used. 
**If this is incorrect:** Revert with a different forward fix.

Remove projectIsPledgeOverTimeAllowed

---

Kickstarter.xcodeproj/project.pbxproj
Library/ViewModels/ApplePayTokenUseCase.swift
Library/ViewModels/ApplePayTokenUseCaseTests.swift

Create a use case that will handle ApplePay in the regular (live) pledge flow.
This puts a lot of ApplePay code in one place, so we can pull it out of `NoShippingPledgeViewModel` in the next release.
More broadly: our goal is to simplify our checkout code. One way we can do this is by breaking it down into smaller, more understandable parts. We're following Android's lead here and building 'Use Cases', which are small chunks of code related to a single behavior or feature. These little pieces are much easier to understand, debug, and test.
It's worth noting that ApplePay in late + live pledges is fundamentally different - they use different Stripe APIs. It would be nice to consolidate that, but that would be out of scope without further API changes. This is just a refactoring for niceness …

Create ApplePayTokenUseCase and tests

---

Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCardViewModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOContainerViewController.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOContainerViewModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOViewModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOViewModelTests.swift

Two fixes:
1. Make sure that analytics events are only firing once; if the page reloads, they currently send all events another time.
2. Add a missing event for the user tapping "confirm" on the confirm address popup
1. In order to support the counts properties we need, we use Combine to grab the most recent results from the Paginator. However, when the user pulls to refresh, this causes the Paginator's results publisher to fire again, triggering all analytics events a subsequent time.
2. This event was added but never connected.
1. Instead of using `combineLatest`, this was changed to a `flatMap` + `first`. This causes the Paginator's results method to fire immediately, and only one time. Since this is a flatMap, this process repeats every time the flatMap happens (e.g. every time the …

[MBL-2110] [MBL-2113] Fixes for PPO analytics events

---

Kickstarter-iOS/Features/Activities/Controller/ActivitiesViewController.swift
Kickstarter-iOS/Features/ManagePledge/Controllers/ManagePledgeViewController.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCardModel+Templates.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOContainerViewController.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOContainerViewModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOView.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOViewModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOViewModelTests.swift
Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift

When the user performs an action in PPO, the list now refreshes.
There is a new `shouldRefresh` publisher which is passed into PPOView. When this emits, the PPOViewModel triggers a list refresh. A throttle is used to make sure it doesn't refresh the list multiple times in response to a single event.
This `shouldRefresh` publisher comes from `PPOContainerViewModel` which listens to a few different signals to determine when to reload, including the current user changing, a success banner being shown, when a presented view is dismissed, or when the relevant view controllers fire delegate methods that say they've completed.

[MBL-2109] List refreshing when performing PPO actions

---

Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCreator.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectDetails.swift
Library/PagedContainer/PagedContainerViewController.swift

Prevent hardcoded strings from truncating at all and add more reasonable line limits to strings with user provided content where needed. Also, prevent tab bar titles from growing dynamically at all.
Note: This does NOT change layouts or add tests. I spent some time trying to do each of these things with limited success, so I'm going to submit this pr as is, and hope we'll have time to make this better as a fast follow.
[Jira](https://kickstarter.atlassian.net/browse/MBL-2117)
| Default font size | Largest normal size | Largest accessible size |
| <img width="401" alt="image" src="https://github.com/user-attachments/assets/88ebc2ad-1de8-4073-8e9d-985b3ec41560" /> | <img width="397" alt="image" src="https://github.com/user-attachments/assets/9efaf1ab-ef8c-4b52-9fe3-e42246 …

[MBL-2117] Add minimal large font support

---

Kickstarter-iOS/Features/PledgedProjectsOverview/PPOViewModel.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOViewModelTests.swift

Fixes an error in backings dashboard that prevents the list from loading when there are 0 items.
Changes in #2291 added a check for preventing the list from refreshing unnecessarily (which causes jumping in the list). The issue was caused by the deduplication code, which prevents the screen from reloading unless the values from the paginator are different. However, this returns an empty array for unloaded/loading/error states as well as an empty list of values from the API, which prevents the results from exiting the "loading" case.
Instead, we only do this check if the data has actually loaded. So the check also compares if the results enum is in a "hasLoaded" state, which is already defined for these cases. This fixes the "loading" -> "empty" transition which shows the view correctly. …

Fix empty case in backings dashboard

---

Kickstarter-iOS/SharedViews/PledgeCTAContainerView.swift

When the pledge cta view is loaded but not yet configured with data, default the UI to show the loading indicator and nothing else.
I also updated all the lazy inits in this class to move away from Prelude while I was changing stuff here anyways.
Before this change, whenever we'd open a project page with just the project id, the pledge cta would, by default, try to lay out all its possible UI states. Usually, this led to the loading indicator and the "retry" button showing. I considered updating the pledge cta config data to no longer require a project in the loading state, but this led to a lot of tedious test updates (and the pledge CTA still required a full `Project` class once loaded). Instead, I did this the quick and easy way, and set the pledge cta and the retry stack view to be …

[MBL-2141] Default pledge cta button and retry stack view to hidden

---

Kickstarter-iOS/Features/BackerDashboardProjects/Views/Cells/BackerDashboardProjectCell.swift
Kickstarter-iOS/Features/Search/Views/Cell/MostPopularSearchProjectCell.swift
Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphAPI.swift
KsApi/GraphQLFiles.xcfilelist
KsApi/fragments/BackerDashboardProjectCellFragment.graphql
Library/ViewModels/BackerDashboardProjectCellFragment+ProjectCellModel.swift
Library/ViewModels/BackerDashboardProjectCellViewModel+Utilities.swift
Library/ViewModels/BackerDashboardProjectCellViewModel.swift
Library/ViewModels/BackerDashboardProjectCellViewModelTests.swift
Library/ViewModels/MostPopularSearchProjectCellViewModel.swift
Library/ViewModels/MostPopularSearchProjectCellViewModelTests.swift
Library/ViewModels/Project+ProjectCellModel.swift

- Add the protocol `ProjectCellModel`
- Use a `ProjectCellModel` as input to `BackerDashboardProjectCellViewModel`
- Implement an extension on `Project` to implement `ProjectCellModel`
- Add a GraphQL fragment, `BackerDashboardProjectCellFragment`, which also implements `ProjectCellModel`
- Share UI code between `BackerDashboardProjectCell` and `MostPopularSearchProjectCell`
This is one of the pieces that's been blocking us from using GraphQL in the Search flow. This refactoring will allow us to use a short fragment, `BackerDashboardProjectCellFragment`, to power our old Search UI, instead of the Project page fragment `ProjectFragment`.
I did my best to minimize collateral damage with this refactoring:
1. I made the protocol first, and made it match `Project` whenever possible.
2. Then I …

Refactor BackerDashboardProjectCell to support GraphQL

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/GraphAPI.swift
KsApi/GraphQLFiles.xcfilelist
KsApi/MockService.swift
KsApi/Service.swift
KsApi/ServiceType.swift
KsApi/fragments/ProjectCardFragment.graphql
KsApi/models/Money.swift
KsApi/models/graphql/adapters/Project+ProjectFragment.swift
KsApi/queries/SimilarProjectQuery.graphql
Library/UseCases/SimilarProjects/SimilarProject+Parsing.swift
Library/UseCases/SimilarProjects/SimilarProject.swift
Library/UseCases/SimilarProjects/SimilarProjectsUseCase.swift
Library/UseCases/SimilarProjects/SimilarProjectsUseCaseTests.swift
Library/ViewModels/ProjectPageViewModel.swift

Adds a new GraphQL query for Similar Projects carousel, along with a basic ProjectCardFragment to populate it. Also adds new functions to ServiceType, Service, and MockService to support querying a GraphQL query directly.
We need data for SPC and this is how we get it.
We also are adding more direct querying of GraphQL to prevent needing to add more endpoints to ServiceType.
A new standard GraphQL query was added which includes a fragment for loading similar projects, and hooked into the existing plumbing in SimilarProjectsUseCase.
To support calling this, I also added a method to Service which allows someone to call a GraphQL query directly, along with support in MockService for mocking responses. 
- Tests should pass

[SPC] MBL-2165: Connect GraphQL query for similar projects

---

Library/ViewModels/SimilarProjectsCardViewModel.swift

Rename two helper methods in `SimilarProjectsCardViewModel`.
These methods matched variable names in `SimilarProjectsCardViewModel`; `swiftformat` kept trying to be clever and rename them to `self.method`, which breaks (because there is no such thing).

Rename methods that swiftformat keeps breaking

---

Kickstarter-iOS/Features/ProjectPage/SimilarProjects/Cells/SimilarProjectsLoadingCollectionViewCell.swift
Kickstarter-iOS/Features/ProjectPage/SimilarProjects/Cells/SimilarProjectsTableViewCell.swift
Kickstarter-iOS/Features/ProjectPage/SimilarProjects/Datasource/SimilarProjectsCollectionViewDataSource.swift
Kickstarter.xcodeproj/project.pbxproj

Creates a UICollectionViewCell with our gray shimmer loading animator to replace the project cards while they load.
Just the initial class setup. This will be fully wired up when I implement this and the [collection view work](https://github.com/kickstarter/ios-oss/pull/2336) into the Project Page.
Loading states are helpful and make sense.
- create `SimilarProjectsLoadingCollectionVIewCell`
- use this new cell instead of the main project card cell while they are loading in `SimilarProjectsCollectionViewDataSource`
**Not fully wired up yet. Used my test code to get a screen recording.**
| isLoading == true | |
| --- | --- |
| ![Simulator Screen Recording - iPhone 15 Pro 17 5 - 2025-03-18 at 15 42 06](https://github.com/user-attachments/assets/9f07c761-731e-44c7-a936-00a6d1785c8d) |  |

[MBL-2166] SPC - Project Cards Loading Cell

---

Kickstarter-iOS/Features/ProjectPage/SimilarProjects/Cells/SimilarProjectsTableViewCell.swift

- Adds a UIPageControl to the Similar Projects Carousel 
- Implements custom collectionview cell paging logic.
- I was having trouble using the built in paging logic without having the middle cells being cut off by the content view edges. This is likely due to the collection view no being the full width of the screen.
- Rather than implement custom paging logic I opted to not have the collection page at all for now so we can get this out.
- Design says and it's helpful UX
Add a UIPageControl based on the [designs](https://www.figma.com/design/a9GQ3iQn7XzRUxbpE3cVpE/Search-%26-Discover?node-id=270-49686&t=foaUor18uurLWZRR-4) and make sure it updates to the currently visible project cell.
|  |  |
| --- | --- |
| ![Simulator Screen Recording - iPhone 15 Pro 17 5 - 2025-03-20 at 14 09 …

[MBL-2167] SPC - Page Control

---

Library/UseCases/SearchFiltersUseCase.swift

Turn `guard` statement into `if` statement.
It doesn't need to eject on failure, just throw an assert. Also it was breaking the build.

Turn guard statement into if statement

---

Library/UseCases/SearchFiltersUseCase.swift
Library/UseCases/SearchFiltersUseCaseTests.swift
Library/ViewModels/SearchViewModel.swift
Library/ViewModels/SearchViewModelTests.swift

Clear selected sort and filter options when the search query clears, is canceled, or is an empty string.
This behavior feels a little more natural. Otherwise, you can get caught in a weird state where you have no search results, cancel the search, but then have 'retained' filters from your last failed query.

Clear sort and filter options when search query is cleared

---

Kickstarter.xcodeproj/project.pbxproj
Library/ViewModels/CreditCardCellViewModelTests.swift

Fix asset loading in `Library-iOSTests` by adding the `Assets.xcassets` to the test target and using the `image(named:)` helper for better asset resolution in unit tests.
- Added `Assets.xcassets` to the `Library-iOSTests` test target to ensure test cases can load images and colors from the asset catalog.
- Replaced instances of `UIImage(named:)` in tests with the `image(named:)` helper, which resolves assets using `AppEnvironment.current.mainBundle`.

Add Assets.xcassets to Library-iOSTests and switch to image(named:) helper

---

Kickstarter-iOS/Features/RewardAddOnSelection/Views/RewardAddOnCardView.swift
Kickstarter-iOS/Features/RewardsCollection/Views/RewardCardView.swift
Library/Extensions/UIStackView+Helper.swift
Library/Extensions/UIView+Helper.swift

Fixes the aspect ratio issue for the add-on image shown on the pledge flow. The image was appearing compressed due to incorrect content mode configuration.
- Created a private `applyRewardImageViewStyle(_:)` helper method to apply consistent styling to the reward image view.
- Applied `.scaleAspectFill` and `clipsToBounds = true` to ensure images are rendered properly.
- Updated the following views:
- `RewardAddOnCardView.swift`
- `RewardCardView.swift`
- [Ticket](https://kickstarter.atlassian.net/browse/MBL-2260)
| --- | --- |
| ![IMG_5946](https://github.com/user-attachments/assets/755b84c1-63f4-491e-9bd2-2d84c16c7117) | ![image](https://github.com/user-attachments/assets/e5e90000-d3a4-485b-b2c9-01c818ae3095) |

Images on rewards aspect ratio

---

Kickstarter-iOS/Features/PledgeManagement/Controllers/PledgeManagementViewPledgeViewController.swift
Kickstarter.xcodeproj/project.pbxproj
Library/ProjectURLBuilder.swift
Library/ProjectURLBuilderTests.swift
Library/ViewModels/PledgeManagementViewPledgeViewModel.swift
Library/ViewModels/PledgeManagementViewPledgeViewModelTests.swift
Library/ViewModels/PledgeStatusLabelViewModel.swift

Creates a new web view controller that will display a user's backing details.
For backers who pledged to a campaign and completed PM or who just completed PM, we'll show a web view when they want to see their backing details. 
This is a crunch time approach. There are plans to update our native screen with PM backing details, etc., once we're out of crunch time 🤞.
- Creates a new ViewController that inherits from our WebViewController class.
- Load the existing backing details URL on viewDidLoad using a passed in `Project`.
This is just the view controller. The next PR will wire it up and use the new `Backing.Order` object, and the feature flag, to determine when to show this web view and when to show the existing native screen.
The entry points will include the Project Page and Messages. …

[MBL-2317] View Your Pledge Web View

---

KsApi/GraphAPI.swift
KsApi/Service.swift
KsApi/models/DiscoveryParams.swift
KsApi/queries/SearchQuery.graphql
Library/UseCases/SearchFiltersUseCase.swift
Library/UseCases/SearchFiltersUseCaseTests.swift
Library/ViewModels/SearchViewModel+GraphQL.swift
Library/ViewModels/SearchViewModel.swift

Add API and plumbing support for phase 2, filtering by project status.
This change is effectively a no-op for the existing search - since it sets the default filters to `.all`. I split this out into its own PR for clarity's sake.

MBL-2222: Add support to GraphQL, DiscoveryParams and view models for filtering by project state

---

Kickstarter-iOS/Assets.xcassets/new design system/colors/background/accentGraySubtle.colorset/Contents.json
Kickstarter-iOS/Assets.xcassets/new design system/colors/border/active.colorset/Contents.json
Library/Styles/Colors/NewDesignSystemColors.swift
Library/Styles/Fonts/CustomFont.swift

* Add two colors to our design system
* Add a default size of `nil` to `swiftUIFont`, for convenience
I need these for the search filter pill buttons.

Add accent/gray/subtle and border/active to new design system colors

---

Kickstarter-iOS/Features/Search/Controller/SearchViewController.swift
Library/UseCases/SearchFilterPill.swift
Library/UseCases/SearchFiltersUseCase.swift
Library/UseCases/SearchFiltersUseCaseTests.swift
Library/ViewModels/SearchViewModel.swift
Library/ViewModels/SearchViewModelTests.swift

Implement project state filters for Phase 2 of the sort & filters project.
* Added project state filters to `SearchFiltersUseCase` and `SearchViewModel`
* Show placeholder pills for 'All' filters and project state filters
* Show placeholder UI for choosing project filters
* Refactor `SearchFiltersUseCase` to make it easier to add more filter types in the future
* Refactor the data types used to show the filter modals
I like to implement scaffolding like this before I go in and write the UI - it makes it easier for me to hook everything up later. Might as well sort out the hard problems first before making it pretty.

MBL-2222: Add project state filters to Search

---

Library/ViewModels/ProjectPageViewModel.swift
Library/ViewModels/ProjectPageViewModelTests.swift

Fixes image and audio loading when opening a project from search.
So people can see images in search results.
Search loads without a Project instance, and instead passes a param (like an id or slug) of a project. The project page then loads that project one time.
The existing signal chain was assuming that the project page would be opened via a Project instance, so the signals would receive two projects. The first one being partial, the second one being complete.
Since it was making this assumption, it was skipping the first project returned. When opening via a param, this is the ONLY project being returned. So it was not doing the work to load images (and, it turns out, audio elements and I think page view events). So images and audio elements were not being shown.
This fixes by removing …

[MBL-2328] Fix image/audio element loading in campaign from search

---

Kickstarter.xcodeproj/project.pbxproj

Fixes a crash when running `fastlane` for the beta build by converting the `PledgeManagement` group from a *sync group* (`PBXFileSystemSynchronizedRootGroup`) to a standard folder reference in Xcode.
- In Xcode, updated the `PledgeManagement` group to use a regular folder reference instead of a sync group.
- This ensures compatibility with the tooling used by `fastlane` and resolves the CI crash.
-[CircleCI](https://app.circleci.com/pipelines/github/kickstarter/ios-private/1517/workflows/7ed388b9-4c5a-41ea-88dd-04ce3e82feb4/jobs/19747)

Fix beta build failure due to PBX sync group in PledgeManagement

---

Kickstarter-iOS/Assets.xcassets/new design system/colors/background/accentGraySubtle.colorset/Contents.json
Kickstarter-iOS/Assets.xcassets/new design system/colors/border/active.colorset/Contents.json

Add dark mode colors for background/accent/gray/subtle and border/active
I didn't add these earlier, and now I know what colors they are!
For reference, the main Figman board: https://www.figma.com/design/enEdulL4R1rsMcMttfxJRr/Kickstarter-Design-System---Mobile

Add dark mode colors for background/accent/gray/subtle and border/active

---

Kickstarter-iOS/Info.plist

Fixes Facebook SDK login.
As part of #2356 I removed the URL scheme for AppCenter, not noticing that there was a Facebook SDK scheme there. The Facebook SDK scheme was deleted by accident, so now Facebook logins appear broken.
This change just re-adds the scheme.
[Error events](https://console.firebase.google.com/u/0/project/kickstarter-ios/crashlytics/app/ios:com.kickstarter.kickstarter/issues/4775b110883a794b2702a61798310a48?time=last-twenty-four-hours&versions=5.24.1%20(1744776)&types=crash&sessionEventKey=23871d77925b4666b6e0a033abd7e07a_2074285278984436477)

[MBL-2364] Fix facebook URL scheme

---

Kickstarter-iOS/Features/Search/Controller/SearchViewController.swift
Kickstarter-iOS/Features/SortFilter/FilterCategory/FilterCategoryView.swift
Kickstarter-iOS/Features/SortFilter/FilterRootView.swift
Kickstarter.xcodeproj/project.pbxproj

* Add `FilterRootView` with placeholder, but functional, UI
* Use `NavigationStack` so that tapping on "Category" button links you to a `FilterCategoryView` pushed on top of a `FilterRootView`
This is the last big leap from Phase 1 of search into Phase 2!

MBL-2227: Support navigation for filters and add placeholder root filter view

---

Kickstarter-iOS/Features/Activities/Controller/ActivitiesViewController.swift
Kickstarter-iOS/Features/Activities/Datasource/ActivitiesDataSource.swift
Kickstarter-iOS/Features/RewardTracking/Views/RewardTrackingDetailsView.swift
Library/ViewModels/ActivitiesViewModel.swift
Library/ViewModels/ActivitiesViewModelTests.swift
Library/ViewModels/RewardTrackingDetailsViewModel.swift
Library/ViewModels/RewardTrackingDetailsViewModelTest.swift

…f being in their own section
- Use the sort order of the `v1/activities` response so that the tracking # cards are interspersed among the other activities and next to their relevant project Activity.
- Also adds logic to only hide the "Track shipment" button if the `trackingURL` is nil.
- It makes more sense for these cards to be paired with their relevant project activities. 
We also don't want to bury any surveys unnecessarily.
- If the `trackingURL` is nil, it will still be useful for backers to know their tracking numbers and that their rewards have shipped. Rather than hiding the entire view.
- Use the existing data source `.load` method, that is already populating the `activities` section of the table, to load up the shipped activities.
- Remove the code that handles loading these …

[MBL-2385] Intersperse Tracking # Cards With Activities

---

Library/UpdateBackingInput+Constructor.swift
Library/UpdateBackingInput+ConstructorTests.swift

Fixes the **Feature disabled** error shown when attempting to change the payment method for PLOT pledges by ensuring only the `paymentSourceId` or `applePay` field is sent, and excluding `rewardIds`, `amount`, and `locationId`.
The backend expects only `paymentSourceId` or `applePay` to be present in the payload when updating payment method for PLOT pledges. Sending additional fields like `rewardIds` causes the endpoint to reject the request with a **Feature disabled** error.
- Introduced a new boolean condition `isChangePaymentMethodAndPlot`.
- Used this to conditionally exclude `amount`, `rewardIds`, and `locationId` from the `UpdateBackingInput` payload when the context is `.changePaymentMethod` and the pledge is a PLOT type.
- …

[MBL-2366] Fix update payment method for PLOT pledges

---

Kickstarter-iOS/Features/Search/Controller/SearchViewController.swift
Kickstarter-iOS/Features/SortFilter/FilterCategory/FilterCategoryViewModelTest_PhaseOne.swift
Kickstarter-iOS/Features/SortFilter/FilterCategory/FilterCategoryViewModel_PhaseOne.swift
Kickstarter-iOS/Features/SortFilter/FilterCategory/FilterCategoryViewTest_PhaseOne.swift
Kickstarter-iOS/Features/SortFilter/FilterCategory/FilterCategoryView_PhaseOne.swift
Kickstarter.xcodeproj/project.pbxproj

Split `FilterCategoryViewModel` into `FilterCategoryViewModel` and `FilterCategoryViewModel_PhaseOne`
This will limit the subcategory work (and other refactoring for root filters) to code that's behind the phase 2 flag. There were some substantial changes to the view models that necessitated this.

Split FilterCategoryViewModel into FilterCategoryViewModel and FilterCategoryViewModel_PhaseOne

---

Kickstarter-iOS/Features/Search/Datasource/SearchDataSource.swift
Kickstarter-iOS/Features/Search/Datasource/SearchDataSourceTests.swift
Kickstarter.xcodeproj/project.pbxproj
Library/ViewModels/SearchViewModel.swift

Fix crash caused by tapping on title row in search results.
This crash occurred because I didn't checking for the title row in the method `indexOfProject(forCellAtIndexPath)`. If you tapped on the title row, this method returns `-1`, causing a crash when the view model tries to fetch `projects[-1]`.

Fix crash caused by tapping on title row in search results.

---

Library/Styles/Buttons/KSRButtonStyleConfiguration.swift

Fixes an issue where buttons styled with `KSRButtonStyle` would appear blank (white background, no title or border) after device orientation changes.
When `applyStyleConfiguration` is called multiple times — such as during a layout update on rotation — the style configuration was being reassigned, but visual changes (like `tintColor`, `backgroundColor`, and `border` styling) weren’t being immediately reflected. This happened because those updates were deferred until a state change (e.g., touch), via `configurationUpdateHandler`.
- Added `setNeedsUpdateConfiguration()` just after the button configuration is set.
| --- | --- |
| ![Simulator Screen Recording - iPhone 16 Pro - 2025-04-30 at 09 20 …

Fix KSRButtonStyle is blank after orientation change

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/AppDelegateViewModel.swift
Kickstarter-iOS/AppDelegateViewModelTests.swift
Kickstarter-iOS/Info.plist

Turn on dark mode in the app.
This is one of our most (if not _the_ most) requested features!
* Dynamically set `overrideUserInterfaceStyle` on the window depending on the value of `featureDarkModeEnabled()`
* Remove the interface style override from our `Info.plist`
📠 cc @jovaniks @stevestreza-ksr  📠

[Part 4] Enable dark mode when featureDarkModeEnabled() is true

---

Kickstarter-iOS/Features/Activities/Storyboard/Activity.storyboard
Kickstarter-iOS/Features/Activities/Views/Cells/ActivityFriendBackingCell.swift
Kickstarter-iOS/Features/Activities/Views/Cells/ActivityFriendFollowCell.swift
Kickstarter-iOS/Features/Activities/Views/Cells/ActivityProjectStatusCell.swift
Kickstarter-iOS/Features/Activities/Views/Cells/ActivitySurveyResponseCell.swift
Kickstarter-iOS/Features/Activities/Views/Cells/ActivityUpdateCell.swift
Kickstarter-iOS/Features/Activities/Views/Cells/FindFriendsFacebookConnectCell.swift
Kickstarter-iOS/Features/Discovery/Storyboard/DiscoveryPage.storyboard
Kickstarter-iOS/Features/Discovery/Views/Cells/ActivitySampleBackingCell.swift
Kickstarter-iOS/Features/Discovery/Views/Cells/ActivitySampleFollowCell.swift
Kickstarter-iOS/Features/Discovery/Views/Cells/ActivitySampleProjectCell.swift

- Replace custom white color value in Storyboards for Activity and Activity preview cells with semantic `white` color from asset catalog
- Add programmatic background colors to Activity cells, wherever they were missing. I specifically used `background/surface/primary` so that the dark mode version looks a little nicer, instead of using `legacy/white`. 
| --- | --- |
| <img width="200" src="https://github.com/user-attachments/assets/0d3ddfcb-40d0-4b2c-8fa2-f7b324efbe94" /> | <img width="200" src="https://github.com/user-attachments/assets/7c817af4-2506-4b0f-ae59-b2ae87fc708b" /> 
| <img width="200" src="https://github.com/user-attachments/assets/e001adbc-153e-4583-9406-432bc0b70b49" /> | <img width="200" src="https://github.com/user-attachments/assets/5a53522b-9c7b-4 …

Update Activity feed for dark mode

---

Kickstarter-iOS/Features/ProjectCard/ProjectCardViewTests.swift
Library/UseCases/SimilarProjects/ProjectCardProperties.swift

Regression fix for search results so they no longer show "coming soon" unnecessarily. One of the tests was misconfigured to include `isLaunched: true` for the "coming soon" case, so when the original fix was built to keep the tests as-is, the `isLaunched` flag was no longer checked, causing the issue.
Add a check for `isLaunched` when determining if prelaunch, and update the test to not rely on the flag.

Fix 'coming soon' state on search results

---

Kickstarter-iOS/Features/SortFilter/Components/RadioButton.swift
Kickstarter-iOS/Features/SortFilter/PercentRaisedView/PercentRaisedView.swift
Kickstarter-iOS/Features/SortFilter/SortView/SortView.swift
Kickstarter.xcodeproj/project.pbxproj

Make the % raised screen look like the designs.
I also made `RadioButton` into its own component. (Slightly ironically, it's not a button, just a view - I wrapped it in a button.)

MBL-2348: Bring % raised screen up to spec

---

Kickstarter-iOS/Features/RewardsCollection/Views/RewardCardContainerView.swift

Fixes a layout issue where the "Secret Reward" and "Your selection" badges overlap when rotating the device in the **Edit reward** screen.
- Introduced `currentRewardCardMaskViewTopMarginInset` property to store the current top margin value dynamically.
- Created `updateRewardCardMaskViewLayout()` to apply margin updates based on whether extra spacing is needed (e.g., when the reward is backed and is a secret reward).
- Called `updateRewardCardMaskViewLayout()` during `bindStyles()` to reflect layout changes.
- Removed hardcoded `.zero` margin.
[Bug ticket](https://kickstarter.atlassian.net/browse/MBL-2479)
| --- | --- |
| ![Simulator Screen Recording - iPhone 16 Pro - 2025-06-03 at 05 55 05](https://github.com/user-attachments/assets/13dcfa73-a067-4c73-a46b-2eb765a8 …

[MBL-2478] Fix badge overlap on Edit Reward screen when rotating device

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/models/graphql/adapters/Location+LocationFragment.swift
Library/UseCases/FetchLocations/FetchLocationsUseCase.swift
Library/UseCases/FetchLocations/FetchLocationsUseCaseTests.swift

Add `FetchLocationsUseCase`. 
This is a small use case for getting default and suggested locations from the server. It will be used by `SearchFiltersUseCase`.
Pulling this behavior out into its own use case makes it easy to test these network calls, and easier to test and hook up `SearchFiltersUseCase`.

Add FetchLocationsUseCase

---

Kickstarter-iOS/Features/PledgeView/Controllers/PledgeViewController.swift
Library/ViewModels/PaymentMethodsUseCase.swift
Library/ViewModels/PledgeOverTimeUseCase.swift
Library/ViewModels/PledgeOverTimeUseCaseTests.swift
Library/ViewModels/PledgeViewModel.swift

This PR improves the default selection logic for the payment plan in the "Edit Pledge Over Time" flow.
Specifically:
- The default selected plan will now reflect the backer's original selection (i.e., if they selected **Pledge In Full** originally, that will remain selected when editing).
- Previously, the default was always **Pledge In Full**, regardless of the backer's choice.
This change uses `backing.paymentIncrements.isEmpty` to determine whether **Pledge Over Time** or **Pledge In Full** should be preselected.
- Retain PLOT pre-selection only if the new pledge amount meets the eligibility threshold (amountIsPledgeOverTimeEligible)
Added a new variable:
```swift
let isPledgeOverTimePreSelected = project.personalization.backing?.paymentIncrements.isEmpty == false
let …
```

Hotfix: Preselect the original payment plan when editing a Pledge Over Time

---

KsApi/models/Project.swift
Library/ViewModels/PledgeCTAContainerViewViewModel.swift
Library/ViewModels/PledgeCTAContainerViewViewModelTests.swift

Currently, we only show the go to pledge manager button on the project page for net new backers. We should also show it for existing backers!
Show go to pledge manager flow for net-new backers || existing backers.
- [MBL-2547](https://kickstarter.atlassian.net/browse/MBL-2547)
[MBL-2547]: https://kickstarter.atlassian.net/browse/MBL-2547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-2547] Show "Go to Pledge Manager" button for existing backers

---

KsApi/models/Backing.swift
Library/ViewModels/PledgeCTAContainerViewViewModel.swift
Library/ViewModels/PledgeCTAContainerViewViewModelTests.swift
Library/ViewModels/PledgeStatusLabelViewModel.swift
Library/ViewModels/PledgeStatusLabelViewModelTests.swift

Add `.dummy` as a backings status type and include minimal support. Use the `.dummy` status to decide if project page CTA should open pledge manager.
Note: I've also updated the native manage pledge page, mostly because it had an exhaustive switch statement, so I'm including a screenshot here. I don't think users can navigate to this page, so I didn't worry too much about what it looks like.
[Jira](https://kickstarter.atlassian.net/browse/MBL-2606)
| Before 🐛 | After 🦋 | Native manage pledge view after |
| <img width="415" height="855" alt="image" src="https://github.com/user-attachments/assets/183b1e67-8033-46c0-a34b-4850922fbbe4" /> | ![Simulator Screen Recording - iPhone 16 - 2025-07-10 at 13 06 06](https://github.com/user-attachments/assets/14c7cd1c-176e-4c2a-a8e8-c …

[MBL-2606] Add basic dummy pledge support

---

Kickstarter.xcodeproj/project.pbxproj

… folder reference
Fix beta build by converting the `GraphAPI` and `GraphAPITestMocks` from a sync group (`PBXFileSystemSynchronizedRootGroup`) to a standard folder reference in Xcode.
[CircleCI](https://app.circleci.com/pipelines/github/kickstarter/ios-private/1690/workflows/5e5eadd3-d859-41c9-bc8c-9f7f794de063/jobs/20610)

Update `GraphAPI` and `GraphAPITestMocks` from sync group to standard folder

---

KsApi/MockService.swift

Moves some `GraphAPI` extensions and `Result` helpers inside the `#if DEBUG` macro to prevent beta build errors caused by missing GraphAPI types in non-debug contexts.
After the Apollo upgrade, `GraphAPI` was converted into a framework, which broke previous assumptions about type visibility. Some `GraphAPI` extensions (like `GraphAPI.CompleteOnSessionCheckoutMutation.Data`) were being declared outside the `#if DEBUG` macro and caused build errors in beta pipelines where the framework is not available outside test/debug contexts.
- Moved the following extensions inside the `#if DEBUG` macro:
- `extension GraphAPI.CompleteOnSessionCheckoutMutation.Data`
- `extension GraphAPI.BuildPaymentPlanQuery.Data`
- `extension Result` (value/error)
- This ensures the code is only compiled in the …

Fix beta build error by moving GraphAPI extensions inside DEBUG macro

---

Library/ViewModels/RewardsCollectionViewModel.swift

This PR disables the auto-scroll behavior to secret rewards when those rewards are not available.
- Updated `firstSecretRewardIndexPath` logic in `RewardsCollectionViewModel` to return only the first available secret reward (via `isAvailable == true`)
- This avoids triggering auto-scroll when secret rewards are present in the data, but not currently accessible to the backer.
- [MBL-2533](https://kickstarter.atlassian.net/browse/MBL-2533)
| Available Secret Reward | Unavailable Secret Reward |
| --- | --- |
| ![Simulator Screen Recording - iPhone 16 Pro - 2025-07-31 at 16 35 21](https://github.com/user-attachments/assets/a688c5d2-141c-47dc-b067-3c665182502b) | ![Simulator Screen Recording - iPhone 16 Pro - 2025-07-31 at 16 33 58](https://github.com/user-attachments/assets/59967c73-0e1a-4780 …

[MBL-2533] Disabled autoscroll for unavailable secret rewards

---

Kickstarter-iOS/Features/Onboarding/Views/OnboardingItemView.swift

German translations have some longer text that we don't want truncated.
I think the `.lineLimit` property was left over from trying to maintain the view height and button placement a few PRs ago.
| --- | --- |
| <img width="300" height="700" alt="179d251d-347e-4669-8311-028396645c6e" src="https://github.com/user-attachments/assets/46b5952d-8f5c-4872-a8d2-f711bdc34f08" /> | ![Simulator Screen Recording - iPhone 15 Pro 17 5 - 2025-08-11 at 14 04 42](https://github.com/user-attachments/assets/e562a431-4733-46b6-a439-484e00263fba) |

[MBL-2715] Remove Subtitle Line Limit

---

Library/ViewModels/SearchViewModel+GraphQL.swift

Fix default search sort order by setting toggle-related params to `false` when the toggles are not selected.
Note: Specifically, the filter that caused this was the starred/saved projects toggle, but it feels safer to me to just set all of them to nil.
[Jira](https://kickstarter.atlassian.net/browse/MBL-2714)
| --- | --- |
| <img width="404" height="823" alt="image" src="https://github.com/user-attachments/assets/ba14c524-c260-4607-aebf-02bec246a2c8" /> | <img width="409" height="826" alt="image" src="https://github.com/user-attachments/assets/4e15effd-2ae1-47a2-8ecc-8a0828f83e89" /> |

[MBL-2714] Fix default search results sort order bug

---

Kickstarter-iOS/Features/Onboarding/OnboardingStyles.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOStyles.swift
Library/Styles/Colors/CoreColor.swift
Library/Styles/Colors/LegacyColors.swift

* Replace hardcoded hex values for three colors in the app
I'm making `UIColor.hex` private to the `KDS` package. These colors need to use either a core color, or a semantic color.
I spoke with design to get their nearest equivalents!

MBL-2658: Use palette colors instead of hex colors in OnboardingStyles and PPOStyles

---

Library/OnboardingUseCase.swift
Library/OnboardingViewModel.swift
Library/OnboardingViewModelTests.swift
Library/Tracking/KSRAnalytics.swift

Moves the App Tracking View to be before the Push Notifications View.
We want to be able to track as much data as we can if users have consented to AppTracking.
Today, if users consent after the notifications view we won't know what they actually did on that screen.
I also updated our app tracking analytic event so that we don't send anything if user "denied" consent permissions. That would defeat the purpose of denying!
| | After 🦋 |
| --- | --- |
|  | ![Simulator Screen Recording - iPhone 16 Pro - 2025-09-03 at 08 36 00](https://github.com/user-attachments/assets/87fb2453-8477-4b57-aad9-a5c44be06940) |

[MBL-2743] Onboarding - Move App Tracking View & Update Analytics Events

---

.circleci/config.yml
Kickstarter.xcodeproj/project.pbxproj

* Delete the update schema step from our CircleCI build configuration
* Add the update schema step to the Generate GraphQL Library target
Updating the schema in CircleCI effectively worked as a smoke test - if someone changed the GraphQL schema in a way that broke the apps, our build on CircleCI would get the new schema, try to build KsApi, and then break. This happened maybe once or twice a year as a rare failure mode.
However, we no longer automatically generate GraphQL objects when KsApi is built. That means we’re spending an extra ~30 seconds in the CircleCI build for no benefit.
Instead, it makes more sense to re-download the schema when we actually re-generate the objects.
I filed a separate ticket to rebuild this smoke test, if we decide it's useful in the future.

MBL-2681: Move GraphQL schema download from CircleCI step into GraphQL build target

---

Kickstarter-iOS/Features/Onboarding/Views/OnboardingItemView.swift
Kickstarter-iOS/Features/Onboarding/Views/OnboardingView.swift

Update onboarding views to account for smaller screen sizes.
The new Onboarding view is cut off on small phones - the progress bar is missing, and the secondary button is pushed towards the bottom.
For example, here’s how it looks on the iPhone SE:
From what I've found, SwiftUI doesn’t have a way to auto-scale an entire view tree to fit a device's height if the content height exceeds it. `minimumScaleFactor` only works on `Text`, and `ViewThatFits` swaps layouts, but it doesn’t scale them.
`scaleEffect` was also causing blurry text depending on the font size which was no good either.
I ended up putting the text and lottie view in a scrollview and pinning the CTA to the bottom safe area inset.
I ran this by Alison and she gave the ok as well. It's not my favorite that you can see the main …

[MBL-2774] Auto Scale Onboarding Views For Smaller Devices

---

Kickstarter-iOS/AppDelegate.swift
Kickstarter-iOS/AppDelegateViewModel.swift
Kickstarter-iOS/AppDelegateViewModelTests.swift

The segment/braze upgrade broke our push notification registration for some edge cases. Fix push token setup by
1. Ensuring that we tell Braze when new users log in (this fixes the Braze issue where we had to quit and relaunch the app after deleting and reinstalling the app)
2. Telling Braze to never attempt to automatically set up push notifications or push registration. This doesn't fully fix aws notification registration (it still sometimes gets in a weird state when you uninstall and reinstall the app), but it seems to help
[Jira](https://kickstarter.atlassian.net/browse/MBL-2744)

[MBL-2744] Fix push notification registration

---

Kickstarter.xcodeproj/project.pbxproj
KsApi/AsyncApolloClient.swift
KsApi/AsyncApolloClientTests.swift
KsApi/MockApolloClient.swift

Adds a lightweight `AsyncApolloClient` to `KsApi` with some unit tests.
This wrapper converts Apollo’s callback-based fetch and perform methods into modern Swift async/await APIs.
- Adds`AsyncApolloClient`:  a minimal async/await bridge around `ApolloClientProtocol`.
- Supports both fetch (queries) and perform (mutations).
- Adds `MockApolloClient` for testing.
- simulates success/failure cases
- records callbackQueue changes
- Adds `AsyncApolloClientTests`
- Tests success and failure paths for both fetch and perform.

[MBL-2690] Async/Await Apollo Wrapper

---

Kickstarter-iOS/Features/Discovery/Views/DiscoveryProjectCategoryView.swift

Removes a use of IBDesignable, which is deprecated in iOS 18.

[MBL-2766] Remove IBDesignable

---

Kickstarter-iOS/AppDelegateViewModel.swift
Kickstarter-iOS/AppDelegateViewModelTests.swift

Filter out `ksr://` urls before we open unrecognized urls in safari.
Also, add non-fatal error tracking when the app is opened with an invalid `ksr://` url. I didn't add the specific url to the logging, since this could theoretically include sensitive info. If we're seeing a lot of these non-fatal errors and we want to investigate further in the future, we can talk to legal about if it makes sense to log them.
In the app, we fall back to opening unrecognized urls in safari. This is generally a good thing. However, `ksr://` urls will always open the kickstarter app, so we used to get into the following loop for these urls:
- Attempt to open weird `ksr://` url
- Realize we couldn't, so we tell safari to open it instead
- Safari helpfully recognizes it as a `ksr://` url and therefore opens …

[MBL-2829] Stop trying to open unrecognized ksr urls in safari

---

Kickstarter-iOS/AppDelegateViewModel.swift
Kickstarter-iOS/Features/Activities/Controller/ActivitiesViewController.swift
Kickstarter-iOS/Features/Messages/Controller/MessagesViewController.swift
Kickstarter-iOS/Features/PledgedProjectsOverview/PPOContainerViewController.swift
Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
Kickstarter-iOS/Features/SurveyResponse/Controller/PledgeManagerWebViewController.swift
Kickstarter.xcodeproj/project.pbxproj
Library/Navigation.swift
Library/NavigationTests.swift
Library/ViewModels/PledgeManagerWebViewModel.swift
Library/ViewModels/PledgeManagerWebViewModelTests.swift

1. Rename all the classes that contain `SurveyResponse` to `PledgeMangerWebView`.
2. Rename the navigation type `surveyWebview` to `pledgeManagerWebView`
3. Rename some other survey-specific variables
I'm working on implementing deep links and push notifications for order edits, which is a new feature in Pledge Manager. I found that the best way to do that would be to extend the functionality of `SurveyResponseViewController` and the `surveyWebview` navigation type. We want essentially the same behavior - links that go to an embedded webview, with login support - so it makes sense.
For clarity, I renamed all of these types to be a little more generically applicable to Pledge Manager.

Rename SurveyResponse classes to PledgeManagerWebView
